### ISSUE TITLE
misalignment of icons in titles

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8453] opened 2021-09-21 14:40 UTC
## Observed behavior

Observed in screenshots @radinamatic posted in https://github.com/learningequality/kolibri/pull/8449#issuecomment-923611087

![image](https://user-images.githubusercontent.com/2367265/134192029-e8db028f-b5b4-4bd4-8125-09f3ee6f8aab.png)

## Expected behavior

Icons should (roughly) align with text baseline:

![image](https://user-images.githubusercontent.com/2367265/134191848-93f5328e-034d-4570-afc7-c48732bd54f6.png)

If this is implemented using `KLabeledIcon` we can transfer this issue to KDS

## Context

0.15 

cc @radinamatic mind adding details about your Android version & browser in that testing?

**Comment by radinamatic** [comment] 2021-09-21 15:29
Mediapad T5, Android version 8.0.0

Visible on Firefox 92 and Chrome 93 on Windows 10, too.

Firefox | Chrome
--- | ---
![Win10 (start)  Running  - Oracle VM VirtualBox_038](https://user-images.githubusercontent.com/1457929/134200801-52e8a897-de00-4f5c-84f5-af59c94f9fcb.png) | ![Win10 (start)  Running  - Oracle VM VirtualBox_039](https://user-images.githubusercontent.com/1457929/134200830-0b363096-f9bf-43bc-98cd-31bb751043aa.png)

**Comment by sairina** [comment] 2022-02-25 04:43
@radinamatic @indirectlylit I'm trying to reproduce this issue in the title, but am unsure that I'm doing this correctly. I'm in Learn and in a class, and I don't see this issue with the misalignment of icons in the title Is this still an issue after the release of Kolibri 0.15? (Looking at Chrome, Surface Pro Android tablet)

<img width="950" alt="Screen Shot 2022-02-24 at 8 40 20 PM" src="https://user-images.githubusercontent.com/13563002/155655035-5f0613c1-315c-423b-b63f-3f45672f92b1.png">

**Comment by pcenov** [comment] 2022-02-25 13:15
I think we can close this one as it's no longer extant in 0.15.1:

| Issue| Screenshot |
:-------------------------:|:-------------------------:
| Desktop |  ![2022-02-25_15-08-04](https://user-images.githubusercontent.com/79847249/155721117-837049dd-eef4-48e6-acf5-9d42e796e6f1.png) |
| Mobile |  ![2022-02-25_15-11-34](https://user-images.githubusercontent.com/79847249/155721165-9c157fa8-2932-405b-af5e-77eadba3da13.png) |

@radinamatic

**Comment by radinamatic** [comment] 2022-02-25 13:45
Thank you for re-testing, @pcenov 👍🏽 

@sairina The original issue seems to have been resolved, and the only doubt remains why the _In progress_ icon is not appearing any more alongside the lesson name, as it was present in my first screenshot from last year... 🤔 

As I can infer from the latest @pcenov screenshot, some of the resources are completed and others are in progress, but the lesson is still not labeled as _In progress_. Did we decide to eliminate that label for lessons, or is this a regression?

**Comment by jtamiace** [comment] 2022-02-25 17:16
There should be an in progress icon & label for lessons. Design reference here https://www.figma.com/file/uiZuCIqh2KYvBUfbCiJyyA/Hybrid-Learning?node-id=1915%3A82995

**Comment by sairina** [comment] 2022-02-26 05:08
It looks like the screenshots match the 0.15 designs in Figma, so I'll close out this issue. Thanks for investigating this, everyone!

**Closed as completed by sairina** 2022-02-26 05:08 UTC
Labels: bug, TAG: regression, DEV: frontend

**Comment by radinamatic** [comment] 2022-02-28 07:37
Ok, so the lesson progress/completed icon is present on the Class home page, but not inside the lesson itself anymore, so there was a change since this issue is reported initially.
