### ISSUE TITLE
Unable to cancel content import

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1673] opened 2017-06-16 00:12 UTC
## Summary

I was importing a content channel and wanted to cancel. I pressed cancel and it appeared as though the import canceled but then the import bar reappeared. Note: This may be an issue using an old phone.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta5.dev244 - APK
 - Operating system: Android 6.0.1 (on Samsung S5)
 - Browser: n/a (Android App)

## How to reproduce

1. Install Android App
2. Import Channel ID (I was using 93a5bfcfa2a74962be843288aefcfc0e) from the Internet.
3. Press cancel.

## Screenshots

https://goo.gl/photos/wxGgdLPx8uwfsZ6fA

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

This seems like a useful functionality. I'm assuming it's actually canceling on the backend, so perhaps not that problematic in terms of actually being able to use the app.

**Comment by laurenlichtman** [comment] 2017-06-16 00:35
The same thing occurred when importing a much smaller channel (8e06f21efdf23ffab4b026f674a8c442) on a Pixel (Android 7.1.2).

**Comment by jonboiser** [comment] 2017-06-20 18:57
@laurenlichtman This is a known issue on all platforms. @aronasorman Do you know the root cause of this and will it be fixed with the new task queue?

**Comment by indirectlylit** [comment] 2017-06-22 23:53
Note, this is still an issue post-iceqube

**Comment by rtibbles** [comment] 2017-08-24 16:13
Fixed in #2003

**Closed by rtibbles** 2017-08-24 16:13 UTC
Labels: TASK: bug
