### ISSUE TITLE
On Profile Page, leaf SVG shows at full screen before it is cached

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5240] opened 2019-03-04 21:40 UTC
### Observed behavior

GIF begins when screen goes white. The Leaf SVG flashes briefly and occupies the entire page.

![kapture 2019-03-04 at 13 38 19](https://user-images.githubusercontent.com/10248067/53764750-fe063100-3e82-11e9-9bdf-132a90ac10c9.gif)

### Expected behavior

Leaf SVG does not load too early and flash the way it does in the GIF.

### Steps to reproduce

This happens only when you refresh on profile page, or visit it for the first time in a session.

### Context
0.12

**Comment by jonboiser** [comment] 2019-03-04 21:41
I'm actually not seeing this on Kolibribeta. Is this yet another devserver-only phenomenon?

**Comment by rtibbles** [comment] 2019-03-04 21:43
If it was in hot mode, it could well be a flash of unstyled leaf caused by the dynamically injected styles we use for hot mode.

**Comment by indirectlylit** [comment] 2019-03-06 00:50
closing as a hot reload fluke

**Closed as completed by indirectlylit** 2019-03-06 00:50 UTC
