### ISSUE TITLE
Cannot export channels to a flash drive

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8251] opened 2021-08-02 12:30 UTC
## Observed behavior
I can't export channels to a flash drive as I'm constantly getting the following message: Could not find a writable drive connected to the server

## Expected behavior
It should be possible to export my channels.

## Steps to reproduce the issue
1. Install the following 0.15 alfa 2 build: https://buildkite.com/organizations/learningequality/pipelines/kolibri-windows/builds/1522/jobs/4d506e7c-949f-49ab-9824-32320614996a/artifacts/57eee854-a0f7-4743-baed-0b464a56c21c
2. Go to Device>Channels>Options and select the Export channels option
3. Select a channel and click Export

## Additional information

![2021-08-02_15-26-57](https://user-images.githubusercontent.com/79847249/127862825-76502967-c5e2-4556-afd9-693cbe05dfe6.png)

## Errors and logs
[logs.zip](https://github.com/learningequality/kolibri/files/6916892/logs.zip)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by pcenov** [comment] 2021-08-02 12:30
https://learningequality.testquality.com defect [D4](https://learningequality.testquality.com/project/12317/result/2456386/defect/8033).

**Comment by radinamatic** [comment] 2021-08-06 04:17
I can replicate this on both Windows 10 and on my Ubuntu dev VM on branch 0.15.x.

It gives 500 error on `/api/tasks/tasks/localdrive/` with `AttributeError: 'dict' object has no attribute 'id'`

Windows 10 | Ubuntu dev VM
--- | ---
![Win10 (start)  Running  - Oracle VM VirtualBox_019](https://user-images.githubusercontent.com/1457929/128454940-c7b4bf16-9523-4491-a0a8-311ac5894ef7.png) | ![LEDev2104 (start)  Running  - Oracle VM VirtualBox_014](https://user-images.githubusercontent.com/1457929/128455060-5ac4e81f-d9ed-4b6f-833c-9a3a9250bb56.png)

cc @rtibbles (and @jredrejo since we discussed it on Slack)

**Comment by rtibbles** [comment] 2021-08-06 06:21
Could you attach log files for this so we can see the full traceback?

**Comment by radinamatic** [comment] 2021-08-06 07:36
This is from my dev VM, let me know if you need the logs from the Win 10 one too.

[debug.txt](https://github.com/learningequality/kolibri/files/6943939/debug.txt) (full debug.txt was huge, I copied only the relevant day)
[kolibri.txt](https://github.com/learningequality/kolibri/files/6943940/kolibri.txt)

**Comment by pcenov** [comment] 2021-08-26 10:30
@radinamatic and @rtibbles the channel export functionality is now working correctly in this [build](https://buildkite.com/learningequality/kolibri-windows/builds/1751) - - drives are displayed correctly and I am able to select one and export channels.

**Comment by radinamatic** [comment] 2021-08-26 13:59
A bug that fixed itself...? 😛

**Comment by rtibbles** [comment] 2021-08-26 14:27
There was another issue opened at one point that seemed to be non-reproducible where an external drive suddenly became unfindable during export, I wonder if this is another manifestation of that?

**Comment by pcenov** [comment] 2021-08-26 15:03
I guess I was too happy to see it working but now I have to report that both channel export and import to a flash drive are not working and I'm getting the 500 errors in the console while I can still see that the flash drive is correctly attached to the device and is accessible. Tried restarting Kolibri and tried with different channels. Here are the logs:
[logs.zip](https://github.com/learningequality/kolibri/files/7060691/logs.zip)

**Comment by rtibbles** [comment] 2021-09-02 15:49
Fixed in #8369

**Comment by pcenov** [comment] 2021-09-07 14:22
@radinamatic today I retested this as part of the daily regression test run on the following [build](https://buildkite.com/learningequality/kolibri-python-package/builds/3559) and strangely enough the export/import is not functioning again:
![2021-09-07_13-21-32](https://user-images.githubusercontent.com/79847249/132361046-8cc5f72d-db30-4061-88d0-4be7bf67ae26.png)
Tested in Win 10, Ubuntu and Android

**Comment by radinamatic** [comment] 2021-09-07 14:28
Thank you @pcenov! 

Reopening as the issue has raised it's ugly head again 😒

**Comment by rtibbles** [comment] 2021-09-14 21:44
This issue was so good, I fixed it twice!

**Comment by rtibbles** [comment] 2021-09-14 21:44
Fixed in #8425

**Closed as completed by rtibbles** 2021-09-14 21:44 UTC
Labels: bug, P0 - critical
