### ISSUE TITLE
Importing channels turns the page unresponsive and freezes the server

### ISSUE THREAD

**Issue by jinchuika** [learningequality/kolibri#3028] opened 2018-01-04 16:27 UTC
### Observed behavior
Channels can't be downloaded from the import section, the server freezes and stops working.

### Context
This was tried with the 0.7 version installed from the .deb package and also with the 0.7 downloaded from the repository on Ubuntu 17.04 while trying to download the Khan Academy (es) channel.

This error doesn't occur when Kolibri is installed from the .whl file. We installed it with `pip install kolibri-0.7.0-py2.py3-none-any.whl` and then ran it with `python -m kolibri start`. This method works, but there isn't an option to make it run at boot.

**Comment by rtibbles** [comment] 2018-01-04 16:36
@jinchuika would you be able to attach the `kolibri.log` file from when this happened?

**Comment by jinchuika** [comment] 2018-01-09 15:20
Sure,

```
INFO 2018-01-09 08:42:48,566 cli Going to daemon mode, logging to /var/kolibri/.kolibri/server.log
INFO 2018-01-09 08:42:49,729 utils Started new MESSAGEPROCESSOR thread ID#jersey-romeo-fifteen-two
INFO 2018-01-09 08:42:49,730 utils Started new SCHEDULER thread ID#edward-montana-snake-bluebird
INFO 2018-01-09 08:42:49,730 utils Started new WORKERMESSAGEHANDLER thread ID#jig-jupiter-hot-carbon
INFO 2018-01-09 08:42:50,304 ping Attempting a ping.
INFO 2018-01-09 08:42:50,430 ping data: {"language": "es-es", "uptime": 0, "system_id": "", "mode": "", "sysversion": "3.5.3 (default, Nov 23 2017, 11:34:05) \n[GCC 6.3.0 20170406]", "version": "0.7.0", "database_id": "a702b695134e42139c1494c365e78280", "instance_id": "38c9fafdd3e9a9cf7bc61e0e68acbf2e", "platform": "Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty", "node_id": "a55c63c3049d1f47608c"}
WARNING 2018-01-09 08:43:50,593 ping Ping failed (connection timed out). Trying again in 15.0 minutes.
INFO 2018-01-09 08:58:50,608 ping Attempting a ping.
INFO 2018-01-09 08:58:50,684 ping data: {"language": "es-es", "uptime": 16, "system_id": "", "mode": "", "sysversion": "3.5.3 (default, Nov 23 2017, 11:34:05) \n[GCC 6.3.0 20170406]", "version": "0.7.0", "database_id": "a702b695134e42139c1494c365e78280", "instance_id": "38c9fafdd3e9a9cf7bc61e0e68acbf2e", "platform": "Linux-4.10.0-42-generic-x86_64-with-Ubuntu-17.04-zesty", "node_id": "a55c63c3049d1f47608c"}
INFO 2018-01-09 08:58:51,169 ping Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.
WARNING 2018-01-09 08:59:09,273 api Did not find language code None in our le_utils.constants!
WARNING 2018-01-09 08:59:09,274 api Did not find language code None in our le_utils.constants!
INFO 2018-01-09 08:59:28,150 importchannel Downloading data for channel id c1f2b7e6ac9f56a2bb44fa7a48b66dce
```

**Comment by lyw07** [comment] 2018-01-09 22:02
Hi! The Debian installer uses Python 3 to run Kolibri, and there is a built-in package `urllib3` in Python 3 that is relatively older than the version we bundled inside Kolibri. This older version of `urllib3` caused the channel not being downloaded fully. 

To confirm that your issue is caused by this older version of urllib3, please try the following commands:
```
> python3
>>> import urllib3
>>> urllib3.__version__
```

The version of your system built-in `urllib3` could probably be 1.15.1, or something older than 1.22, which is the version we bundled inside Kolibri.


We are planning to release 0.7.1 soon that will fix this issue, but I'm not sure if we are going to have a Debian installer for 0.7.1 (@benjaoming, do you know if we will have that? Thank you!).

If you want to use the 0.7.0 debian installer now, my suggestion would be to upgrade your system's `urllib3` by doing:
```
> service kolibri stop
> sudo su kolibri
> pip3 install urllib3==1.22
> service kolibri start
```

**Comment by benjaoming** [comment] 2018-01-09 22:14
@lyw07 yes, I agree that this would be fixed because PYTHONPATH was re-ordered in https://github.com/learningequality/kolibri/pull/2808

Yes, 0.7.1 will also ship an updated version -- @jinchuika you can subscribe to our PPA if you didn't do that already: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri/

(Or the PPA for testing stuff: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed/ )

**Comment by jinchuika** [comment] 2018-01-11 20:34
The solution given by @lyw07 worked!

@benjaoming Yes, I already did. Thanks :smile:

**Comment by indirectlylit** [comment] 2018-01-14 21:01
is this a duplicate of #2805?

**Comment by lyw07** [comment] 2018-01-15 00:31
@indirectlylit I think they are very similar issues, in which due to the order of the PYTHONPATH, we are using Ubuntu's relatively old system packages instead of the ones we bundle inside Kolibri. If I remember correctly, #2805 is because of `cryptography`, and this issue is related to `urllib3`.

**Comment by indirectlylit** [comment] 2018-01-15 22:08
more to the point, is this issue fixed by #2808?

**Comment by lyw07** [comment] 2018-01-16 04:06
yes I think so

**Comment by indirectlylit** [comment] 2018-01-16 06:45
thank you!

**Closed by indirectlylit** 2018-01-16 06:45 UTC
Labels: DEV: distributions
