### ISSUE TITLE
import/export: supposedly available content cannot be exported

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2806] opened 2017-12-04 17:26 UTC
### Observed behavior

I apparently have contents but cannot export them:

![image](https://user-images.githubusercontent.com/2367265/33566460-ea884164-d8d4-11e7-8d76-484de6bd62fe.png)

![image](https://user-images.githubusercontent.com/2367265/33566529-1d60a20c-d8d5-11e7-896b-49a5bae47bc9.png)

### Expected behavior

If I have content, it should be exportable

### User-facing consequences

broken/confusing behavior

### Errors and logs

none

### Steps to reproduce

unknown

### Context

* Kolibri version: 0.7-beta5
* Operating system: osx
* Browser: chrome

**Comment by lyw07** [comment] 2017-12-04 18:54
Will try to replicate this

**Comment by lyw07** [comment] 2017-12-04 19:30
@jonboiser Is it possible to filter the channels in the export page with the new implemented "available" field in the channelmetadata? Thank you!


Steps to reproduce the issue:
1. Import channel 'portion control' with id `fb51dae6df7545af8455aa3a0c32048d`
2. Go to the public channel page and select 'khan academy (en)` to download the database
3. Click `export` and go to the `khan academy (en)` page

**Comment by jonboiser** [comment] 2017-12-04 19:50
@lyw07 Let me check. I think at the moment it filters Exportable Channels based on `resources_on_device > 0`. What is the difference if I were to use `available === true`?

**Comment by lyw07** [comment] 2017-12-04 20:10
@jonboiser I think the difference is that, when the "khan academy (en)" has shared resources with the channel "portion control", and we download all the content from "portion control" and only the database from "khan academy (en)", for "khan academy (en) channel, it will has "resources_on_device" greater than 0. But since its content has never been actively downloaded by a user, its field "available" will be marked as `false`. 

I think the problem caused the issue shown in the picture is that since we don't actively import the content from channel "khan academy (en)", only the resource nodes have "available" marked as `true` but not the top level topic nodes. So I guess during export, since we check the top level's topic nodes' availability, and they are not available, the topic nodes are thus not shown here. If we can prevent the users from exporting the channels that are not actively imported by them, I guess we can avoid this issue? Please let me know if I don't explain clearly or miss anything. Thanks!

**Comment by jonboiser** [comment] 2017-12-05 00:37
@lyw07 Okay, I'll change it to use the available flag. But is this the theory on how we get to this scenario?

1. Download a Channel A that shares ContentNodes with Channel B.
1. Click "Export", then select Channel B (which shows up erroneously because we are not using the `available` flag)
1. Expect to see Nodes to export, but see none (since teh child nodes have `available: false`).

**Comment by lyw07** [comment] 2017-12-05 00:39
@jonboiser yes I think so. Thank you!

**Closed** 2017-12-05 10:54 UTC
