### ISSUE TITLE
Displaying English as an option for UI when it's *not* available

### ISSUE THREAD

**Issue by Lito-Frito** [learningequality/kolibri#10124] opened 2023-02-16 19:05 UTC
## Observed behavior

When English is not an option for the UI (e.g. because a language list was hard-coded as envars), it seems that English still shows up as an option. 

Furthermore, clicking on it returns that the resource is not found. I've confirmed with @rtibbles that English should not be an option if it's not available, so it seems the front-end should not include it as an option. 

Here are screenshots of the UI when only French was passed as an envar for languages/the UI setting:

![image](https://user-images.githubusercontent.com/56422761/219460781-6b0fcfcd-22ac-4a16-86a4-9973466bff92.png)
![image](https://user-images.githubusercontent.com/56422761/219461154-3fe7af27-e24c-44f6-8686-9a89e2a9de6e.png)

## Errors and logs

N/A

## Expected behavior

Expected behavior per @rtibbles is that English **not** be displayed if it's not actually available/passed as an option

## User-facing consequences

User sees superfluous UI/language options; user could also be misled about options in which the app's UI is available in

## Steps to reproduce

I passed `["fr-fr"]` as an envar (via Terraform/BCK) to test the new UI language filter and noticed that English was always present as an option, even when not loaded/passed as an envar.

## Context

* Kolibri version
 0.15
 
 * Operating system
 Linux Mint 20.3 x86_64
 
 * Browser
 Firefox for Linux Mint: V 109.0.1 (64 bit)

**Comment by akila-i** [comment] 2023-02-27 17:05
Hi @crc8109 , I'm new to this kolibri community, and I like to learn more about this issue and give it a try if I could. I'm familiarized with Terraform as well. However, can you point me to somewhere that I can learn to reproduce the error in a bit more detail please? :)

**Comment by rtibbles** [comment] 2023-02-27 17:20
Hi @Akila-I - this can also be reproduced outside of a Terraform environment! If you set the `KOLIBRI_LANGUAGES` environment variable to `fr-fr` and then run Kolibri, you should be able to reproduce this.

I believe the issue is probably happening in the frontend, and English is being shown as a language option by default, regardless of whether it has been enabled.

**Comment by akila-i** [comment] 2023-02-27 17:40
I tried creating a .env file at the root level, then added the following line
```
"KOLIBRI_LANGUAGES"=["fr-fr"]
```

then tried `npm run devserver` . but always redirect to english language

Can you help a little?

**Comment by rtibbles** [comment] 2023-02-27 17:41
You can either set the env var for the session:
```
export KOLIBRI_LANGUAGES=fr-fr
```

Or you can set it inline when running the devserver:
```
KOLIBRI_LANGUAGES=fr-fr yarn run devserver-hot
```

Note we recommend using yarn (v1) rather than npm, because of the way we use yarn to configure our package workspaces.

**Comment by akila-i** [comment] 2023-02-27 17:51
Thanks, I'm able to reproduce the error now. English displays with every language list. I'll see if I can fix it. Can you assign the issue to me?

**Comment by rtibbles** [comment] 2023-02-27 17:51
Have done, thank you!

**Comment by Lito-Frito** [comment] 2023-02-28 02:34
Apologies for the delay @Akila-I but as @rtibbles has explained, it's as you've seen with English always being shown, despite only having one language hard-coded for the UI. Thank you so much for attempting to fix this!!!! Sincerely appreciate!

**Comment by akila-i** [comment] 2023-03-01 14:13
I had a look at the relevant components and figured that this happens because we are importing `defaultLanguage` from `kolibri-design-system/lib/utils/i18n` and use it when declaring the `availableLanguages` object. If we were to initialize `availableLanguages` as an empty object and then assigned languageGlobals to it, The problem seems to disappear. Shall we proceed that way? @crc8109 @rtibbles 


kolibri/core/assets/src/utils/i18n.js
```
export const availableLanguages = {
   [defaultLocale]: defaultLanguage,
};
```
if we went with:
```
export const availableLanguages = {}
```
the behavior of this issue is not appearing.

WDYT?

**Comment by Lito-Frito** [comment] 2023-03-03 18:59
@rtibbles honestly, I'm not too sure if there's any harm in implementing this way. Does this seem like it makes sense?

**Comment by akila-i** [comment] 2023-03-05 07:20
the application seems to work without the issue. however several test cases get failed because of this change. I'll have a look at the test cases and provide an update here.

**Comment by Lito-Frito** [comment] 2023-03-06 20:36
Wow, amazing progress nonetheless @Akila-I . Thank you so much for continuing to debug, it is sincerely much appreciated

**Comment by akila-i** [comment] 2023-03-30 09:23
Hey guys, I was a little busy with my GSoC proposal.
I'm going through the failed test cases arose from the change I mentioned in a previous comment.

when testing the `DeviceSettingsPage` component, (`kolibri/plugins/device/assets/src/views/DeviceSettingsPage/__test__/DeviceSettingsPage.spec.js` directory), it expects the following in the test case

`expect(data.language).toMatchObject({ value: 'en', label: 'English' });`

should this still be valid to use in this way? Either we should test the default language in a different way, or we should set the backend to hardcode English as the default language, even if the language list is overridden with a list that doesnt contain English.

A decision from design level is appreciated.

**Comment by Lito-Frito** [comment] 2023-03-31 03:13
No worries! Hope the proposal went well.

Good question @Akila-I . This is def something for the dev team here to comment on. Richard has been out sick this week but when he's back in, I'll ask him about this. 

Thank you so much for everything!

**Comment by akila-i** [comment] 2023-03-31 06:23
Thanks @crc8109 , I believe I have a shot with the proposal.
Wish Richard speedy recovery, and hope an update when he's back.

Always glad to contribute !

**Comment by rtibbles** [comment] 2023-04-10 18:04
Hi @Akila-I - unless the test is failing once you have your fix in place, it should be OK. The default language in the frontend is still English (redundantly with the backend) so this test may still pass, especially as these frontend tests run independently of the backend. You would only need to worry about this if you made the change to fix the behaviour, and the test was now failing.

**Comment by akila-i** [comment] 2023-04-11 06:33
Yes, @rtibbles , I made above mentioned change to fix the behaviour and the test got failed. Shall I make a PR and review there?

**Comment by rtibbles** [comment] 2023-04-11 15:14
Yes please!

**Comment by akila-i** [comment] 2023-04-11 16:38
Hi everyone, I was about to make a PR with my changes, and when trying out the changes again I met with an issue with the `change language` button. I noticed that it has been created as an issue here #10407 and is not fixed yet.
Maybe we need to wait on that?

**Comment by rtibbles** [comment] 2023-04-11 16:41
Ah yes, that does rather seem like a blocker!

**Comment by varunsh17** [comment] 2023-04-12 10:06
@Akila-I Thanks for providing related information. I am working on #10407 and will update you once that issue is resolved.

**Comment by varunsh17** [comment] 2023-04-20 04:19
> Ah yes, that does rather seem like a blocker!

The issue is now solved and merged.

**Comment by akila-i** [comment] 2023-04-20 04:26
> > Ah yes, that does rather seem like a blocker!
> 
> The issue is now solved and merged.

Thanks @varunsh17 for the update

**Comment by akila-i** [comment] 2023-04-27 13:21
Hi @rtibbles , I have made a PR with the change I did to resolve this issue. We can discuss there and made further improvements.

**Closed as completed** 2023-06-09 15:18 UTC
Labels: TAG: cloud
