### ISSUE TITLE
Add regression testing for channel update deletion behaviour

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#5960] opened 2019-09-27 17:54 UTC
Ref: https://github.com/learningequality/kolibri/pull/5853/files/b0104f3ef0e978f41beddf090240c4f1b5cafe04..94c5800705a4f5f5b5295de4fb75b9d7e4a75c6e#r329181611

Add a test to ensure that deleting during an upgrade proceeds properly.

**Comment by YashJipkate** [comment] 2021-03-24 06:01
Hi @indirectlylit @rtibbles I would like to take this up.

I had a doubt as to where should I place the tests. Should it be in a new file (something like `test_channel_update_deletion.py`) or in the `test_channel_import.py`?

**Comment by jonboiser** [comment] 2021-03-25 21:39
@YashJipkate I think if it's more convenient, you can just add a new test case to an existing module like `test_channel_import`

**Comment by muhammadalics** [comment] 2021-04-09 05:18
@YashJipkate Are you working on this issue? If not, can I work on it?

**Comment by YashJipkate** [comment] 2021-04-09 05:47
@muhammadalics currently no, but I was planning to resume it post the GSoC application period. But if you want to work on it, then feel free to go ahead. And let us know if you are up for it.

**Comment by Pursottam6003** [comment] 2023-03-31 13:05
Hii i would like to work on this issue please assign me the issue @marcellamaki

**Comment by MisRob** [comment] 2023-04-05 10:57
Hello @Pursottam6003, thank you for your interest. As you volunteered for more issues and already have some of them assigned, I'm leaving this unassigned for now in case someone else wanted to tackle it as you're working on other issues. When your plate is empty, if this issue is still available, please remind yourself here and we can assign it to you.

**Comment by nikkuAg** [comment] 2023-09-08 11:09
Hi, is this issue still open? I would like to work on it.

**Comment by rtibbles** [comment] 2023-09-11 15:53
Yes, these tests have not been written yet! I will assign you.

**Comment by nikkuAg** [comment] 2023-09-25 14:32
Hey,
Can you help me with how to write the regression test.

**Comment by MisRob** [comment] 2023-09-28 11:10
Hi @nikkuAg, what exactly would you need to know at this point?

**Comment by nikkuAg** [comment] 2023-10-24 08:28
@MisRob, I wanted to know how to write the test. Could you share some resources?

**Comment by LianaHarris360** [comment] 2023-10-24 19:37
Hi @nikkuAg There are [some available tests](https://github.com/learningequality/kolibri/blame/e7c0d65526e09e7125c32c8b695da9f7caecf6de/kolibri/core/content/test/test_channel_import.py#L645) for the deletion of channel related metadata during an upgrade. The first step would involve looking over these tests to identify any additional areas that have not been covered. You may also find helpful information about running automated tests in Kolibri [here](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#automated-testing:~:text=Kolibri%20comes%20with%20a%20Python%20test%20suite%20based%20on%20pytest.%20To%20run%20all%20back%2Dend%20tests%3A). I hope this helps!

**Comment by aarishshahmohsin** [comment] 2023-12-15 08:41
Can I be assigned this issue?

**Comment by marcellamaki** [comment] 2023-12-15 15:02
Hi @aarishshahmohsin - yes, thank you for your interest. I will assign you. Let us know if you have any questions. 

Learning Equality will be closed for the end of the year from December 22 - January 2. Our team may be slower to respond during this time.

**Comment by yashpandey002** [comment] 2024-01-14 09:35
Hey @marcellamaki, I went through the whole conversation of the issue and it seems to me that the task still remains to work as I also didn't find any linked PR with the issue. If it's still open can you please assign it to me? I would love to contribute.

**Comment by AlexVelezLl** [comment] 2024-01-15 13:29
Hi @yashpandey002! Sure!  I have assigned the issue to you. Thanks for your interest in contributing to Kolibri :open_hands: Please let us know if you have any questions.

**Comment by yashpandey002** [comment] 2024-01-15 13:39
Thanks, @AlexVelezLl, and ya I will let you know if I have any queries👐

**Comment by yashpandey002** [comment] 2024-01-16 12:46
Hey @AlexVelezLl, actually I am having difficulty setting up the repository locally, it's showing me some errors related to some Python libraries not found. 

I went through the Github discussions but didn't find any solution to my problem and now I am confused about where to ask this query as it is related to the setup and not issue-specific. Please guide me about this.

**Comment by ozer550** [comment] 2024-01-16 12:50
Hi @yashpandey002! Did you follow the following [step](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#install-python-dependencies) and install the Python dependencies?

**Comment by yashpandey002** [comment] 2024-01-16 13:25
Hey @ozer550 actually I was following the setup steps and when I tried setting up the virtual environment with pyenv(as it is recommended in docs) by following these instructions: https://kolibri-dev.readthedocs.io/en/develop/howtos/installing_pyenv.html I got some errors and not able to set up the virtual environment

- I am using Fish shell so I did all the required steps for it and successfully installed the Pyenv.
- But when I tried installing a Python version using pyenv by this command: pyenv install 3.9.9, it gave me a long error of some libraries not found.
- The libraries this error pointing to are: bzip2, ncurses, libffi, and OpenSSL, but when I checked I found that all the libraries are already installed

If you want I can show you the exact error but I am not sure about how should I do it, like should I copy-paste the whole error here?

**Comment by ozer550** [comment] 2024-01-16 13:31
I was wondering if you installed all the pre-requisites mentioned by pyenv [here](https://github.com/pyenv/pyenv/wiki/Common-build-problems#prerequisites)?

**Comment by yashpandey002** [comment] 2024-01-16 14:35
Looks like after following the prerequisite instructions I have successfully installed the 3.9.9 version of Python with pyenv but now when I try to activate the virtual environment by this command: "pyenv activate kolibri-py3.9" it showing me: "pyenv-virtualenv: prompt changing not working for fish" and when I tried it again it showed: "pyenv-virtualenv: version `kolibri-py3.9' is already activated". So I am not sure if it is working fine or not?

I searched for the "prompt changing not working for fish" and found this thread: https://github.com/pyenv/pyenv/issues/1723 where it seems like they have closed it already

**Comment by rtibbles** [comment] 2024-01-16 15:40
If you type `python --version` if it outputs `3.9.9` then the venv should be activated (unless that's your system Python version!).

**Comment by yashpandey002** [comment] 2024-01-16 18:08
Thanks @rtibbles, when I executed the python --version command in Kolibri command it gave me 3.9.9(which I tried installing), and when I executed the same command in my global terminal it gave me 3.11.7, so now I am good to go right?

**Comment by rtibbles** [comment] 2024-01-16 18:28
Seems so!

**Comment by yashpandey002** [comment] 2024-01-18 12:08
![image](https://github.com/learningequality/kolibri/assets/75162407/caa96ef2-b9fa-42f5-a019-676baf223ffd)
Can anyone please help me with this error, I can't exactly understand what it is trying to say, all I can understand is that the "yarn run build-base --mode=development --watch" command is failing.

**Comment by jredrejo** [comment] 2024-01-18 16:14
The error is described in the line mentioning the `git describe --tags` command . For some reason you've tagged your version code in your repo and does not match current kolibri version schema.

https://git-scm.com/docs/git-describe shows the latest version tag in the git repository, I get `v0.16.0-beta10-116-gbad3d07cf2` in my local repository . I guess you have added more tags that are not in sync with the version file of the repo.

**Comment by thesujai** [comment] 2024-02-08 10:24
can i be assigned to this?

**Comment by AlexVelezLl** [comment] 2024-02-08 17:57
Sure! @thesujai. I will assign this issue to you :).

**Comment by thesujai** [comment] 2024-02-10 19:26
Hello 👋🏽 
Just to clarify my approach and my understanding
For a test case lets call it `ChannelImportDeleteTestCase`, I will have following methods(tests)(All centered arround `check_and_delete_existing_channel()`):

1. Test case when channel already exists
2. Test case to check and delete an existing channel during partial import
3. Test case to check and delete an existing channel with an older version(verifies that the appropriate methods are called to delete the old channel data)
4. Test case when the channel being imported has the same or newer version already present in the database.
5. Test case to check if the existing channel is deleted when the channel does not exist.

@rtibbles If my approach seems okay, then also let me know which branch to target the PR, it is often unclear with the labels

**Comment by rtibbles** [comment] 2024-02-12 16:18
Yes, all looks correct. For (2) just to clarify that doing a partial import over a full import should not trigger a deletion, but doing a full import over a partial import should.

This work should be targeted to develop.

**Closed as completed** 2024-03-02 00:42 UTC
Labels: TAG: tech update / debt, P2 - normal, DEV: backend, TAG: unit tests, help wanted, good first issue
