### ISSUE TITLE
previous content disappears if import of new content is canceled

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4005] opened 2018-07-09 23:34 UTC
### Observed behavior

* was working on a Pi, which already had some KA content loaded on it
* updated the content DB, which was out-of-date
* selected some new content to import, and started the import
* waited a while; then canceled the import

at this point, I could no longer see the KA channel in either Learn or Device

However, when I went to reimport, it seemed to still know about it:

![image](https://user-images.githubusercontent.com/2367265/42481172-d48df176-8395-11e8-9071-05b42a95d277.png)

### Expected behavior

Existing content should not disappear

### User-facing consequences

frustration and potential for lost content

### Steps to reproduce

see above

### Context

0.10.0

**Comment by lyw07** [comment] 2018-10-24 21:03
I think the issue is originally because the channel was updated. After the channel was updated, all the local files of the channel were marked as unavailable. But this was fixed in 0.10.2: https://github.com/learningequality/kolibri/pull/4123

For the part: `waited a while; then canceled the import`, unfortunately I'm not able to reproduce this. After I cancelled the import of two files, I can see from the Learn that one of the files was actually imported. 

However, in the latest pex from release-0.11 branch, I found another issue. 
After the channel was updated, the local files are successfully marked as available. But the Resources/Size of `On your device` are still 0. 
<img width="986" alt="screen shot 2018-10-24 at 2 01 07 pm" src="https://user-images.githubusercontent.com/19424916/47461324-62a6d600-d795-11e8-8af1-9eb5910f7879.png">

I assume this would be something related to front-end? Do you think I should create a new issue for it? Thank you!

**Comment by jonboiser** [comment] 2018-10-24 21:11
@lyw07 	Could you take a look at the response from `api/devicechannel` to make sure its `on_device_files/resources` is correct?

**Comment by lyw07** [comment] 2018-10-24 21:14
Hi @jonboiser the endpoint `api/devicechannel` doesn't exist on my side. I'm now running the pex from the release 0.11 branch. Do you know if it's named to something else? Thanks!

**Comment by jonboiser** [comment] 2018-10-24 21:18
It should look like this in the network tab: `device/api/device_channel/1ceff53605e55bef987d88e0908658c5/?include_fields=total_resources%2Ctotal_file_size%2Con_device_resources%2Con_device_file_size&1540415826085=1540415826085`

**Comment by lyw07** [comment] 2018-10-24 21:19
thank you! Here is what I get:
```
{
    "author": "",
    "description": "",
    "id": "3eb71b96aae544a88f78b9728fb59685",
    "last_updated": "2018-10-24T14:00:51.560298-07:00",
    "lang_code": "ab",
    "lang_name": "аҧсуа",
    "name": "Only one node",
    "root": "3eb71b96aae544a88f78b9728fb59685",
    "thumbnail": "",
    "version": 19,
    "available": true,
    "num_coach_contents": 0,
    "total_resources": 3,
    "total_file_size": 11123641,
    "on_device_resources": null,
    "on_device_file_size": null
}
```

**Comment by jonboiser** [comment] 2018-10-24 21:24
I wonder why `on_device_resources/file_size` is `null`. This should only happen if on the Python serializer size, this field is assigned `None`.

**Comment by lyw07** [comment] 2018-10-24 21:33
Yes in the device page, the channel size is shown as 0. It's weird because if it's 0, then the channel shouldn't show up.
<img width="522" alt="screen shot 2018-10-24 at 2 32 30 pm" src="https://user-images.githubusercontent.com/19424916/47462964-bddac780-d799-11e8-82fe-40ff3e208822.png">


I think this is actually back-end related. Will investigate on this more. Thank you for the help!

**Closed as completed** 2018-10-26 22:53 UTC
