### ISSUE TITLE
'last activity' can be in the future

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5079] opened 2019-02-16 01:56 UTC
### Observed behavior

Noticed that the 'last activity' column very briefly said "in 3 seconds", indicating a negative value:

![image](https://user-images.githubusercontent.com/2367265/52892752-7615ec80-314a-11e9-9cb6-bfeac5533f0b.png)

### Expected behavior

We should determine how it happened that the value went negative and prevent it.

One thing to be particularly careful of is that we're always comparing server time to server time, and never server time to client time because they could be very different. This bug might be due to that.

Let's also add a gherkin story that explicitly tests various parts of the app when the server and client times are different. (cc @radinamatic @mrpau-dev)

### User-facing consequences

If server and client times are very different, values in this column may be days or even years off

### Steps to reproduce

unknown, but possibly try changing your local computer time and then browsing the beta server (assuming the theory above is correct)

### Context

0.12.0 beta 6

**Comment by indirectlylit** [comment] 2019-02-21 01:45
let's just check for worst-case scenario

**Comment by jonboiser** [comment] 2019-02-25 20:57
I have just seen, in a single session of the same user one resource being something reasonable like "10 min ago", and then another resource (same session, same user) have something in the future like "in 15 minutes", and the videos were viewed within minutes of each other.

But then I logged out/in and the next video had an accurate-looking last activity time.

**Comment by jredrejo** [comment] 2019-02-27 18:18
This problem seems to have the same origin than #5113

**Comment by rtibbles** [comment] 2019-02-27 20:52
This may be partially resolved by #5198, but I am doing some follow up work.

**Comment by rtibbles** [comment] 2019-02-28 00:11
This is caused by a bug in the server time setting code. To replicate this follow these steps:
1) Login.
2) Walk away for ten minutes (or more) leaving the browser tab open - perhaps have a nice soothing cup of tea?
3) Come back.
4) Do anything with any content.
5) Observe the last activity to be ~`<however long you went away for>` in the future.

**Comment by rtibbles** [comment] 2019-02-28 02:39
Fixed in #5210.

**Closed as completed by rtibbles** 2019-02-28 02:39 UTC
Labels: P1 - important
