### ISSUE TITLE
The letters run over the images of the question in KA Hi Channel.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1767] opened 2017-06-29 15:39 UTC
## Summary

The letters run over the images of the question in KA Hi Channel.

e890b1acbcad44939688dbb1b7dde2e5

गणितकक्षा 7 (India)--->आंकड़ों का प्रबंधन--->  संयोग और प्रायिकता--> सरल प्रायिकता 

## System information
 - Version: Kolibri 0.4.1
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Navigate to the above topic.
2. Start solving questions and after 5 questions , you will notice the test running over images.

## Screenshots
![1](https://user-images.githubusercontent.com/13453618/27696460-494bd784-5d0f-11e7-98ab-f02f576cfb59.png)
![2](https://user-images.githubusercontent.com/13453618/27696461-499c76a8-5d0f-11e7-92c0-f291566f5a20.png)

**Comment by rtibbles** [comment] 2017-06-29 23:32
@harishbalachandran this is intended behaviour, as can be seen on this question on KA: https://hi.khanacademy.org/math/in-in-grade-10-ncert/in-in-chapter-15-probability-2/copy-of-probability-basics/e/probability_1

![image](https://user-images.githubusercontent.com/1680573/27714797-166ace82-5ce8-11e7-9cbb-9f0f8b887296.png)

The main difference is that we have the Hindi translations for the labels, which are translated as 'blue part' rather than just 'blue', which makes them overly long.

In addition, there is an issue with the way the text is rendered that is internal to MathJax, the renderer that the exercises renderer uses (KA have their own library KATeX that tries to render it, but it fails with non-Western character sets, such as Hindi).

Relevant issues on MathJax and KATeX:

https://github.com/mathjax/MathJax/issues/474#issuecomment-38324717
https://github.com/Khan/KaTeX/issues/729

The only thing that can be fixed here (but again, not internally to Kolibri), is for the Hindi translations to be shortened just to 'blue' etc. rather than 'blue part'.

**Comment by rtibbles** [comment] 2017-06-29 23:34
Closing as can't fix within Kolibri.

**Closed by rtibbles** 2017-06-29 23:34 UTC
