### ISSUE TITLE
Develop - Setup wizard is broken

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9427] opened 2022-05-13 15:01 UTC
## Observed behavior
While routinely checking the latest develop [build](https://buildkite.com/learningequality/kolibri-python-package/builds/5470) I noticed that the Setup wizard is no longer working. I checked the previous builds and it's this [build](https://buildkite.com/learningequality/kolibri-python-package/builds/5459) that's introducing the issue.

## Expected behavior
Fully functional Setup wizard.

## Steps to reproduce the issue
1. Install the following [build](https://buildkite.com/learningequality/kolibri-python-package/builds/5459)
2. Attempt to go through the Setup wizard
3. I'm unable to proceed after selecting an option at 'How are you using Kolibri?'

## Screenshots
![2022-05-13_14-28-15](https://user-images.githubusercontent.com/79847249/168311483-e4a5340d-0a0d-407c-847e-bd278f1f53cd.png)

## Usage Details
Ubuntu - Chrome

**Comment by pcenov** [comment] 2022-05-13 15:01
@radinamatic

**Comment by jredrejo** [comment] 2022-05-13 16:32
@nucleogenesis I think this is caused by https://github.com/learningequality/kolibri/pull/9405 Just let me know if you prefer to take this issue or assign it to me without any problem

**Comment by nucleogenesis** [comment] 2022-05-13 16:56
Sorry Peter - I should have noted that the setup wizard will be undergoing maintenance for a bit and may be a bit broken for a while as we make our changes. It may be worth skipping it during routine tests of develop for a few sprints.

**Comment by nucleogenesis** [comment] 2022-05-16 18:17
ETA 2-4 weeks before Setup Wizard is fully functional again - closing this issue for now

**Closed as completed by nucleogenesis** 2022-05-16 18:17 UTC
Labels: P0 - critical
