### ISSUE TITLE
"Great work" modal pops up and interrupts reading of an HTML5 app

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#1727] opened 2017-06-25 00:56 UTC
## Summary

We mark completion and award points for simply spending a short period (10, 15 seconds?) on a PDF or HTML5 app, as we have no better way to track. However, it doesn't seem to make sense for these content types to pop up with a "congrats! next item..." message, as nothing in particular has been accomplished yet, and it's likely the person is still reading.

We probably want to make the showing of that modal configurable by content renderer.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.4.0beta10.dev396
 - Operating system: Android 4.4
 - Browser: Webview (Chromium)

## How to reproduce

1. Log in as a learner
1. Go to an HTML5 app
1. Wait, or click around a bit
1. Profit

## Screenshots

![img_20170624_173114](https://user-images.githubusercontent.com/618416/27512899-68865b86-5906-11e7-9790-9200b53676ea.jpg)

**Comment by rtibbles** [comment] 2017-06-25 00:57
Duplicate of #1709.

**Comment by rtibbles** [comment] 2017-08-07 20:44
Closing in favour of #1709

**Closed by rtibbles** 2017-08-07 20:44 UTC
Labels: TASK: ux update
