### ISSUE TITLE
Channel import ends up with "Something went wrong!" page

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#7197] opened 2020-06-26 15:25 UTC
Reported by @cpauya in #7046.

### Observed behavior

_"Re-tried again and this time the import did not proceed and showed a "Something went wrong!" page:"_

![84506736-5d8ff500-acf2-11ea-958f-9387a67a998a](https://user-images.githubusercontent.com/13509191/85873692-c5a20900-b7d1-11ea-974f-44ad37b1a63e.png)

Probably has something in common with

```
21:17:31.263 TypeError: An id must be specified api-resource.js:752
```

Might be related to #7196.

### Expected behavior

Channel import works.

### User-facing consequences

Broken import.

### Steps to reproduce

1. Navigate to [import resources selection](http://127.0.0.1:8000/en/device/#/content/channels)
2. Import a channel

### Context

- Kolibri version: release-v0.14.x branch
- Operating system: macOS v10.14.6 Mojave
- Browser: Firefox v77.0.1
- Python: v3.7.7

**Comment by indirectlylit** [comment] 2020-07-13 22:36
cannot reproduce

**Comment by MisRob** [comment] 2020-07-14 06:42
Thanks for checking this @indirectlylit , I haven't been able to reproduce this either so far.

**Comment by rtibbles** [comment] 2020-07-27 17:36
One replication of this has been pinpointed by @aronasorman as being due to attempting to import a channel database that had channel metadata, but no contentnodes - although this was on a PostgreSQL backed instance, whereby the attempt to import the channel metadata produced foreign key constraint violation because the contentnodes were not present.

**Comment by rtibbles** [comment] 2020-07-27 17:37
I think the issue in the frontend is failing to handle channel metadata import failure properly.

**Comment by MasakoOllivier** [comment] 2020-09-07 18:49
I see this problem on Android 5.1 (BLU). It happens consistently.

Channels > Clicked Import > Selected Local network or internet > Selected a local Kolibri > Clicked on Select Resources > Since the channel listing never shows up on this device (probably too slow), clicked the arrow at the top to go back on page > Clicked the X on the top left corner > The error message "Sorry! Something went wrong!" appears.

Here are the error details from the console:

![image](https://user-images.githubusercontent.com/70489926/92412211-e22abd80-f0ff-11ea-9d6c-f164ab433860.png)

I'd like to note, though, that Android 10 (Nokia 1.3, which is a newer device than BLU) does not have this issue.

**Comment by rtibbles** [comment] 2021-04-05 21:52
Need to add a defensive check that `topic.id` is indeed defined here: https://github.com/learningequality/kolibri/blob/44bf1ed3591321f4b7ef7c4e5c6ceda8c01db7ae/kolibri/plugins/device/assets/src/modules/wizard/handlers.js#L268 if not, should skip straight to the content wizard error state in the `catch` block.

**Comment by pcenov** [comment] 2022-08-02 11:34
@radinamatic this one is no longer being observed in 0.15.6

**Comment by radinamatic** [comment] 2022-08-03 17:08
Closing as not extant in the most recent release.

**Closed as completed by radinamatic** 2022-08-03 17:08 UTC
Labels: P1 - important, APP: Device, TODO: needs QA re-review
