### ISSUE TITLE
Facility page crashed after the upgrade

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3807] opened 2018-06-15 08:49 UTC
### Observed behavior
After the upgrade from 0.7.2 to 0.10.0b2 the facility page crashed.

### Errors and logs
![screen shot 2018-06-15 at 4 48 07 pm](https://user-images.githubusercontent.com/8663934/41459349-f28e92a8-70bb-11e8-810c-f7e1ee3af40b.png)

### Steps to reproduce
* Install the 0.7.2
* Copy the [0.7.2 Kolibri sample data](https://drive.google.com/open?id=1HAJcFr7Yhqj2C8gE88-4gMR7sNJtQiuh) at the `.kolibri`
* Upgrade to 0.10.0b2
* Log in as admin
* Navigate at the facility page.

### Context

Tell us about your environment, including:
 * Kolibri version: 0.10.0b2
 * Operating system: Windows 10
 * Browser: firefox

**Comment by indirectlylit** [comment] 2018-06-15 14:40
duplicate of #3806

**Closed as completed by indirectlylit** 2018-06-15 14:40 UTC
