### ISSUE TITLE
Content import progress bar not reaching 100% 

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#4014] opened 2018-07-10 23:01 UTC
### Observed behavior

The progress bar for importing a content channel via USB stopped at a % below 100% even though it was finished.

### Expected behavior

For cases where the import process has to skip files or import incomplete files, force 100% at the end of import. 

### User-facing consequences

Confusion about the finished or unfinished status of content import

### Errors and logs

…

### Steps to reproduce

1. Export a channel to USB but interrupt it so it doesn't finish
2. On another device, import the channel via USB to Kolibri
3. Expect the progress bar to reach 100% eventually. It doesn't

### Context

Kolibri v0.10
Raspbian (R Pi 3+)
Chromium browser

![img_20180710_143338](https://user-images.githubusercontent.com/5150483/42542060-edb62032-8459-11e8-963f-ed48791d36d3.jpg)

**Comment by jamalex** [comment] 2018-07-10 23:21
>Export a channel to USB but interrupt it so it doesn't finish

Would likely also happen if you export just a subset (not just if you interrupt).

**Comment by lyw07** [comment] 2018-07-10 23:49
Hi! I tried to import an entire channel from Studio to Kolibri, and then export only a subset of the channel to USB. After that, I deleted the entire channel in Kolibri and tried to import the entire channel from USB. I can see from the logs that some number of files are skipped, but the progress bar reached 100%. I'm not sure which step I didn't follow correctly. Do you mind giving me more instructions to debug? Thank you!

**Comment by jeepurs** [comment] 2018-07-11 01:23
I would try importing on a completely different server if you want to replicate what i did exactly.

**Comment by lyw07** [comment] 2018-07-11 17:00
I tried again to import to a different server but still couldn't reproduce the issue... Here are my steps:
1. import the entire channel from Studio to Kolibri
2. export only a subset of the channel to USB
3. create a virtual machine, and set the USB's KOLIBRI_DATA folder to be a shared folder of the virtual machine (this should work as an external drive to the virtual machine)
4. try to import the entire channel from the shared folder (external drive). The progress bar reached 100%, and the log shows that 73 files are skipped.

**Comment by indirectlylit** [comment] 2018-07-13 00:31
I wonder if this is the same issue as #614, which was closed as not reproducible?

**Comment by benjaoming** [comment] 2018-08-06 13:15
Fixed in #4059 and released in 0.10.1

**Closed as completed by benjaoming** 2018-08-06 13:15 UTC
Labels: P1 - important
