### ISSUE TITLE
Import not blocked when disk space is insufficent

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4007] opened 2018-07-10 16:51 UTC
### Observed behavior

I have set `KOLIBRI_HOME` to point to the path of a different drive. Kolibri reports that "18 GB" are available, and I have no immediate idea of where that figure is from. One guess would be that it is reporting the disk space *after* importing.

There are 2 issues:

1. The estimate is wrong, displaying "0 B" is wrong, and the figure below is confusing
1. If the estimate was correct, then the import should be blocked?

The good news: The import isn't actually blocked!

![image](https://user-images.githubusercontent.com/374612/42524643-7167d4a4-8471-11e8-84e3-0c7204806127.png)

![image](https://user-images.githubusercontent.com/374612/42524659-7c249404-8471-11e8-8ea4-66635335742e.png)

### Expected behavior

Clarification of whether the estimate is *before* or *after* import. Kolibri should block the import based on the reported figures, because starting an import and running out of disk space may produce some unpredictable results?

### User-facing consequences

Well, not sure. Users may try and know better than the estimate and click "import" anyways since the button isn't disabled.

### Errors and logs

n/a

### Steps to reproduce

I think that setting `KOLIBRI_HOME` to the path of a different device might be the case?

### Context

 * Kolibri version: 0.10.0
 * Operating system: Raspian

**Comment by benjaoming** [comment] 2018-07-10 16:53
Clarification for the heavily contextualized reader: "Your remaining disk space" does NOT say whether it's the remaining disk space *now* or *after* the import :)

**Comment by lyw07** [comment] 2018-08-23 21:29
Yes it's actually `remaining disk space after the import`. Maybe a UI change suggested in https://github.com/learningequality/kolibri/issues/3883#issuecomment-413708535 could help?

**Comment by benjaoming** [comment] 2018-08-24 09:40
Hi @lyw07 - thanks for the ref! I can now see that this is partly a duplicate of #3883. I have changed the title so the two issues do not overlap.

I agree with @indirectlylit that the other part can be fixed through unambiguous labels of disk space.

**Comment by indirectlylit** [comment] 2018-09-20 01:08
closing as duplicate of #3883

> Import not blocked when disk space is insufficent

This appears to be working in the latest `develop`:

![image](https://user-images.githubusercontent.com/2367265/45789881-f1748000-bc36-11e8-8708-e8dbd85f7042.png)

**Closed as completed by indirectlylit** 2018-09-20 01:08 UTC
Labels: P1 - important, TAG: user strings
