### ISSUE TITLE
Delete task - Cancel button is missing

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7618] opened 2020-10-26 15:39 UTC
### Observed behavior

When a user deletes a resource no Cancel button is visible next to the task in the Task manager as it is with the other tasks (Import, Export, etc.)
<img width="953" alt="2020-10-26_154849" src="https://user-images.githubusercontent.com/72492554/97193828-1cd0de00-17b2-11eb-902d-c25b49171fc8.png">

### Expected behavior

When a user deletes a resource a Cancel button must be displayed next to the task in the Task manager as it is with the other tasks (Import, Export, etc.)

### User-facing consequences

It is impossible for the user to cancel a Delete task

### Errors and logs

…

### Steps to reproduce

Preconditions: Channels imported
1. Login and go to Device > Channels
2. Click the Manage button for a given channel
3. Check a resource and click Delete button
4. See the Task manager and look for a Cancel button

### Context

Kolibri 0.14.3
Raspberry Pi 4
OS: Raspbian GNU, Linux 10
Chrome (latest) + Firefox (latest)

**Comment by jonboiser** [comment] 2020-10-26 16:27
Closing as duplicate of #6727

**Closed as completed by jonboiser** 2020-10-26 16:27 UTC
