### ISSUE TITLE
Replicate: (UNW) Long delay between channel update finishing and changes reflecting on Learn page

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#7944] opened 2021-04-02 19:31 UTC
### Acceptance Criteria

Per @rtibbles this should be fixed in #7766 (a closed issue) in 0.14.7 - so:

- [ ] Verify that this issue is indeed closed in 0.14.x
- [ ] Either: 1) Close this issue with a comment saying that it no longer is a bug and that you've confirmed it or 2) Investigate the cause of the issue. If it is a quick fix (~45 mins from start to PR) then fix it, otherwise, create a new issue explaining everything you've learned about this issue and what it will take to fix it and close this issue.

### Observed behavior
On the UNW online servers, updates are showing on the Device tab immediately after the import finishes, but there's a long delay before they show on the Learn page.

Reported by Penny from UN Women:
When updating the channel on the [India] server, it takes a long time for updates to appear on the Learn tab. My last update of the Second chance channel took 45 minutes for the changes to appear. The strange thing is that the updated version is shown immediately on the Device tab, but then there’s this very long wait for it to display on Learn. The updates do not involve massive or resource-heavy changes. I’ve had this delay problem before when importing to the Mexico server

### Steps to reproduce
- Make updates to a channel that was previously imported, and import the updates

…

### Context
Tell us about your environment, including:
 * 0.14.6 UN Women India online server

**Comment by rtibbles** [comment] 2021-04-02 19:35
Note that this should be fixed in 0.14.7 by this PR: #7766

**Comment by lauradanforth** [comment] 2021-04-02 19:36
Looks similar to #4463

**Comment by rtibbles** [comment] 2021-04-02 19:38
> Looks similar to #4463

It's slightly different, as #4463 is a case where import was interrupted by power failure, and we currently have no way in the UI for a user to recover from this intermediary state. The issue here is probably that the cache invalidation was not working as intended.

**Comment by lauradanforth** [comment] 2021-06-16 22:22
Update from Penny as this seems to still be persisting: 

> It raised its head again this morning when I was importing new content (two new topics) for the Segunda oportunidad con el apoyo de Pro- México & Prosociedad channel on the Mexico server. It took over an hour for the imported resources to display in Learn, after they were visible in the Device tab.  I know the 0.14.7 upgrade was due to have resolved this, hence the issue in Notion being marked as complete.

**Comment by lauradanforth** [comment] 2021-06-22 14:30
Following the update from Penny that the issue was persisting, she tried again and had some improved results:
> I wanted to report that I imported two new channels to the Mexico server this morning and the delay between import and displaying on Learn was between 7 and 10 minutes for one and a few minutes for the other, so much improved from previously. Those kind of delays are quite acceptable from my point of view.  I’ll keep monitoring when I do further imports and let you know.

**Comment by rtibbles** [comment] 2021-06-22 14:32
Thanks for the follow up info, @lauradanforth - sounds like the fixes we put in place had some effect. Possible that intervening caching might be responsible for the remaining delay, but we can double check whether it is similar on a regular Kolibri instance.

**Comment by rtibbles** [comment] 2021-08-31 18:49
Quite acceptable works for me!

**Closed as completed by rtibbles** 2021-08-31 18:49 UTC
Labels: bug, P1 - important, APP: Device
