### ISSUE TITLE
Home and Library tabs are inaccessible with keyboard navigation (Firefox)

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#9194] opened 2022-03-14 23:14 UTC
## Observed behavior
With the exception of the Bookmark tab, the Library and Home (access to classes) is inaccessible by keyboard navigation.

## Errors and logs
None

## Expected behavior
Users should be able to use their keyboard to navigate throughout the app

## User-facing consequences
Inaccessible to keyboard users

## Steps to reproduce
1. Log in as learner
2. Click on the "Home" tab and try to use the keyboard to navigate through the classes, recent lessons, quizzes, etc.
3. Click on the "Library" tab and try to use the keyboard to navigate

## Context
Kolibri 0.15
Firefox

**Comment by marcellamaki** [comment] 2022-05-02 14:34
After some investigation, I think this is due to default MacBook settings, not a Kolibri issue. After updating my settings I am able to tab through full navigation as expect. 

![firefox-main-nav.gif](https://images.zenhubusercontent.com/6047f6e691103a78d3ad0ace/1718b0df-70f6-4c11-adbf-0adabbada7e3)

**Comment by marcellamaki** [comment] 2022-05-02 15:50
cc @radinamatic -- to double check before closing

**Comment by pcenov** [comment] 2022-05-03 08:42
Confirmed - with the correct settings enabled the tab navigation works correctly on Safari, Firefox and Chrome on Mac.

**Closed as completed** 2022-05-03 12:56 UTC
Labels: P0 - critical, TAG: a11y, DEV: frontend
