### ISSUE TITLE
"The page not found" page opens after opening the exercise with questions

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7610] opened 2020-10-23 13:24 UTC
### Actual result:
"The page not found" page opens after opening the exercise with questions
Expected result:
The lesson page opens correctly
### Steps to reproduce:

1. You are at  *Learn > Classes > '<class>' > '<lesson>'* page
2. You see exercise with questions
3. Click on the exercise content card
4. Pay attention to the opened page
### Video:
http://e.pc.cd/6zbotalK

### Context:
Kolibri version: 0.14.3
Device: Raspberry Pi 3B+
OS: tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

**Comment by rtibbles** [comment] 2021-04-05 21:56
@radinamatic @pcenov Is this replicating for you at all? See video for details. Possibly Raspberry Pi specific, but I'm not sure how.

**Comment by radinamatic** [comment] 2021-04-05 22:05
Haven't seen that error in a while, but @pcenov has the RPi device ready with the `0.14.7-rc1` release, and can test tomorrow to confirm!

**Comment by pcenov** [comment] 2021-04-06 15:26
@rtibbles I had a chance to take a look at this today on my Raspberry Pi 4 Model B and tested the above described scenario on a Mac Mini and was not able to reproduce the issue. I did stumble upon an issue with exercises not being displayed correctly in Safari which I'll report separately.

**Comment by rtibbles** [comment] 2021-04-06 15:38
OK, let's close this for now then!

**Closed as completed by rtibbles** 2021-04-06 15:38 UTC
Labels: TODO: needs clarification, APP: Learn
