### ISSUE TITLE
anchor-tag buttons are not aligned on Safari

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5606] opened 2019-06-03 07:01 UTC
### Observed behavior
Error page buttons are not aligned on Safari 12.11

### Expected behavior
It should be aligned in all browsers.

### Errors and logs
![Screen Shot 2019-06-03 at 2 50 16 PM](https://user-images.githubusercontent.com/8663934/58781953-d94f6000-860f-11e9-9981-b65643f8a7d2.png)

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4b4
 * Operating system:  macOS
 * Browser: Safari 12.11

**Comment by jonboiser** [comment] 2019-06-19 23:06
The reason for this is that Safari seems to interpret the `display: inline-table` differently.

My current hack is to use Safari 10+ media query to override the `display:` rule for Safari only.

A less hacky solution would be to replace the `<a>` used for the "Back to home" with a normal button whose click handler would be to redirect to `/` using JavaScript.

**Comment by indirectlylit** [comment] 2019-06-29 00:44
> The reason for this is that Safari seems to interpret the `display: inline-table` differently.



I don't actually understand why our buttons have `display: inline-table` on them. Looks like I added that and left the comment "helps with vertical layout" but unfortunately that is not helpful enough...

**Comment by jonboiser** [comment] 2019-08-14 21:22
There are more cases like this in the code. Here's the bottom panel on the quiz creation page:

![IMG_0922](https://user-images.githubusercontent.com/10248067/63057363-e48bfb00-be9e-11e9-9320-19247bed0a60.PNG)

**Comment by indirectlylit** [comment] 2019-08-23 21:27
this should be addressed in #5900

**Comment by jonboiser** [comment] 2021-06-23 20:39
This looks to be okay on kolibri-beta viewed on Safari 14. The labels are different, but this is still a anchor tag + a button

![CleanShot 2021-06-23 at 13 36 54](https://user-images.githubusercontent.com/10248067/123164695-22a5be80-d428-11eb-9028-e304f168192e.png)

**Comment by indirectlylit** [comment] 2021-06-24 16:18
confirmed, also looks fine on kolibri demo 0.14.7

![image](https://user-images.githubusercontent.com/2367265/123298159-37488c00-d4e6-11eb-805c-73bb76c3d2c7.png)

**Closed as completed by indirectlylit** 2021-06-24 16:18 UTC
Labels: bug, safari
