### ISSUE TITLE
Unable to create users or enroll Learners via admin account (RACHEL installation)

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#4490] opened 2018-10-30 17:12 UTC
### Observed behavior
When logged in as an admin, the buttons to create users and to enroll learners in a class have disappeared.

Note that this has also been reproduced by another user running Kolibri on a RACHEL device. 

### Errors and logs
![creating users error](https://user-images.githubusercontent.com/22602993/47736537-3da6dd00-dc45-11e8-9f81-b93a46dec476.PNG)
![creating coaches error](https://user-images.githubusercontent.com/22602993/47736539-3f70a080-dc45-11e8-9d29-188f9666b1a5.PNG)
![enrolling learners to class errors](https://user-images.githubusercontent.com/22602993/47736544-413a6400-dc45-11e8-9bbb-5340a307109a.PNG)

### Context

Tell us about your environment, including:
 * 0.9.2
 * RACHEL-Plus
* Browser: Edge and Chrome
![device info](https://user-images.githubusercontent.com/22602993/47736473-1f40e180-dc45-11e8-9b42-d88c557fcc7e.PNG)

…

**Comment by jonboiser** [comment] 2018-10-30 19:05
The 'Locale "default" is not well formed' errors might be coming from the use of `localeCompare` when sorting users in the table. This `localeCompare` is not available on older version of Edge.

**Comment by indirectlylit** [comment] 2018-10-30 23:29
re: `localeCompare`, see #3887 and #3888

I'm surprised the issue is occuring in Chrome though

**Comment by lauradanforth** [comment] 2018-10-31 14:35
A followup message was sent saying that it's mostly being run on Edge, so I'll re-confirm whether Chrome has been used or not.

**Comment by indirectlylit** [comment] 2018-10-31 19:20
Thanks. I'm fairly confident this issue is the same as #3804, which was closed by #3887 in 0.10.x

If these users cannot upgrade Kolibri, let's recommend that they use Firefox or Chrome as their browser.

Closing - please re-open if we get new information indicating that the scope is different from #3804

**Closed as completed by indirectlylit** 2018-10-31 19:20 UTC
Labels: bug
