### ISSUE TITLE
app bar loading constantly displayed throughout several plugins

### ISSUE THREAD

**Issue by thanksameeelian** [learningequality/kolibri#10814] opened 2023-06-08 19:26 UTC
## Observed behavior
In `Coach` > `Reports`, all sections of `Facility` (except `Data`), and all sections of Device (except `Facilities)`, the app bar loading indication is constantly displaying. 

## Errors and logs
screen recording of some of the cases 

https://github.com/learningequality/kolibri/assets/43046460/00df9867-db12-4002-8377-7de58db3df4d

## Expected behavior
initial loading indicator, but not constant unless loading is truly constantly occurring

## User-facing consequences
loading indicator is not trustworthy as actually indicating loading

## Steps to reproduce
please see screen recording/description - this was observed as a superadmin and as a learner in the sections mentioned (that a learner could access).

**Comment by marcellamaki** [comment] 2023-06-14 14:01
Thanks for flagging this @thanksameeelian. This looks like a follow along issue for @nucleogenesis 's work in https://github.com/learningequality/kolibri/issues/10731 and https://github.com/learningequality/kolibri/issues/10729

Jacob, I'm assigning this to you, but assuming that it will be resolved in the course of your existing work, not something separate you need to work on.

**Comment by nucleogenesis** [comment] 2023-06-16 22:59
Noting here that Device & Facility has this issue fixed throughout in #10841

**Comment by MisRob** [comment] 2023-08-21 06:23
As @nucleogenesis mentions, this is fixed in Device and Facility. I couldn't reproduce it in the Coach either. I assume it's been fixed already with recent updates to loading states.

**Closed as completed by MisRob** 2023-08-21 06:23 UTC
Labels: bug, APP: Device, APP: Facility, APP: Coach, DEV: frontend
