### ISSUE TITLE
Library - Missing 'Language' filter

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10235] opened 2023-03-14 14:30 UTC
## Observed behavior
While testing https://github.com/learningequality/kolibri/pull/10233 I noticed that the Language filter in the Library page is no longer being displayed. There's also nothing displayed under the label 'Show resources'.

## Expected behavior
The issue should be further investigated.

## Steps to reproduce the issue
1. Install the the [following build ](https://buildkite.com/learningequality/kolibri-debian/builds/6281) 
2.  Navigate to Learn > Library
3. Observe the the filter section of the page

## Screenshot

![2023-03-14_11-52-28](https://user-images.githubusercontent.com/79847249/225032355-f5f06de5-148f-483a-b23f-29a4c315839c.png)

## Usage Details
Windows 10, Ubuntu 22  - Chrome

**Comment by pcenov** [comment] 2023-03-14 14:30
cc @radinamatic @marcellamaki

**Comment by marcellamaki** [comment] 2023-03-14 18:49
@radinamatic @pcenov initial investigation suggests this is a regression, not related to strings. I mentioned this to @rtibbles and I don't think we need to resolve this before the translators begin working.

**Comment by Rohitrky2021** [comment] 2023-03-19 18:55
is this issue opn will i work on it?

**Comment by rtibbles** [comment] 2023-03-19 23:54
@Rohitrky2021 - you can see that this issue is already assigned to @marcellamaki - best to look for issues that are not already actively assigned.

**Comment by Rohitrky2021** [comment] 2023-03-20 10:01
ok @rtibbles  am finding a matching one
thanks

**Comment by marcellamaki** [comment] 2023-05-23 13:51
It's possible that this has been resolved incidentally since March through other updates, and it should be confirmed which, if any, of these issues are still present as the first part of dev work for this issue.

**Comment by rtibbles** [comment] 2023-05-23 14:02
The language filter is definitely still missing, but as far as I can tell the show resources section is being properly displayed.

**Closed as completed** 2023-06-01 16:30 UTC
Labels: P0 - critical
