### ISSUE TITLE
ERROR while importing channel from Local Drive.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1640] opened 2017-06-13 11:02 UTC
## Summary

ERROR while importing channel from Local Drive. 

This is in addition to #538 #614 #769 #847 

Our program managers are not teach savvy and this feature to work seamlessly very soon is crucial for implementation ,else updation of the content becomes very challenging for us.

## System information
 - Version: Kolibri 0.4.0beta10
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce
1. Try to import channel from local drive.
2. Observer the progress bar.

## Screenshots
![while import 2](https://user-images.githubusercontent.com/13453618/27079582-cd0f8e7e-5055-11e7-9239-71bcfda06abf.png)
![while importing channel](https://user-images.githubusercontent.com/13453618/27079583-cd78966c-5055-11e7-8530-b29dfa1beb60.png)

**Comment by rtibbles** [comment] 2017-06-13 17:15
Channel used for reference: `e890b1acbcad44939688dbb1b7dde2e5`.

I can't replicate this due to the fact that the 0.4.x import export does not detect any drives on my device.

I think this will be fixed in 0.5.x, but will see if someone else can replicate and provide a shorter term fix.

**Comment by jonboiser** [comment] 2017-06-13 20:44
@harishbalachandran Did you click the 'Cancel' button on the first screenshot before seeing the second? Or did the second screenshot with the red error box appear on its own?

**Comment by harishbalachandran** [comment] 2017-06-14 05:13
@jonboiser The channel import showed finished at first, had to refresh the page to see the channel name #769. Then again issue #538 occurred. This is when I clicked on Cancel and got the error page, then refreshed the error page went away and the progress bar reached till the end and I had to click on cancel post which the import stopped.

**Comment by jonboiser** [comment] 2017-06-14 19:01
@harishbalachandran So to clarify, the thing that immediately preceded the 'error page' was clicking Cancel?

But when you refreshed the browser after seeing the 'error page', the Progress Bar returned. But when you closed it the second time, there weren't any problems?

**Comment by harishbalachandran** [comment] 2017-06-15 01:26
@jonboiser your understanding is perfect! 👍

**Comment by jonboiser** [comment] 2017-06-15 19:25
Thanks @harishbalachandran this narrows things down a bit for debugging.

There are lots of failure states for import/export workflow, so we're going to think of ways to make it easier for end-users to understand errors like the on you've reported.

**Comment by radinamatic** [comment] 2017-07-09 19:39
## System information

 - Version: [`0.4.0-446-gd1737c5`](https://github.com/learningequality/kolibri/pull/1805)
 - Operating system: Windows 7
 - Browser: Chrome

No errors on import from CC server, nor on export/import to/from local USB drive. The only issue is that after content is imported, whether from local drive or Internet, it does not appear under `My Channels` until user navigates away from Management and then comes back. 

![selection_328](https://user-images.githubusercontent.com/1457929/27996982-56743686-64ee-11e7-8f3d-cb2e1044b7d9.png)

State is correctly reported after deleting the channel (meaning that the channel is not visible after deleting), just not after importing.

![selection_329](https://user-images.githubusercontent.com/1457929/27997016-f7fee186-64ee-11e7-88fb-35a2a5aee173.png)

**Comment by jonboiser** [comment] 2017-07-11 22:44
Just ran into the error @radinamatic posted above.

To my mind, there is no reason why this would be any different from importing from a remote source.

@jamalex After a new channel is added to the system, `update_channel_metadata_cache` is supposed to be run as a side-effect; hence when the ChannelList is refreshed it will have the brand-new channel. It happens if the new channel comes from a remote source, but not from a local source. Are the implementations of these two Commands different somehow?

**Comment by radinamatic** [comment] 2017-07-12 15:52
@jonboiser Not sure which PR fixed it, but on latest `v0.5.0-beta2` release channels are visible immediately upon local import, but the page still need a reload to make channels imported remotely visible.

**Comment by jonboiser** [comment] 2017-07-12 17:15
@radinamatic Does that mean the problem switched?

Before: list updates with _remote_ import; list does not update with _local_ import
0.5.0-beta2: list updates with _local_ import; list does not update with _remote_ import

**Comment by radinamatic** [comment] 2017-07-12 18:28
@jonboiser I don't have that VM snapshot to test again, but reviewing my comment:

Before: list is updated upon _deleting_ channels, reload needed for both imports
0.5.0.beta2: list is updated after _delete_ & _local_ import, _remote_ still needs reload.

**Comment by jamalex** [comment] 2017-07-13 19:36
> # never reached

Hmm, strange! It's possible a `StopIteration` is raised in there somewhere, but I don't think it would bubble up to here. Perhaps try wrapping the block before that line in `try ... except` and see if something is getting thrown?

**Comment by rtibbles** [comment] 2017-08-11 17:51
Should be remedied in work following #1947

**Comment by radinamatic** [comment] 2017-08-25 16:17
Still extant on `0.5.0-beta9`.

 - Operating system: Windows 7
 - Browser: Chrome

No errors on import from CC server, nor on export/import to/from local USB drive. The issue that still remains is that after content is imported, whether from local drive or Internet, it does not appear under `My Channels` until the page is reloaded. 

State is correctly reported after deleting the channel (meaning that the channel is not visible after deleting), just not after importing.

@rtibbles

**Comment by radinamatic** [comment] 2017-08-25 18:26
Confirmed as extant on Ubuntu too, both after internet and local import:

![ubuntu3 0 5-beta9 running - oracle vm virtualbox_495](https://user-images.githubusercontent.com/1457929/29727299-8c96fb5e-89d3-11e7-86fe-07005f3b622d.png)

**Comment by radinamatic** [comment] 2017-08-25 18:52
Opened a [new issue](https://github.com/learningequality/kolibri/issues/2030) for the occurrence on `0.5.0-beta9`, not sure if this should be closed... :thinking:

**Comment by rtibbles** [comment] 2017-08-25 18:55
Can be closed when #1947 is merged.

**Closed** 2017-09-01 19:05 UTC
Labels: TASK: bug
