### ISSUE TITLE
The remove option in Lesson does not work all the time

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3515] opened 2018-04-10 14:36 UTC
### Observed behavior

In the lesson feature, remove option is temporarily showing that the resource is removed but when we go back and then enter the lesson, the resources are still there.

### Expected behaviour

In the lesson feature, remove option must remove a resource from the lesson.

### User-facing consequences

Will not be able to remove a resource.

### Steps to reproduce

1. Login as admin and create a lesson in the class with 2-4 resources.
2. Try to remove the resource, go back and check whether the resources were removed or not.

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### screenshots

![l1](https://user-images.githubusercontent.com/38091824/38563493-a4080546-3cfa-11e8-8af1-083343c7a363.png)
![l2](https://user-images.githubusercontent.com/38091824/38563494-a47ae200-3cfa-11e8-82e1-6027828bc262.png)
![l3](https://user-images.githubusercontent.com/38091824/38563495-a4c11d4c-3cfa-11e8-90fb-e31c6a4ccd91.png)
![l4](https://user-images.githubusercontent.com/38091824/38563497-a532a0c0-3cfa-11e8-8dba-8a5966f54715.png)

**Comment by DXCanas** [comment] 2018-04-11 19:24
So, this happens because the API `patch` isn't made until that snackbar goes away. The idea is you can batch remove a ton of different resources and have all of that equate to a single API call (The removals stack into a single operation that you can undo). Or, if you end up hitting undo, it would be only 1 call rather than 2 (or however many items it is you removed).

The problem, I think, is that we're navigating to a page that doesn't have a `workingResources` state property before snackbar disappears. If you navigate to "add resources", this works fine, but only because `workingResources` is carried over.

I tried fixing this by passing a duplicate of the array (pass-by-value rather than pass-by-reference) to the autosave function. But I'm pretty sure that, because the snackbar's `hideCallback` isn't called until it's actually hidden (which may be on another page), it doesn't work as planned. 

Potential quick fixes _could_ be binding the callback (though that might not work, since the element will have been destroyed by this point anyway?) or passing the data needed as parameters (with defaults?) to the callback.

Long term, it'd be nice if we could leverage [`vue-router`'s In-Component guards](https://router.vuejs.org/en/advanced/navigation-guards.html#in-component-guards). I made an attempt that ultimately ended up taking too long. Main obstacle is our modified version of `vue-router` to use actions rather than state. One approach (suggested by @rtibbles) I was trying but gave up on is binding a dummy component (with state) to the route for the sole purpose of using the guard. It wasn't working for me, but by that point I thought I was in too deep a rabbit hole.

**Comment by indirectlylit** [comment] 2018-04-12 01:35
I could see it being potentially useful to be able to trigger actions based on those other events (leaving and updating URLs). If that seems like it'd be useful, we can probably integrate that into our router wrapper

**Comment by rtibbles** [comment] 2018-04-12 17:43
@DXCanas do you have bandwidth to do a quick fix for this?

**Comment by DXCanas** [comment] 2018-04-12 22:39
@rtibbles How soon do we need it? I can probably take it on tomorrow?

**Comment by rtibbles** [comment] 2018-04-12 22:40
Would be good to get it into the 0.9.1 patch release, which is scheduled for next week.

**Closed** 2018-04-19 01:43 UTC
Labels: P1 - important, TASK: bug fix
