### ISSUE TITLE
Not able to sort coach reports

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4621] opened 2018-12-18 06:50 UTC
### Observed behavior
When coach wants to sort based on "v" on last activity. It won't work as expected when there is combination of days and hours.

### Expected behavior
It must sort days and hours as expected.

### Steps to reproduce
1. Login with Coach and go to the coach.
2. Click on channels.
3. go to the exercise and sort when there is combination of hours and days.

Please find attached database so you can able reproduce this at your end.
[db.sqlite3.zip](https://github.com/learningequality/kolibri/files/2689205/db.sqlite3.zip)

### Context
 * Kolibri version : kolibri 0.11.0
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/50136865-3607ca00-02bf-11e9-85d6-d42ee6c34d2f.png)

Days must at the end when we sort using v
![2](https://user-images.githubusercontent.com/12776071/50136866-3607ca00-02bf-11e9-85a8-3accfcc4e99a.png)

**Comment by indirectlylit** [comment] 2020-05-23 10:11
closing as duplicate of https://github.com/learningequality/kolibri/issues/4620

**Closed as completed by indirectlylit** 2020-05-23 10:11 UTC
Labels: TAG: new feature, P1 - important
