### ISSUE TITLE
Logged in as a coach, unable to use any of the functionality of a coach. 

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1245] opened 2017-04-18 08:15 UTC
## Summary

Logged in as a coach, unable to use any of the functionality of a coach. 

## System information
 - Version: Kolibri 0.4.0alpha2
 - Operating system: Ubuntu14.04 LTS
 - Browser: Chrome and Firefox

## How to reproduce
1. Login as a admin.
2. Create a learner form user tab.
3. Enroll the user into a class.
4. Go to class and switch the learner to coach.
5. Logout and login as a coach.
6. Click on the class.

## Screenshots

![class1](https://cloud.githubusercontent.com/assets/13453618/25120833/34dac61c-243d-11e7-9f7f-bd85c0af8144.png)
![class2](https://cloud.githubusercontent.com/assets/13453618/25120834/34dcedb6-243d-11e7-8271-5193094d44a7.png)

**Comment by swapnil106111** [comment] 2017-04-18 10:31
When we logged in as a Facility Admin, we are able to access the functionalities of a coach. 
But even as Device Owner (Superuser) the coach functionality is not accessible.

Facility Admin
![facility admin](https://cloud.githubusercontent.com/assets/12776071/25126535/41443902-2450-11e7-872c-5d130cf2aa9e.png)

Device Owner
![super user](https://cloud.githubusercontent.com/assets/12776071/25126536/4144f270-2450-11e7-92ba-8dfa5a8a5ad5.png)

**Comment by rtibbles** [comment] 2017-04-18 16:42
Thanks for reporting - this has the same root cause as #1238 so I am closing this in favour of that one.

**Closed by rtibbles** 2017-04-18 16:42 UTC

**Comment by yogeshmhaskule** [comment] 2017-04-24 11:15
@rtibbles We have tested it. it's showing all the options of coach tab.
![options_of_coach_tab_showing](https://cloud.githubusercontent.com/assets/7850420/25334695/5b4fa4a0-290d-11e7-9be3-2d0bee91dd27.png)
