### ISSUE TITLE
'Select a source' modal - Broken 'Add new device' link

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12085] opened 2024-04-16 14:00 UTC
## Observed behavior

Observed while testing https://github.com/learningequality/kolibri/pull/12077 -  the 'Add new device' link is not working in the 'Select a source' modal (tested both in Chrome and Firefox):

https://github.com/learningequality/kolibri/assets/79847249/5f6578d2-2b25-4c9a-97e9-c34b9d6c660e

## Expected behavior

Functional 'Add new device' link.

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/12077
2. Go through the Setup Wizard by importing a full facility.
3. When you dismiss the 'Welcome modal' at Device > Channels you will see the 'Select a source' modal.
4. Attempt to add a new device by clicking the 'Add new device' link

## Usage Details
Kolibri 0.16.1
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment] 2024-04-16 14:01
@radinamatic @jredrejo

**Comment by jredrejo** [comment] 2024-05-02 18:00
@pcenov @radinamatic  I can't reproduce this issue  anymore. I think this has been solved in recent 0.16.x implementations. Let me know if you have a chance to reproduce it somehow or let's close it

**Comment by pcenov** [comment] 2024-05-07 08:23
Hi @jredrejo - I am still able to replicate this in https://github.com/learningequality/kolibri/releases/tag/v0.16.2-beta1:


https://github.com/learningequality/kolibri/assets/79847249/ad1c3b2a-0e47-461a-a222-48006182a5a3

**Comment by jredrejo** [comment] 2024-05-07 09:00
> Hi @jredrejo - I am still able to replicate this in https://github.com/learningequality/kolibri/releases/tag/v0.16.2-beta1:
> 
>  2024-05-07_11-14-29.mp4

Hi @pcenov  , can you give me some hints to reproduce it? I tested it with the same version.
What steps do you take to reach that point? I imported one facility and later I went to the channels tab to import new channels.
What could be the difference?

**Comment by pcenov** [comment] 2024-05-07 09:17
Hi @jredrejo, I am not doing anything different than following these steps:

1. Go through the Setup Wizard by importing a full facility.
2. When you dismiss the 'Welcome modal' at Device > Channels you will see the 'Select a source' modal.
3. Attempt to add a new device by clicking the 'Add new device' link

I am using the same Beta 1 build on both VM's and I have done a clean install of Kolibri, and have cleared all cache and cookies in the Chrome browser. When I click the link 'Add new device' I don't see any errors in the console.

**Comment by jredrejo** [comment] 2024-05-07 17:21
@pcenov thanks, I could reproduce it now. It was not actually an error: it was this feature had never been implemented in this part of the code. Let me know if you find any issue when checking the PR that fixes it.

**Comment by jredrejo** [comment] 2024-05-09 11:05
Closed in #12136

**Closed as completed by jredrejo** 2024-05-09 11:05 UTC
Labels: P1 - important
