### ISSUE TITLE
Import content UI on Vodafone's 0.3.0 pex frozen

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#1096] opened 2017-03-20 18:00 UTC
## Summary

Import content UI on Vodafone's 0.3.0 pex frozen

## System information

 - From filename: kolibri-vf-v0.3.0.pex
 - Operating system: macOS Sierra 10.12.3
 - Browser: Chrome 56.0.2924.87

## Traceback or relevant snippet from server.log or browser console

No errors appeared in the console

## How to reproduce

1. Install kolibri from 0.3.0 pex file 
1. Log in as device admin
1. On Content page under Manage, try to import a content channel using a code from https://docs.google.com/document/d/1frJ37D5S3uZkK2DIge3bzKyw4p5DLDDfi81OifGLVT8/edit#

## Screenshots

![screen shot 2017-03-20 at 10 59 24 am](https://cloud.githubusercontent.com/assets/6668144/24114119/55343436-0d5c-11e7-8d0f-f7afcb504136.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

*If applicable*

**Comment by aronasorman** [comment] 2017-03-20 18:09
I'll take a look on what's happening here.

**Comment by radinamatic** [comment] 2017-03-20 19:38
Confirmed on Ubuntu Linux 16.10. 
It doesn't exactly freeze, it seems to be stopping and restarting on it's own, not sure if it's supposed to work that way...

![ubuntu3 start running - oracle vm virtualbox_119](https://cloud.githubusercontent.com/assets/1457929/24118017/8ed0b748-0d69-11e7-84c6-1a4f2685c234.png)

![ubuntu3 start running - oracle vm virtualbox_120](https://cloud.githubusercontent.com/assets/1457929/24118030/96f317ae-0d69-11e7-9344-e3dec5071f9c.png)

![ubuntu3 start running - oracle vm virtualbox_121](https://cloud.githubusercontent.com/assets/1457929/24118064/b96df042-0d69-11e7-83aa-d81b9f53fcbc.png)

**Comment by radinamatic** [comment] 2017-03-20 19:39
I was able to import my own small channel, but it's only 20 MB...

**Comment by benjaoming** [comment] 2017-03-21 12:41
@radinamatic it's not stopping and starting on those screenshots.

It's the progress bar which re-renders on a new line. Notice the percentage and the downloaded bytes.

I can reproduce that behaviour as follows:

1) `kolibri start --foreground`
1) Start retrieving a channel in the browser
2) Look at the terminal
3) Make a request in the browser, e.g. navigate to a different page
4) Notice that a new line with progress bare output appears.

I would refer your problem to #1091 - I created this, anticipating that more confusion and inconvenience about downloading channels was to come because of the lacking user feedback.

**Comment by indirectlylit** [comment] 2017-03-21 14:56
I've added this issue to the high-level list of import/export bugs here: https://trello.com/c/2nCLWsj2/721-import-export-bugs

**Comment by radinamatic** [comment] 2017-03-21 15:28
@benjaoming 
I will try to repro again with `--foreground` flag, but in the UI it presented the `Please try again` with the `CLOSE` button, and the third time it seemed to have restarted itself without me actually pushing the button.

In the #1091 you articulated much better what I reported back in August in #463. :wink:

**Comment by benjaoming** [comment] 2017-03-21 16:33
I don't think this issue can be solved before we have more user feedback - if there _is_ a legitimate problem about processes freezing, we would be able to tell because the user feedback would indicate so.

Suggesting to close and put efforts in adding user feedback first...

**Comment by indirectlylit** [comment] 2017-03-21 16:36
It sounds like the behavior reported by @radinamatic is different than the original issue, where no progress was made whatsoever. This would be a fairly serious issue, independent of user feedback...

**Comment by radinamatic** [comment] 2017-03-21 17:26
Tested on latest Windows installer with the `--foreground` flag and the UI opened as suggested.

No feedback in the UI when the process was finished:
![virtualbox_msedge - win10_preview_21_03_2017_10_03_41](https://cloud.githubusercontent.com/assets/1457929/24160977/73d4eba0-0e20-11e7-92c3-973d6635a863.png)

When I navigate away from `Manage > Content` and come back, it finally gives the `Finished` feedback:
![virtualbox_msedge - win10_preview_21_03_2017_10_17_28](https://cloud.githubusercontent.com/assets/1457929/24161063/a8b99550-0e20-11e7-8d3f-cb2c6e18393e.png)

**Comment by radinamatic** [comment] 2017-03-21 17:49
Second import went a bit better, at least I didn't have to navigate away & back:

![virtualbox_msedge - win10_preview_21_03_2017_10_43_28](https://cloud.githubusercontent.com/assets/1457929/24162040/6ff1be02-0e23-11e7-9af7-9b46079c71a5.png)

There is also a weird delay, just remembered I experienced it even before, right after user pastes the channel ID and pushes the import button: Terminal import starts right away, but 2-3 seconds pass before the UI reacts and starts showing the progress bar, enough for user to wonder if the import actually started or they need to repeat the request... 😒

**Comment by rtibbles** [comment] 2017-07-17 15:45
No confirmed recurrence on 0.5.x, closing.

**Closed by rtibbles** 2017-07-17 15:45 UTC
Labels: DEV: backend, DEV: frontend, TASK: bug
