### ISSUE TITLE
Thoughtful Learning documents are not visible using WebKit browsers

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri#7659] opened 2020-11-03 17:31 UTC
### Observed behavior

Using the MacOS Kolibri app, the Linux / Flatpak Kolibri app, as well as certain web browsers such as GNOME Web, documents in the Thoughtful Learning channel are not visible. Instead, they appear as an empty white box:

![Screenshot from 2020-11-03 09-24-44](https://user-images.githubusercontent.com/132063/98019326-763e9b80-1db6-11eb-9252-353d6367ad07.png)

### Expected behavior

Instead, this content should be rendered as usual. It is visible using Firefox, Google Chrome, or the Kolibri Windows app.

### User-facing consequences

For users without access to one of those solutions, the content is inaccessible.

### Errors and logs

I haven't seen any relevant log messages, including in my browser's console. Please do let me know if there is something you'd like me to share!

### Steps to reproduce

Add the Thoughtful Learning channel and some content:

    kolibri manage importchannel network 74f36493bb475b62935fa8705ed59fed
    kolibri manage importcontent --node_ids=35193147e66b57dc8193922b490a13f3 network 74f36493bb475b62935fa8705ed59fed

Using one of the front-ends listed earlier, attempt to view the document in Thoughtful Learning / Writing Assessments / Grades 4-5 / Personal Narrative: The Broken Statue (Good).

### Context

* Kolibri version: 0.14.3
* Operating system: Linux
* Browser: [GNOME Web](https://www.flathub.org/apps/details/org.gnome.Epiphany)

**Comment by jonboiser** [comment] 2020-11-03 18:18
I just reproduced this in Safari. This message looks relevant

From https://kolibri-beta.learningequality.org/en/learn/#/topics/c/91ed1fa9eee85fc0a4139010df9efc3b

![image](https://user-images.githubusercontent.com/10248067/98024939-e56bbe00-1dbd-11eb-9825-e22c24cefc7d.png)

```
Tried to setup the SCORM API in a sandboxed environment, it will not be enabled
```

From https://kolibri-beta.learningequality.org/en/learn/#/topics/c/cca9674dca345e5f8849d9bea9adb8cd

![image](https://user-images.githubusercontent.com/10248067/98025108-2368e200-1dbe-11eb-830f-5d2e96beab96.png)

**Comment by rtibbles** [comment] 2020-11-03 18:29
This caught error is expected behaviour until we merge the work that allows SCORM to work without the sandbox being removed.

This is more likely an issue with hashi page rerendering that will be resolved by #7254 - the specific issue for Thoughtful Learning on Webkit is probably related to load event handlers not firing as or when expected.

**Comment by radinamatic** [comment] 2020-11-03 19:00
(re: #7254) [SCORM resources are looking good](https://github.com/learningequality/kolibri/pull/7254#issuecomment-721316458) on Safari client (macOS Mojave VM browsing content on Windows 7 server).

**Comment by radinamatic** [comment] 2021-08-31 23:28
@pcenov Could you please try to replicate and confirm if this is still extant? Thank you!

**Comment by pcenov** [comment] 2021-09-01 09:55
Hi @radinamatic, after importing the Thoughtful Learning channel I can confirm that the resources are not visible in the MacOS Kolibri app. For some reason it attempts to open a URL in the default browser pointing to: http://localhost:65503/content/static/hashi/hashi-5266606b03050de071fee9c2a743e322.html

![2021-09-01_12-06-39](https://user-images.githubusercontent.com/79847249/131650894-2560c607-4181-4fb4-bf88-177a9bacad12.png)

At the same time I can see correctly the documents in Safari and Chrome browsers through the server URL but there are multiple errors in the console:

![2021-09-01_12-10-42](https://user-images.githubusercontent.com/79847249/131650933-dbae824b-019b-4ca6-b21b-32fccffcbe82.png)

**Comment by rtibbles** [comment] 2021-09-01 15:19
In the latter case, The console errors are due to issues in the content itself, so not a result of what Kolibri is doing.

In the first case, it seems like it is trying to open the URL for the iframe in an external window, rather than opening it in the iframe - this definitely needs more debugging.

**Comment by rtibbles** [comment] 2021-09-01 15:20
Does the same error occur in Safari outside of the app context?

**Comment by pcenov** [comment] 2021-09-02 15:00
No that error doesn't occur is safari outside of the app context:

![2021-09-02_17-58-26](https://user-images.githubusercontent.com/79847249/131867623-52e88e49-5f4c-49fb-9429-833ea9862b3a.png)

**Comment by rtibbles** [comment] 2021-09-02 15:44
OK, in that case I think this specific issue is fixed, but we should file a follow up issue that's more generally about HTML5 apps not working as expected in the Mac app context!

**Closed as completed by rtibbles** 2021-09-02 15:44 UTC
Labels: bug, DEV: content, DEV: renderers, safari
