### ISSUE TITLE
Coach > View learners - Missing 'Device status' and 'Last synced' values

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#10588] opened 2023-04-28 14:03 UTC
## Observed behavior
The 'Device status' and 'Last synced' values are no longer displayed in Coach reports.

## Expected behavior
The 'Device status' and 'Last synced' values should be displayed correctly.

## Steps to reproduce the issue
1. On Device 1 setup a full facility
2. On Device 2 create a learn-only user for the facility on Device 1
3. Assign lessons/quizzes to the learner and complete them
4. As a coach go to Class home > View learners or Coach > Reports > View learner devices

## Video

https://user-images.githubusercontent.com/79847249/235168764-fb8a53dc-4c1a-4692-9d06-221495cb3239.mp4

## Usage Details
Kolibri 0.16alfa13
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment] 2023-04-28 14:04
@radinamatic

**Comment by Pursottam6003** [comment] 2023-04-30 20:18
Hii @pcenov  Sir is it a backend issue or front end issue it looks like the `front end ` is not able to display the data correctly and in the video I can able to see the console whether I guess it is showing `array of objects ` of learners data?

Btw nicely identifying the bug  🫡

I will also reproduce this issue :)

**Comment by akolson** [comment] 2023-05-01 13:44
HI @Pursottam6003. This is most likely a front-end issue, but first replicating the issue should clear this. Also, is this an issue you would like to take up?

**Comment by Pursottam6003** [comment] 2023-05-01 19:17
> HI @Pursottam6003. This is most likely a front-end issue, but first replicating the issue should clear this. Also, is this an issue you would like to take up?

Hii @akolson  I would be happy to take this issue I tried to replicate this issue on my device but here what I did is created the users from the same device but here i am able to get the `Last synced values `

![image](https://user-images.githubusercontent.com/81693090/235512760-473e47e5-5273-4a4f-8213-ca9430ec5b92.png)


But I think I need to create a virtual machine to clearly understood the issue

**Comment by AllanOXDi** [comment] 2023-05-18 13:30
Hey @pcenov  I have been trying to replicate this bug but I am unable to. Are you able to dig into this further? Let me know.

**Comment by pcenov** [comment] 2023-05-18 13:48
Hi @AllanOXDi could you please let me know on which build are you testing and perhaps share a video of what you are observing. I can confirm that I am able to replicate the issue in Kolibri 0.16.0a13.

**Comment by AllanOXDi** [comment] 2023-05-18 13:56
I tested with 0.16.0a13 built.

**Comment by pcenov** [comment] 2023-05-18 14:53
@AllanOXDi here's a screenshot of what I am observing at the moment, just to make sure we are talking about the same thing:

![2023-05-18_17-41-11](https://github.com/learningequality/kolibri/assets/79847249/5d07eb24-7109-42d1-b2e4-d46024fe036d)

Let me know if you need further clarification.

**Comment by AllanOXDi** [comment] 2023-05-23 16:00
As I found this hard to reproduce and work on . I suspect looking into  `this.fetchUserSyncStatus` in the [ClassLearnersListPage](https://github.com/learningequality/kolibri/blob/4ad3e289ddf4a00d91f5bccfdf7977147611d0f9/kolibri/plugins/coach/assets/src/views/ClassLearnersListPage.vue#L178). To me it appears that , whatever is  being returned from this [endpoint ](https://github.com/learningequality/kolibri/blob/f550fcd83233dc90e412737bd20dcbb6d1eb3ab9/kolibri/core/device/api.py#L281)is where the issue could be.

**Comment by akolson** [comment] 2023-06-12 22:35
Hi @pcenov I was able to get it to show the `status` and `last synced` columns. I however suspect that this is closely related to the syncing issue experienced previously, but also a big possibility of the logic responsible for the display of the two columns is skewed. Here is a screenshot of what I was able to replicate.


![Image](https://github.com/learningequality/kolibri/assets/5203639/a7f7f638-8b07-4b5c-bf9d-2d5aafee72e0)

As a next step to help resolve the bug, when you find some time, could you please post the response from `/api/device/usersyncstatus` api endpoint(Should be similar to response shown in right side of screenshot above)?

**Comment by pcenov** [comment] 2023-06-14 11:12
Hi @akolson, I had a chance to take a closer look at this today. Looks like it's not just the device status and last sync that are not displayed, I am also not seeing anything in the 'Device activity' panel.

Here's a short video of what I am doing and observing (I've skipped some parts to make it shorter):

https://github.com/learningequality/kolibri/assets/79847249/5807b6f1-aea9-487d-8bda-737d6509ec89

Here's the api response:

![2023-06-14_14-05-47](https://github.com/learningequality/kolibri/assets/79847249/a09fabb9-90e5-47e5-a679-f1a788fd55b8)

Logs and databases for both devices:
[Learner_device.zip](https://github.com/learningequality/kolibri/files/11744968/Learner_device.zip)
[MAIN_device.zip](https://github.com/learningequality/kolibri/files/11744969/MAIN_device.zip)

Let me know if you need additional info.

**Comment by akolson** [comment] 2023-06-14 13:36
It looks like the `sync_session_id` field(in the `UserSyncStatus` model) is not being set on the main device. Thus the reason why all the properties that depend on the presence of the `sync_session_id` are `null`.
<img width="1800" alt="Screenshot 2023-06-14 at 16 26 57" src="https://github.com/learningequality/kolibri/assets/5203639/735fec17-2077-4eb3-9c57-64cff6ad651d">

However, it is being set correctly on the learner device
<img width="1800" alt="image" src="https://github.com/learningequality/kolibri/assets/5203639/db1442f1-0def-4378-8fdf-837ccc103872">
cc @rtibbles @bjester

**Comment by bjester** [comment] 2023-06-14 14:10
@akolson I believe this code should be setting it on the server-side https://github.com/learningequality/kolibri/blob/develop/kolibri/core/device/kolibri_plugin.py

**Comment by bjester** [comment] 2023-06-14 14:11
I think it might be setting it for the LOD too. Perhaps something is clearing it?

**Comment by akolson** [comment] 2023-06-14 14:31
Yes,, based on the db, it is being set on the LOD. The comment [here](https://github.com/learningequality/kolibri/blob/52cf5be730392cf37a432fee73daeeeda0c93793/kolibri/core/auth/tasks.py#L706) suggests that it is being cleared

**Comment by bjester** [comment] 2023-06-14 14:42
Hmm, but where's the actual code that deletes it? That might be a red herring, just an idea. The alternate possibility is that the hooks are broken

**Comment by akolson** [comment] 2023-06-14 14:49
Yeah, still looking around

**Comment by akolson** [comment] 2023-06-21 19:53
Hi @pcenov! So we dug out [the pr](https://github.com/learningequality/kolibri/pull/9438) that introduced these changes, thanks to @marcellamaki 🙂 . Just wondering if you could test test against the artifacts of this pr when you find some time. _(PS: The pr is about a 13 months old so its possible a lot has changed and it may not work.)_

**Comment by pcenov** [comment] 2023-06-22 10:03
Hi @akolson I am getting a `Failed to generate URL to download artifact.` error when I attempt to download any of the build assets from https://github.com/learningequality/kolibri/pull/9438.

**Comment by rtibbles** [comment] 2023-06-22 15:19
They've probably expired - I think the default retention period for artifacts is 3 months.

**Comment by akolson** [comment] 2023-06-22 15:32
@rtibbles is there a way to rerun the build?

**Comment by bjester** [comment] 2023-07-27 17:43
We reproduced this again in the bug hunt. @akolson I can help figure out what's going wrong. 
![Screenshot from 2023-07-27 10-38-08](https://github.com/learningequality/kolibri/assets/819838/76b845e2-56f2-43ba-aaa8-2ed8781c76f6)

**Comment by bjester** [comment] 2023-09-12 15:54
1) Unless I'm misremembering, [this `active=True` filter](https://github.com/learningequality/kolibri/blob/a90ccd8b9fb7213b956570aedb4e6d6371bfde4c/kolibri/core/device/api.py#L331) doesn't seem to make sense. A completed transfer should be `active=False` and an errored transfer likely has `active=True`, so no query filter against that should be used. Perhaps the variable naming are inconsistent with its intention but it could use more clarity.
2) The [`last_synced` annotation](https://github.com/learningequality/kolibri/blob/a90ccd8b9fb7213b956570aedb4e6d6371bfde4c/kolibri/core/device/api.py#L326) is tracking that last activity of a LOD sync session, which will likely always have some value and isn't representative of a completed sync. Additionally, if something fails and the sync is garbage collected, a new sync session will be created.
3) The above pieces of information are important for [`map_status`](https://github.com/learningequality/kolibri/blob/a90ccd8b9fb7213b956570aedb4e6d6371bfde4c/kolibri/core/device/api.py#L257) which also appears that there is a scenario where it could produce no status!

**Comment by bjester** [comment] 2023-09-12 15:57
> an errored transfer likely has `active=True`

that is until the sync session is garbage collected.

**Comment by rtibbles** [comment] 2023-09-13 22:43
> Unless I'm misremembering, [this active=True filter](https://github.com/learningequality/kolibri/blob/a90ccd8b9fb7213b956570aedb4e6d6371bfde4c/kolibri/core/device/api.py#L331) doesn't seem to make sense. A completed transfer should be active=False and an errored transfer likely has active=True, so no query filter against that should be used. Perhaps the variable naming are inconsistent with its intention but it could use more clarity.

Looking at the map_status function, the reason we are doing the `active=True` filter is because we are only using this information when a sync is in progress or has errored, which seems to accord with your description of when this would be the case.

> The [last_synced annotation](https://github.com/learningequality/kolibri/blob/a90ccd8b9fb7213b956570aedb4e6d6371bfde4c/kolibri/core/device/api.py#L326) is tracking that last activity of a LOD sync session, which will likely always have some value and isn't representative of a completed sync. Additionally, if something fails and the sync is garbage collected, a new sync session will be created.

I think this is where the null values are likely coming from - if the sync has been garbage collected, then the sync session associated with the sync status is null, and so the last_synced value is null. As a result we fail to catch any of the conditionals in `map_status` and return None, rather than `NOT_RECENTLY_SYNCED`.

**Comment by rtibbles** [comment] 2023-09-13 23:56
This helps a little to actually show a status when there is no sync session, but is not the root of the problem. The root appears to be that morango never actually starts the initializing stage, as far as I can tell.

I think this is because the LocalSessionContext defaults to the `INITIALIZING` stage, and therefore the session controller doesn't think there's been a state change when it fires the middleware, and so never fires the `started` signal handlers.

See https://github.com/learningequality/morango/blob/release-v0.7.x/morango/sync/context.py#L234 and https://github.com/learningequality/morango/blob/release-v0.7.x/morango/sync/controller.py#L250

I am guessing the salient difference when the sync is being run on the LODs, because they are running the management command is to do with these lines of code, which appear to be causing the initializing started signals to be fired: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/core/auth/management/utils.py#L560

**Comment by rtibbles** [comment] 2023-09-13 23:56
Seems like the solution here may be to add equivalent code into the TransferSessionViewset create method in morango, in order to ensure that the initializing started signals are always fired.

**Comment by rtibbles** [comment] 2023-09-15 19:45
This issue will only be completely solved once https://github.com/learningequality/morango/pull/201 is merged, and a new version of morango is released and kolibri updated with it.

**Comment by bjester** [comment] 2023-09-18 15:53
The firing of the `initializing.started` signal was a hack implemented in Kolibri to get around the issue of the signals firing within the transaction. Morango never fired that signal itself, because it was inconsistent with other signals on what data was available-- the initialization stage creates the sync session so a `started` signal wouldn't have the same information as all other signals. 

My mistake here was forgetting to preserve the attachment to the `completed` signal, and only attach to the `started` signal in the sync command. We wouldn't want to fire the signal in the viewset like https://github.com/learningequality/morango/pull/201 because that creates a discrepancy between client and server side signal firing. In short, the signal firing discrepancy originated in Kolibri from my hack, so I think it's best to contain the hacks to Kolibri until we have better flexibility in morango (that flexibility would delete the changes made in the morango PR anyway)

**Comment by rtibbles** [comment] 2023-09-21 17:14
After a bit of a tag team effort here, this has been resolved by @bjester in #11268

**Closed as completed by rtibbles** 2023-09-21 17:14 UTC
Labels: bug, P1 - important, TAG: regression, APP: Coach
