### ISSUE TITLE
Difficult questions are not displayed

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12147] opened 2024-05-09 14:36 UTC
_Originally posted by @radinamatic in https://github.com/learningequality/kolibri/issues/12111#issuecomment-2100740029_:

> Difficult questions are not displayed. I had 3 learners give incorrect answers to same 6 questions. 

   ![difficult-questions](https://github.com/learningequality/kolibri/assets/1457929/42cea09a-df79-435e-80a5-02f2214d11e7)

[db-logs.zip](https://github.com/learningequality/kolibri/files/15250374/db-logs.zip)

**Comment by AlexVelezLl** [comment] 2024-05-15 17:06
Hi @radinamatic I havent been able to replicate the issue 🥲. Could you help me with a little more of the context in which this happened? And if it happens always or only in specific scenarios/quizzes?

**Comment by AlexVelezLl** [comment] 2024-05-15 18:01
Oh I finally get it. I saw the complete comment in https://github.com/learningequality/kolibri/pull/12111#issuecomment-2100740029, and what happens is that there is a section that does not have resources, so the questions from that section dont appear to the student (but the section appears and the number of questions in the section is added), and the submit button does not appear because it think that they still need to complete that section, but there are no questions there. Therefore the difficult questions on the report screen are not visible because the students have not yet submitted their quiz as they appear to be in progress still.

**Comment by nucleogenesis** [comment] 2024-05-16 17:21
@radinamatic to retest this

**Comment by pcenov** [comment] 2024-05-21 14:30
Hi @radinamatic I confirm that the behaviour is exactly as described by @AlexVelezLl - you have to submit the Quiz in order to see the difficult questions displayed at Coach > Reports. This is the same behaviour as in Kolibri 0.15.2.

**Comment by radinamatic** [comment] 2024-05-21 16:02
Thank you @AlexVelezLl and @pcenov , closing for the time being as it's not a regression.

**Closed as completed by radinamatic** 2024-05-21 16:02 UTC
Labels: P0 - critical, TAG: regression
