### ISSUE TITLE
[RPi] The error "a lesson with this name already exists" is displayed for a while after creating a lesson with non existed name 

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7576] opened 2020-10-19 11:56 UTC
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011)
Browser: Google Chrome latest

Severity; minor

Preconditions; user is logged in as a coach, *Coach - '<class>' > Plan > Lessons* page is opened

Steps to reproduce;

1. Click on the "new lesson" button
2. Enter the non existed name for a lesson to the title field
3. Click on the "Save changes" button
4. Pay attention to the title field before the reloading the page

Actual result: The error "a lesson with this name already exists" is displayed for a while after creating a lesson with non existed name 
Expected result; The error "a lesson with this name already exists" shouldn't be displayed after creating a lesson with non existed name 
Attachment; http://e.pc.cd/FHbotalK

**Comment by jonboiser** [comment] 2020-10-19 16:58
This is a duplicate of #6593, which should be fixed in the latest Kolibri 0.14.4 pre-release.

**Closed as completed by jonboiser** 2020-10-19 16:58 UTC
