### ISSUE TITLE
Subtitle is showing language code, not the language name

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#2284] opened 2017-09-25 23:12 UTC
## Summary

When viewing a video with multiple subtitles, the language code appears, not the name as in previous versions.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: v0.6.0-beta3
 - Operating system: Windows 10
 - Browser: Chrome

## How to reproduce

1. View a video containing subtitles
2. Click on "cc" button to view subtitles

![img_20170925_190714](https://user-images.githubusercontent.com/25990164/30835251-61ea3a00-a225-11e7-952e-ddfe640a8be1.jpg)

## Real life implications

Just a bit confusing for someone who doesn't know the code. It was correct in an earlier version.

**Comment by christianmemije** [comment] 2017-09-26 01:09
@laurenlichtman Cannot seem to reproduce on the 0.6 branch. Can you share the channel id?

**Comment by laurenlichtman** [comment] 2017-09-26 02:53
ID: bcd99d8aeef04ce6b9e25a88d87eedb7
I'm viewing it locally on my computer. Social Studies --> Countries --> Syria --> Culture --> Girls' Clothing.

**Comment by christianmemije** [comment] 2017-09-26 16:52
Tested in Browserstack on Windows 10 and Chrome and cannot reproduce. Seems that `track.lang.lang_name` is missing so it's falling back to the lang code. @laurenlichtman Can you try to reimport the channel? 

https://github.com/learningequality/kolibri/blob/de06274bd2397784184b8dec87755359634c0097/kolibri/plugins/media_player/assets/src/views/index.vue#L16

**Comment by rtibbles** [comment] 2017-09-26 17:17
Yes, this does seem to be an issue with an old channel database (from when before we added the language names to the channel database).

**Comment by laurenlichtman** [comment] 2017-09-27 19:10
@christianmemije I wasn't able to reimport this channel (see Slack) and had to uninstall Kolibri completely and reimport the channels. When I upgrade to v0.6.x-beta in the future, I'll test this out and make sure it works.

**Comment by christianmemije** [comment] 2017-09-28 20:09
Closing as it seems that it was due to an outdated database.

**Closed by christianmemije** 2017-09-28 20:09 UTC
