### ISSUE TITLE
kolibri cannot start after switching from sqlite to postgresql database

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#5721] opened 2019-06-28 00:43 UTC
### Observed behavior

Kolibri cannot start when the database switches from sqlite to postgresql because there are no migrations applied to the postgresql database.
Running `kolibri manage migrate` doesn't help because the command errors out before actually running migrations.
I had to delete the `.data_version` file to force running migrations on postgresql database.

### Expected behavior

users should be able to start kolibri successfully after they switch from sqlite to postgresql if they run some additional commands, e.g. kolibri manage migrate.

### User-facing consequences

users cannot start kolibri after they switch from sqlite to postgresql

### Errors and logs

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "./kolibri/core/device/middleware.py", line 31, in __call__
    request
  File "./kolibri/core/device/translation.py", line 81, in get_language_from_request_and_is_from_path
    if not getattr(resolve(request.path_info).func, "translated", False):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/urls/resolvers.py", line 366, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/urls/resolvers.py", line 366, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/urls/resolvers.py", line 366, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/urls/resolvers.py", line 366, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/urls/resolvers.py", line 366, in resolve
    sub_match = pattern.resolve(new_path)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/urls/resolvers.py", line 361, in resolve
    match = self.regex.search(path)
  File "./kolibri/core/device/translation.py", line 164, in regex
    device_language = get_device_language() or get_settings_language()
  File "./kolibri/core/device/translation.py", line 35, in get_device_language
    DEVICE_LANGUAGE_CACHE_KEY, DeviceSettings.objects.get().language_id, 600
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "device_devicesettings" does not exist
LINE 1: ...device_devicesettings"."default_facility_id" FROM "device_de...
```

### Steps to reproduce

1. start kolibri with sqlite database, so the migrations are applied there
2. stop kolibri server
3. put the postgresql database settings to options.ini file
4. start kolibri

### Context

kolibri version: 0.12.5
operating system: OSX and Ubuntu 16.04

**Comment by indirectlylit** [comment] 2019-06-28 14:55
What is the expected behavior? Should data that was previously in one database be transferred to the other?

**Comment by lyw07** [comment] 2019-06-28 14:57
I think the expected behavior should be something like ‘kolibri manage migrate’ works for applying the migrations to postgresql database.

**Comment by indirectlylit** [comment] 2019-06-28 15:19
So to clarify, that would initialize the new postgresql database and allow the app to run, but existing data in sqlite would not be migrated?

**Comment by lyw07** [comment] 2019-06-28 15:26
Ah I forgot about the existing data in sqlite database, sorry. I don’t think running migrate command will migrate the existing data from sqlite to postgresql database (Please correct me if I’m wrong @rtibbles thank you!). So we will need some other operations to do that I think?

**Comment by rtibbles** [comment] 2019-06-28 15:35
Yes, there is no expectation that the data should transfer.

If we want to implement that, it would be an additional feature - probably most easily done by doing a django fixture dump and restore, but it would be very slow.

**Comment by lyw07** [comment] 2019-06-28 16:51
Do we have documentation about how to change to use postgresql database? I don't find it in our user doc. Maybe for now, we can add additional guidance about how to migrate the data from sqlite to postgresql in the user documentation.

**Comment by radinamatic** [comment] 2019-06-28 17:11
> Do we have documentation about how to change to use postgresql database? I don't find it in our user doc.

Nope, this is the first case I hear of somebody attempting it.

It would certainly need to be placed among the advanced management topics, but if there's consensus that we need to cover it, I'm all for it! 👍

**Comment by indirectlylit** [comment] 2019-06-29 01:43
It sounds from [this thread](https://community.learningequality.org/t/implications-of-large-db-sqlite3-file-for-kolibri-performance/1218) that data transfer would be a need, unless there were some other way to achieve it (e.g. using sync functionality)

> If we want to implement that, it would be an additional feature - probably most easily done by doing a django fixture dump and restore, but it would be very slow.

Agreed.

Just flagging that `migrate` from an end-user's perspective will carry the connotation of "data migration", even though in this context it means "initialize database". It's [another scenario](https://github.com/learningequality/kolibri/pull/5494#issuecomment-495821563) where I think the `manage` commands might eventually be hidden behind a less Django-tainted CLI.

**Comment by jredrejo** [comment] 2019-09-10 18:50
@indirectlylit I think this should be moved to `clearinghouse` : This is not a current issue because we are not documenting anywhere that we have this feature. However, migrating both the structrure and the data from sqlite to postgresql it's clearly a 'nice to have' feature for the feature.

**Comment by indirectlylit** [comment] 2019-09-17 02:24
done, thanks

**Closed as completed by indirectlylit** 2019-09-17 02:24 UTC

**Comment by socketbox** [comment] 2021-12-17 22:29
See https://www.notion.so/learningequality/Move-a-SQLite-database-to-PostgreSQL-Using-PGLoader-8807b6515d8d4dc0a08b78934a6aebfa
