### ISSUE TITLE
My Downloads has eternal KCircularLoader when there are no downloads

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11029] opened 2023-07-27 21:16 UTC
## Observed behavior
Reported by @nucleogenesis in the beta0 bug bash

## Expected behavior
The string for no download state should be displayed, not an infinite loading state

## User-facing consequences
Mis-communicates the state of user downloads

## Steps to reproduce
Navigate to myDownloads page when you have not downloaded anything

## Context
0.16.0-beta0

**Comment by marcellamaki** [comment] 2023-08-22 13:42
It seems like this may have been fixed incidentally with some other updates. @radinamatic or @pcenov - could you confirm on the latest beta? (Not urgent - when there is time after other PR QA is completed)

**Comment by AllanOXDi** [comment] 2023-08-22 13:47
Yep! I was not able to reproduce it after pulling the latest changes on 0.16.x
<img width="1469" alt="Screenshot 2023-08-22 at 16 45 54" src="https://github.com/learningequality/kolibri/assets/103313919/9b4a113f-099c-4851-a4be-ae0f354a713c">

**Comment by pcenov** [comment] 2023-08-23 13:24
I confirm that as well - the eternal KcircularLoader is not being displayed in beta3 so this issue can be closed.

**Comment by radinamatic** [comment] 2023-08-23 13:42
Closing as not extant anymore.

**Closed as completed by radinamatic** 2023-08-23 13:42 UTC
Labels: P0 - critical, DEV: frontend, SIZE: small
