### ISSUE TITLE
Coach stuck on resource preview page when trying to add resources to lesson

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7633] opened 2020-10-28 05:46 UTC
### Observed behavior

When on the screen for adding resources to a lesson, nothing happens if Coach clicks the back button - so they would not be able to exit the section that way.
…

### Expected behavior

The coach should be able to click the back arrow in the upper left hand corner and return to the previous screen. 
…

### User-facing consequences

Coach would be unable to easily go back to any other area of the app without completely restarting Kolibri.
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app (for example on Mac) and log in to Coach account
2. From the class home page, click on an existing lesson (or create a new one if there is not one already existing)
3. The lesson should open under the "Reports" tab. From the lesson title box, click the "options" drop-down menu and click "manage resources"
4. Click on a content channel
5. Click on a topic 
6. View the list of individual resources under that topic and click on one of them 
7. This should open a new screen with a preview of that topic's content and a back arrow in the upper left corner
8. Click the back arrow
9. Observe that the clicking the back arrow does not take the user to the previous page
10. Note that the only way for the user to get out of this page is to quit and restart the app. 

Here's a screen recording showing the behavior:

https://drive.google.com/file/d/1G8lhRJbWIosXKz5m5HRMcGZe2sy9d7AJ/view

Note - Line 57 is where this issue occurs in the testing workflow:

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-lesson.feature 

…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment] 2020-11-03 22:26
Closing as a duplicate of #7584 (same root cause)

**Closed as completed by jonboiser** 2020-11-03 22:26 UTC
