### ISSUE TITLE
Content is lost when upgrading Maharashtra Grade 3-8/9 from version 26 to latest (31)

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#4592] opened 2018-12-12 19:41 UTC
### Observed behavior

A Kolibri server (linux laptop) used in a Nalanda classroom had version 26 of "Maharashstra state class 3 to 9 (english)" installed on August 2018.

In December 2018, an attempt to upgrade this channel ended up "removing" (e.g. making inaccessible from Learn) some content in the Grade 6 topic, which then broke a Lesson using that content. The Nalanda program manager re-installed version 26 from a thumb drive.

Later I observed the upgrade process again. Merely updating the content metadata DB had the effect of making many content items appear as if they were no longer installed on the drive. This was manifested on the Select Content Page (import) as nodes that should have been disabled (since they were already installed) becoming selectable again (as if they were not already installed).

We then went ahead and tried to re-download the channel from the internet, selecting the entire channel checkbox and going ahead with the download. The `kolibri.log` file did not show any download progress bars, but did show some "annotating availability" logs. This was expected because there _shouldn't_ have been a lot of content to download (if it was already on the server_. On the other hand, this was unexpected because V31 should have some new content, namely the content for Grade 9.

The import process took almost 1 hour, even though the channel is not that large (although deeply nested). The end result was the same as in the morning: resources were missing. And so we needed to re-install V26 for the next class using Kolibri.

Info

* Channel ID `8fc515793aad4e52b490b03c48ad21de`. [STudio link](https://develop.studio.learningequality.org/channels/8fc515793aad4e52b490b03c48ad21de/view/76182b5)
* Kolibri version 0.9.5b3
* Total file size of v26 is about 800 MB. V31 should be larger, but after installation it is 300 MB.

### Expected behavior

1. Since V31 is a superset of V26, updating the content metadata DB should not affect the availability contents of the server.
1. 

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment] 2018-12-13 18:17
possibly related? #4342

**Comment by jredrejo** [comment] 2019-01-04 17:42
@jonboiser  how did you reinstall v26? In order to reproduce this problem (similar to #4342 ) I'd like to be able to do it.

**Comment by radinamatic** [comment] 2019-01-04 17:48
If I understood correctly they had v26 previously exported on an USB drive, and available to import from... Would be good to have it confirmed, I cannot think of another way atm.

This does not help us reproduce, as we would have to have KA EN v13 on an external drive to try... :confused:

**Comment by jredrejo** [comment] 2019-01-04 20:22
I can confirm the issue happens with kolibri versions up to 0.10.1
Using 0.10.2 it does not happen anymore. PR #4123 fixed it.

However, after the issue happens using <0.10.2, upgrading to an upper version of Kolibri does not solve it. It keeps the content lost.

**Comment by indirectlylit** [comment] 2019-01-08 18:36
Is there something we can do to "un-lose" the content?

**Comment by jredrejo** [comment] 2019-01-09 13:03
@indirectlylit I think we can, after reproducing the problem I see the content is kept in .kolibri/content/storage. The problem is in the database. 
I am trying to find a logical way to undelete the deleted content , not conflicting with _real_ deletions done by the user.

**Comment by jredrejo** [comment] 2019-01-10 14:04
@jonboiser  would it be possible to reproduce the problem to check the new command can recover the lost content after updating?

**Comment by indirectlylit** [comment] 2019-11-06 22:04
this is being addressed by ongoing changes in 0.13.0

**Closed as completed by indirectlylit** 2019-11-06 22:04 UTC
Labels: TAG: ux update
