### ISSUE TITLE
App crashed after initiating a search within a channel

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7636] opened 2020-10-28 07:03 UTC
### Observed behavior

After initiating a search within a channel, the app crashed.
…

### Expected behavior

The user should receive the relevant search results.
…

### User-facing consequences

The user is unable to view search results and has to restart the app.
…

### Errors and logs

Note: these two are identical, but one is a PDF and the other is a .docx - it wouldn't let us upload the isolated copied version in the RTF format it was in, so we wanted to provide two file types in case one is preferable:

(This ticket is for the first crash within the log below)

[crash logs Mac - Oct 27 - kolibri.pdf](https://github.com/learningequality/kolibri/files/5450160/crash.logs.Mac.-.Oct.27.-.kolibri.pdf)

[crash logs Mac - Oct 27 - kolibri doc.docx](https://github.com/learningequality/kolibri/files/5450162/crash.logs.Mac.-.Oct.27.-.kolibri.doc.docx)

Here's a .txt version of the full log from this session:

[kolibri.txt](https://github.com/learningequality/kolibri/files/5450165/kolibri.txt)

The crash happened between 10:50pm and 11pm Pacific time on October 27th.

This is the debut.txt file, which doesn't really contain anything -- but attaching per request, if only to note that it is indeed empty.

[debug.txt](https://github.com/learningequality/kolibri/files/5450166/debug.txt)

…

### Steps to reproduce

Note: this is not 100% reproducible, and appears to be somewhat of an edge case. But these were the steps taken:

1. Open Kolibiri desktop app and log in to Coach account
2. From the class home page, click on an existing lesson (or create a new one if there is not one already existing)
3. The lesson should open under the "Reports" tab. From the lesson title box, click the "options" drop-down menu and click "manage resources."
4. Click on a content channel - in this case, HP LIFE - Courses (English)
5. Enter a search term in the search bar and click the magnifying glass
6. Observe that the app crashes 
(Not 100% reproducible)
…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment] 2020-10-28 16:50
This looks like a duplicate of #7639. I think there's a misunderstanding that the Search bar works differently after clicking a channel. They are actually the same regardless of which channel or topic you are looking at.

**Closed as completed by jonboiser** 2020-10-28 16:50 UTC

**Comment by MindfulQA** [comment] 2020-10-28 18:28
Thanks for clarifying, @jonboiser! We weren't sure if this might have a related cause but need an additional fix implemented in this area as well.
