### ISSUE TITLE
spurious 'removed 0 resources' notification

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4848] opened 2019-01-31 22:45 UTC
### Observed behavior

observed by @jtamiace during 0.12.0 alpha 7 testing:

> ![image](https://user-images.githubusercontent.com/2367265/52090516-761cc680-2566-11e9-9b77-4b073035b10b.png)

### Expected behavior

Notifications should not be displayed until the user has made a change

### User-facing consequences

possible confusion

### Errors and logs

…

### Steps to reproduce

…

### Context

0.12.0 alpha 5

**Comment by jredrejo** [comment] 2019-02-01 09:57
@jtamiace I can't reproduce this in develop, can you guide me to try to reproduce it?
I have tried it with alpha5, alpha7 and develop.

**Comment by jtamiace** [comment] 2019-02-01 17:38
I've reproduced this in `Plan > New lesson` and `Plan > New quiz`:

1. Go all the way to the preview of a resource
2. Click "Add":
<img width="969" alt="screen shot 2019-02-01 at 9 33 08 am" src="https://user-images.githubusercontent.com/6668144/52139235-681d8300-2604-11e9-8db5-f25de13f93f0.png">

3. Click the back arrow before the snackbar goes away
4. Continue navigating back and forth between "preview" of any resource and the back arrow before the snackbar goes away and it will keep popping up as if you are adding new things
5. If you exit the quiz creation while the snackbar is open, it pops up again outside also:
<img width="986" alt="screen shot 2019-02-01 at 9 36 27 am" src="https://user-images.githubusercontent.com/6668144/52139414-f560d780-2604-11e9-98e4-19e04f601c11.png">
....And it keeps popping up when you navigate to other pages before you let the snackbar go away (I had tried this again with a different resource)
<img width="981" alt="screen shot 2019-02-01 at 9 40 28 am" src="https://user-images.githubusercontent.com/6668144/52139640-8fc11b00-2605-11e9-9992-45bca6d39daa.png">


Hope that helps

**Comment by radinamatic** [comment] 2019-02-04 01:14
Not sure if it's related, but I'm replicating a similar issue: the snackbar appears when clicking on topic cards (and even just pressing the *Manage resources* button), but only _until_ the first resource is actually added. After the first resource is in, the spurious snackbar does not appear anymore. 

![removed-0](https://user-images.githubusercontent.com/1457929/52185653-99bb6780-2819-11e9-9711-d50030a08844.gif)

**Comment by radinamatic** [comment] 2019-02-07 01:31
Still seeing this on `release-v0.12.x` branch, seems as if #4906 did not cover all the bases... 😕

**Comment by jredrejo** [comment] 2019-02-07 09:07
@radinamatic  it's likely the same problem existed in other parts of the application. That PR solved it when planning new quizzes/lessons. Where do you see it exactly? Same solution will have to be applied to the components you 're using.

**Comment by radinamatic** [comment] 2019-02-07 12:48
Thanks for the clarification @jredrejo 👍 
I'm still seeing this when adding resources to lessons, as in the screenshot above ^^

**Comment by radinamatic** [comment] 2019-02-12 21:47
Fixed in #5010 👍

**Closed as completed by radinamatic** 2019-02-12 21:47 UTC
Labels: P1 - important
