### ISSUE TITLE
Bookmarks - The 'Completed' label is displayed over the 'Bookmarked N minutes ago' text

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8676] opened 2021-11-12 16:39 UTC
## Observed behavior
When a bookmarked item has been completed by the Learner the 'Completed' label is displayed over the 'Bookmarked N minutes ago' text.

## Expected behavior
The labels should not overlap.

## Steps to reproduce the issue
1. Install the following [build.](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta2)
2. Bookmark several completed resources and go to http://127.0.0.1:8080/en/learn/#/bookmarks

## Additional information

![2021-11-12_16-02-26](https://user-images.githubusercontent.com/79847249/141501938-1a47a147-274f-4cbe-a5da-d879fc3d9a60.png)

## Usage Details
 - OS: Windows 10, Ubuntu
 - Browser: Chrome, Firefox

**Comment by pcenov** [comment] 2021-11-12 16:40
@radinamatic

**Comment by rtibbles** [comment] 2021-11-16 23:19
This is a duplicate of #8613 - closing to consolidate reports.

**Closed as completed by rtibbles** 2021-11-16 23:19 UTC
Labels: bug, P1 - important, APP: Learn, DEV: frontend
