### ISSUE TITLE
User options alignment issue

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7079] opened 2020-06-18 13:34 UTC
### Observed behavior
User options text alignment issue and not displaying with the right font size. 

### Expected behavior

…

### Errors and logs
![c1](https://user-images.githubusercontent.com/8663934/85026278-0d5dda80-b1ab-11ea-9db4-04fe4c97e806.PNG)

Please wrap errors in triple backticks for clean formatting like this:
```
01:10 info: something happened
01:12 error: something bad happened
```
-->

…

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version:  0.14.0b2
 * Operating system: Windows 10
 * Browser: Chrome 83 & IE11

**Comment by indirectlylit** [comment] 2020-06-18 17:18
duplicate of https://github.com/learningequality/kolibri/issues/6986

**Closed as completed by indirectlylit** 2020-06-18 17:18 UTC
