### ISSUE TITLE
Lesson report for learner

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5110] opened 2019-02-20 09:52 UTC
### Observed behavior
Create a lesson and activate it. Without solving, when we go to the reports lessons tab. After clicking on lesson. click on learner tab and click on any learner and then click on lesson exercise. It will not load a page.

### Expected behavior
It must load a page.

### Steps to reproduce
1. Create lesson.
2. Go to report.
3. Click on lesson and click on learner tab. 
4. Click on learner name.
5. Click on exercise and see the behaviour.

### Context
 * Kolibri version : Kolibri 0.12.0b4
  * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshot

![1](https://user-images.githubusercontent.com/12776071/53082616-3cb2f780-3523-11e9-981e-9a40f10a92bd.png)
![2](https://user-images.githubusercontent.com/12776071/53082615-3c1a6100-3523-11e9-9363-ab7de4749526.png)
![3](https://user-images.githubusercontent.com/12776071/53082612-3c1a6100-3523-11e9-8dc1-c1be0161f0e0.png)
![4](https://user-images.githubusercontent.com/12776071/53082610-3c1a6100-3523-11e9-9b68-00b6c3e33159.png)
![5](https://user-images.githubusercontent.com/12776071/53082609-3b81ca80-3523-11e9-8d4d-5ba9f14ea0ae.png)

**Comment by indirectlylit** [comment] 2019-02-20 17:44
thanks for the report!

duplicate of #5099, and also related to #5032

**Closed as completed by indirectlylit** 2019-02-20 17:44 UTC

**Comment by yogeshmhaskule** [comment] 2019-03-05 10:59
Tested on kolibri 0.12.0. And it works as expected.
![lesson_bug_1](https://user-images.githubusercontent.com/7850420/53800925-e18df580-3f63-11e9-8638-5a47b1c5afb3.png)
![lesson_bug_2](https://user-images.githubusercontent.com/7850420/53800929-e18df580-3f63-11e9-8f95-851287e8ec29.png)
