### ISSUE TITLE
Sync facility data - Constantly seeing 'Most recent sync failed' message

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9091] opened 2022-02-09 16:35 UTC
## Observed behavior
Whenever I attempt to sync my facility to KDP I'm seeing a 'Most recent sync failed' message but if I manually refresh the page I can see that the sync has been successful.

## Expected behavior
The user should be shown the correct status of the sync procedure.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-windows/builds/3136#308b9948-f6b3-466a-a661-162ed2f97d63
2. Go to Faclity>Data and scroll down to the 'Sync facility data' section
3. Register your facility to KDP
4. Click the Sync button and wait for the confirmation message.

## Screenshots
![2022-02-09_17-34-42](https://user-images.githubusercontent.com/79847249/153246018-34fb93f0-7083-4031-b8f4-d38cc0aacee5.png)
![2022-02-09_18-31-54](https://user-images.githubusercontent.com/79847249/153246027-2eb392fe-40ad-4407-9de3-55104c22679d.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment] 2022-02-09 16:36
@radinamatic

**Comment by radinamatic** [comment] 2022-02-09 20:50
I'm also able to replicate this with 0.15.1b0 on Windows 10, sync is reported as failed in the UI until the page is reloaded.

![kdp3](https://user-images.githubusercontent.com/1457929/153287639-8e206b9a-e376-4f50-9ad6-5c1376b2e02f.gif)

**Comment by radinamatic** [comment] 2022-02-09 20:54
@marcellamaki Again, impacts the UX, but syncing is still working: not broken, just user facing incorrectly reported until the reload. Priority to be confirmed.

**Comment by marcellamaki** [comment] 2022-02-09 20:56
@radinamatic and @pcenov  --- thank you! and this maybe be more important than the buttons, since it seems to the user like an _error_

**Comment by MisRob** [comment] 2022-02-11 11:33
> Again, impacts the UX, but syncing is still working: not broken, just user-facing incorrectly reported until the reload. Priority to be confirmed.

@radinamatic To clarify "syncing is still working", did you mean that
(1) it appeared to work after the page reload because the success message was displayed
(2) data has been synced to KDP

?

**Comment by pcenov** [comment] 2022-02-11 11:39
@MisRob, yes, both of the above - the syncing is working because after a page reload we see the success message and also the data has been synced to KDP.

**Comment by radinamatic** [comment] 2022-02-14 05:30
As @pcenov noted, the answer is **yes** to both, although there is no _success message_ as such, user just sees the green ✔️ alongside the facility name after reload (instead of _Sync failed_ error), and the data can be seen as synced on KDP.

1 | 2
--- | ---
![Selection_144](https://user-images.githubusercontent.com/1457929/153805583-b1145961-28e5-4043-b717-302087a07d72.png) | ![Selection_143](https://user-images.githubusercontent.com/1457929/153805586-e24b1ee1-eccf-44b6-b17d-0806a6a27373.png)

**Comment by MisRob** [comment] 2022-02-17 13:19
I was able to reproduce this only once (most likely when KDP wasn't fully functional due to some work in progress) when I got `morango.errors.MorangoError: Stage 'cleanup' failed` in my server terminal when syncing to KDP. 

@jamalex  mentioned
> The "finalization" network request to KDP might time out, hence indicating an error, but then still eventually wrap up on the server side, which would be why the data might still show up.

Looking at frontend code [here](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/device/assets/src/views/FacilitiesPage/index.vue/#L225) and [here](https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/core/assets/src/views/sync/FacilityNameAndSyncStatus.vue#L36-L44), I think it's possible to run into this problem when one of the sync tasks (when polling `/api/tasks`) returns `FAILED` status during any of sync stages, which might not necessarily mean that data hasn't been synced at all as mentioned above, causing a discrepancy between the task status and the `last_synced` field on the facility object later on.

From the user's point of view, this means that although there was a problem during the process, the data has been transferred after all.

I'm not sure what would be the best way to communicate this to users and if we need to change UX, and whether it's possible to technically recognize what kinds of tasks failures caused data really not to be synced. Or maybe there's no need to do anything about it now since it seems that it was happening during deploying the new KDP and also, @jamalex mentioned that the new version shouldn't likely cause timeouts?

Any thoughts @bjester @jamalex @jtamiace ?

**Comment by MisRob** [comment] 2022-02-17 13:20
^ Attaching a link to [the related Slack thread](https://learningequality.slack.com/archives/CB37UM23A/p1644578438287169) for reference

**Comment by bjester** [comment] 2022-02-17 22:23
> From the user's point of view, this means that although there was a problem during the process, the data has been transferred after all.

If the sync fails for any reason, I think our code should assume the worst case scenario, that no data has been actually synced. 

So seems as though we should be persisting the "Most recent sync failed" in this case.

**Comment by MisRob** [comment] 2022-02-18 10:55
@bjester Thank you, that sounds like the safest option (the worst case scenario is that someone could be pleasantly surprised that data has been synced :relaxed: )

Right now, when fetching facility data, it seems that we only have the information about time of the last sync, whether it's been successful or not (that frontend mistakenly assumes to be successful) saved in `last_synced` field on the facility object. To be able to persist success/failure information, I think I'd need to add a new field [to the facility viewset on backend](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/auth/api.py/#L425) to keep this information, is that right? API could then maybe return something like:

```
# time of the last successful sync attempt
last_synced_success: "2022-02-17T09:32:57.000000Z"

# time of the last sync attempt (could be failed)
last_synced: "2022-02-18T13:04:26.000000Z"
```

We could then
- Use `last_synced_success` to display "Last successful sync: [time] ago" message
- Compare `last_synced_success` with `last_synced`. If their values are different, we'd show show "Most recent sync failed" message (right now this message can show only when a task is running and failure information comes from the task status)

Alternatively, we could make sure that `last_synced` will only get updated on the backend when the whole process has been completed without any failures and only add `most_recent_sync_failed` field to the facility object? API would in this case returned:

```
# time of the last successful sync attempt
last_synced: "2022-02-17T09:32:57.000000Z"

most_recent_sync_failed: True
```

Do you have any recommendations?

**Comment by bjester** [comment] 2022-03-04 16:54
@MisRob Sorry for the delay. Yeah I think the general approach of modifications to the viewset that you laid out should work well. I think for simplicity, like you noted, having fields like `last_successful_sync` and `last_failed_sync` should give the frontend everything you need to display this correctly. Here are some filtering recommendations:
```python
    def annotate_queryset(self, queryset):
        transfer_session_dataset_filter = Func(
            Cast(OuterRef("dataset"), TextField()),
            Value("-"),
            Value(""),
            function="replace",
            output_field=TextField(),
        )

        return (
            queryset.annotate(
                num_users=SQCount(
                    FacilityUser.objects.filter(facility=OuterRef("id")), field="id"
                ),
                num_classrooms=SQCount(
                    Classroom.objects.filter(parent=OuterRef("id")), field="id"
                ),
                last_successful_sync=Subquery(
                    # the sync command does a pull, then a push, so if the push succeeded,
                    # the pull likely did too, which means this should represent when the
                    # facility was last fully and successfully synced
                    TransferSession.objects.filter(
                        push=True,
                        active=False,
                        transfer_stage=transfer_stages.CLEANUP,
                        transfer_stage_status=transfer_statuses.COMPLETED,
                        filter=transfer_session_dataset_filter
                    )
                    .order_by("-last_activity_timestamp")
                    .values("last_activity_timestamp")[:1]
                ),
                last_failed_sync=Subquery(
                    # Here we simply look for if any transfer session has errored
                    TransferSession.objects.filter(
                        transfer_stage_status=transfer_statuses.ERRORED,
                        filter=transfer_session_dataset_filter
                    )
                    .order_by("-last_activity_timestamp")
                    .values("last_activity_timestamp")[:1]
                )
            )
        )
```
You can use the [morango constants](https://github.com/learningequality/morango/tree/release-v0.6.x/morango/constants) for filtering.

**Comment by MisRob** [comment] 2022-07-09 07:18
Closed by https://github.com/learningequality/kolibri/pull/9541

**Closed as completed by MisRob** 2022-07-09 07:18 UTC
Labels: P1 - important, TAG: regression, APP: Facility
