### ISSUE TITLE
(Gherkin needs update) The list of all *Channels* doesn't open after deleting the previous search term and pressing *Enter*

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7587] opened 2020-10-20 09:27 UTC
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

Severity; major

Preconditions; user is logged in as a coach, *Coach - '<class>' > Report > Lessons > '<lesson>'* page is opened;

Steps to reproduce;

1. Click on the "Options" dropdown
2. Click on the "Manage Resources" button
3. Enter in the Search field
4. Press the Submit search button
5. Press the *X* button in the search field 
6. Press *Enter* or click on the search button
7. Notice that the page with the list of Channels doesn't open

Actual result: The list of all *Channels* doesn't open after deleting the previous search term and pressing *Enter*

Expected result: The list of all *Channels* opens after deleting the previous search term and pressing *Enter*

Attachment: http://e.pc.cd/gpbotalK

**Comment by jonboiser** [comment] 2020-10-20 22:18
I don't think this expected behavior was part of the original specification for this feature.

The default behavior if "" is provided as search term is to simply do nothing.

**Comment by radinamatic** [comment] 2020-10-22 22:14
Fairly sure that the Gherkin came out from some (initial) implementation that included this behavior. 
And I would also argue that it is what users expect: when they clear the search term and press <kbd>Enter</kbd>, the previous search results should be cleared.

 Thoughts @jtamiace @khangmach?

**Comment by khangmach** [comment] 2020-10-22 22:33
what @jonboiser described was part of the initial designs of the search bar. The current behavior seems fine to me, as the lack of response from the UI nudges you to put in a search term. 

If we had search as you type functionality in the platform, then the action of clearing the search field (with X) to refresh your results seems expected and natural

**Comment by khangmach** [comment] 2020-10-22 22:34
I'll make a note of this when writing search patterns in the kolibri design system. But I do not think this is something we need redesigned at the moment

**Comment by radinamatic** [comment] 2020-10-22 22:39
Gotcha, will amend the Gherkin then! :+1: 

> lack of response from the UI nudges you to put in a search term

Or it might make you think the search is not working :smiling_imp:

**Comment by khangmach** [comment] 2020-10-22 23:08
thank you @radinamatic. Bookmarking this issue for KDS reference

**Comment by jonboiser** [comment] 2020-11-03 20:11
I'm closing #7638 as a duplicate of this, but they point out this behavior was expected in the Quiz workflow as well as the Lesson's workflow.

**Comment by radinamatic** [comment] 2021-01-22 21:27
@metodimilevqa Let's include this change in the current PR with Gherkin updates, which will close #7753.

**Closed as completed** 2021-03-23 22:02 UTC
Labels: TAG: ux update, gherkin update
