### ISSUE TITLE
Exam exercises not working on IE11 only

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3984] opened 2018-07-06 06:17 UTC
### Observed behavior
Can't load exam exercises on IE11 only.
I can load this Exam exercises on other browsers.
related to #3928 

### Errors and logs
![screen shot 2018-07-06 at 2 15 17 pm](https://user-images.githubusercontent.com/8663934/42362720-21f4fb10-8127-11e8-8ea1-8cf0c96fec50.png)

### Context

 * Kolibri version: 0.11
 * Operating system: Windows 10
 * Browser: IE!!

**Comment by indirectlylit** [comment] 2018-07-06 21:30
@christianmemije mind looking into this? As far as I know, this page should have your new layout

**Comment by christianmemije** [comment] 2018-07-06 21:37
Duplicate of https://github.com/learningequality/kolibri/issues/3928. Was fixed in 0.10. Need to publish a new version of perseus for Develop.

**Closed as completed** 2018-07-23 20:36 UTC
