### ISSUE TITLE
Survey modality - Coach cannot assign a survey to a learner

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9022] opened 2022-01-21 14:40 UTC
## Observed behavior
If I attempt to assign a survey to a learner when I sign in as a learner I see the survey as a regular quiz. Also the coach is able to see a report with the correct/incorrect answers. 
Expected: Coach should be able to assign surveys to learners and when looking at reports, they should not display any correct/incorrect information, any scores, or completion criteria.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/4813
2. Import the Colors of Kindness (gutuf-potuv) channel and as a coach assign a survey to a learner user
3.  As a learner complete the assigned survey

## Additional information
A Submit quiz button is visible instead of Submit survey:
![2022-01-21_15-33-03](https://user-images.githubusercontent.com/79847249/150545092-bc828da2-e16c-4a34-bcc6-596655ef9efa.png)

Coach report:
![2022-01-21_15-34-01](https://user-images.githubusercontent.com/79847249/150545097-b19b04f8-298a-4bfc-91c0-8d76b8670906.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by rtibbles** [comment] 2022-01-21 16:09
Is this assigning it within a lesson, or assigning it within a quiz? If the latter, this is intended behaviour at the moment.

**Comment by pcenov** [comment] 2022-01-21 16:26
Assigning within a quiz. Assigning within a lesson is functioning correctly. It just seemed logical to me that it should be possible to assign it as a quiz though...

**Comment by rtibbles** [comment] 2022-01-21 16:35
Right - 'assigning within a quiz' is 'creating a quiz from the survey' so it is expected that it makes a quiz.

**Closed as completed by rtibbles** 2022-01-21 16:35 UTC
