### ISSUE TITLE
Some issues with the h5p viewer plugin

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#7790] opened 2021-02-15 17:24 UTC
### Observed behavior
After testing h5p content with the plugin enabled some issues have appeared:
1. h5p video activities can take a long time to load (probably they can't stream and load the whole video before beginning to play it) and while loading the user does not have any feedback, it looks like a broken app
2. In Google Chrome there's no way to go forward/backward in the video, whenever the cursor is clicked the video resets to its original position. This issue does not happen when using Firefox
3. When you open the video, it doesn’t exactly fit the frame, which means that the progress bar and settings at the bottom are hidden:
![image](https://user-images.githubusercontent.com/1008178/107976775-63915080-6fba-11eb-8274-b54659da487a.png)

### User-facing consequences
h5p interactive videos lack many of the features normal videos have

### Steps to reproduce
Add h5p content to a channel and import it into Studio to test

### Context
Kolibri 0.14.6a2 (Chile UNW server)

**Comment by rtibbles** [comment] 2021-02-15 17:29
> 1. h5p video activities can take a long time to load (probably they can't stream and load the whole video before beginning to play it) and while loading the user does not have any feedback, it looks like a broken app

This is probably a combination of general H5P issues and the video specific issue. H5P, pretty much by design, loads many many static assets all at once. The canonical PHP implementation of H5P gets around this by doing backend asset bundling, so that not as many files are served, but our Python implementation does not do this.

In addition, as you pointed out, the backend the videos are being served from does not support byte-range requests, so the entire video must be loaded before playback can start.

> 2. In Google Chrome there's no way to go forward/backward in the video, whenever the cursor is clicked the video resets to its original position. This issue does not happen when using Firefox

This is due to the lack of byte-range requests on the backend.

> 3. When you open the video, it doesn’t exactly fit the frame, which means that the progress bar and settings at the bottom are hidden:

This problem is not unique to H5P, and we can do more to make sure our iframes properly resize to fit their contents.

**Comment by rtibbles** [comment] 2021-02-15 17:42
Solutions for this:

1. Updating the zipcontent backend to support byte-range requests - this should fix the video specific issue.

2. Client side rendering of H5P files - I have a prototype implementation of this, which would allow us to skip the zipcontent backend entirely for H5P files, and remove the issue of having to load hundreds of files to render a single H5P experience.

**Comment by radinamatic** [comment] 2021-06-30 14:57
https://learningequality.testquality.com defect [D2](https://learningequality.testquality.com/project/12317/result/2429293/defect/7902).

**Comment by radinamatic** [comment] 2021-06-30 14:58
Testing linking issues from the TQ (no actions required at this time).

**Comment by rtibbles** [comment] 2021-08-31 23:20
This should have been resolved by #7989

**Closed as completed by rtibbles** 2021-08-31 23:20 UTC
Labels: bug, DEV: renderers
