### ISSUE TITLE
Incorrect duplicate validation ("A lesson of this name already exists") of lesson name 

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7494] opened 2020-08-27 10:35 UTC
### Observed behavior

Whenever creating a new lesson, there is a duplicate lesson name error momentarily visible. It is a false negative and does not prevent from lesson creation.

![lesson_naming_issue](https://user-images.githubusercontent.com/2577060/91431916-a6316600-e87e-11ea-8cc2-87dad39732a9.gif)

### Expected behavior

The error should be displayed only if a duplicate lesson name exists for the class in which the new lesson is being created.

### User-facing consequences

Raises self doubt for a user and is a false alarm.

### Errors and logs

N/A

### Steps to reproduce

Classes -> choose a class -> Plan -> Lesson -> New Lesson
Give a lesson name and click Save Lesson.

### Context

Kolibri 0.14.3 deb

**Comment by jonboiser** [comment] 2020-09-09 00:27
Closing this as a duplicate of #6593, which also contains more detailed analysis of the root cause.

**Closed as completed by jonboiser** 2020-09-09 00:27 UTC
Labels: bug
