### ISSUE TITLE
When user tries to add a single exercise while creating a Quiz, it throws an error "No resource are selected".

### ISSUE THREAD

**Issue by JatinSharma12** [learningequality/kolibri#7582] opened 2020-10-19 17:12 UTC
## Observed behavior
While creating a Quiz when a coach user tries to add an exercise to the quiz, application throws an error "No resource are selected" whereas it should allow to add a single exercise as well.
…

### Expected behavior
User should be able to add all exercises as well as single exercise.

…

### User-facing consequences
When user want to keep a single exercise for a Quiz, he should be able to add without any error.
…

### Errors and logs
Relevant logs from:
[kolibri-app.txt](https://github.com/learningequality/kolibri/files/5403510/kolibri-app.txt)

 * ~/.kolibri/logs/kolibri.txt

```

```

…

### Steps to reproduce
1. Sign in as Coach user.
2. Click on New Quiz button and try to add an exercise.
3. When we click on an exercise and click on continue button.
4. Observe that application throws an error stating "No Resources are selected".
PFA video for reference.
…

### Context
[AddExercise_Issue.zip](https://github.com/learningequality/kolibri/files/5403503/AddExercise_Issue.zip)

Tell us about your environment, including:
 * Kolibri version 0.14.3
 * Operating system Windows 10

…

**Comment by jonboiser** [comment] 2020-10-20 19:33
This is a duplicate of https://github.com/learningequality/kolibri/issues/7536, which should be fixed in Kolibri 0.14.4 (coming next November). 

Unfortunately, the only way to add single exercises for now is to click the link to see the preview of the exercise, then click the "Add" button on the top-right corner.

**Closed as completed** 2020-10-21 22:12 UTC
Labels: bug, P0 - critical
