### ISSUE TITLE
Background running tasks never ends if the server is killed

### ISSUE THREAD

**Issue by danigm** [learningequality/kolibri#9351] opened 2022-04-25 09:34 UTC
## Observed behavior

When there's a running background task and the Kolibri server is killed by the operating system for some reason, the tasks will be in the RUNNING state forever.

![imagen](https://user-images.githubusercontent.com/50350/165062372-9e19279d-a016-40e1-b1ef-5ab7858b4914.png)

## Expected behavior

The RUNNING tasks are marked as "FAILED" when the Kolibri server detects that there are "RUNNING" tasks from a previous Kolibri process.

## User-facing consequences

The user can cancel long running tasks from the interface, so this is not a severe issue. But there's no information in the interface for the user when this happens so it's possible to think that the task is really running in the background and it doesn't.

## Steps to reproduce

 * Start a dev kolibri process
 * Start a background task, for example download some "big" channel
 * Kill the dev kolibri process, make sure to kill completely, all threads
 * Relaunch again the kolibri process
 * You will find the task running and the progress is not updated

## Context

 * Kolibri 0.15.1
 * Detected in the Android version, also reproduced on Linux

**Comment by rtibbles** [comment] 2022-04-25 15:04
Closing as a duplicate of https://github.com/learningequality/kolibri/issues/9280

**Closed as completed by rtibbles** 2022-04-25 15:04 UTC
