### ISSUE TITLE
Text displayed in places where they should not be

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10307] opened 2023-03-23 22:06 UTC
## Observed behavior
Reported by @lauradanforth in the alpha-10 bug bash. On the import channels and library pages, text was displayed that should not be seen by the user.

## Errors and logs
<img width="868" alt="Screen Shot 2023-03-23 at 12 55 29 PM" src="https://user-images.githubusercontent.com/46411498/227372892-7b32c7d3-ba84-45b7-ba59-204cc1403cd2.png">

<img width="990" alt="Screen Shot 2023-03-23 at 1 02 12 PM" src="https://user-images.githubusercontent.com/46411498/227372910-c31f2483-5acf-4606-ac39-78f1655015a7.png">

## Expected behavior
Software code should not be displayed in UI.

## User-facing consequences 
Code text displayed in UI can confuse users.

## Context
0.16.0-alpha10

**Comment by radinamatic** [comment] 2023-03-23 23:46
Duplicate of #10284

**Closed as completed by radinamatic** 2023-03-23 23:46 UTC
Labels: P1 - important
