### ISSUE TITLE
Content import progress bar not reaching 100% when finished

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4584] opened 2018-12-11 11:48 UTC
### Observed behavior
Not able to see 100% channel imported but it shows Close button in Device tab.

Channel ID : 8fc515793aad4e52b490b03c48ad21de
Channel Path(What to import) : Maharashtra State Class 3 to 9 (English) -> BalBharati -> 3 -> 1 Introduction to Geometrical Figures
Import above menioned path and see.

Please find attached screenshot for more information.

### Expected behavior
We are not sure whether it imports whole content or not. It must show 100% imported if it is imported.

### Steps to reproduce
1. Login with Device owner and Go to the Device tab.
2. Import  Channel ID : 8fc515793aad4e52b490b03c48ad21de
Channel Path(What to import) : Maharashtra State Class 3 to 9 (English) -> BalBharati -> 3 -> 1 Introduction to Geometrical Figures 
3. And check.

### Context
Kolibri version : Kolibri 0.11.0
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshots

![import_v0 11](https://user-images.githubusercontent.com/12776071/49798660-d1051f00-fd68-11e8-930c-79b359301229.png)

**Comment by benjaoming** [comment] 2018-12-11 22:09
Thanks for reporting. And sorry that you had to report it again (referencing #4350 which claimed that #4014 had fixed it)

**Comment by lyw07** [comment] 2018-12-11 23:44
Hi @swapnil106111 

Could you please upload the `kolibri.log` file here? I'm not able to reproduce this issue on my Ubuntu 14.04 virtual machine.
I imported `Maharashtra State Class 3 to 9 (English) -> BalBharati -> 3 -> 1 Introduction to Geometrical Figures` on my local Kolibri 0.11 instance and got the 100% progress bar. 
The log file `kolibri.log` would help us figure out what might go wrong in the backend. Thank you so much!

**Comment by benjaoming** [comment] 2018-12-11 23:52
@lyw07  with this type of issue, it can in some cases be easier to read the code and try to understand if there are cases where it can in theory finalize in a state of non-100% progress. This could be if the frontend stops polling for progress once done. If the frontend has a statement like `if done then progress=100%`, it could be bullet proof.

Mind the pseudo-code in that sketch :)

**Comment by swapnil106111** [comment] 2018-12-12 06:47
@lyw07 Unfortunately, we are also not able to reproduce the same. 

![123](https://user-images.githubusercontent.com/12776071/49851603-9c947000-fe07-11e8-817f-cf0a7a8c2948.png)

**Comment by lyw07** [comment] 2018-12-12 18:25
@benjaoming thank you for the suggestions! I will take a look at the code to find if there are any edge cases that lead to this error. also thank you @swapnil106111 for reporting!

**Comment by lyw07** [comment] 2019-01-07 19:42
Hi @swapnil106111 

Sorry I haven't followed up on this issue for some time. When you encountered the error on 0.11.0, do you recall if your 0.11.0 kolibri a fresh install, or an upgrade from a lower version of kolibri? Thank you!

**Comment by miyer03** [comment] 2019-01-09 11:02
@lyw07 it been an upgrade and not a fresh install

**Comment by rtibbles** [comment] 2019-01-11 20:39
Removing milestone, as not able to replicate, but we can leave the issue open for further investigation.

**Comment by indirectlylit** [comment] 2019-03-26 03:03
closing since we haven't seen it in a while. However, see related issues in #5262  and #4014

**Closed as completed by indirectlylit** 2019-03-26 03:03 UTC
Labels: bug
