### ISSUE TITLE
Unnecessary scroll bar in the bottom bar

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10527] opened 2023-04-20 14:37 UTC
## Observed behavior
Noted in the alpha12 bug bash by @bjester 

## Errors and logs
![Screenshot from 2023-04-06 13-05-02](https://user-images.githubusercontent.com/17235236/233399701-3ba0e21c-e7b9-4286-9019-bac9229f5777.png)

## Steps to reproduce
Device page - on mobile view

## Context
0.16.0-alpha12

**Comment by radinamatic** [comment] 2023-04-20 14:42
Where exactly is the scrollbar? 😕

**Comment by bjester** [comment] 2023-04-20 14:43
@radinamatic the submit button container is scrolled up, which is why the button is nearly at the top edge of the bottom bar

**Comment by estelacruz** [comment] 2023-05-08 01:29
Hello, I wanted to verify what the issue is. I am running in app mode and this is what I see:


<img width="569" alt="Screen Shot 2023-05-07 at 9 26 36 PM" src="https://user-images.githubusercontent.com/79770461/236714467-7e17058b-bfe2-44fa-b09b-b5f1b8ebcece.png">


The issues are 

1) Unnecessary scroll bar in the bottom bar:


<img width="74" alt="Screen Shot 2023-05-07 at 9 27 46 PM" src="https://user-images.githubusercontent.com/79770461/236714655-7abbcf2b-0917-47ef-809f-eae57d0838dd.png">



2) "save changes" button container is scrolled up/ the button is at the top edge of the bottom bar

<img width="401" alt="Screen Shot 2023-05-07 at 9 27 56 PM" src="https://user-images.githubusercontent.com/79770461/236714665-082ab577-22bb-4ec6-a0d1-3bf46aa9b830.png">


## Resolving the Issue

What design are you looking for in terms of the save changes button?

**Comment by 0xV0YD** [comment] 2023-09-23 10:43
@marcellamaki can i work on this issue

**Comment by aarishshahmohsin** [comment] 2023-12-15 08:41
Can I be assigned this issue?

**Comment by marcellamaki** [comment] 2023-12-15 14:52
Hi @aarishshahmohsin - thank you for your interest! It looks like we already have a PR open from @iskipu that might close this issue. 

We currently have contributing opportunities in three repositories. You can see the contributing guidelines including links to issues suitable for contribution for each repository here:

- [Kolibri Contributing Guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md)

- [Kolibri Design System Contributing Guidelines](https://github.com/learningequality/kolibri-design-system/blob/main/CONTRIBUTING.md)

- [Studio Contributing Guidelines](https://github.com/learningequality/studio/blob/unstable/CONTRIBUTING.md)

**Closed as completed** 2024-01-03 17:31 UTC
Labels: DEV: frontend, help wanted, good first issue
