### ISSUE TITLE
Older browsers cannot display PDF-ressources

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10692] opened 2023-05-12 09:10 UTC
## Observed behavior

On e.g.

- Ipad - 10.3.3
- Ipad - 9.3.5

And also a lot of Chrome browers on old tables will show this:

![20230512_105123](https://github.com/learningequality/kolibri/assets/148026/a89a6918-41c7-4a8b-b824-341c685c407a)

Then you can download the ressource as a PDF, but you need to click on (I) in the corner to do that.

![20230512_105144 (1)](https://github.com/learningequality/kolibri/assets/148026/d17b25e4-3482-4593-9699-e8a92d8dbe10)

When Kolibri is not able to show the ressource, could it be an idea, that you show the download button on the error page. Like this.

![20230512_105123](https://github.com/learningequality/kolibri/assets/148026/82f1fe4c-6738-4801-9a89-2e967dfa2fcd)

…

## Errors and logs

…

## Expected behavior

…

## User-facing consequences

I have seen it gets confusing for both staff and students if the ressources are not being showed. Also when downloading the content on all devices tried, they were able to show in the pdf-viewer already on the devices.

…

## Steps to reproduce

…

## Context

…

**Comment by rtibbles** [comment] 2023-05-22 23:27
I suspect this is a duplicate of this: https://github.com/learningequality/kolibri/issues/10707

**Closed as completed** 2023-07-26 22:39 UTC

**Comment by rtibbles** [comment] 2023-07-26 22:42
Hi @lsolesen - thanks for the suggestion here, we have implemented a version of it in #10998 which should be in the next version of Kolibri.
