### ISSUE TITLE
After every digit is entered, the keyboard goes back.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2084] opened 2017-09-01 05:41 UTC
## Summary
While entering the answers the keyboard goes back after entering any digit, thus, again the answer box has to be clicked and the process repeats till the complete answer has been written.

## Detailed Description

- While entering the answers the keyboard goes back after entering any digit.
- Thus, again the answer box has to be clicked and the process repeats till the complete answer has been written.
- Watch the Video to get idea of this problem.

## System information

Kolibri Version: Kolibri 0.4.5
Operating System : Ubuntu 14.04
Browser : Chrome

## Video
[VID-20170901-WA0003.mp4.zip](https://github.com/learningequality/kolibri/files/1269237/VID-20170901-WA0003.mp4.zip)

**Comment by DXCanas** [comment] 2017-09-18 20:31
Not seeing this on 0.4.5 on desktop on phone. I think it might be an older version of Chrome on android. Testing, will update this comment.

**Comment by indirectlylit** [comment] 2017-09-27 19:01
clearing milestone until we get more info

**Comment by swapnil106111** [comment] 2017-11-06 11:04
@DXCanas @rtibbles Tested on kolibri 0.4.9.
When we were conducting tablet session in classrooms, observed such behaviour in channel ID : 8fc515793aad4e52b490b03c48ad21de (Maharashtra state English Medium). This is not channel specific.
In the class of 28 students, 3-4 students facing this issue.

Path : BalBharati - 3 - 3 Addition without Carrying Over - Addition of two numbers - Level 2: Addition of two numbers

Tablet chrome version: 50.0.2661.89
Operating System: Android 5.1.0

[VID_20171102_150908 - converted with Clipchamp.mp4.zip](https://github.com/learningequality/kolibri/files/1445968/VID_20171102_150908.-.converted.with.Clipchamp.mp4.zip)

**Comment by christianmemije** [comment] 2018-06-05 22:06
Cannot reproduce this in latest 0.10.

**Comment by indirectlylit** [comment] 2018-06-06 00:39
reproducing this has been super challenging, even in 0.4.x :/ Maybe google might implicate some _possible_ reason that we could at least take a stab at?

**Comment by indirectlylit** [comment] 2018-06-21 02:40
@swapnil106111 unfortunately we still can't repro :(

**Comment by rtibbles** [comment] 2021-04-07 23:35
Unable to reproduce for over 3 years. Closing.

**Closed by rtibbles** 2021-04-07 23:35 UTC
Labels: P1 - important, TODO: needs clarification, bug
