### ISSUE TITLE
Remove button is not working.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#1364] opened 2017-04-27 11:28 UTC
## Summary
While removing student from class, remove button is not working.

## System information

 - Version: Kolibri 0.4.0aplha5
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome browser and Firefox

## How to reproduce

1. Login as a Facility Admin.
2. Click manage tab, and Select Classes tab.
3. Click on Class name.
4. Remove is not working.

## Screenshots

![screen shot 2017-04-27 at 4 29 44 pm](https://cloud.githubusercontent.com/assets/12776071/25481433/c5769dd4-2b6a-11e7-9776-f3344bd01eae.png)

**Comment by jonboiser** [comment] 2017-04-27 15:52
I was able to reproduce this on Kolibri 0.4.0aplha5, but it seems to be fixed in the latest dev version.

**Comment by indirectlylit** [comment] 2017-04-27 17:46
thanks - I'll close this. @swapnil106111 this should be fixed in the next alpha you receive

**Closed by indirectlylit** 2017-04-27 17:46 UTC
Labels: DEV: frontend, TASK: bug

**Comment by swapnil106111** [comment] 2017-04-28 05:24
@rtibbles  Retested. Now , Remove button is working.

![1364_1](https://cloud.githubusercontent.com/assets/12776071/25515274/0d5f9506-2c01-11e7-8fb9-4aa43311069b.png)
![1364_2](https://cloud.githubusercontent.com/assets/12776071/25515275/0d60608a-2c01-11e7-83d0-e077ca92ff2a.png)
![1364_3](https://cloud.githubusercontent.com/assets/12776071/25515276/0d609168-2c01-11e7-9072-83830de38da4.png)
