### ISSUE TITLE
Selection of facility unexpectedly appears on the create account page

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#6209] opened 2019-12-04 14:53 UTC
### Observed behavior

For Instant Schools plugin, there should be no need to select a facility

For Kolibri, the selection option appears only after refreshing the create account page, and appears even when there is one option.

### Expected behavior

For Instant Schools, no selection needed

For Kolibri, I expect to only need to select it if there's more than one to choose from. Or rather, I expected to have only chosen this from the main page, not the create account page

### User-facing consequences

For Instant Schools: VF's expectations not met

For Kolibri: confusion, but doesn't deter from finishing sign-up

### Errors and logs

…

### Steps to reproduce

1. Go to either instantschools.learningequality.org or instantschools-testsite.learningequality.org
2. Click button to create an account
3. Once on create account page, refresh
4. You are presented with a modal

![Screenshot from 2019-12-04 06:39:04](https://user-images.githubusercontent.com/5150483/70152872-ce2ec880-1662-11ea-992e-fd346e37bda3.png)

### Context

…

**Comment by indirectlylit** [comment] 2019-12-04 23:31
interesting - this is clearly a bug, but i'm not able to reproduce using the steps above

**Comment by nucleogenesis** [comment] 2019-12-06 18:16
@jeepurs @indirectlylit I believe this was fixed with https://github.com/learningequality/kolibri-instant-schools-plugin/pull/165 and I cannot replicate this on the latest deployed build.

**Closed as completed** 2019-12-09 12:08 UTC
Labels: bug
