### ISSUE TITLE
Character encoding problems on ios/iphone/safari

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1043] opened 2017-03-09 18:43 UTC
## Summary

iPhone seems picky about displaying certain characters like º or '...
All works well on Android... :sunglasses: 

## System information

 - Version: 0.2.0alpha5.dev35
 - Operating system:  iPhone 5S
 - Browser: all (Safari, Chrome, Firefox)

## Screenshots

![encoding](https://cloud.githubusercontent.com/assets/1457929/23764572/e39ce05e-04b2-11e7-94c5-b83228f9100b.JPG)

![encoding2](https://cloud.githubusercontent.com/assets/1457929/23764582/ea596818-04b2-11e7-9238-420591916a2c.JPG)

**Comment by jonboiser** [comment] 2017-03-28 18:44
@radinamatic Could you check which version of iOS your iPhone is using? I cannot reproduce this on 10.3 using simulator and actual phone.

Based on searches, this does seem related to the encoding scheme used for that Global Warming article. This fellow has the same exact problem: http://stackoverflow.com/questions/14755420/perl-word-degree-sign-shows-up-preceded-by-a-circumflex

This might need to be fixed upstream in the actual content, specifying the correct encoding in the article.

**Comment by radinamatic** [comment] 2017-03-28 19:22
@jonboiser I don't have access to that same iPhone anymore, but I'll ask and report back!

**Comment by christianmemije** [comment] 2017-03-28 19:44
Not sure if this might have to do with this issue, but these articles are missing the proper html5 doctype and utf-8 encoding. Might be useful to add this to the html @jamalex 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
```

**Comment by indirectlylit** [comment] 2018-09-27 19:08
Anyone recall what content this was? We should file an upstream issue on the sushi chef

**Comment by radinamatic** [comment] 2018-09-27 21:59
From the screenshots it looks like one of IS-VF channels, but that issue is 18 months old... :blush: 
I don't have an Iphone handy atm to re-test, so can't confirm if it's still extant.

**Comment by indirectlylit** [comment] 2018-09-27 23:34
cc @jeepurs you might know?

If not I'll close this

**Comment by jeepurs** [comment] 2018-10-04 15:21
Yup @indirectlylit that source is probably CK-12!

**Comment by indirectlylit** [comment] 2018-10-04 18:06
migrating to https://github.com/learningequality/sushi-chef-ck12/issues/6

**Closed by indirectlylit** 2018-10-04 18:06 UTC
Labels: DEV: frontend, TASK: bug fix
