### ISSUE TITLE
In postgres, importing changing channel content moves channel to top of list

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6560] opened 2020-02-14 00:01 UTC
### Observed behavior

postgres-specific follow-up from https://github.com/learningequality/kolibri/issues/6376

From @jonboiser 

> Unforunately, this unwanted re-ordering issue is still happening when using Postgresql, except that the channel goes to the top of the list.

### Expected behavior

Updating a channel doesn't change its position

### User-facing consequences

* Users will need to move the channel again
* Users might not immediately realize the channel moved

### Steps to reproduce

* run with postgres
* import, adjust position, import more

### Context

0.13.1 beta 2

**Comment by paulbusse** [comment] 2020-11-11 11:06
I found the root cause for this one. The query 
```python
    latest_order = model.objects.latest("order").order 
    if latest_order is None: 
         channel.order = 1
```
is indeed the problem as pointed out to me by @jonboiser. `latest` is implemented as an `order by` which in Postgres puts the NULL values first (see [Postgres docs](https://www.postgresql.org/docs/13/queries-order.html)). As channels are created with a NULL in the `order` field, this query will always return NULL when an actual order is assigned to the channel.

PR follows later this week after testing is complete.

**Comment by indirectlylit** [comment] 2020-11-12 00:24
great, thanks!

**Closed as completed** 2020-11-13 17:45 UTC
Labels: bug, P1 - important, DEV: backend
