### ISSUE TITLE
Something went wrong in 'Login next' button

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#7263] opened 2020-07-08 04:05 UTC
### Observed behavior

In login page, the next button is not performing properly. Here are the following issues:

1. When I fill in a user account and press the enter key. It refresh the page and remove the username that I entered.
    
2. When I attempt a wrong password and log-in again with same user account. The next button cannot proceed to enter a password.
![image](https://user-images.githubusercontent.com/38421180/86872198-59e36880-c10e-11ea-969f-5cb0e9717a83.png)

3. In the console, I see the `Source map error: Error: request failed with status 401`
![image](https://user-images.githubusercontent.com/38421180/86872517-1d643c80-c10f-11ea-84ac-1983c0b31f6d.png)

### Expected behavior

The next button and enter key must perform properly.

### User-facing consequences

…

### Errors and logs

```
Kolibri Modules: kolibri.plugins.user.app registered
:8080/api/auth/session/:1 Failed to load resource: the server responded with a status of 400 (Bad Request)
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 400
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
:8080/api/auth/session/:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
:8080/api/auth/session/:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
:8080/api/auth/session/:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
:8080/api/auth/session/:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
:8080/api/auth/session/:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
:8080/api/auth/session/:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
:8080/api/auth/session/:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/iframe_handler.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/en/user/kolibri.core.frontend_head_assets-0.14.0b8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for chrome-extension://fheoggkfdfchfphceeifdbepaooicaho/sourceMap/chrome/content.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/en/user/kolibri.plugins.facility.side_nav-0.14.0b8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/en/user/kolibri.plugins.user.user_profile_side_nav-0.14.0b8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/en/user/kolibri.plugins.user.login_side_nav-0.14.0b8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/en/user/kolibri.plugins.learn.side_nav-0.14.0b8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/en/user/kolibri.plugins.device.side_nav-0.14.0b8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://127.0.0.1:8080/en/user/kolibri.plugins.coach.side_nav-0.14.0b8.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
xhr.js:178 POST http://127.0.0.1:8080/api/auth/session/ 401 (Unauthorized)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
module.exports @ kolibri.core.default_frontend-0.14.0b8.js:1
module.exports @ kolibri.core.default_frontend-0.14.0b8.js:1
Promise.then (async)
Axios.request @ kolibri.core.default_frontend-0.14.0b8.js:1
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
client @ kolibri.core.default_frontend-0.14.0b8.js:1
Resource.client @ kolibri.core.default_frontend-0.14.0b8.js:1
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Promise.then (async)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
ConditionalPromise @ kolibri.core.default_frontend-0.14.0b8.js:1
Model.save @ kolibri.core.default_frontend-0.14.0b8.js:1
Resource.saveModel @ kolibri.core.default_frontend-0.14.0b8.js:1
kolibriLogin @ kolibri.core.default_frontend-0.14.0b8.js:1
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Store.dispatch @ kolibri.core.default_frontend-0.14.0b8.js:1
Store.dispatch @ kolibri.core.default_frontend-0.14.0b8.js:1
normalizeMap.forEach.res.<computed> @ kolibri.core.default_frontend-0.14.0b8.js:1
signIn @ kolibri.plugins.user.app-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
invoker @ kolibri.core.default_frontend-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
Vue.$emit @ kolibri.core.default_frontend-0.14.0b8.js:1
handleClick @ kolibri.core.default_frontend-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
invoker @ kolibri.core.default_frontend-0.14.0b8.js:1
original._wrapper @ kolibri.core.default_frontend-0.14.0b8.js:1
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Promise.then (async)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Promise.then (async)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
ConditionalPromise @ kolibri.core.default_frontend-0.14.0b8.js:1
Model.save @ kolibri.core.default_frontend-0.14.0b8.js:1
Resource.saveModel @ kolibri.core.default_frontend-0.14.0b8.js:1
kolibriLogin @ kolibri.core.default_frontend-0.14.0b8.js:1
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Store.dispatch @ kolibri.core.default_frontend-0.14.0b8.js:1
Store.dispatch @ kolibri.core.default_frontend-0.14.0b8.js:1
normalizeMap.forEach.res.<computed> @ kolibri.core.default_frontend-0.14.0b8.js:1
signIn @ kolibri.plugins.user.app-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
invoker @ kolibri.core.default_frontend-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
Vue.$emit @ kolibri.core.default_frontend-0.14.0b8.js:1
handleClick @ kolibri.core.default_frontend-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
invoker @ kolibri.core.default_frontend-0.14.0b8.js:1
original._wrapper @ kolibri.core.default_frontend-0.14.0b8.js:1
xhr.js:178 POST http://127.0.0.1:8080/api/auth/session/ 401 (Unauthorized)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
module.exports @ kolibri.core.default_frontend-0.14.0b8.js:1
module.exports @ kolibri.core.default_frontend-0.14.0b8.js:1
Promise.then (async)
Axios.request @ kolibri.core.default_frontend-0.14.0b8.js:1
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
client @ kolibri.core.default_frontend-0.14.0b8.js:1
Resource.client @ kolibri.core.default_frontend-0.14.0b8.js:1
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Promise.then (async)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
ConditionalPromise @ kolibri.core.default_frontend-0.14.0b8.js:1
Model.save @ kolibri.core.default_frontend-0.14.0b8.js:1
Resource.saveModel @ kolibri.core.default_frontend-0.14.0b8.js:1
kolibriLogin @ kolibri.core.default_frontend-0.14.0b8.js:1
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Store.dispatch @ kolibri.core.default_frontend-0.14.0b8.js:1
Store.dispatch @ kolibri.core.default_frontend-0.14.0b8.js:1
normalizeMap.forEach.res.<computed> @ kolibri.core.default_frontend-0.14.0b8.js:1
signIn @ kolibri.plugins.user.app-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
invoker @ kolibri.core.default_frontend-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
Vue.$emit @ kolibri.core.default_frontend-0.14.0b8.js:1
handleClick @ kolibri.core.default_frontend-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
invoker @ kolibri.core.default_frontend-0.14.0b8.js:1
original._wrapper @ kolibri.core.default_frontend-0.14.0b8.js:1
api-resource.js:167 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 401
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Promise.then (async)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Promise.then (async)
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
ConditionalPromise @ kolibri.core.default_frontend-0.14.0b8.js:1
Model.save @ kolibri.core.default_frontend-0.14.0b8.js:1
Resource.saveModel @ kolibri.core.default_frontend-0.14.0b8.js:1
kolibriLogin @ kolibri.core.default_frontend-0.14.0b8.js:1
(anonymous) @ kolibri.core.default_frontend-0.14.0b8.js:1
Store.dispatch @ kolibri.core.default_frontend-0.14.0b8.js:1
Store.dispatch @ kolibri.core.default_frontend-0.14.0b8.js:1
normalizeMap.forEach.res.<computed> @ kolibri.core.default_frontend-0.14.0b8.js:1
signIn @ kolibri.plugins.user.app-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
invoker @ kolibri.core.default_frontend-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
Vue.$emit @ kolibri.core.default_frontend-0.14.0b8.js:1
handleClick @ kolibri.core.default_frontend-0.14.0b8.js:1
invokeWithErrorHandling @ kolibri.core.default_frontend-0.14.0b8.js:1
invoker @ kolibri.core.default_frontend-0.14.0b8.js:1
original._wrapper @ kolibri.core.default_frontend-0.14.0b8.js:1
```

### Steps to reproduce

…

### Context

 * Kolibri version: 0.14.0 beta 8
 * Operating system: Windows 10
 * Browser: Firefox v78, Chrome v83

**Comment by jredrejo** [comment] 2020-07-08 08:41
@mrpau-julius  I think this is a duplicate of #7248 . Please check it and close this issue if that's the case. Thanks

**Comment by mrpau-julius** [comment] 2020-07-08 12:56
@jredrejo, The first issue that I mentioned is semilar on that. But the second and third are different issues.
It's about the behavior of next button that failed to proceed and I can't type a password because of this thing.

**Comment by jonboiser** [comment] 2020-07-08 19:02
Yeah, this reminds me more of #7199, but is also not exactly the same. In that issue, the "Incorrect password" alert doesn't show up. But it is similar in that the password field doesn't show up afterwards.

 @mrpau-julius does your server also have the "Password not required for learners" setting turned on?

**Comment by mrpau-julius** [comment] 2020-07-08 22:42
@jonboiser yes it's turn on the "Require password for learner". Yes slightly the same, the difference of this issue is, once you have a incorrect password( the error message will shown up) and try it again but it not proceed because the 'next' button is not working (like disable to proceed next).

![login-next-button](https://user-images.githubusercontent.com/38421180/86977004-4ab3f780-c1ae-11ea-8a61-db4519b94159.gif)

**Comment by indirectlylit** [comment] 2020-07-09 16:47
@nucleogenesis something to investigate during your login work

**Comment by nucleogenesis** [comment] 2020-07-17 20:01
Ought to be resolved in: https://github.com/learningequality/kolibri/pull/7306

**Closed as completed by nucleogenesis** 2020-07-17 20:01 UTC
Labels: P0 - critical
