### ISSUE TITLE
Question numbers all turn into (1) in difficult question list for an exercise

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#5271] opened 2019-03-14 21:43 UTC
### Observed behavior

![Mar-14-2019 14-34-24](https://user-images.githubusercontent.com/6668144/54393241-e723c380-4666-11e9-85c2-b4f139125972.gif)

### Expected behavior

Question number in difficult question list should not all change to 1.

### Steps to reproduce

1. Log in as coach
2. Look at report for an exercise in a lesson
3. Click "difficult questions" tab
4. Click a question
5. Observe the question number change on the detailed question report
6. Click 'X' back to the difficult question list
7. Observe all question numbers being (1)

### Context

Kolibri 0.12.1
MacOS
Chrome

Link to exercise: 
https://kolibridemo.learningequality.org/coach/#/f6e7f562bb0ea654340c726e1f81bbe9/reports/lessons/e4a5e8f0b2e8d72505472839643797b7/exercises/088f2413ca534bdcade84e48a0827e3e/learners

**Comment by jonboiser** [comment] 2019-03-14 22:03
Might be related that the number in parentheses can also be NaN

From: https://kolibridemo.learningequality.org/coach/#/f6e7f562bb0ea654340c726e1f81bbe9/reports/quizzes/d354d3c1bbf4cbd84321ff37a56b82a0/questions

![Screen Shot 2019-03-14 at 3 02 32 PM](https://user-images.githubusercontent.com/10248067/54394532-5cdd5e80-466a-11e9-90e8-087301175d29.png)

**Comment by jonboiser** [comment] 2019-03-14 22:07
The reason it is always "(1)" is probably from this line:

https://github.com/learningequality/kolibri/blob/5ad470336fd8c65abe7817ca4d736294ee76f2af/kolibri/plugins/coach/assets/src/modules/questionList/actions.js#L63-L68

Which makes me think this is related to the issue in #5247.

The reason it gets the question numbers right the first time you go to Difficult Questions, but then switches when you leave then return to Difficult Questions may have something to do with caching.

**Comment by rtibbles** [comment] 2019-03-21 17:16
Confirmed, this was due to the api-resource model `fetch` method returning the direct model attributes, rather than a clone of them, upon fetch.

**Comment by rtibbles** [comment] 2019-03-21 18:39
Fixed in #5298

**Closed as completed by rtibbles** 2019-03-21 18:39 UTC
Labels: bug
