### ISSUE TITLE
Uncaught errors in zeronconf handling

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#6655] opened 2020-03-12 11:21 UTC
### Observed behavior
From a log file:
```
Exception in thread zeroconf-ServiceBrowser_Kolibri._sub._http._tcp.local.:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\kolibri\dist\zeroconf.py", line 1443, in run
    handler(self.zc)
  File "C:\Python34\lib\site-packages\kolibri\dist\zeroconf.py", line 1384, in <lambda>
    state_change=state_change,
  File "C:\Python34\lib\site-packages\kolibri\dist\zeroconf.py", line 1280, in fire
    h(**kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\zeroconf.py", line 1353, in on_change
    listener.add_service(*args)
  File "C:\Python34\lib\site-packages\kolibri\core\discovery\utils\network\search.py", line 137, in add_service
    bytes.decode(key): json.loads(val) for (key, val) in info.properties.items()
  File "C:\Python34\lib\site-packages\kolibri\core\discovery\utils\network\search.py", line 137, in <dictcomp>
    bytes.decode(key): json.loads(val) for (key, val) in info.properties.items()
  File "C:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

### Expected behavior
Should not throw errors when handling zeroconf events.

### User-facing consequences
Zeroconf will not run properly.

### Errors and logs
See above

**Comment by jamalex** [comment] 2020-03-12 18:01
What version was this?

**Comment by rtibbles** [comment] 2020-03-12 18:02
0.13.1 on Windows 10

**Comment by indirectlylit** [comment] 2020-03-12 22:39
(duplicate of https://github.com/learningequality/kolibri/issues/6615)

**Closed as completed by indirectlylit** 2020-03-12 22:39 UTC
