### ISSUE TITLE
Keypad doesn't contain variables in algebraic expression questions

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2616] opened 2017-11-16 07:01 UTC
### Observed behavior
The keypad appearing for certain questions in the chapter algebraic expressions in grade 8 doesn't show the required variables due to which the student is not able to enter the answer or proceed further in the exercise.

Channel ID: 9e5305326ed742d0892479dea825a514-CBSE English Medium

Path of the topic: Topics > CBSE > 8 >  9 Algebraic Expressions and Identities > KA Resources > Addition and subtraction of algebraic expressions

Exercise name: Add polynomials

Showing all other variables but there is problem only in the case of variable 'h'.
 
### Expected behavior
Keyboard must show variables used in algebraic expression question.

### Steps to reproduce
1. Login with learner on tablet.
2. Follow the path( CBSE > 8 >  9 Algebraic Expressions and Identities > KA Resources > Addition and subtraction of algebraic expressions ->  Add polynomials) 

### Context

* Kolibri version: Kolibri 0.4.9
* Operating system: Ubuntu 14.04
* Browser on server: Chrome 
* Browser on tablet: Chrome (62.0.3202.84) 

### Screenshots:

![img_20171024_105343](https://user-images.githubusercontent.com/12776071/32877895-aaf8c83e-cac9-11e7-8bf0-0f0f874103e9.jpg)

**Comment by indirectlylit** [comment] 2017-11-20 17:47
we'll need to check [whether this occurs on KA's site](https://www.khanacademy.org/math/algebra2/rational-expressions-equations-and-functions/adding-and-subtracting-rational-expressions/e/adding_and_subtracting_rational_expressions_5)

**Comment by rtibbles** [comment] 2018-03-01 19:47
On portrait, is there:
![image](https://user-images.githubusercontent.com/1680573/36866161-6227f880-1d46-11e8-9f63-6fca93acdbce.png)

**Comment by christianmemije** [comment] 2018-03-05 22:15
Can reproduce
![localhost_8000_learn_](https://user-images.githubusercontent.com/7193975/37002621-302b1b28-207f-11e8-9174-9f518a17e040.png)

**Comment by christianmemije** [comment] 2018-03-05 23:48
Not on the KA site 
![www khanacademy org_math_algebra_introduction-to-polynomial-expressions_adding-and-subtracting-polynomials_e_adding_and_subtracting_polynomials nexus 6p](https://user-images.githubusercontent.com/7193975/37006295-8f5c5c94-208c-11e8-9031-9851beadc779.png)

https://www.khanacademy.org/math/algebra/introduction-to-polynomial-expressions/adding-and-subtracting-polynomials/e/adding_and_subtracting_polynomials

**Comment by christianmemije** [comment] 2018-03-06 01:12
Issues appears to be with the content data:
http://khan.github.io/perseus/?renderer#content=%7B%22question%22%3A%7B%22content%22%3A%22%2A%2AAdd.%2A%2A%20%20%5Cn%2AYour%20answer%20should%20be%20a%20polynomial%20in%20standard%20form.%2A%5Cn%5Cn%24%285h%5E3-8h%29%20%2B%28-2h%5E3-h%5E2-2h%29%3D%24%20%5B%5B%E2%98%83%20expression%201%5D%5D%22%2C%22images%22%3A%7B%7D%2C%22widgets%22%3A%7B%22expression%201%22%3A%7B%22type%22%3A%22expression%22%2C%22alignment%22%3A%22default%22%2C%22static%22%3Afalse%2C%22graded%22%3Atrue%2C%22options%22%3A%7B%22answerForms%22%3A%5B%7B%22value%22%3A%223h%5E3-h%5E2-10h%22%2C%22form%22%3Atrue%2C%22simplify%22%3Afalse%2C%22considered%22%3A%22correct%22%2C%22key%22%3A0%7D%5D%2C%22buttonSets%22%3A%5B%22basic%22%2C%22prealgebra%22%5D%2C%22functions%22%3A%5B%22f%22%2C%22g%22%2C%22h%22%5D%2C%22times%22%3Afalse%7D%2C%22version%22%3A%7B%22major%22%3A1%2C%22minor%22%3A0%7D%7D%7D%7D%2C%22answerArea%22%3A%7B%22calculator%22%3Afalse%2C%22chi2Table%22%3Afalse%2C%22periodicTable%22%3Afalse%2C%22tTable%22%3Afalse%2C%22zTable%22%3Afalse%7D%2C%22itemDataVersion%22%3A%7B%22major%22%3A0%2C%22minor%22%3A1%7D%2C%22hints%22%3A%5B%7B%22replace%22%3Afalse%2C%22content%22%3A%22Rewrite%20without%20parentheses%3A%5Cn%5Cn%24%5C%5CblueD%7B5h%5E3-8h%7D%20%5C%5CmaroonD%7B-2h%5E3-h%5E2-2h%7D%24%22%2C%22images%22%3A%7B%7D%2C%22widgets%22%3A%7B%7D%7D%2C%7B%22replace%22%3Afalse%2C%22content%22%3A%22Group%20like%20terms%3A%5Cn%5Cn%24%28%5C%5CblueD%7B5h%5E3%7D%20%20%5C%5CmaroonD%7B-2h%5E3%7D%29%20%20%5C%5CmaroonD%7B-h%5E2%7D%2B%28%5C%5CblueD%7B-8h%7D%20%20%5C%5CmaroonD%7B-2h%7D%29%24%22%2C%22images%22%3A%7B%7D%2C%22widgets%22%3A%7B%7D%7D%2C%7B%22replace%22%3Afalse%2C%22content%22%3A%22Simplify%3A%5Cn%5Cn%243h%5E3-h%5E2-10h%24%22%2C%22images%22%3A%7B%7D%2C%22widgets%22%3A%7B%7D%7D%5D%7D

**Comment by benjaoming** [comment] 2018-03-26 18:58
Closing this, can someone try if this is actually reproducible with the latest version of the channel?

**Comment by benjaoming** [comment] 2018-05-15 13:09
Alright, sorry about that, thanks for triaging @swapnil106111  - although the issue seems to be with content data, let's maybe keep it open until solved..

**Comment by rtibbles** [comment] 2018-05-16 18:33
@swapnil106111 is this with an updated version of the content also? This is a content issue, not a Kolibri issue.

**Comment by rtibbles** [comment] 2018-08-22 21:44
@swapnil106111 is this still extant? As noted previously, this is an issue with the content item, so if content has been updated, this should not be happening.

**Comment by swapnil106111** [comment] 2018-12-20 09:45
@rtibbles Able to see respective variable on keyboard which are used in the question.
![screenshot_2018-12-20-15-12-48-582_com android chrome](https://user-images.githubusercontent.com/12776071/50277368-3abcb180-046a-11e9-85c3-4885a4c8d79a.png)

**Closed** 2019-01-09 18:38 UTC
Labels: DEV: frontend, TAG: bug fix
