### ISSUE TITLE
iPhone 5S flexbook fullscreen

### ISSUE THREAD

**Issue by marisak** [learningequality/kolibri#977] opened 2017-02-24 22:31 UTC
## Summary

Can't fullscreen flexbooks on iPhone 5S. 

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: InstantSchools, 0.2.0alpha4
 - Operating system: OSX 10.1.1, iPhone 5S 
 - Browser: Safari, Chrome 

## How to reproduce

1. Navigate to InstantSchools. 
2. Go to Global Climate Change Flexbook (accessible by scrolling down landing page)
3. Click on Enter Fullscreen 
4. Fullscreen doesn't work :( 
5. I experienced the same issue with Kolibri on Mon. 2/20/17 

## Screenshots

![2017-02-17 17 18 11](https://cloud.githubusercontent.com/assets/16570574/23323456/7c6c754e-fa9d-11e6-85fc-1495afb5f778.png)
Slightly older screenshot 

## Real-life consequences 

Because of how small my screen is, it's impossible to read the book without using fullscreen. The nesting of the book makes scrolling without fullscreen all but impossible.

**Comment by indirectlylit** [comment] 2017-03-03 21:44
thanks for the bug report!

I was able to reproduce this in browserstack: navigating to an HTML5 app and clicking 'full-screen' does not work:

![image](https://cloud.githubusercontent.com/assets/2367265/23570040/488db0ba-0017-11e7-8d29-bb36656a162c.png)

**Comment by radinamatic** [comment] 2017-03-07 08:08
Confirmed on "real" iPhone, on both Safari, Firefox and Chrome.

However, it works well in Chrome on Android 4.2.2 (Samsung GT-S7580)... :stuck_out_tongue:

**Comment by radinamatic** [comment] 2017-03-07 08:17
![fullscreen](https://cloud.githubusercontent.com/assets/1457929/23647570/5dab3c5e-02cb-11e7-9740-e496b27b84a9.JPG)

**Comment by christianmemije** [comment] 2017-03-07 17:57
@radinamatic So the library we use to toggle fullscreen is https://sindresorhus.com/screenfull.js/. Can you check whether the same issue exists `on "real" iPhone, on both Safari, Firefox and Chrome.` on the demos provided in the library's page?

**Comment by christianmemije** [comment] 2017-03-07 18:06
Actually, yes looks like there is no support for fullscreen on iOS Safari http://caniuse.com/#feat=fullscreen

**Comment by radinamatic** [comment] 2017-03-07 19:46
@christianmemije  On real iPhone Sindre's demo is not working at all on either Chrome or Firefox.

On Android phone, opens fullscreen (request) in both, but it won't scroll in Firefox, and in Chrome on top of not scrolling it's loosing responsiveness... :unamused:

**Comment by christianmemije** [comment] 2017-09-01 18:36
Fixed in #1823

**Closed by christianmemije** 2017-09-01 18:36 UTC
Labels: DEV: frontend, TASK: bug
