### ISSUE TITLE
Profile page responsive layout

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1210] opened 2017-04-11 15:28 UTC
## Summary

It seems OK for the default max media queries, but fails if the user starts to manually resize the browser window on wider displays. Not urgent by any means, but filing as `UX debt`.

## System information

 - Version: kolibri-v0.3.1-beta2-6-g57c2c9c.pex
 - Operating system: Ubuntu 16.10
 - Browser: Chrome & Firefox

## Screenshots

<img width="907" alt="ubuntu_16_10__start___running_2" src="https://cloud.githubusercontent.com/assets/1457929/24917034/2cf58236-1edc-11e7-80db-8be9f57a9130.png">

**Comment by christianmemije** [comment] 2017-04-14 19:56
@radinamatic Cannot reproduce on develop. Can you confirm that?

**Comment by radinamatic** [comment] 2017-04-20 17:00
True, when I test the latest develop `0.4.0alpha2.dev81`, it behaves just as it should and scales perfectly on manual resize... :thinking: 

Same OS, same browsers, just not in a VM as original issue. :confused:

**Comment by indirectlylit** [comment] 2017-04-21 00:38
I'm going to close this for now but please re-open if you see it again. I think it's a bit more serious than just UX debt - not a blocker but definitely a bug.

**Closed by indirectlylit** 2017-04-21 00:38 UTC
Labels: DEV: frontend, TASK: bug

**Comment by radinamatic** [comment] 2017-04-21 11:44
Working OK on `0.4.0alpha3` on Windows VM (both Chrome & Firefox)!.

**Comment by radinamatic** [comment] 2017-04-21 12:42
Looking good on Ubuntu too... 👍 

![virtualbox_ubuntu 16 10_21_04_2017_14_38_41](https://cloud.githubusercontent.com/assets/1457929/25277841/a1b429bc-26a0-11e7-8fc8-edc2c6aa94b9.png)

**Comment by indirectlylit** [comment] 2017-04-21 19:40
glad to hear. Wonder how it happened before...
