### ISSUE TITLE
Download Resource button is cut off with small window sizes

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri#9346] opened 2022-04-22 22:58 UTC
## Observed behavior

In the "information" panel for some resources, the Download resource button is cut off:

![Screenshot 2022-04-22 at 15-55-52 Watch Me - TED-Ed Lessons - Kolibri](https://user-images.githubusercontent.com/132063/164814984-9693db76-0f34-4053-86e3-795c1f6ae3d2.png)

## User-facing consequences

This makes it impossible to download certain resources. Note that, if a user's screen resolution is limited, the availability of the button depends on the length of the description associated with the content.

Instead, the information panel should be a scrolling container.

## Steps to reproduce

This occurs some Ted Ed content at https://kolibri-demo.learningequality.org/en/learn/#/topics/c/5900e6eab432596d88ab8cf455a77995?last=TOPICS_TOPIC_SEARCH&topicId=68ad96dcf36f54db9367e76ee7afc015.

## Context

The screenshot was created using Firefox with a 1366×655 resolution. We encountered it on a device with 1366x768 screen resolution using the Kolibri desktop app for GNOME (https://flathub.org/apps/details/org.learningequality.Kolibri).

**Comment by rtibbles** [comment] 2022-04-25 15:10
This appears to be a duplicate of https://github.com/learningequality/kolibri/issues/9271 which has been resolved, it should be released in 0.15.3.

**Closed as completed by rtibbles** 2022-04-25 15:10 UTC
