### ISSUE TITLE
The Topic mastered disappears after few seconds and shows in progress.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1511] opened 2017-05-16 10:20 UTC
## Summary
A learner masters an exercise, gets the point. But after few seconds the Next Item button, Points and mastered sign all disappears form the screen and even on the profile screen the points are not recorded.

Note:
We have faced this in todays testing and was able to replicate it 6/10 times.
Channel ID: abb42df1203f4043a7b6e430de257d90

## System information

 - Version: Kolibri0.4.0beta2
 - Operating system: Ubuntu 14.04
 - Browser: Chrome

## How to reproduce

1. Master a topic observer for few seconds.
2. The points, Next Item button, Mastered sign and the exercise progress bar all get messed up or disappears. 

## Screenshots
Before Mastery: 
![whatsapp image 2017-05-16 at 3 35 02 pm 5](https://cloud.githubusercontent.com/assets/13453618/26101430/d1a8a140-3a4e-11e7-9f4b-d0058c39df79.jpeg)

After Mastery:
![whatsapp image 2017-05-16 at 3 35 02 pm 4](https://cloud.githubusercontent.com/assets/13453618/26101461/df62a5f6-3a4e-11e7-9257-febf8089d16a.jpeg)

Observe the Next Item: its missing and the Progress bar shows a different attempts:
![whatsapp image 2017-05-16 at 3 35 02 pm 3](https://cloud.githubusercontent.com/assets/13453618/26101540/2180fc76-3a4f-11e7-8e38-cefe41f0f5dc.jpeg)

The progress on the recommended tab shows In progress:
![whatsapp image 2017-05-16 at 3 35 02 pm 2](https://cloud.githubusercontent.com/assets/13453618/26101579/40a0283e-3a4f-11e7-92e5-6ac32de0c4f6.jpeg)

**Comment by christianmemije** [comment] 2017-05-16 15:56
Duplicate of https://github.com/learningequality/kolibri/issues/1505

**Comment by rtibbles** [comment] 2017-05-16 17:31
Not so sure it is, @christianmemije. This seems to be similar to a bug that had previously been reported but I had not been able to reproduce.

I think it is due to a race condition from the saving of the MasteryLog - but we should investigate further.

**Comment by harishbalachandran** [comment] 2017-05-18 16:01
@rtibbles haven't noticed this in todays testing, you can close . Will reopen if found.

**Closed** 2017-05-18 17:06 UTC
