### ISSUE TITLE
Cannot finish an exam

### ISSUE THREAD

**Issue by DXCanas** [learningequality/kolibri#1357] opened 2017-04-26 23:52 UTC
## Summary

Once I arrive to the last question, I'm unable to click on "Next Question" to complete all the questions in the exam.

![can t submit answer](https://cloud.githubusercontent.com/assets/9877852/25461921/95d25160-2aa0-11e7-9e41-148d4b80ae27.png)

**Comment by rtibbles** [comment] 2017-04-26 23:53
This is by design. You have to click submit to finish.

**Comment by DXCanas** [comment] 2017-04-26 23:54
I think the worrisome part was the modal that said I needed to complete one more. Closing for now, I might have missed something.

**Comment by DXCanas** [comment] 2017-04-26 23:58
![the problem](https://cloud.githubusercontent.com/assets/9877852/25462083/8d0caf84-2aa1-11e7-8992-10b383538e3d.gif)

**Comment by indirectlylit** [comment] 2017-04-27 00:18
yes that looks like a real issue, and I think I've noticed it before.

Re: the UI, for what it's worth I was confused by that the first time I went through it also. (cc @jtamiace @khangmach)

Reason: the 'submit' button is at the top-right instead of bottom-right. (This is also true in the 'enroll students to class' page - I find this button placement disorienting compared to most modals and forms which put the 'submit' button below the thing being submitted.)

I'd personally recommend moving this block _below_ the next/previous question buttons, and in general avoiding putting submit buttons at the tops of pages.

**Comment by rtibbles** [comment] 2017-04-27 01:35
@DXCanas please ensure that you have updated your pip packages, as this bug will occur if your perseus renderer is not up to date.

**Comment by rtibbles** [comment] 2017-04-27 02:23
The behaviour reported above is a duplicate of https://github.com/learningequality/kolibri/issues/1247, which was fixed in https://github.com/learningequality/kolibri-exercise-perseus-plugin/pull/66, and has been confirmed as fixed.

**Closed by rtibbles** 2017-04-27 02:23 UTC
Labels: DEV: frontend, TASK: bug

**Comment by khangmach** [comment] 2017-04-28 18:37
@indirectlylit @rtibbles 

Per request, here's a short term re-appropriation of the submit button/previous/next buttons

https://cloud.githubusercontent.com/assets/25045166/25542331/ebd73e60-2c06-11e7-9814-4b4a8017c71c.png

**Comment by jtamiace** [comment] 2017-04-28 18:44
^ can you copy/paste this to #1394 ?
