### ISSUE TITLE
Search button is working when user is trying to remove the search content from Search bar and refresh the display.

### ISSUE THREAD

**Issue by JatinSharma12** [learningequality/kolibri#7577] opened 2020-10-19 12:05 UTC
### Observed behavior
When user performs search on Manage Resources page, search items load according to searched content but when user removes the searched content from search bar and click on search button, the page is not refreshing the records whereas it should display all the [records](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-assign-learners-groups.feature).

…

### Expected behavior 
Search button should work properly and should be able to refresh the page so that user is able to see all the records available on that page initially.
…

### User-facing consequences

User is not able to see all the records after searching some content on the page.

…

### Errors and logs

```

```
…

### Steps to reproduce

1. Login as Coach.
2. Navigate to Lessons > Manage Resources.
3. Enter a valid resource name in the search bar  and click Search.
4. searhed records will display on the page.
5. Remove the resource name from search bar and click Search.
6. Observe that Search button is not performing any search operation,
PFA the video for reference.
[SearchBar_Issue.zip](https://github.com/learningequality/kolibri/files/5401556/SearchBar_Issue.zip)

…

### Context
Tell us about your environment, including:
 * Kolibri version 0.14.3
 * Operating system Windows 10

…

**Comment by jonboiser** [comment] 2020-10-22 22:00
This looks like a duplicate #7587 .

I don't recall this behavior being part of the original implementation of resource search. Is this in a Gherkin story somewhere? (the one linked in the issue doesn't pertain to search)

**Comment by radinamatic** [comment] 2020-10-22 22:19
Agreed that it is a duplicate of #7587, can be closed.

The correct reference for the [Gherkin search scenario](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-lesson.feature#L102).

**Comment by jonboiser** [comment] 2020-11-03 20:07
Closing as duplicate of #7587

**Closed as completed by jonboiser** 2020-11-03 20:07 UTC
