### ISSUE TITLE
Loading issues while viewing reports 

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#11824] opened 2024-01-31 01:28 UTC
## Observed behavior
At first I thought that the issues I was experiencing in this VM were due to limited resources I usually give to my VMs (2 CPU cores and 8 GB of RAM), so I doubled them to retest, but the issues persisted, though they were now (obviously) somewhat less prominent. 

You can notice 2 issues in the recordings below:
1. The title of the exercise in the lesson (that several learners ``need help`` with), lags to load fully, and you can see the placeholder ``Resource not found`` before it does. With the stronger configuration, when trying to open the ``need help`` resource in the second lesson, there is also a brief flash of the title of the ``need help`` resource from the first lesson. 

2. Size of the lesson (before the resource itself is opened) has a flash of ``NaN B``.

Dual Core 8GBs | Quad Core 16GB
-- | --
https://github.com/learningequality/kolibri/assets/1457929/a6c850c1-6fcb-413f-bdc7-4b01bae3deaa | https://github.com/learningequality/kolibri/assets/1457929/eaad3f2b-5812-4943-b908-519e94e99b6c

## Errors and logs
No errors in the Network tab or the console. @pcenov will try to replicate on his VMs, and you can use any of the following to debug:

* [full home folder (280MB)](https://drive.google.com/file/d/14fdx8ynheoCajPBeVyTlOzAffv7sqXnr/view?usp=drive_link)
* [everything but the content (38MB)](https://drive.google.com/file/d/1wQcgFKFxmUiPUkaeDy1LDhiI8ognXcSQ/view?usp=drive_link) 
* [just logs](https://drive.google.com/file/d/1YSi_ymrlXTQnUB0joZe-6hP1lGXXPYvz/view?usp=drive_link)

## Expected behavior
Granted the facility has many classes, but I have been using only one for less than a week, and Kolibri is supposed to be able to handle many more reports without these glitches. 

## User-facing consequences
On weaker VM configuration I experienced browser freezes, without noticing 100% resource usage in the Task manager. Definitely bad coach experience. 

## Steps to reproduce
Load the home folder provided above, try to navigate the **Lek3** and **Lek4** lessons to open and review the resources that learners ``need help`` with.

## Context

 * Kolibri version: 0.16b13
 * Operating system: Windows 7

**Comment by pcenov** [comment] 2024-01-31 11:49
Yes, I was able to replicate the issue using Radina's home folder. I think it's a problem with the loading state which can be reproduced regardless of the computer RAM/processing power when on slower internet connection (or using Chrome's Slow 3g throttling option:

https://github.com/learningequality/kolibri/assets/79847249/e7392b87-0d92-491f-85fc-ab775bae769d

**Comment by marcellamaki** [comment] 2024-02-01 14:13
Yes, this looks like a lingering issue from our loading state problems in coach that wasn't caught before now! Thanks for documenting @pcenov and @radinamatic

**Comment by rtibbles** [comment] 2024-02-09 21:09
The blocking part of this issue is fixed in #11843 - other remaining loading state concerns will be filed as follow up by @radinamatic.

**Closed as completed by rtibbles** 2024-02-09 21:09 UTC
Labels: P0 - critical, OS: Windows, APP: Coach, DEV: frontend
