### ISSUE TITLE
errant POST to /api/auth/session

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#8835] opened 2021-12-07 18:15 UTC
This bug has returned where we make an errant POST to /api/auth/session which returns 400 even though the user signs in successfully - it sends the same login request but with empty password

https://www.notion.so/learningequality/REGRESSION-Sign-in-5998238077dc48dc8cb8d4ce135478d3

**Comment by nucleogenesis** [comment] 2021-12-08 06:26
Reducing this to P2. It is a minor problem overall and the only fix I can think of is disproportionately complex. 

When a user puts their username and clicks "Next" we try to sign them in without a password. If the settings of Kolibri permit passwordless login for that user they are logged in, otherwise, they get a 400 and are asked to enter a password.

The fix would require some separate endpoint that doesn't return 400 and lets us know if the user needs to enter their password. Then, ideally, it would then log a user in if they don't need a password.

**Comment by marcellamaki** [comment] 2021-12-08 13:43
Thanks for clarifying @nucleogenesis -- sounds good!

**Comment by rtibbles** [comment] 2021-12-08 14:54
If this is what is happening I don't think it is a bug at all - the idea that we should never receive a non-error response from the backend during normal operation is erroneous.

The only things we might want to do are:
Not make this check unless we are setup to allow passwordless login (I thought we already did this but maybe not).
Add an "expected error code" option to our fetches to prevent loud logging when we get an error we expect. This would prevent people looking at the console thinking an error has occurred (we could also then use this in device for expected 404s).

**Comment by rtibbles** [comment] 2021-12-09 19:50
Note: I looked into this ^ slightly, and it seems that the big red error that bothers everyone in the console is generated by Chrome anyway, so the best we could do is add some conciliatory messages (which it seems that people ignore).

**Comment by rtibbles** [comment] 2022-04-27 22:18
Closing this as I don't think this is a bug at all. This is intended behaviour.

**Closed as completed by rtibbles** 2022-04-27 22:18 UTC
Labels: P2 - normal
