### ISSUE TITLE
HTML viewer - Full screen mode is not covering the entire screen area

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9517] opened 2022-06-14 14:47 UTC
## Observed behavior
The HTML viewer is not going in complete full zoom when using Kolibri 0.15.3 on a device with small resolution 1360x768 (16:9) and a 200%-400% zoomed browser). There's always a black portion of the screen at the bottom of the viewer.

## Steps to reproduce the issue
1. Install 0.15.3 and import the QA channel
2. Go to any HTML resource and select the "Enter fullscreen" option

## Screenshots
![2022-06-14_15-04-29](https://user-images.githubusercontent.com/79847249/173606047-09625a72-93e5-428c-acd5-5549706edd5f.png)

## Expected behavior
Fully expanded HTML viewer when in full screen mode.

## Usage Details
Ubuntu 20 - Chrome, Firefox

**Comment by pcenov** [comment] 2022-06-14 14:47
@radinamatic

**Comment by GarvitSinghal47** [comment] 2023-09-04 09:16
hey @marcellamaki i would like to work on this issue , can you assign it to me and can you also tell me how to reproduce the issue as  i am not able to find or get any html resource using the above mentioned step.

**Comment by marcellamaki** [comment] 2023-09-08 15:15
Hi @GarvitSinghal47 - thanks, I will assign you! You can import the channel we use for QA on Kolibri using the token `nakav-mafak` and the "Import with token" workflow. You should see folders that include HTML resources once you have imported it. From there, you should be able to reproduce this issue. Let me know if you have any further questions!

**Comment by MisRob** [comment] 2023-10-13 07:20
Unassigning due to no activity

**Comment by pcenov** [comment] 2023-10-27 12:09
Hi @radinamatic this is no longer extant in 0.16.0b6:


https://github.com/learningequality/kolibri/assets/79847249/b5e8f995-5db4-4b2c-a522-3d0f6b97415d

**Comment by radinamatic** [comment] 2023-10-27 12:22
Closing as not extant on 0.16!

**Closed as completed by radinamatic** 2023-10-27 12:22 UTC
Labels: P1 - important
