### ISSUE TITLE
content import doesn't distinguish between duplicate items in multiple topics

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#4082] opened 2018-07-30 11:35 UTC
### Observed behavior
We have exported whole channel (599cda55ed1141e58cab7ab1d97e998d) in pen drive. When we are trying to import only Class3 and Class4 in other server from that pen drive, it is also importing Class8 in the server.

### Expected behavior
It must import selected content in the server.

### Steps to reproduce
1. Import channel (599cda55ed1141e58cab7ab1d97e998d) in kolibri.
2. Export this channel to the pen drive.
3. Connect pen drive to the other server.
4. Select Class3 and Class4 which are in Science folder.
5. Import the channel.

### Context

 * Kolibri version : Kolibri 0.9.4b3
 * Operating system : ubuntu 14.04
 * Browser : Chrome 

### Screenshots

![screenshot from 2018-07-30 16-45-57](https://user-images.githubusercontent.com/12776071/43395172-c4428468-941a-11e8-9adc-e27cffb931df.png)
![screenshot from 2018-07-30 16-46-54](https://user-images.githubusercontent.com/12776071/43395174-c478f890-941a-11e8-9e3f-51ae4d3f5ab7.png)
![screenshot from 2018-07-30 16-55-24](https://user-images.githubusercontent.com/12776071/43395175-c4a54332-941a-11e8-9273-e191ce05eb83.png)

**Comment by indirectlylit** [comment] 2018-07-31 03:03
@swapnil106111 is there any chance that some content in Class8 also exists in Class3 or Class4?

**Comment by swapnil106111** [comment] 2018-08-20 13:29
@indirectlylit Yes. Class8 contents are present in Class3 and Class4.

**Comment by indirectlylit** [comment] 2018-08-21 21:36
@swapnil106111 unfortunately for the moment this is expected behavior, because the duplicate content within a channel is considered "the same", and we can't currently distinguish between multiple copies in different topics.

I'll log an internal report on this UX issue.

Two potential work-arounds might be:

* create a separate channel for each class, and import them independently
* use lessons to assign only the content from a particular class to the students

**Comment by swapnil106111** [comment] 2018-12-12 10:41
@indirectlylit Still this issue appears. 
Kolibri version : Kolibri 0.11.0
OS : ubuntu 14.04

Channel ID : mizam-zoruk
Import only grade 3 and see. 

Please find attached screenshot for more information:
![issue_1](https://user-images.githubusercontent.com/12776071/49863832-2acc1e80-fe27-11e8-8f0c-600927219441.png)
![issue_2](https://user-images.githubusercontent.com/12776071/49863833-2acc1e80-fe27-11e8-8c5d-194b1e772156.png)

**Comment by indirectlylit** [comment] 2018-12-13 17:57
Thank you @swapnil106111 -

We are exploring ways to address this, but it's not an easy fix because it's working "as designed" - we currently treat duplicate items as being identical, and have no way of distinguishing them.

The main workaround that I can think of is to use lessons as a way to direct learners to a subset of the content, thereby allowing them to focus on the main topics.

We have a related issue here and are working on design changes: #4549

**Comment by intelliant01** [comment] 2019-01-22 17:37
@indirectlylit Is the "design" such that the content nodes have the meta-info about the topics they belong to embedded into them? Hence during export they carry along that same signature and recreate it during import irrespective of the user's intent?

**Comment by indirectlylit** [comment] 2019-01-22 18:59
@intelliant01 no, content is not aware of which topics they belong to. Rather, topics contain content by referencing a content ID, but topics will often 'share' a single content item so that it only needs to be downloaded once even if it appears in many places.

**Comment by intelliant01** [comment] 2019-01-24 04:19
@indirectlylit then I fail to understand how is it that topics which are not being selected during the export are still being recreated during import?

**Comment by indirectlylit** [comment] 2019-01-24 05:07
Current implementation is that there's a single indivisible database file for each published version of each channel. This database contains a fixed representation of the entire channel topic structure.

When content is imported, Kolibri copies over the content and then marks which ones are available. The import process currently only knows about channels and content nodes.

Topics are just part of the channel metadata and don't get individually created or imported. In order to resolve this issue, we'll need to make import aware of topics also. It's a bit subtle though because there are some situations where the current 'location agnostic' behavior is actually useful, either for performance or UX reasons, and we'll need to consider all scenarios.

**Comment by intelliant01** [comment] 2019-01-24 05:36
If I have understood it correct, then during import of each content node,
it is being checked if the same exists in any of the topic nodes amongst
the channel meta data then the topic nodes gets recreated.

If the above is correct, then simply setting an additional flag on the
topics intended to be exported and additionally checking for its presence
during import should address the issue without any or much of a performance
overload or UX implications.

Risking this suggestion but I may be way off, given my limited
understanding of the data structures involved.

**Comment by indirectlylit** [comment] 2019-01-24 17:45
I don't personally have a full understanding yet of any competing tensions involved, but once I have a fuller picture I'll share back here

**Comment by indirectlylit** [comment] 2019-01-28 21:59
removing milestone - it wasn't supposed to be targeted to 0.12. Sorry for the confusion

**Comment by indirectlylit** [comment] 2019-09-25 04:14
FYI, design and development work is underway to improve the user experience for this sort of issue in 0.13.0. We'll update with details soon.

**Comment by indirectlylit** [comment] 2019-11-06 22:18
This is being addressed in ongoing changes in 0.13.0.

Specifically:

* import and deletion now acts on only a single instance of a content item when duplicates exist
* we allow individual instances to be deleted

**Closed as completed by indirectlylit** 2019-11-06 22:18 UTC
Labels: TAG: ux update
