### ISSUE TITLE
Thumbnails: Not appearing when updating the channel

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#9550] opened 2022-07-05 17:51 UTC
## Observed behavior

I imported channel B onto Kolibri where thumbnails appeared on the files. 

To create a channel, I had used the clipboard to import from channel A to channel B. In channel B, I changed the thumbnails on the the audio files.

Channel A is installed on Kolibri. I imported channel B into Kolibri, and no thumbnails appeared. 

I deleted channel A and B on the server, and reimported channel B, and it appeared correctly. 

## Expected behavior
It is expected that if you update a channel with a thumbnail, the thumbnail will render on Kolibri. 

## User-facing consequences

Frustrations that adding a thumbnail does not work + confusion

## Steps to reproduce
see above

## Context
Tell us about your environment, including:
 * Kolibri version: 0.15.2
 * Operating system: BCK instance (Windows)
 * Browser: Chrome

**Comment by bjester** [comment] 2022-08-30 15:35
@radinamatic Could you and/or @pcenov reproduce this?

**Comment by pcenov** [comment] 2022-08-31 11:21
@bjester I'm not able to replicate the issue following the steps provided above. Tested in Kolibri 0.15.7.
Here's a screenshot showing the original Channel A and the subsequently created Channel B using content from Channel A and containing both a modified thumbnail and an unchanged resource with the original thumbnail from Channel A:

![2022-08-31_14-14-48](https://user-images.githubusercontent.com/79847249/187667143-3849e86c-ee0a-44b2-bccb-cf5a5406616b.png)

**Comment by bjester** [comment] 2022-08-31 13:54
Thanks @pcenov! With your confirmation this is working on standalone installations, we believe this must be isolated to BCK deployments, and will help us further investigate the cause.

**Comment by rtibbles** [comment] 2022-09-12 21:00
It would be good to check this behaviour on a BCK server, as I cannot currently see why there would be any difference in behaviour.

It's possible that this was accidentally fixed by https://github.com/learningequality/kolibri/pull/9338 (which went into 0.15.3, while this issue was reported on 0.15.2).

**Comment by pcenov** [comment] 2022-09-13 13:11
@rtibbles I checked the behavior on the following BCK server: https://content-demo.learningequality.org/ and was again not able to replicate the issue - all thumbnails are displayed correctly.

**Comment by rtibbles** [comment] 2022-09-13 13:34
OK, I believe this was indeed fixed by #9338 then, and I'll close this.

**Closed as completed by rtibbles** 2022-09-13 13:34 UTC
Labels: P1 - important, TODO: needs QA re-review
