### ISSUE TITLE
Unable to create users on `kolibri-server`

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5214] opened 2019-02-28 02:17 UTC
### Observed behavior

Unable to create users:

![create-users](https://user-images.githubusercontent.com/1457929/53536526-11be3a00-3b07-11e9-952e-b96e7e978f6a.gif)

### Expected behavior

...

### User-facing consequences

…

### Errors and logs

```
{
  "request": {
    "path": "/api/auth/facilityuser/",
    "entity": "{\"facility\":\"0d7a9f000a70a22d9bc171a92dbdac5b\",\"username\":\"abbyl\",\"full_name\":\"Abby L.\",\"password\":\"abbyl\"}",
    "params": {
      "1551319935546": 1551319935546
    },
    "headers": {
      "Content-Type": "application/json",
      "Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2",
      "X-CSRFToken": "WWBpMr6hmfqGKnxDHxnPKp86m1DqJRwhFcBftRcrs6AfcISqEmcwSG5v710h77bQ"
    },
    "method": "POST",
    "canceled": false
  },
  "url": "/api/auth/facilityuser/?1551319935546=1551319935546",
  "raw": {},
  "status": {
    "code": 504,
    "text": "Gateway Time-out"
  },
  "headers": {
    "Connection": "keep-alive",
    "Content-Length": "192",
    "Content-Type": "text/html",
    "Date": "Thu, 28 Feb 2019 02:13:15 GMT",
    "Server": "nginx/1.10.3 (Ubuntu)"
  },
  "entity": "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"
}
```

### Steps to reproduce

…

### Context

Version:           0.12.0b10
OS:                Linux-4.4.0-142-generic-x86_64-with-Ubuntu-16.04-xenial
Installer:         kolibri(apt) with kolibri-server Version: 0.2-0beta3
Server:            nginx/1.10.3 (Ubuntu)
Browser:         Firefox & Chrome

cc @jredrejo

**Comment by jredrejo** [comment] 2019-02-28 08:22
@radinamatic  as expected, I can't reproduce it :(
Can you attach the files `kolibri.log` and `uwsgi.log` from the .kolibri folder?
Also, can you add the options you have active in the `/facility/#/settings` page?

**Comment by radinamatic** [comment] 2019-02-28 11:21
[uwsgi.log](https://github.com/learningequality/kolibri/files/2914701/uwsgi.log)
[kolibri.log](https://github.com/learningequality/kolibri/files/2914702/kolibri.log)

These settings were those created by the default options in the setup wizard:

![ubuntu 16 04 3 kolibri-server-beta10 running - oracle vm virtualbox_440](https://user-images.githubusercontent.com/1457929/53562956-0264de00-3b53-11e9-86cd-1ccaf916e45e.png)

**Comment by radinamatic** [comment] 2019-02-28 11:22
However, this morning when I restarted the same VM, I _am_ able to create users... 
Let's investigate why it was not possible yesterday.

**Comment by indirectlylit** [comment] 2019-03-25 20:38
closing. If this is still an issue, let's re-open in https://github.com/learningequality/kolibri-server

**Closed as completed by indirectlylit** 2019-03-25 20:38 UTC
Labels: bug, P0 - critical, OS: Linux
