### ISSUE TITLE
Main page scrolls when Learner opens info side panel in Bookmark page by keyboard navigation

### ISSUE THREAD

**Issue by sairina** [learningequality/kolibri#9095] opened 2022-02-10 06:37 UTC
## Observed behavior
When a learner has bookmarked resources, if they use the keyboard to go to the Bookmark tab and open up the info side panel, they will see that as they navigate through the info side panel, the background from the main page scrolls.

## Errors and logs
![2022-02-09 22 34 38](https://user-images.githubusercontent.com/13563002/153351395-3a51f86e-564d-4958-8b1e-57696b3617d0.gif)

## Expected behavior
Ideally, the main content page will not move while a user has a side panel open.

## User-facing consequences
This is just a strange annoyance.

## Steps to reproduce
1. Sign in as learner
2. Bookmark a resource from the Library
3. Navigate to the Bookmark tab
4. Once in the Bookmarks, use the keyboard to navigate to a card, and to the info button icon
5. Press enter to open the info side panel
6. Notice that the main page will shift

## Context
Important: Kolibri v15.0.1

**Comment by Akash-Kumar-Sen** [comment] 2022-08-07 16:47
Hi @sairina is this issue still open? Then I can give it a go.

**Comment by MisRob** [comment] 2022-08-08 08:58
Hello @Akash-Kumar-Sen, thank you for your interest. This issue is open, and you're welcome to try to reproduce it and fix it. Please see [our developer's documentation ](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html) if you haven't done so already. You should find everything needed to get started there.

Just note that on the `develop` branch, which is the branch mentioned in the documentation, it may not be currently possible to set up a new facility due to some work in progress (details can be found in [the comments of another issue](https://github.com/learningequality/kolibri/issues/9574)). So if you don't have Kolibri set up yet, please go through setup on the `release-v0.15.x` branch instead of `develop,` and it should be fine. So in the documentation, instead of
```
git checkout develop # Checkout the development branch
```
please do

```
git checkout release-v0.15.x
```

and then see if you can reproduce the problematic behavior reported in the issue. Its description says it should be present on the release branch.

**Comment by MisRob** [comment] 2022-08-08 08:59
@Akash-Kumar-Sen If you could let me know as soon as you start working, it'd be great. I would assign you so that we know that the issue has been taken.

**Comment by Akash-Kumar-Sen** [comment] 2022-08-08 10:21
Sure @MisRob you can assign this to me now.

**Comment by Akash-Kumar-Sen** [comment] 2022-08-08 10:24
I have also showed interest in this issue : https://github.com/learningequality/kolibri/issues/9563 you can also assign that to me if it is still open.

**Comment by MisRob** [comment] 2022-08-08 10:28
@Akash-Kumar-Sen Adding myself as an assignee too just to keep an eye on comments

**Comment by MisRob** [comment] 2022-08-08 10:30
@Akash-Kumar-Sen Okay, you're also assigned to the other issue. Thank you.

**Comment by Akash-Kumar-Sen** [comment] 2022-08-08 10:59
@MisRob Getting this error while running the step `yarn install` can you suggest what to do?
```
`(kolibri-4cBZohfZ) akash_sen@DESKTOP-ITNLNPR:~/kolibri$ yarn install
yarn install v1.22.19
$ node ./packages/kolibri-tools/lib/npm_deprecation_warning.js
[1/5] Validating package.json...
error kolibri-root@0.12.0-dev.1: The engine "node" is incompatible with this module. Expected version "10.x". Got "16.16.0"
error Found incompatible module.`
```

**Comment by MisRob** [comment] 2022-08-08 11:03
@Akash-Kumar-Sen 

This asks you to use Node v10 (we haven't upgraded it to v16 on the current release branch)

```
nodeenv -p --node=10.13.0 
```

**Comment by amitpanwar789** [comment] 2022-12-07 11:33
Hi @sairina is this issue still open? Then I can give it a go.

**Comment by deeppatel23** [comment] 2023-02-15 03:38
Hi, if the issue is still open, I can give it a try. Can you assign it to me, @MisRob?

**Comment by MisRob** [comment] 2023-02-15 12:32
Hello @deeppatel23, you're welcome to take this issue on. Please try if you can reproduce it at first. It'd be helpful if you could let us know as soon as you start working and I will assign you. If you haven't done so already, please have a look [at our developer documentation](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html).

**Comment by deeppatel23** [comment] 2023-02-15 17:14
Hi, I have done the setup and added a list of resources in Bookmarks. I am not able to product the issue, I can see that info (i) is clicked using the arrows of the keyboard. I am using Mac Keyboard, can you guide how to produce this issue?

**Comment by deeppatel23** [comment] 2023-02-16 08:19
@MisRob any suggestion for this error when trying to install node=10.13.0: 
Please use either Python 2.6 or 2.7
nvm: install v10.13.0 failed!
I am on Mac M1 and my current branch if release-v0.15.x. I have checked for solutions on StackOverflow for this issue, but nothing works. 

Also, I tried to create this bookmark tab behaviour in develop branch, but the issue was not generated there.

**Comment by deeppatel23** [comment] 2023-02-16 16:35
@MisRob the above-mentioned issue is fixed and I am able to reproduce this issue and I am working on it.

**Comment by MisRob** [comment] 2023-02-17 06:47
Hi @deeppatel23, alright, thank you

**Comment by harshtalati2410** [comment] 2023-03-14 10:39
Hello, @MisRob , I'm Harsh Talati. I would like to know if this issue is still open for contribution. If so, I would like to contribute to it. I've gone through the developers guide and if it is open, I can start working on it.

**Comment by MisRob** [comment] 2023-03-14 12:33
Welcome @harshtalati2410. It seems no one is working on this issue, so you're welcome to take this on.

**Comment by Pursottam6003** [comment] 2023-03-31 12:08
Hii @MisRob   I am interested in working on this issue. Could you please assign it to me so we can get started?
I can assure you that I will do this task within a few hours

**Comment by Pursottam6003** [comment] 2023-04-01 19:44
![image](https://user-images.githubusercontent.com/81693090/229311031-56e1ba26-a96e-4fbf-b19a-1a6a5f483ee8.png)


Hi i had also tried to reproduce the issue but i am unable to figure out any shifts /srolls

**Comment by nikkuAg** [comment] 2023-09-05 06:32
Hi, is this issue still open? I want to contribute to it.

**Comment by marcellamaki** [comment] 2023-09-08 15:09
Hi @nikkuAg - this issue is still open, but has been open for quite some time and it's possible that it may have been fixed incidentally over development in the last year. You are welcome to work on it, if you are still able to reproduce it. If you're not able to, let us know. Thank you for your interest!

**Comment by nikkuAg** [comment] 2023-09-21 18:44
Hi @marcellamaki, Yes I am able to reproduce this.

**Comment by nikkuAg** [comment] 2023-09-22 09:20
@marcellamaki,
I have added a PR. Please review it.

**Comment by rtibbles** [comment] 2023-09-25 19:31
Hi @nikkuAg - thanks for the fix, which I have merged - although it doesn't actually resolve _this_ issue which is specifically about the side panel in the bookmarks page. If you could replicate that same logic on the bookmark page, that would be great!

**Comment by rtibbles** [comment] 2023-09-25 19:32
See here: https://github.com/learningequality/kolibri/blob/release-v0.16.x/kolibri/plugins/learn/assets/src/views/BookmarkPage.vue

**Comment by nikkuAg** [comment] 2023-09-30 07:10
> Hi @nikkuAg - thanks for the fix, which I have merged - although it doesn't actually resolve _this_ issue which is specifically about the side panel in the bookmarks page. If you could replicate that same logic on the bookmark page, that would be great!

@rtibbles I have added a PR for the bookmarks page

**Comment by MisRob** [comment] 2023-11-10 12:33
Unassigning due to long time of inactivity. See https://github.com/learningequality/kolibri/pull/11341#issuecomment-1805315723 for more

**Comment by MisRob** [comment] 2023-12-13 12:52
Closed by https://github.com/learningequality/kolibri/pull/11607

**Closed as completed by MisRob** 2023-12-13 12:52 UTC
Labels: P2 - normal, TAG: a11y, APP: Learn, DEV: frontend, help wanted, good first issue
