### ISSUE TITLE
zip content in some exercises fails to load

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1272] opened 2017-04-21 00:35 UTC
Seeing lots of messages like this:

```
Request URL:http://localhost:8000/zipcontent/d1f0312b354f2feca06a2d26a96cb22e.perseus/images/faa680996bcb9b5fbd322819648bcbc7-data.json
Request Method:GET
Status Code:404 Not Found
```

```
Request URL:http://localhost:8000/zipcontent/d1f0312b354f2feca06a2d26a96cb22e.perseus/images/faa680996bcb9b5fbd322819648bcbc7.svg
Request Method:GET
Status Code:404 Not Found
```

```
Request URL:http://localhost:8000/zipcontent/d1f0312b354f2feca06a2d26a96cb22e.perseus/images/4cca117d94143a0364e1fa334337b78e.svg
Request Method:GET
Status Code:404 Not Found
```

For example:

* URL: http://localhost:8000/learn/#/f6d2f857af2e304093648daf2d8cacec/topics/c/37666e5422735d1ba711ca2d4dd88e27
* Name: Subtract within 100

gives:

![image](https://cloud.githubusercontent.com/assets/2367265/25216214/68a0bb04-2556-11e7-88f0-212179cbd4ca.png)

![image](https://cloud.githubusercontent.com/assets/2367265/25216206/63364bf2-2556-11e7-8fc6-dfa8ee6a756d.png)

----

(migrated from #1263)

**Comment by ralphiee22** [comment] 2017-04-25 19:52
@indirectlylit I believe you are you not getting the images because this is one of the early testing channels. It might be wise of me to delete it, as there might be other already resolved issues in this channel.
For example, for `Subtract within 100` on the demo server, the images do show up.
https://instantschools.learningequality.org/learn/#/topics/11d9de56da744f98877cc9fe710bb78d/content/1284a00afd28408d8670aad97c0cd540

**Comment by indirectlylit** [comment] 2017-04-25 20:04
@ralphiee22 note this issue also occurred in a new magogenie channel - see #1304

**Comment by indirectlylit** [comment] 2017-04-25 20:06
Also, this testing channel has worked fine for me until relatively recently. Should I be able to assume that existing, functional channels will in general stay functional, or do we make breaking changes sometimes?

**Comment by ralphiee22** [comment] 2017-04-25 20:26
What do you mean recently? Did you re-download the channel?
or did something change in Kolibri that made it unable to find the files anymore?

**Comment by indirectlylit** [comment] 2017-04-25 21:01
I'm not sure what changed specifically, but we've had to re-publish and re-download channels from the CC server to support changes to both of them.

**Comment by indirectlylit** [comment] 2017-04-26 21:37
reported by @jtamiace in the 'portion control' channel (`fb51dae6df7545af8455aa3a0c32048d`):

![image](https://cloud.githubusercontent.com/assets/2367265/25458171/c5069ba2-2a8d-11e7-8ab2-f711a0649d99.png)

**Comment by jamalex** [comment] 2017-04-27 17:10
The most recent incarnation of this was caused by the optimizations I made to the CC server last week; when an exercise node was cloned across channels, it didn't bring the images along with it. The cloning code has been fixed in https://github.com/fle-internal/content-curation/pull/235 and relaunched, and I'm now in the process of going through and fixing the data for nodes already cloned.

**Comment by jamalex** [comment] 2017-04-27 17:11
Of note, 24K unique nodes have been cloned since last week. :)

**Comment by jamalex** [comment] 2017-05-03 17:52
This should now be fixed across all channels (missing images have been cloned across to the new nodes), and all affected channels have been republished -- if there are any remaining issues after re-importing content into Kolibri, please open a new issue with the channel ID, and the URL for the exercise.

**Closed by jamalex** 2017-05-03 17:52 UTC
Labels: DEV: cc server, DEV: content pipeline, DEV: frontend, TASK: bug

**Comment by harishbalachandran** [comment] 2017-05-04 08:44
@jaime Not sure if the republish that you are talking above went through, because I just reimported the channel ID:7769d932b2cc49efb18c5e665cda64ff and found the issue to exist.

But when I republished the same channel, reimported and tested. All the images were loading up nicely.

Hence you may want to take a look at the republish that you tried at your end went through completely.
