### ISSUE TITLE
No "needs help" status in the exercise report page.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7229] opened 2020-07-01 10:07 UTC
The exercise report page does not show the "needs help" status.

### Observed behavior

I see two (or three) issues while testing [coach-track-lesson-groups-notifications.feature - Gherkin story](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-track-lesson-groups-notifications.feature#L51)

1. I cannot see the "needs help" status in the exercise report page.  However when I checked the `View by groups`, it shows the *i*/needs help red icon but it has no values.  I expected "needs help" to replace the "started" status.
<img width="1016" alt="Screen Shot 2020-07-01 at 5 31 53 PM" src="https://user-images.githubusercontent.com/175580/86229906-f499ef80-bbc2-11ea-8728-bf467650a7c7.png">

2. The status icons are helpful in the page BUT it only shows when the `View by groups` is checked.  It should be displayed in all views (grouped or ungrouped).
<img width="1016" alt="Screen Shot 2020-07-01 at 5 39 20 PM" src="https://user-images.githubusercontent.com/175580/86229864-e4821000-bbc2-11ea-97ad-efa6557cb274.png">

Here's the `Difficult Questions` tab showing the "needs help" status.
<img width="1016" alt="Screen Shot 2020-07-01 at 5 31 58 PM" src="https://user-images.githubusercontent.com/175580/86229975-0b404680-bbc3-11ea-8bb0-b6f3bd6ff470.png">

Here's the `.gif` of the exercise page as I navigated it:
![2020-07-01-wed--1--v0 14 0-b7--coach track lesson group notification 4](https://user-images.githubusercontent.com/175580/86230278-725dfb00-bbc3-11ea-9c65-098b047363b5.gif)

3. And perhaps we can also update the Lessons page to show the "needs help" status as another column?  I think it's very helpful to the coaches.
<img width="1016" alt="Screen Shot 2020-07-01 at 6 03 23 PM" src="https://user-images.githubusercontent.com/175580/86231794-a803e380-bbc5-11ea-87cb-7e8de9e9c122.png">

### Expected behavior
The "needs help" status must be shown in the exercise report page.  I expected it to replace the "Started" status.

### User-facing consequences
As a coach, I will not see which learners "needs help".

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4857063/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4857066/kolibri.txt)

### Steps to reproduce

1. Install [v0.14.0-beta7](https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta7) in a Win7 VM.
1. Follow this [coach-track-lesson-groups-notifications.feature - Gherkin story](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-track-lesson-groups-notifications.feature#L51). 

### Context

* Kolibri version: [v0.14.0-beta7](https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta7)
* Operating system: Win7 on VM
* Browser: Firefox v77
* Python: v3.6.8

**Comment by MisRob** [comment] 2020-07-20 11:22
I need to move on to another project, so at least adding a couple of observations. Although I saw it happen once myself, I haven't been able to find conditions to reproduce this issue reliably yet. (2) and (3) seem to be just a consequence of (1) - whenever "needs help" is working correctly, status icons are displayed.

**Comment by nucleogenesis** [comment] 2020-07-21 00:34
@rtibbles @indirectlylit @MisRob 

I tested this first on KOLIBRI_HOME 1 - which replicated the issue. This has long been the main home folder I've been using for a while. I did some digging and found that the LearnerProgressNotifications were not being saved into the notifications.sqlite3 db as I'd expect while I was taking the lesson as a learner.

I then tested on KOLIBRI_HOME 2 - which I made for last week's bug bash where we tested syncing to the Kolibri beta. I did not replicate the issue across several attempts on different resources (including that in @cpauya 's report).

So I thought maybe I'd remove the notifications.sqlite3 from KOLIBRI_HOME 1 - where I had replicated the issue - start the server fresh. At this point I was no longer able to replicate the issue in the KOLIBRI_HOME where I initially replicated it.

To see if this was an upgrade issue - I spun up KOLIBRI_HOME 0.12.x - which is how old it is. After running migrations and taking lessons poorly once more, I was not able to replicate the reported issue.

---

The issue was replicated, but not consistently. It doesn't seem like it is related to upgrading - at least not from 0.12.

All testing done on Debian run from source on the latest `release-v0.14.x` branch in Chrome.

---

I'd like to see if someone else can successfully replicate this to be sure before closing it because I did replicate it once.

**Comment by MisRob** [comment] 2020-07-21 05:14
Thanks @nucleogenesis for taking this issue and all new information. If this helps I spent relatively lots of time trying, most of the time also on the latest `release-v0.14.x`. Hopefully someone else can check it so we can be sure.

**Comment by indirectlylit** [comment] 2020-07-21 17:40
lowering priority because this is not going to affect all users

**Comment by nucleogenesis** [comment] 2020-07-22 13:21
@bjester and @rtibbles made some progress figuring this out yesterday and replicating, will bump back up to P0.

**Closed as completed** 2020-07-30 02:08 UTC
Labels: P0 - critical, TAG: regression
