### ISSUE TITLE
Survey modality - Cannot see the report for a survey submitted without any answered questions

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9023] opened 2022-01-21 14:47 UTC
## Observed behavior
If I submit a survey without answering any of the questions and then go ahead and check the report I see only a spinner icon and an error in the console: TypeError: Cannot read properties of undefined (reading 'item')
 
## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/4813
2. Import the Colors of Kindness (gutuf-potuv) channel
3. Complete any of the available surveys and check the report page

## Additional information
![2022-01-21_15-14-18](https://user-images.githubusercontent.com/79847249/150546900-856006ac-737a-4a99-b6f2-80f47bc4be35.png)

## Usage Details
Windows 10, Ubuntu - Chrome

**Comment by nucleogenesis** [comment] 2022-01-21 16:56
@jtamiace @radinamatic 

Should the expected behavior here be that the user is not permitted to submit an empty survey or that they see an empty report?

I can add some placeholder strings that I think fit unless y'all have some suggestions for how best to handle this UX.

**Comment by radinamatic** [comment] 2022-01-21 17:07
Wouldn't the easiest solution be to **not** introduce any new strings? If the user submits a survey without any answers, the report should display exactly that, no answers. 

Not liking the idea that we keep pushing in new strings on the fly and in the rush... 😕

**Comment by nucleogenesis** [comment] 2022-01-21 21:29
The only difference then should be that the loader isn't shown?

For the purposes of getting this done by deadline, that seems fine, but after the fact (for 0.16) we should develop a better UX - at least some microcopy that says "you submitted no answers, you can submit the survey again if this was a mistake" or something?

**Comment by radinamatic** [comment] 2022-01-21 21:51
Agreed that we should improve the UX, and since this feature is a last minute addition, I'd be very eager to hear some feedback from users first, before we dive into that.

As of now users can re-submit the survey weather they answered some, all, or none of the questions inside, so we might want to consider that too, when thinking about the microcopy improvements.

**Comment by nucleogenesis** [comment] 2022-01-27 16:47
Closed by #9000

**Closed as completed by nucleogenesis** 2022-01-27 16:47 UTC
Labels: P0 - critical, APP: Learn, DEV: frontend
