### ISSUE TITLE
fix createsuperuser command

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2245] opened 2017-09-21 22:34 UTC
scenario:

* there is only one user on a device with 'superuser' permission
* the user forgets their password

Currently there is no straightforward way to recover and get superuser access again.

We should update the `kolibri manage createsuperuser` command to work with the new superuser flag logic.

**Comment by rtibbles** [comment] 2017-09-25 19:38
Duplicate of #1985

**Closed by rtibbles** 2017-09-25 19:38 UTC
