### ISSUE TITLE
Kolibri cant generate device info

### ISSUE THREAD

**Issue by maxwellfundi** [learningequality/kolibri#7243] opened 2020-07-03 08:02 UTC
### Observed behavior
Kolibri does not show the device info. This is after i upgraded form 0.13

### Expected behavior
By opening Device>Info, i expected to find information about the device, Ip addresses etc

### User-facing consequences
You would be able to easily identify the IP address to share with people to access Kolibri

### Errors and logs

![image](https://user-images.githubusercontent.com/9798689/86445936-e7444880-bd1b-11ea-973b-6eca840ea66e.png)

### Steps to reproduce
Open Kolibri then go to Device>Info

### Context

Tell us about your environment, including:
 * Kolibri version - 0.14 beta 6
 * Operating system - window 10 
 * Browser - Coogle Chrome

**Comment by indirectlylit** [comment] 2020-07-03 22:26
Thanks for the report @maxwellfundi 

I'm not able to reproduce here. Would you mind clicking this button and checking if there's addition error information available?

![image](https://user-images.githubusercontent.com/2367265/86499689-6d26ba80-bd41-11ea-8130-04cda6cae615.png)


You might also check if there are errors in the Kolibri log files under `~/.kolibri/logs`

**Comment by maxwellfundi** [comment] 2020-07-11 05:42
Hello @indirectlylit , I have gone back to Kolibri today to make sure i clarify this but it seems to work fine. Not sure what was happening when i reported this.

**Comment by radinamatic** [comment] 2020-07-11 16:54
Thank you @maxwellfundi!
Closing this but you can reopen if it appears again, and try to add the information @indirectlylit pointed out.

**Closed as completed by radinamatic** 2020-07-11 16:54 UTC
Labels: P1 - important, TODO: needs clarification
