### ISSUE TITLE
Coach can't assign lessons and quiz recipients

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7171] opened 2020-06-24 19:55 UTC
### Observed behavior
Coach can't assign recipients on lessons and quiz

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/85621210-7bb50800-b697-11ea-835e-c1ce109b1e9a.gif)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: release-v0.14.0b4
 * Operating system: Windows 7
 * Browser: Firefox 77

**Comment by radinamatic** [comment] 2020-06-29 23:26
Looks same root cause as in #7200, closing.

**Closed as completed by radinamatic** 2020-06-29 23:26 UTC
