### ISSUE TITLE
Quiz reporting tool  not populating learners information

### ISSUE THREAD

**Issue by maxwellfundi** [learningequality/kolibri#7244] opened 2020-07-03 08:06 UTC
### Observed behavior
I upgraded from 0.13 by running the beta 6 unsigned installer. I created a quiz, which i opened to learners, they did and finished the quiz. After everyone had done the quiz, I ended the quiz. 
I then wanted to see the reports on how each of the students performed in the quiz from Coach>Reports>Quizzes and it indicates that there are no learners and yet when i open difficult questions am able to see how many students did not get the questions right 

When I tried printing report, it was still empty meaning that its not a UI problem. 

![image](https://user-images.githubusercontent.com/9798689/86444076-e231ca00-bd18-11ea-8c21-8219e5eb1d74.png)

![image](https://user-images.githubusercontent.com/9798689/86444134-faa1e480-bd18-11ea-887f-1ddcd573c3f6.png)

### Expected behavior
I expected to have a list of name of the learners, their progress, scores and groups they belong to.

### User-facing consequences
It would not be possible to know how individual learners performed as the report is empty. 

### Steps to reproduce
from Coach module, Create a Class and a quiz. Assign the quiz to the learners ion your class. After they are done with the quiz, end quiz. 
Open quiz reports.

### Context
Tell us about your environment, including:
 * Kolibri version - 0.14 beta 6
 * Operating system - Windows 10
 * Browser - Google Chrome

**Comment by nucleogenesis** [comment] 2020-07-06 05:46
It looks like nobody is assigned to the quiz. On the left sidebar under "Recipients" it says "No one".

Would you mind going to that quiz report page and then click "Options" then "Edit Details" and assign the quiz to the Entire Class.

When you go back, you ought to see all Learners assigned to that quiz.

Did you ever assign the quiz to individual learners or change the selection of who to assign the quiz to? I'm curious because this may be a sign of a bug in that part of the code if the quiz was inadvertently unassigned from the whole class.

**Comment by jonboiser** [comment] 2020-07-06 17:32
There was a bug where Lesson assignees (groups, classes, and learners) were not being displayed properly, that was not fixed until beta 7 (https://github.com/learningequality/kolibri/issues/7200).

It looks similar to this issue, where even though the Quiz was assigned to the whole class, all of the side panels say "assigned to no one". That may seem to be why the "Report" tab is empty. The "Difficult Questions" tab must populate its data differently, which is why it still displays data.

**Comment by radinamatic** [comment] 2020-07-06 23:17
@maxwellfundi This should be fixed in Beta 7 from last week, but you might want to re-try with Beta 8 (hopefully tomorrow?).

**Comment by indirectlylit** [comment] 2020-07-10 22:59
closing. please re-open if it is still reproducible in the latest beta

https://github.com/learningequality/kolibri/wiki/0.14.0-beta-testing

**Closed as completed by indirectlylit** 2020-07-10 22:59 UTC
Labels: P0 - critical

**Comment by maxwellfundi** [comment] 2020-07-11 05:29
Thank you very much for getting this fixed. I look forward to testing it in Beta 8, and eventually on the upcoming release.  @radinamatic @indirectlylit  @jonboiser
