### ISSUE TITLE
My Channels not listing the new channels after import

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#2030] opened 2017-08-25 18:50 UTC
## Summary

After importing a channel, whether from local drive or Internet, it does not appear under `My Channels` until page reload. 

## System information

 - Version: `0.5.0-beta9`
 - Operating system: Windows 7 & Ubuntu 16.10
 - Browser: Chrome

![ubuntu3 0 5-beta9 running - oracle vm virtualbox_494](https://user-images.githubusercontent.com/1457929/29728036-9cf986f8-89d6-11e7-99b0-fc0d7619fbdd.png)

On [version 0.4.0](https://github.com/learningequality/kolibri/issues/1640#issuecomment-313949731) at least there was a green notification, but now it's missing too:

![selection_328](https://user-images.githubusercontent.com/1457929/27996982-56743686-64ee-11e7-8f3d-cb2e1044b7d9.png)

State is correctly reported after deleting the channel, green notification included.

![ubuntu3 0 5-beta9 running - oracle vm virtualbox_496](https://user-images.githubusercontent.com/1457929/29727957-49d8e04a-89d6-11e7-8af6-3a70805475a4.png)

**Comment by jonboiser** [comment] 2017-09-12 19:19
This might be a duplicate of #2145. @radinamatic Did you delete the KA Testing channel before this sequence of downloading it. #2128 has some analysis of why this might be happening.

**Comment by radinamatic** [comment] 2017-09-12 19:50
It may very well be @jonboiser, as assuring the proper deletion of channel databases on Windows was one of the main points while testing that beta release.

**Comment by jonboiser** [comment] 2017-09-15 18:17
#2153

**Closed by jonboiser** 2017-09-15 18:17 UTC
Labels: TASK: bug
