### ISSUE TITLE
Microsoft Edge browser - Video player is displayed with hidden header

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9501] opened 2022-06-08 14:55 UTC
## Observed behavior
When I open a video resource using Microsoft Edge browser the video player is displayed so that the header is hidden (if I scroll up I can see the header but I have to do that every time) and everything looks zoomed in.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5658 from https://github.com/learningequality/kolibri/pull/9222
2. Go to the Library and click on a video resource

## Screenshots
![2022-06-08_16-49-15](https://user-images.githubusercontent.com/79847249/172648030-c0d7ce9c-07f2-4fb4-9aa1-8b55fd4ece9c.png)

## Usage Details
Windows 10 - Microsoft Edge

**Comment by GarvitSinghal47** [comment] 2023-09-04 09:14
hey @marcellamaki i would like to work on this issue , can you assign it to me

**Comment by MisRob** [comment] 2023-09-04 12:12
Hi @GarvitSinghal47. I'm assigning you. At first, I'd recommend trying if you can reproduce it on 0.16 branch

**Comment by GarvitSinghal47** [comment] 2023-09-06 13:02
@MisRob this issue is still present and i was able to reproduce it in 0.16 branch  .


> Hi @GarvitSinghal47. I'm assigning you. At first, I'd recommend trying if you can reproduce it on 0.16 branch

**Comment by MisRob** [comment] 2023-09-06 13:07
Alright, thank you, @GarvitSinghal47. You're welcome to tackle it

**Comment by MisRob** [comment] 2023-10-13 07:22
Unassigning due to no activity

**Comment by pcenov** [comment] 2023-10-27 12:29
@radinamatic this one is still extant in Kolibri 0.16.0b6:

https://github.com/learningequality/kolibri/assets/79847249/03f58000-fc63-4d1a-99b3-df631902ef51

**Closed as completed** 2023-12-05 15:10 UTC
Labels: P1 - important, OS: Windows, APP: Learn, DEV: frontend, help wanted
