### ISSUE TITLE
handling of small thumbnails in channel import screen

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#9106] opened 2022-02-14 18:00 UTC
## Observed behavior

The current layout allows the thumbnail column to shrink in width, which causes inconsistency across cards:

> ![image](https://user-images.githubusercontent.com/2367265/153920039-8d64bb6e-aed9-4450-bc07-769b23979846.png)

## Expected behavior

I would expect the thumbnail area to to have a minimum width so all text areas are horizontally aligned.

## User-facing consequences

Slightly harder to scan text due to misalignment

## Steps to reproduce

http://localhost:8080/en/device/#/content/channels

Search for channels such as:

* Citoyennes: Portraits de femmes engagées pour le bien commun 
* Ciênsação

## Context

0.15

**Comment by marcellamaki** [comment] 2022-06-28 21:01
closing as duplicate of https://github.com/learningequality/kolibri/issues/7751

**Closed as completed by marcellamaki** 2022-06-28 21:01 UTC
