### ISSUE TITLE
0.18 - Plan quizzes - Print report - The 'New quiz' button is visible in the print report

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12715] opened 2024-10-10 14:33 UTC
## Observed behavior
This is a follow-up to https://github.com/learningequality/kolibri/pull/12704:

When I click the 'Print report' button I can see the 'New quiz' button in the generated page:

![print](https://github.com/user-attachments/assets/6719e6b2-6792-47cf-9403-87e7fb2467a8)

## Expected behavior
The 'Print report' label should not be visible in the print report

## Steps to reproduce the issue

1. Install the build from https://github.com/learningequality/kolibri/pull/12704
2. Import the QA channel (nakav-mafak) and create quizzes assigned to learners
3. Complete some of the quizzes and go to Coach > Plan
4. Click the 'Print report' icon

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment] 2024-10-10 14:34
@radinamatic

**Comment by RONAK-AI647** [comment] 2024-10-17 04:58
Hey @radinamatic @pcenov @MisRob I **tried to work on this issue and followed the required steps to reproduce the issue but fortunately i did not find it. I did this on my system and print report has a very clear view and no "new quiz" button seen in the print report .Please let me know , if this issue does not exist .I have attached the screenshot as seen below:**

[![Image](https://github.com/user-attachments/assets/2f8a3ebb-fff6-4eaa-a31b-9434101c33c6)
]

**Comment by AllanOXDi** [comment] 2024-10-17 11:18
Hi @RONAK-AI647 let me also try and see if I can reproduced it and get back to you.

**Comment by pcenov** [comment] 2024-10-17 11:52
By the way @RONAK-AI647 which build asset were you using when you were trying to reproduce the issue? I can confirm that it's still happening in the latest build here: https://github.com/learningequality/kolibri/pull/12704

**Comment by pcenov** [comment] 2024-10-17 12:26
Here's also a video of how to replicate the issue, hope this helps: 

https://github.com/user-attachments/assets/4a41779d-f8d0-4a30-ac3f-dbdd5fd1c67d

**Comment by AlexVelezLl** [comment] 2024-10-17 15:59
Hey @RONAK-AI647! Thanks for your interest in contributing to Kolibri! Unfortunately this issue is not marked as `help wanted` so it was not initially intended for open source contribution. You can take a look at the Kolibri [contribution guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md) to get a better sense of our open source process 🤗. You can take a look at the list of unassigned ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) issues across all repositories. Let me know if you have any questions :).

**Comment by RONAK-AI647** [comment] 2024-10-17 16:11
**Hey @AlexVelezLl ,thank you so much for your suggestions, as I am new here, I am trying my best to understand the issues. But I noticed each "closed issue" or "pull request" has given rise to series of new issues .**

**Comment by marcellamaki** [comment] 2024-10-17 16:36
Hi @RONAK-AI647 -- many of the issues and PRs that you are seeing are related to the ongoing development of new features. As QA happens on these PRs, it may uncover some underlying bugs that pre-date this work, or unexpected scenarios. We manage these in follow up issues as we make decisions and consult with the designers and QA team. Typically, issues that are opened for bug fixes, or are more narrowly scoped, and therefore opened to community contribution, will not have follow up issues opened or the same amount of dynamic decision making. 

As Alex mentioned, please look at the Kolibri [contribution guidelines](https://github.com/learningequality/kolibri/blob/release-v0.16.x/CONTRIBUTING.md) to get a better sense of our open source process. Choosing from ["help wanted"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues) or ["good first issue"](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee&type=issues) would be the best place for you to find ways to contribute and engage with the team.

At this point, I'm going to wrap up this discussion here so we can preserve the issue comments for discussion that is more specific to this issue, once it is assigned to someone on the team. If you have more general questions, please use the [Github discussions](https://github.com/learningequality/kolibri/discussions) for that.

**Closed as completed** 2024-12-18 20:21 UTC
Labels: P1 - important, APP: Coach, DEV: frontend
