### ISSUE TITLE
Kolibri page not loading for few seconds.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5342] opened 2019-04-03 07:37 UTC
### Observed behavior
When we stop and start the kolibri server, we observed that for few seconds it will not load kolibri page(127.0.0.1:8080). It will show a content like "This site can’t be reached".

But when we restart the server, it works as expected.

### Expected behavior
After stop and start the server, it must load the kolibri page.

### Steps to reproduce
1. Stop the server
2. Start the server 
3. Go to the Browser and run 127.0.0.1:8080

### Context
 * Kolibri version : Kolibri 0.12.1
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshot
![Screenshot from 2019-04-03 13_00_18](https://user-images.githubusercontent.com/12776071/55461162-662a6d00-5611-11e9-9b4e-b2b4037e4bad.png)
![Screenshot from 2019-04-03 12_58_47](https://user-images.githubusercontent.com/12776071/55461163-662a6d00-5611-11e9-8ffc-885cd8377e4f.png)

**Comment by arky** [comment] 2019-04-10 16:50
Possibly related to https://github.com/learningequality/kolibri/issues/5348 ?

**Comment by jredrejo** [comment] 2019-04-22 08:14
Nope, I had also noticed this problem (and not the one related in #5348).
Checking the code I can confirm the server takes some time to start (even minutes if it's in a slow filesystem and there are a lot of content nodes in the db) due to this line of code in the starting process:
`update_channel_metadata()`
This code check is needed to fix possible mixmatches between the database content information and thea actual downloaded content in the device. It takes times as it compares the files with the database and updates/deletes it accordingly.
I think this check if needed, but maybe it could be flagged to be done only after channel content is changed, @rtibbles what do you think?

**Comment by rtibbles** [comment] 2019-04-22 13:49
`update_channel_metadata` was originally implemented to handle upgrades from significantly older versions (pre-0.6.x) as prior to that we did not store the channel metadata in the main database. We could probably do some more sophisticated checks to prevent these operations being run every time.

**Comment by jredrejo** [comment] 2019-09-10 17:31
@swapnil106111  After #5494 update will happen only after a new version of Kolibri with database migrations is done. Usual kolibri restarts won't execute this code.
This change will be available with the release of the 0.13.0 version.

**Comment by rtibbles** [comment] 2021-03-22 22:50
This should have been resolved by #5494

**Closed as completed by rtibbles** 2021-03-22 22:50 UTC
Labels: TAG: ux update, TAG: performance, DEV: backend
