### ISSUE TITLE
No progress indication on Lesson

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11879] opened 2024-02-15 13:36 UTC
Reported by @nucleogenesis in the 0.16 sync session Feb 14 2024 

## Observed behavior
I completed a lesson and see no info on the card about it akin to that which I see on the completed quizzes.

This is after going back from viewing the lesson back to the home page. When I navigate away from the Home page and then back to it, the progress indicators are there

## Expected behavior 
Progress indicators should be visible on the lesson, just like it is with quizzes
 
<img width="1409" alt="Screenshot 2024-02-15 at 8 33 28 AM" src="https://github.com/learningequality/kolibri/assets/17235236/575b5e6f-423b-4463-9192-9b7900246e80">

## Steps to reproduce

1. Create a learner and coach/admin account
2. Assign one or more lessons, and make available to the learner 
3. Begin at least one of the lessons
4. Exit the lesson without completing it (there should likewise be a progress indicator within the lesson content renderer - see below for example)
5. Return to the lesson page - a progress bar should be missing
6. Return to the home page
7. Click back into the lesson in question - see that the progress bar is now visible

(progress indicator in the lesson content renderer)
<img width="501" alt="Screenshot 2024-02-15 at 8 32 20 AM" src="https://github.com/learningequality/kolibri/assets/17235236/d85d6673-4bc0-4c67-b96c-70b983522c78">

## Context
Kolibri 0.16.x
Note: this is reproducible in 0.15 kolibri demo server, and therefore isn't a 0.16 regression but is likely an earlier regression.

**Comment by iskipu** [comment] 2024-02-15 14:49
can this be assigned to me ?

**Comment by Abhishekzod007** [comment] 2024-02-17 13:46
Hii @marcellamaki ,  I would like to work on this. Can you assign this issue to me?

**Comment by MisRob** [comment] 2024-02-19 12:52
Hi @Abhishekzod007, thanks for volunteering, I'm assigning you.

**Comment by Abhishekzod007** [comment] 2024-02-19 18:46
Thanks for assigning @MisRob. I'll give you updates about it.

**Comment by himanshuc3** [comment] 2024-03-13 05:02
@MisRob How is the progress calculated?
Even on a short reading resource, it shows partial progress. Even the folder resources cta shows that single resource, so my expectation is that it should be marked completed.
![Screenshot from 2024-03-13 10-29-35](https://github.com/learningequality/kolibri/assets/19166045/e9a39269-1dce-44ea-a21c-08975c217a91)
![Screenshot from 2024-03-13 10-28-54](https://github.com/learningequality/kolibri/assets/19166045/e01f4f93-c422-43c4-acf3-40be43245f8d)

**Comment by Abhishekzod007** [comment] 2024-03-13 18:34
Hii @marcellamaki 
I am sorry that I was not active on this issue. 
But recently I was watching this issue and I have some doubts regarding the issue
When we start a lesson reading or viewing it then ( even it is short or long ) it's progress starts increasing on the indication bar but a very small indication is there even we scrolled out the whole page but as we scrolled the  page completely  the progress indication  should be completed but in place of that it shows some partial amount of progress. That's ok I think.
I tried to do this inother way I stayed at the lesson and waited for some time and keep scrolling up down up down in the same way  once I think that it was a problem that we have to keep scrolling on the page so that we can see the progress but I was wrong it is not like that.
Then I tried and think it  again other way, if we stayed on that page or lesson for a time period about 4 - 5 minutes then the task will be automatic completed and we will see an acknowledgement like this 
![image](https://github.com/learningequality/kolibri/assets/98864225/a9a13dc1-c037-470d-9e60-f0866ca84bf2)
![image](https://github.com/learningequality/kolibri/assets/98864225/6443f59e-f611-41b1-bdcb-d93895bc8427)

I tried this for 2 - 3 times and I observed the same behaviour every time.
So that's all from my end.
Please tell me more about this , what's the particular issue there beacuse I think there is no problem with the  progress indication of a lesson , this behaviour is already set in the backend process.
I think I need more information about this and it will be greatful  if you upload an example with video showing the particular problem.

**Comment by Abhishekzod007** [comment] 2024-03-14 11:11
Hii @marcellamaki  @MisRob could you please give example  about this issue because I trying this for the last 2 days but didn't get the point. 
![image](https://github.com/learningequality/kolibri/assets/98864225/c14754d5-d5be-4f77-a276-e29a3c213502)
When I am returning on the home page it is showing me the progress bar.

**Comment by marcellamaki** [comment] 2024-03-14 14:59
Hi @Abhishekzod007 - thanks for working on this and I'm sorry for the confusion. Please double check and make sure you have follow the first few items in the "Steps to reproduce" directions. It looks from the page here that this learner does not have any lessons assigned. 

1. Create a learner **and coach/admin account**
2. **Assign one or more lessons** and make available to the learner. (note: this has to be done in the **coach** account, then you log out, and then sign in as the learner)
3. Begin at least one of the lessons

The other important note is that the bug is on the **lesson** page (see further down in the steps to reproduce), not the home page. Therefore, in order to reproduce, you must take the steps to create the lessons, so that you can access the lesson page when logged in as a learner, rather than just browse resources, as it looks like you are doing in the screenshots you have shared. If more information about these different roles would be helpful, you can take a look at our [general user documentation](https://kolibri.readthedocs.io/en/latest/manage/user_roles.html), in addition to the [dev docs](https://kolibri-dev.readthedocs.io/en/develop/). 

If you have further questions or uncertainties about the steps to reproduce, please ask them here.

**Comment by Abhishekzod007** [comment] 2024-03-14 15:35
Thanks a lot @marcellamaki , I will give updates about this

**Comment by Abhishekzod007** [comment] 2024-03-14 16:13
Hey @marcellamaki , I tried as you said , First I created a learner as a name of Learner itself so now in Admin account I assigned the learner a task or lesson and then I went again in the learner account and without completing it I came outside of the lesson and then the next part as you are mentioning that learner will not be able to view lesson indication progress but I facing issue there , but I am able to see the progress indication every time when I closes it or If I return to home screen then also no issue is there.
I understood the 50-60% part of the problem can you clarify the other 40% part of the problem please.

**Comment by AlexVelezLl** [comment] 2024-03-14 16:47
Hi @Abhishekzod007 I just recorded a Video to make the issue clearer, the problem is that the lesson is not updating its progress state when we return from the resource. In the video you can see that I need to go back to the home page, or reload the page to have the progress state updated.

https://github.com/learningequality/kolibri/assets/51239030/340a5b7e-c81f-443f-9031-6533b7afafe9

**Comment by Abhishekzod007** [comment] 2024-03-14 17:45
Thanks a lot @AlexVelezLl , now I have a better understanding of this.
But don't you thik that it should  be applicable for the lesson 1 which is completed then why this problem is only occurring with lesson 2 not with lesson 1.

**Comment by AlexVelezLl** [comment] 2024-03-14 19:07
Oh Lesson 1 is there only because of previous tests, you can ignore it

**Comment by Abhishekzod007** [comment] 2024-03-14 19:24
That's ok

**Comment by Abhishekzod007** [comment] 2024-03-15 09:26
Hii @marcellamaki  is there any problem when we allocate a resource or manage it , then it shows like that
![image](https://github.com/learningequality/kolibri/assets/98864225/3aec3636-849c-49a9-ab3e-b40852aed512)
this is the first step
if we only select then that lesson will be assigned to the lesson class
But if we click on that lesson itself then 
![image](https://github.com/learningequality/kolibri/assets/98864225/73f36f1b-22b8-4874-bfb3-ac5391f45387)
this error showed up. 
is this an error or something else ?

**Comment by Abhishekzod007** [comment] 2024-03-15 10:19
And you mentioned Kolibri 0.16.x server , what is that ?
Where I have to work in the codebase that is triggering this problem ?

**Comment by marcellamaki** [comment] 2024-03-15 14:56
Hi @Abhishekzod007 - it's possible that there is a problem with previewing the resource, although your second question might help us understand if there is a bug there, and whether or not it is related to the issue described here. 

In github, for Kolibri, we have many different [branches](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches) of work. The current issue, as reported, exists in the line of work for the `0.16.x` releases, which is the branch `release-v0.16.x`. This is the branch you should be running locally. 

So, the first step would be to make sure then when running your local dev environment, you are running that branch, rather than `develop` for this particular issue. 

If you still encounter this problem with the lessons when running this branch, could you share any error message you see in your terminal and/or in the browser console?

**Comment by Abhishekzod007** [comment] 2024-03-16 11:00
![image](https://github.com/learningequality/kolibri/assets/98864225/a61f467c-a036-4437-869f-4e2193823313)
@marcellamaki 
while trying to run on `release-v0.16.x` I see this.
I do not encounter this while trying to run `develop` branch.

**Comment by marsian83** [comment] 2024-03-16 11:44
> ![image](https://private-user-images.githubusercontent.com/98864225/313399695-a61f467c-a036-4437-869f-4e2193823313.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1ODc0OTAsIm5iZiI6MTcxMDU4NzE5MCwicGF0aCI6Ii85ODg2NDIyNS8zMTMzOTk2OTUtYTYxZjQ2N2MtYTAzNi00NDM3LTg2OWYtNGUyMTkzODIzMzEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDExMDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNTk0ZmZjMjJjNmJhMjNlYjQ5NGNlODkzNmNkMWZiMDY0M2Q5MDc0YTRhMmYzY2JmZGQ0ZGIxMDUwODUwY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TluOgb8-bexYR-PoVld7h97vWOKTCnzjGPX5gQQJ9k8)
> 
> while trying to run on `release-v0.16.x` I see this. I do not encounter this while trying to run `develop` branch.

Hi @Abhishekzod007 
I encountered same issue when running `learningequality/studio` a while back
There is a simple fix for this -> [check it out here](https://github.com/learningequality/studio/pull/3923)

**Comment by Abhishekzod007** [comment] 2024-03-21 10:30
Hii @marcellamaki @bjester 
I am facing the same issue on the Kolibri 0.16.x 
![image](https://github.com/learningequality/kolibri/assets/98864225/0dd9660d-5478-4f3b-8461-47d4f58822b4)
 and I trying to solve this from past few days.
I tried in the  same way as @marsian83 did by adding .git as a suffix but it didn't work out.
 Could you please help me out with this?

**Comment by ozer550** [comment] 2024-03-21 10:43
> Hii @marcellamaki @bjester I am facing the same issue on the Kolibri 0.16.x ![image](https://private-user-images.githubusercontent.com/98864225/315251749-0dd9660d-5478-4f3b-8461-47d4f58822b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTc3MjgsIm5iZiI6MTcxMTAxNzQyOCwicGF0aCI6Ii85ODg2NDIyNS8zMTUyNTE3NDktMGRkOTY2MGQtNTQ3OC00ZjNiLTg0NjEtNDdkNGY1ODgyMmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDEwMzcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NTg1NzY4ZmFhYjZjMWY2MWNkNGVkZDk2ZWY1NjczMzY0MjRiOTA4YTA2ZmNmMjExMzc0MzRmOGY2Y2Y0OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8HvLK-_Pvo51WVt3NSK1OHZy7sxA-W59iHwMcA2D4v8) and I trying to solve this from past few days. I tried in the same way as @marsian83 did by adding .git as a suffix but it didn't work out. Could you please help me out with this?

Hi @Abhishekzod007! did you remove your node_modules folder before doing this? I would recommend deleting the node_modules folder, applying the fix that @marsian83 has mentioned then try running yarn install.

**Comment by Abhishekzod007** [comment] 2024-03-21 11:17
Hii @ozer550 I did what u said
But the same error is there
![image](https://github.com/learningequality/kolibri/assets/98864225/09cb49f5-1a67-4fce-8d22-01a57cd3c86d)

**Comment by ozer550** [comment] 2024-03-21 11:38
just to confirm you updated the URL adding .git suffix in the package.json of perseus_viewer?

**Comment by Abhishekzod007** [comment] 2024-03-21 11:55
@ozer550 I didn't understand , what is perseus_viewer ? and where it is in the codebase

**Comment by ozer550** [comment] 2024-03-21 11:59
> @ozer550 I didn't understand , what is perseus_viewer ? and where it is in the codebase

[here](https://github.com/learningequality/kolibri/blob/fd2b58ff9b4eea8bd623cea085f8095f93d94b0b/kolibri/plugins/perseus_viewer/package.json#L10)

**Comment by Abhishekzod007** [comment] 2024-03-21 12:32
Thanks @ozer550 I solved it

**Comment by Abhishekzod007** [comment] 2024-03-21 12:58
Hey @ozer550 @marcellamaki the issue is there when a learner completes the lesson then "completed" is marked there and then when we return to lesson page then it still shows "in progress"  after we refresh then it marks "completed".
I wanna ask , which part of code is triggering this problem

**Comment by Abhishekzod007** [comment] 2024-03-22 19:35
![image](https://github.com/learningequality/kolibri/assets/98864225/b42ceb95-0066-4dda-bc36-789b7d3d0d1a)
My guess is since the computed property depends upon `classId` and it does not change when coming back a level from within the class, while on the other hand when we visit after refetching the classes it reloads.
I'd love to know your opinions on this
@marcellamaki @bjester @ozer550 

The screenshot is from the file `\kolibri\plugins\learn\assets\src\views\classes\ClassAssignmentsPage.vue` line 61

**Comment by MisRob** [comment] 2024-03-23 05:35
Hello @Abhishekzod007, sounds you are perhaps onto something. You can try to debug this place in more detail, for example by console logging or some other technique, to confirm that this computed property is indeed causing the issue.

**Comment by Abhishekzod007** [comment] 2024-03-28 03:53
Hii @MisRob , I have tried by all the ways which I can, but I think the issue is associated with the class Id in the computed part 
I am pretty sure about this because when we go toh the particular lesson then the class Id remains same so no changes rendered there but when we go to home page and then we return back to the lesson page then the class id changes/refreshes because there could be many classes or lessons so it reloads again. So this is what I am thinking of. 
I tried by console logging also but facing problem with this.

**Comment by MisRob** [comment] 2024-03-29 04:42
Alright, thanks for debugging @Abhishekzod007. You may need to look in more detail at the ways that class ID is updated in the codebase. Also, not sure if this helps but from the issue description it seems that quizzes are working so you could perhaps study that logic and see if you can find some inspiration to resolve lessons issues.

**Comment by nathanaelg16** [comment] 2024-05-17 12:31
Hi team, I started looking into this and it seems like the issue is due to a combination of the 30 second delay between polling for updates + the updates not triggering a refresh of the active lessons. If I tweak the delay to 1 second and force a refresh of the active lessons I am able to get the progress indicator to show up. However, there is something funky going on with the way lesson progress is persisted across the different media types, which I would like to look into further. I'd love to hear if you have any thoughts on this and I'd be happy to pick this issue up. @MisRob

**Comment by AlexVelezLl** [comment] 2024-05-17 17:16
Hi @nathanaelg16! Thanks for looking into this :). Reducing polling from 30s to 1s doesn't look like the best option here, we'll probably have to look at reloading the resources or updating the status of lessons. Please fell free to open a PR with with the proposed solution that you have, and we can continue the discussion there. I will assign you this issue.

**Comment by nathanaelg16** [comment] 2024-05-17 17:42
Yeah, I figured reducing the polling wasn't desirable, I just wanted to share what I had discovered so far. I'll continue to look into this and keep you updated. Thanks!

**Comment by rtibbles** [comment] 2024-05-22 15:16
Fixed in #12185

**Closed as completed by rtibbles** 2024-05-22 15:16 UTC
Labels: bug, P1 - important, APP: Learn, DEV: frontend, help wanted
