### ISSUE TITLE
entering and exiting full screen causes epub to become blank

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#5566] opened 2019-05-28 20:47 UTC
### Observed behavior

entering and exiting full screen causes epub to become blank:

![fullscreen](https://user-images.githubusercontent.com/2367265/58511078-f6d38400-814e-11e9-8812-1d0df0602570.gif)

### Expected behavior

epub should render as normal

### User-facing consequences

user confusion

### Steps to reproduce

* open epub
* enter full-screen
* press 'escape'

epub will be blank

### Context

* 0.12.4 beta 4
* chrome
* mac

**Comment by rtibbles** [comment] 2019-05-28 20:54
I feel like this happened before, but I can't find any record of it. My intuition is that it is due to the new version of epubjs (but worth checking 0.12.3 to see if the behaviour exists there).

**Comment by danigm** [comment] 2022-03-08 17:52
I can reproduce this problem in the current release v0.15.1, just in chrome. In firefox this doesn't happens to me.

We've a workaround fix for the Endless Key, just reemiting the resize event after fullscreen: https://github.com/endlessm/kolibri-explore-plugin/commit/98b809ea346bb63476fae8d2cc54f727f1bced37

**Comment by jamalex** [comment] 2022-03-08 17:54
Reopening so we can see if we can replicate this

**Comment by radinamatic** [comment] 2022-03-08 17:57
@pcenov Could you try to replicate this tomorrow? Thank you!

**Comment by pcenov** [comment] 2022-03-09 15:23
@radinamatic yes I confirm that this issue is still extant in release v0.15.1 in Chrome only - works fine in Safari and the Mac app.

**Comment by rtibbles** [comment] 2022-03-10 18:27
I think this may also be related to the issues we have seen when trying to update epubjs to a newer version.

**Comment by vanessa-chang** [comment] 2023-05-30 10:59
Test on Kolibri android version 0.15.6-92dd435-official & endless key (kolibri: 0.16.0a12)

The presentation breaks (as the screenshot below) when it enters to a full screen mode, and it cannot change the page by clicking the back/ next button.
It will display normally if you exit the full screen mode.

***note***: This issue is only reproduced on the Android 9, 32-bit device. It works well on the andriod 11 device.

Android 9 / ChromeOS: 113.0.5672.134 (32-bit)
Android 11 / ChromeOS: 113.0.5672.134 (64-bit)

![Screenshot 2023-05-30 18 40 49](https://github.com/learningequality/kolibri/assets/31236978/16389e97-5270-42a6-b3ac-78ae50f903f6)

**Comment by radinamatic** [comment] 2024-08-06 16:34
cc @pcenov

**Comment by pcenov** [comment] 2024-08-07 09:41
Hi @radinamatic - this issue is no longer extant in Kolibri 0.17 - tested in all supported browsers.

**Comment by radinamatic** [comment] 2024-08-07 14:33
Closing as not extant on 0.17!

**Closed as completed by radinamatic** 2024-08-07 14:33 UTC
Labels: P1 - important, DEV: renderers, PLUGIN: epub, TODO: needs QA re-review
