### ISSUE TITLE
“Something went wrong!” error during setup

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3079] opened 2018-01-12 20:06 UTC
### Observed behavior

A couple users have reported this error:

* https://community.learningequality.org/t/trying-to-install-kolibri-on-mint-18-3/449
* https://community.learningequality.org/t/kolibri-setup-issue/426/6

Seems to be independent of the 'hyphen issue' #2996

### Expected behavior

Setup works as expected

### Errors and logs

…

### Steps to reproduce

…

### Context

Kolibri 0.7 on Linux

**Comment by rtibbles** [comment] 2018-01-12 20:11
Worth noting that in the second case, this happens on the PPA install, but not when running from the PEX.

**Comment by benjaoming** [comment] 2018-01-12 20:16
Could we possibly add some more debugging info to the "oops something went wrong" page? It's not exactly helping anyone -- users have to do extra work to fetch logs etc, and devs have to ask additional questions.

Regarding the issue itself, we will have to ask those questions, unless we can reproduce.

**Comment by rtibbles** [comment] 2018-01-12 20:17
My assumption is that it is the Morango futures issue that @lyw07 is currently trying to fix.

**Comment by benjaoming** [comment] 2018-01-12 20:21
@rtibbles sounds likely -- the pex will invoke Python 2 by default, and the .deb is invoking Python 3. There are many pitfalls. I'm almost giving up on troubleshooting the particular issue, because 0.7.1 and 0.8 will both contain multiple fixes.

**Comment by benjaoming** [comment] 2018-01-28 22:49
Closed as a duplicate of the above - @rtibbles and @indirectlylit please make a call on whether a separate issue should be opened about the rather low information error page :) (I would suggest a textarea with some copy-paste ready exception information from the failed API callback)

**Closed by benjaoming** 2018-01-28 22:49 UTC
