### ISSUE TITLE
epub settings are not saved

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4244] opened 2018-09-13 20:52 UTC
### Observed behavior

Font size and theme are reset every time I refresh or navigate to a different book

### Expected behavior

settings are saved and re-used, at least within a session

### User-facing consequences

need to re-set settings every time

### Steps to reproduce

* change settings
* refresh

### Context

develop

----

cc @christianmemije

**Comment by christianmemije** [comment] 2018-09-20 19:38
Duplicate of #4268

**Closed as completed by christianmemije** 2018-09-20 19:38 UTC
