### ISSUE TITLE
Setup wizard step bug on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6444] opened 2020-01-08 08:31 UTC
### Observed behavior
Setup wizard automatically proceed from step 6 to 7 when I open and close the `Usage and privacy` Modal

### Expected behavior
Setup wizard must stay on step 6 when I open and close the `Usage and privacy` Modal

### User-facing consequences

…

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/71962254-09a94d80-3234-11ea-9f51-608c190f57e8.gif)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0
 * Operating system: Windows 7
 * Browser: IE11

**Comment by jonboiser** [comment] 2020-01-08 19:28
Was able to reproduce this in Browserstack.

An important detail is that the form needs to be completely filled in. This bug won't occur if the form is blank.

My hunch is that this is caused by propagating "submit" events (not the Vue event, but the default "submit" event forms implement in HTML) from the form inside of the PrivacyModal down to the form in the Setup Wizard.

**Comment by jonboiser** [comment] 2020-02-06 18:51
Fixed in #6506 by replacing the "primary" button in the privacy modal with a plain-old button without the `type=submit` attribute, as this appears to be interpreted by IE11 as the submit button for the higher-level form inside the setup wizard. 🤷‍♂

**Closed as completed by jonboiser** 2020-02-06 18:51 UTC
Labels: bug, P2 - normal
