### ISSUE TITLE
A horizontal green line appears on Kolibri App Setup Wizard page and other pages randomly

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7762] opened 2021-01-26 13:25 UTC
### Observed behavior

Sometimes a horizontal green line (spanning end to end) appears on Kolibri App Setup Wizard page and other pages randomly after the setup is completed. 

<img width="960" alt="greenLine" src="https://user-images.githubusercontent.com/72492554/105850559-8f886a00-5fea-11eb-9199-292267dee607.png">
<img width="960" alt="2021-01-26_152227" src="https://user-images.githubusercontent.com/72492554/105850685-b9419100-5fea-11eb-8e1b-7db59ea3d0ff.png">

### Expected behavior

No green line appears on Kolibri App screens.

### Steps to reproduce

1. Start a fresh new setup of the Kolobri App
2. See the Setup Wizard page

### Context

Kolibri 0.14.3 - App
Windows 10 Virtual Machine
IE

**Comment by jonboiser** [comment] 2021-01-26 20:37
I believe this is a windows and/or IE11-only issue. It would be really helpful to understand what element is being underlined here, since probably the hack would be to give that element a `tabindex=0` attribute. 

The underline is actually a full outline around the entire mystery element (like we do when keyboard-focusing buttons and links). It's just the top and side borders are cut off by the window.

**Comment by Aadi71** [comment] 2021-03-13 16:04
I think this is due to your version of Windows. As I also tested for the same issue, and mine is not showing that horizontal green line.
If still you are not convinced please try from another PC and then report again if the issue arises again.

**Comment by Pursottam6003** [comment] 2023-03-31 12:52
Hey, I am interested in working on this issue. Could you please assign it to me @MisRob

**Comment by MisRob** [comment] 2023-04-05 10:57
Hello @Pursottam6003, thank you for your interest. As you volunteered for more issues and already have some of them assigned, I'm leaving this unassigned for now in case someone else wanted to tackle it as you're working on other issues. When your plate is empty, if this issue is still available, please remind yourself here and we can assign it to you.

**Comment by hustlernik** [comment] 2023-12-03 22:13
Hey @MisRob, Can I work on this issue? Please assign me if possible.

**Comment by MisRob** [comment] 2023-12-07 13:05
Hi @hustlernik, thanks for volunteering, I'm assigning you

**Comment by MisRob** [comment] 2023-12-07 13:07
@hustlernik Let's see if you can reproduce it at first. This may be specific to Internet Explorer.

**Comment by hustlernik** [comment] 2023-12-13 15:13
@MisRob I'm trying.

**Comment by MisRob** [comment] 2023-12-15 13:52
Alright, thanks @hustlernik! This is my last day before few weeks off so I won't be able to follow-up until I am back. Perhaps some of my colleagues jumps in if needed, but please note Learning Equality will be closed for the holidays from December 22 to January 2, and even as we're transitioning to and from this period of rest we may be slow to respond.

**Comment by marcellamaki** [comment] 2024-01-03 15:14
Hi @hustlernik - with 0.17 release of Kolibri, we will be dropping IE11 support. If you are not able to reproduce this on another browser, other than IE11, we will close it out as we will no longer need to fix it. Please let us know if you need any additional support in reproducing, and thank you for your interest in this issue!

**Comment by hustlernik** [comment] 2024-01-10 04:26
hello @marcellamaki, I wasn't able to reproduce it in other browsers. I guess it works well with other browsers.

**Comment by rtibbles** [comment] 2024-01-15 20:23
Due to IE11 deprecation, we are closing this and similar IE11 specific issues.

**Closed as completed by rtibbles** 2024-01-15 20:23 UTC
Labels: bug, P3 - low, OS: Windows, ie11, help wanted

**Comment by MisRob** [comment] 2024-01-16 12:14
@hustlernik thanks for confirming it's okay on another browsers
