### ISSUE TITLE
500 Points without completing the complete video. The system is calculating the duration for which the video is watched.

### ISSUE THREAD

**Issue by amit3107** [learningequality/kolibri#3491] opened 2018-04-07 13:26 UTC
### Observed behavior

As the learner begins watching the video, it is calculating the total duration for which the video is being watched and accordingly the points are given.
For eg. A video of 2.30 min is being watched, if the learner watches till 1.30 and then closes and again starts the video and watches for 1min or more,  the learner gets 500 points and technically the video is not being completed.

### Expected behavior

The student must get 500 points only when the complete video is watched in one go.

### User-facing consequences

The admin/coach would think the student has watched the video.

### Steps to reproduce

1. Login as admin or learner and go to any channel and select a video.
2. For eg. A video of 2.30 min is being watched, if the learner watches till 1.30 and then closes and again starts the video and watches for 1min or more,  the learner gets 500 points and technically the video is not being completed.

Kolibri version : kolibri 0.9.0
Operating system : ubuntu 14.04
Browser : Chrome

### Screenshot
![error](https://user-images.githubusercontent.com/38091824/38455414-7619a43a-3a95-11e8-9935-066ac960cd13.png)
![error2](https://user-images.githubusercontent.com/38091824/38455415-765df856-3a95-11e8-8ba2-0c1686419135.png)
![error3](https://user-images.githubusercontent.com/38091824/38455416-769e2af2-3a95-11e8-8c78-cc65b3c7fa97.png)

**Comment by indirectlylit** [comment] 2018-04-07 21:12
thanks - this is unfortunately a known issue. closing as duplicate of https://github.com/learningequality/kolibri/issues/3126

**Closed by indirectlylit** 2018-04-07 21:12 UTC
