### ISSUE TITLE
graceful handling of server disconnection and log-out

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1477] opened 2017-05-11 21:54 UTC
It will be fairly common for a previously accessible Kolibri instance to become unavailable.

Some examples:

* a student may be using a tablet and walk out of range of a hotspot
* a laptop hosting kolibri may run out of battery power
* the host machine remains accessible, but someone shuts down the kolibri instance running on it

We should look at both the technical and UX side of things.

1. Write code to catch and handle errors these kinds of errors holistically, and set some global vuex state that represents whether the host is accessible
2. Add a pop-up, overlay, or similar to indicate to the user that the app is disconnected. Potentially prevent further interaction with the app until it reconnects.  (cc @jtamiace @khangmach)

We probably don't want to go down the 'leave parts usable when disconnected' rabbit hole yet...

**Comment by indirectlylit** [comment] 2017-10-10 21:07
updated the scope of this issue now that we've implemented session time-out

**Comment by indirectlylit** [comment] 2017-10-10 21:13
see also: https://github.com/learningequality/kolibri/issues/2390

**Comment by rtibbles** [comment] 2017-10-23 17:55
Yeah, at the very least simple things like 'connection to server lost', and 'you have been logged out, please log in again' are important here.

The main improvement on the latter case we need, is detecting 403s when they happen, and assuming this has been caused by session timeout.

**Comment by khangmach** [comment] 2017-11-01 22:45
@indirectlylit here's an idea of how we can frame copy to handle both the disconnect case and logout case.

![disconnection-handling](https://user-images.githubusercontent.com/25045166/32301547-a1a0780e-bf1b-11e7-8bda-bbf30f37a980.png)

Some thoughts and documentation that went into the design: https://docs.google.com/document/d/1iz7Wxp7CryS7KNIUi7gRVZkxNWnaPFi7Us8pNdvIwq4/edit#

**Comment by khangmach** [comment] 2017-11-02 02:46
here's an update:
![disconnection-handling](https://user-images.githubusercontent.com/25045166/32307357-559422e0-bf3d-11e7-97ce-7ae2cbd3933f.png)

**Comment by christianmemije** [comment] 2017-11-14 01:22
I have a few questions. Does the disconnected from server alert apply to all pages/pugins? Even on the sign in page? Is it only when signed in? 

Also, what happens when the 'try again` is pressed. Circular loader? 

@richard had also mentioned the possibility of having a `will attempt to reconnect in x seconds/mins` Some mockups showing this interaction appreciated. :pray:

@khangmach @jtamiace

**Comment by khangmach** [comment] 2017-11-14 19:38
@christianmemije If the sign-in page requires a connection to access, which I think it should...right? Then the disconnect from server alert should also appear on the sign-in page. 

When try again is pressed the system message should change to convey that Kolibri is attempting to connect. This attempt message should timeout after something like 10-20 seconds? See mockup for this. If the circular loaded presented in the mockup isn't feasible, then I am also okay with using our Kolibri loader or whatever loaders we're typically use. 

![disconnect-messages](https://user-images.githubusercontent.com/25045166/32800812-339addbc-c930-11e7-9629-09f34fe01f1e.png)

**Comment by indirectlylit** [comment] 2017-11-20 18:25
FYI this is assigned to both @rtibbles and @christianmemije

@christianmemije were you going to work on it?

**Comment by rtibbles** [comment] 2017-11-20 18:26
Intentionally so, @christianmemije is implementing the interface, I am working on the state management.

**Comment by christianmemije** [comment] 2017-11-20 18:28
@indirectlylit Yes, jumped back on it this morning.

**Comment by christianmemije** [comment] 2017-11-20 21:06
@khangmach These screenshots should cover all states. Do the strings looks good?

![localhost_8000_user_ galaxy s5](https://user-images.githubusercontent.com/7193975/33041511-69766c4a-cdf3-11e7-834a-bd844901a511.png)
![localhost_8000_user_ galaxy s5 1](https://user-images.githubusercontent.com/7193975/33041512-698e9f04-cdf3-11e7-8bb8-99cfd4cc0fe5.png)
![localhost_8000_user_ galaxy s5 2](https://user-images.githubusercontent.com/7193975/33041513-69a3e0bc-cdf3-11e7-93ad-b1de0f93c931.png)
![localhost_8000_user_ galaxy s5 3](https://user-images.githubusercontent.com/7193975/33041515-69bdd60c-cdf3-11e7-991f-96219db6518b.png)

**Comment by khangmach** [comment] 2017-11-20 21:10
looks great

**Comment by christianmemije** [comment] 2017-11-30 20:36
Last of this was addressed in #2747 :champagne:

**Closed by christianmemije** 2017-11-30 20:36 UTC
Labels: DEV: frontend, P0, TASK: new feature, TASK: tech update, TASK: ux update, user-text
