### ISSUE TITLE
Unidentified "undefined" string inside Perseus

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#1811] opened 2017-07-09 21:22 UTC
## Summary

String `undefined` appears on the side or below the exercise, inside the Perseus renderer, below `problem-area` and above the `hintsarea`... :thinking: 

## System information

 - Version: [`0.4.0-446-gd1737c5`](https://github.com/learningequality/kolibri/pull/1805)
 - Operating system: Windows 10 & Ubuntu 16.10
 - Browser: Chrome

## Screenshots

![ubuntu3 start running - oracle vm virtualbox_331](https://user-images.githubusercontent.com/1457929/27997633-1e5ac788-64fd-11e7-87ae-47621b32c6f7.png)

![win10 start running - oracle vm virtualbox_319](https://user-images.githubusercontent.com/1457929/27997613-4343ed32-64fc-11e7-831a-8ffbc68d7f01.png)

**Comment by rtibbles** [comment] 2017-07-09 22:16
Hrm, this appears to be a vue js issue that should have been fixed in 2.0.4 according to this commit: https://github.com/vuejs/vue/commit/d0afcd3cf9ad572621676ef02005d226cb4ac7c4 investigating further to see why it might be recurring here.

**Comment by rtibbles** [comment] 2017-07-09 22:21
This seems to be precisely this issue: https://github.com/vuejs/vue/issues/4107, not sure why we are getting it when we are using vuejs 2.3.3.

**Comment by radinamatic** [comment] 2017-07-10 05:24
Whatever that was, it's gone in the latest 0.5.0 build ([1673](https://buildkite.com/learningequality/kolibri/builds/1673)), and the hint button is showing correctly :+1: 

![win10 start running - oracle vm virtualbox_332](https://user-images.githubusercontent.com/1457929/28003739-22dc8aa6-6540-11e7-95f9-bb707e0b1638.png)

![ubuntu3 start running - oracle vm virtualbox_333](https://user-images.githubusercontent.com/1457929/28003744-2d7be33a-6540-11e7-94ce-b1b485646c91.png)

Closing this for now, unless @rtibbles wants to chase the elusive undefined down the rabbit hole... :wink:

**Comment by radinamatic** [comment] 2017-07-11 15:38
Resurfaced on PEX build from #1816, it is unclear to me which conditions make the `Hint` button not showing correctly... :disappointed: 

It appears on both device owner or a learner, independent of whether I start the PEX with Pyton 2 or 3, no errors whatsoever in the console or the Terminal... Will test on Windows next.

![ubuntu3 start running - oracle vm virtualbox_342](https://user-images.githubusercontent.com/1457929/28076626-9d47edb0-665f-11e7-9807-5549fd38eb5c.png)

Anything specific to look for @rtibbles?

**Comment by radinamatic** [comment] 2017-07-11 16:27
Present on Windows 7 too, on EXE build from #1816, no idea if the "undefined" on the right has anything to do with "undefined" on the left... :confused: 

![win7 start running - oracle vm virtualbox_344](https://user-images.githubusercontent.com/1457929/28078876-8b0195c8-6666-11e7-9308-1d050e72eedc.png)

**Comment by rtibbles** [comment] 2017-07-15 23:44
Is this always in a vm, @radina? Thinking that it is due to a race condition that applies due to resource constraints. Will try replicating on a more resource constrained system.

**Comment by radinamatic** [comment] 2017-07-19 04:03
@rtibbles No, it was reported during the RTL hack session, and you can see it on KA Early Math exercises on the demo server:

https://kolibridemo.learningequality.org/learn/#/1ceff53605e55bef987d88e0908658c5/topics/c/69e5e6abf479581483d441b83d7d76f4

**Comment by rtibbles** [comment] 2017-07-20 01:04
I can reproduce this on demo servers, but not locally, either in production or development mode.

**Comment by rtibbles** [comment] 2017-07-20 01:13
Nor in either dev or production on browserstack...

**Comment by rtibbles** [comment] 2017-07-31 16:00
This should be fixed.

**Closed by rtibbles** 2017-07-31 16:00 UTC
Labels: DEV: frontend, TASK: bug

**Comment by radinamatic** [comment] 2017-07-31 16:04
Haven't seen it in on the latest versions, will report back if I stumble upon again!

**Comment by rtibbles** [comment] 2017-07-31 16:15
That's because I fixed it, of course!

**Comment by radinamatic** [comment] 2017-07-31 16:17
Of course, wouldn't dream of diminishing your merit! :blush: :+1:
