### ISSUE TITLE
Import from Studio is repeatedly failing

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#6267] opened 2019-12-10 14:52 UTC
### Observed behavior
Part 1: While trying to Import a channel, the channel reached about 70% and then failed. Subsequent attempts produced immediate failure.
![image](https://user-images.githubusercontent.com/22602993/70539998-772d6580-1b32-11ea-87f0-a244acc5b633.png)

Part 2: Switching to a different channel also resulted in immediate failure, while not recognizing channel name
![image](https://user-images.githubusercontent.com/22602993/70539987-73014800-1b32-11ea-82fa-b5f62b75b7af.png)

…

### Errors and logs

```
vue-router.esm.js:2051 Uncaught (in promise) 
NavigationDuplicated
message: "Navigating to current location ("/content/manage_tasks") is not allowed"
name: "NavigationDuplicated"
_name: "NavigationDuplicated"
stack: "Error↵    at new NavigationDuplicated (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js:1:402560)↵    at HashHistory.History.confirmTransition (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js:1:404936)↵    at HashHistory.History.transitionTo (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js:1:404208)↵    at HashHistory.push (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js:1:409916)↵    at http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js:1:415066↵    at new Promise (<anonymous>)↵    at VueRouter.push (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js:1:415014)↵    at Sub.goToManageTasksPage (http://127.0.0.1:8080/static/kolibri.plugins.device.app/kolibri.plugins.device.app-0.13.0b4.js:1:309516)↵    at http://127.0.0.1:8080/static/kolibri.plugins.device.app/kolibri.plugins.device.app-0.13.0b4.js:1:310317↵    at http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js:1:1144284"
__proto__: Error
```
-->

…

### Steps to reproduce

Attempt to Import a channel via Kolibri Studio

### Context

Tell us about your environment, including:
 * Kolibri version - 0.13.0b4
 * Operating system - OS (pex)
 * Browser - Chrome

**Comment by radinamatic** [comment] 2019-12-10 16:52
I'm running the b4 PEX **on Ubuntu**, but importing channels work a-OK for now.

I did see the `(Channel name unavailable)` during our hack session last week, but it was for the KA Fulfulde channel @ralphiee22 was actively trying to update, and I thought it was a fluke 😞

**Comment by lauradanforth** [comment] 2019-12-10 18:34
```INFO 2019-12-10 00:10:41,031 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 00:10:41,831 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '127.0.0.1', 'base_url': 'http://127.0.0.1:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 00:56:29,011 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 00:56:29,797 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '127.0.0.1', 'base_url': 'http://127.0.0.1:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 01:53:46,034 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 01:53:47,243 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '127.0.0.1', 'base_url': 'http://127.0.0.1:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 04:10:10,036 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 04:10:10,772 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '10.0.0.79', 'base_url': 'http://10.0.0.79:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 04:52:33,039 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 04:52:34,296 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '127.0.0.1', 'base_url': 'http://127.0.0.1:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 05:44:57,038 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 05:44:57,899 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '10.0.0.79', 'base_url': 'http://10.0.0.79:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 05:56:04,026 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 05:56:05,130 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '127.0.0.1', 'base_url': 'http://127.0.0.1:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 06:00:16,026 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 06:00:17,259 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '10.0.0.79', 'base_url': 'http://10.0.0.79:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 06:51:32,042 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 06:51:32,921 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '127.0.0.1', 'base_url': 'http://127.0.0.1:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 08:20:02,069 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 08:20:02,792 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '10.0.0.79', 'base_url': 'http://10.0.0.79:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 08:23:11,030 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 08:23:12,187 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '10.0.0.79', 'base_url': 'http://10.0.0.79:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 09:10:30,028 search 
Kolibri instance '47f7' has left the zeroconf network.

INFO 2019-12-10 09:10:37,102 search Kolibri instance '47f7' joined zeroconf network; service info: {'ip': '10.0.0.79', 'base_url': 'http://10.0.0.79:8080/', 'data': {u'version': [0, 13, 0, u'alpha', 0]}, 'port': 8080, 'host': u'47f7.kolibri.local', 'local': True, 'id': u'47f7'}

INFO 2019-12-10 09:46:00,402 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-subset.en.css?v=0.13.0b4 HTTP/1.1" 200 16026 "http://127.0.0.1:8080/en/user/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:00,414 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/kolibri.core.default_frontend/kolibri.core.default_frontend0.13.0b4.css HTTP/1.1" 200 16485 "http://127.0.0.1:8080/en/user/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:00,434 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-common.css?v=0.13.0b4 HTTP/1.1" 200 107426 "http://127.0.0.1:8080/en/user/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:00,435 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/kolibri.plugins.user.app/kolibri.plugins.user.app-0.13.0b4.js HTTP/1.1" 200 24470 "http://127.0.0.1:8080/en/user/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:00,485 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js HTTP/1.1" 200 354282 "http://127.0.0.1:8080/en/user/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:01,234 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-full.NotoSans.400.woff HTTP/1.1" 200 432828 "http://127.0.0.1:8080/static/assets/fonts/noto-full.en.modern.css?v=0.13.0b4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:01,234 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-full.NotoSans.700.woff HTTP/1.1" 200 433488 "http://127.0.0.1:8080/static/assets/fonts/noto-full.en.modern.css?v=0.13.0b4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:01,433 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/background.jpg?0.13.0b4-Default%20theme-1 HTTP/1.1" 200 211311 "http://127.0.0.1:8080/en/user/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:04,731 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/kolibri.plugins.facility.app/kolibri.plugins.facility.app-0.13.0b4.js HTTP/1.1" 200 41917 "http://127.0.0.1:8080/en/facility/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:15,520 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/kolibri.plugins.device.app/kolibri.plugins.device.app-0.13.0b4.js HTTP/1.1" 200 76469 "http://127.0.0.1:8080/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:20,637 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-full.NotoSansArabic.700.woff HTTP/1.1" 200 176396 "http://127.0.0.1:8080/static/assets/fonts/noto-full.en.modern.css?v=0.13.0b4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:20,643 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-full.NotoSansArabic.400.woff HTTP/1.1" 200 163056 "http://127.0.0.1:8080/static/assets/fonts/noto-full.en.modern.css?v=0.13.0b4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:20,648 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-full.NotoSansGujarati.700.woff HTTP/1.1" 200 187244 "http://127.0.0.1:8080/static/assets/fonts/noto-full.en.modern.css?v=0.13.0b4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:20,652 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-full.NotoSansDevanagari.700.woff HTTP/1.1" 200 190804 "http://127.0.0.1:8080/static/assets/fonts/noto-full.en.modern.css?v=0.13.0b4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:24,745 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-full.NotoSansGujarati.400.woff HTTP/1.1" 200 186112 "http://127.0.0.1:8080/static/assets/fonts/noto-full.en.modern.css?v=0.13.0b4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:24,752 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/assets/fonts/noto-full.NotoSansDevanagari.400.woff HTTP/1.1" 200 181776 "http://127.0.0.1:8080/static/assets/fonts/noto-full.en.modern.css?v=0.13.0b4" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
INFO 2019-12-10 09:46:29,278 importchannel Downloading data for channel id 0418cc231e9c5513af0fff9f227f7172
ERROR 2019-12-10 09:46:29,631 importchannel An error occurred during channel import: pickle protocol 4 asked for; the highest available protocol is 2
ERROR 2019-12-10 09:46:29,653 worker Job 851ae45f25a342ed814cf0a20a8c926b raised an exception: Traceback (most recent call last):
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 69, in handle_finished_future
    result = future.result()
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 222, in wrap
    raise e
ValueError: pickle protocol 4 asked for; the highest available protocol is 2

INFO 2019-12-10 09:46:44,570 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/kolibri.plugins.device.app/kolibri.plugins.device.app-0.13.0b4.js.map HTTP/1.1" 200 227292 "" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
INFO 2019-12-10 09:46:44,689 cherrypy.access.4564919632 127.0.0.1 - - "GET /static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b4.js.map HTTP/1.1" 200 1088051 "" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36"
INFO 2019-12-10 09:48:55,887 importchannel Downloading data for channel id 197934f144305350b5820c7c4dd8e194
ERROR 2019-12-10 09:48:56,298 importchannel An error occurred during channel import: pickle protocol 4 asked for; the highest available protocol is 2
ERROR 2019-12-10 09:48:56,312 worker Job 9dee285b1bd24913b2e8b5db502a7bd8 raised an exception: Traceback (most recent call last):
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 69, in handle_finished_future
    result = future.result()
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 222, in wrap
    raise e
ValueError: pickle protocol 4 asked for; the highest available protocol is 2

INFO 2019-12-10 11:02:57,913 utils Ping succeeded! (response: {u'messages': [], u'id': 499205})
ERROR 2019-12-10 11:02:57,924 worker Job a9ee2a1b0e43413da3234a510e95f04c raised an exception: Traceback (most recent call last):
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 69, in handle_finished_future
    result = future.result()
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/lauradanforth/.pex/install/kolibri-0.13.0b4-py2.py3-none-any.whl.94f39b4fc0bd6445dae536778251b4546c621b79/kolibri-0.13.0b4-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 222, in wrap
    raise e
ValueError: pickle protocol 4 asked for; the highest available protocol is 2

```

**Comment by indirectlylit** [comment] 2019-12-15 03:16
closing as duplicate of https://github.com/learningequality/kolibri/issues/6238

**Closed as completed by indirectlylit** 2019-12-15 03:16 UTC
Labels: bug, P0 - critical
