### ISSUE TITLE
Attempts and "Need Help"

### ISSUE THREAD

**Issue by cotchiba** [learningequality/kolibri#5324] opened 2019-03-28 11:02 UTC
Learners who answer the questions with one wrong attempt are marked as "need help". Those who haven't answered the question yet are marked as "need help" as well. This can be misguiding data for the coach in terms of determining who really needs support.

![image](https://user-images.githubusercontent.com/49025961/55152810-c9bc2280-5159-11e9-97a8-158576f5086f.png)

**Comment by jonboiser** [comment] 2019-03-28 22:56
Both these behaviors:

1. Learner answers question with 1 wrong attempt
1. Learner hasn't answered the question yet

Should not lead to either a "Needs Help" notification or an entry in the "Difficult Questions" page, generally speaking.

I wonder if there is something unique about this particular multiple choice question that is causing the behavior in the original post.

**Comment by rtibbles** [comment] 2021-08-17 23:22
Not clear what the cause here is or the resolution - closing. Please feel free to reopen with more info.

**Closed as completed by rtibbles** 2021-08-17 23:22 UTC
Labels: bug, TODO: needs clarification
