### ISSUE TITLE
Exercise mastery set at content curator for a channel is not working.

### ISSUE THREAD

**Issue by harishbalachandran** [learningequality/kolibri#1302] opened 2017-04-24 11:25 UTC
## Summary
Exercise mastery set at content curator for a channel is not working. We have set 4 out of 5 model for the exercise.
Channel ID: 7769d932b2cc49efb18c5e665cda64ff
Topic: MG copied
Sub topic: 1 Squares and square roots exercise.

## System information
 - Version: Kolibri 0.4.0alpha4
 - Operating system: Ubuntu 14.04 LTS
 - Browser: Chrome

## How to reproduce

1. Start and exericse with mastery part from 5 check marks. 
2. The mastery applied at the content curator is not working.

## Screenshots
![screen shot 2017-04-24 at 4 46 38 pm](https://cloud.githubusercontent.com/assets/13453618/25334977/924beee0-290e-11e7-9414-e5dd60993c72.png)
![mastrey](https://cloud.githubusercontent.com/assets/13453618/25334983/9884a18a-290e-11e7-8238-97c360123d51.png)
![mastrey 1](https://cloud.githubusercontent.com/assets/13453618/25335026/b79da9c2-290e-11e7-87ce-62e3a3797300.png)
![mastrey 2](https://cloud.githubusercontent.com/assets/13453618/25335028/b8fbcfe2-290e-11e7-972f-a90aa0d4a1f3.png)
![mastrey 4](https://cloud.githubusercontent.com/assets/13453618/25335035/bd693074-290e-11e7-89ad-b3c4c2952a50.png)

**Comment by rtibbles** [comment] 2017-04-25 15:33
@harishbalachandran I have reproduced this behaviour in unit testing, so will investigate further and fix. Thanks for the bug report!

**Comment by rtibbles** [comment] 2017-04-25 15:58
Hrm, retracting that, this is not reproducing - will continue testing to track down where this issue is occurring.

**Comment by rtibbles** [comment] 2017-04-25 18:18
This seems to be a content export issue on the content workshop, have opened a PR to fix it there. Will close this issue once it is live on the production server. @aronasorman please advise when https://github.com/fle-internal/content-curation/issues/229 makes it to production.

**Comment by indirectlylit** [comment] 2017-04-27 16:08
this should be closed now

**Comment by indirectlylit** [comment] 2017-04-27 16:09
please re-export from cc server, re-import to kolibri, and try testing again? thanks!

**Comment by harishbalachandran** [comment] 2017-04-28 12:15
@indirectlylit Sushi chef is under construction for MagoGenie Channel, the minute its ready we will re-export, test this and close it.

**Comment by harishbalachandran** [comment] 2017-05-02 09:18
@rtibbles @indirectlylit Tested, after reimport through Sushi Chef to CC and then to Kolibri, still the mastery is off. It is set 4 out of 5.
**Note:**
Even on the front end we are seeing "Try to get 5 check marks to show up" which is wrong and should read according to the mastery set at the CC.

![mastrey not working](https://cloud.githubusercontent.com/assets/13453618/25611909/6213c3e0-2f46-11e7-8481-5aedf91eac04.png)
![mastrey_](https://cloud.githubusercontent.com/assets/13453618/25611911/6277432a-2f46-11e7-92cd-1cb698d23011.png)
![mastrey](https://cloud.githubusercontent.com/assets/13453618/25611910/626da81a-2f46-11e7-83a9-1930878e48de.png)

**Comment by rtibbles** [comment] 2017-05-03 17:44
With the latest imported content from the CC server, this is now working as intended.

**Closed by rtibbles** 2017-05-03 17:44 UTC
Labels: DEV: backend, DEV: cc server, DEV: frontend, TASK: bug

**Comment by harishbalachandran** [comment] 2017-05-04 12:22
We too Retested and found it to work. Thanks!
![1302_1](https://cloud.githubusercontent.com/assets/13453618/25703234/579b237e-30f2-11e7-939d-ae738a067e13.png)
![1302_2](https://cloud.githubusercontent.com/assets/13453618/25703238/5b5b5fce-30f2-11e7-86de-a47d8e7af563.png)
