### ISSUE TITLE
The resource completed dialog appears while I am still watching a video

### ISSUE THREAD

**Issue by dylanmccall** [learningequality/kolibri#9348] opened 2022-04-22 23:41 UTC
## Observed behavior

Kolibri understands whether a user has watched an entire video based on how much time they have spent watching it, rather than whether they have reached the end. This means if I seek backwards in a video, Kolibri will believe I have finished the video before I have actually reached the end. That is probably an okay compromise, but it leads to the "Resource completed" dialog blocking the video.

## Expected behavior

Instead, Kolibri should wait until the video is _finished_ before showing the "Resource completed" dialog.

## Steps to reproduce

- Choose a video to watch.
- Watch most of the video.
- Rewind to the beginning.
- Continue watching the video.
- The "Resource completed" dialog will appear before you are finished watching.

![Screenshot from 2022-04-22 16-35-04](https://user-images.githubusercontent.com/132063/164817579-e7fc9196-b816-404e-bb75-afac32c3ccd1.png)

## Context

I reproduced this using Kolibri 0.15.1 with the Kolbiri app for GNOME (https://flathub.org/apps/details/org.learningequality.Kolibri).

**Comment by rtibbles** [comment] 2022-04-25 15:19
This is intended behaviour - I am disinclined to change it, especially as it would require disambiguating between 'finishing' and 'finishing' a resource.

What it does perhaps point to is an issue we have faced before with this kind of modal pop-up, that in some cases not having it is highly detrimental, because learners never move on, and in other cases, it is a pain because it is interfering with a learner's intent to remain within the resource.

At the moment we have managed that with the 'stay here' button which dismisses the modal - there are possibly things that we can do here, but I'd like to hear more direct feedback from users around the interaction.

**Comment by MisRob** [comment] 2022-05-16 11:34
I saw this too while working on the completion dialog and in some cases, it felt confusing and unpleasant disruption of user experience to me. For example, when you watch half of a video, leave, return to the same resource later and start watching it again. If my memory is correct, in such cases the completion dialog would be displayed when I was in the half of watching. I also reported an issue related to this here https://github.com/learningequality/kolibri/issues/8309#issuecomment-919864207, describing similar problems when rewinding videos.

I think this could be solved by improving the condition for considering a video as completed (or at least the condition for showing the completed dialog) to:

1. Time spent watching is equal to video length
AND
2. Was the end of the video reached?

Something like that could also have another benefit that we'd be more sure that someone has really finished the video (rather than watching the first half of it two times)

@rtibbles I don't think this would cause any problems in the areas you described, or am I missing something here?

**Comment by rtibbles** [comment] 2022-05-16 15:21
If the only concern is about when to display the completion modal, perhaps we should have a discrete 'finish' event that a renderer can emit to determine when a user has finished interacting with the resource?

I can see an advantage to this ^ as it means that the completion modal actually shows up more often, as 'completion' is a one time event for any particular user, whereas repeat engagement here could still trigger a modal.

Given that we'd probably need to emit some sort of event from the media player plugin anyway to achieve this, I think this might be the simplest solution.

**Comment by MisRob** [comment] 2022-05-17 07:37
@rtibbles 

> If the only concern is about when to display the completion modal, perhaps we should have a discrete 'finish' event that a renderer can emit to determine when a user has finished interacting with the resource?

'finish' event sounds good. However, I don't think we can separate the completion criteria of accumulated time from showing the dialog completely if that's what this solution implies? I imagine we'd need to take into account accumulated time criteria too otherwise we'd run into UX discrepancies, for example by showing the completion dialog with the completed message "Resource completed" together with points obtained in scenarios when the resource hasn't been completed yet (and thus won't be marked with the "Completed" yellow star icon elsewhere in the app). This could happen for example when a user skips to the end of the video they're watching for the very first time. That's why I was suggesting using a combination of both reaching the end of video ('finish' event?) and accumulated time. It still may not cover all scenarios that could lead to some discrepancies but I imagine it might help with the most common cases?

> I can see an advantage to this ^ as it means that the completion modal actually shows up more often, as 'completion' is a one time event for any particular user, whereas repeat engagement here could still trigger a modal.

That'd be great, yes.

**Comment by rtibbles** [comment] 2022-10-17 18:32
To follow up here - once completion has achieved, we will then wait for the `finished` event to trigger the modal.

**Comment by rtibbles** [comment] 2022-11-08 19:20
Fixed in #9814 - should be released in Kolibri 0.15.9.

**Closed as completed by rtibbles** 2022-11-08 19:20 UTC
Labels: DEV: frontend
