### ISSUE TITLE
Errors in IE11 console when I dismiss the sidebar by clicking outside the "X" button.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#7164] opened 2020-06-24 09:43 UTC
In IE11, there are errors when I dismiss the sidebar by clicking outside it's "X" button while it is shown.

### Observed behavior

1. In IE11, there are errors when I dismiss the sidebar by clicking outside it's "X" button while it is shown.  This is not manifested in Firefox v76 or Chrome v81.
![2020-06-24-wed--v0 14 0-b4--3--ie11 error when sidebar is closed 1](https://user-images.githubusercontent.com/175580/85531823-af654300-b641-11ea-8a72-20862fe1018a.gif)

2. Another issue is that the IE11 debugger fires up and prevents further interaction to the page untill I click on the `Continue` button.  I checked and the Debugger setting is `Break on unhandled exceptions` but I do not remember setting it.
<img width="1016" alt="Screen Shot 2020-06-24 at 5 29 02 PM" src="https://user-images.githubusercontent.com/175580/85530437-842e2400-b640-11ea-9322-6ee76ade396e.png">

### Expected behavior
No errors must show when I dismiss the sidebar by clicking outside it's "X" button.

### User-facing consequences
With this error, a user cannot proceed in using Kolibri with IE11, specially if the Debugger setting above is the default.

### Errors and logs
[daemon.txt](https://github.com/learningequality/kolibri/files/4824512/daemon.txt)
[ie11-console-3.txt](https://github.com/learningequality/kolibri/files/4824515/ie11-console-3.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4824516/kolibri.txt)

IE11 error/s in console.
```
...
HTML1300: Navigation occurred.
File: learn
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: learn, Line: 127, Column: 11
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: learn, Line: 128, Column: 11
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: learn, Line: 129, Column: 11
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: learn, Line: 130, Column: 11
HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
File: learn, Line: 131, Column: 11
Kolibri Modules: kolibri.plugins.learn.app registered
TOPICS_TOPIC
SCRIPT5007: Unable to get property '$el' of undefined or null reference
File: kolibri.core.default_frontend-0.14.0b4.js, Line: 1, Column: 1579009
```

### Steps to reproduce
1. Get the [Kolibri Windows installer for v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
1. Use a Windows 7 VM and setup 1 learner using IE11.
1. Login as that learner user and then show the sidebar.
1. Try to dismiss the sidebar by clicking outside of it's window.
1. Notice the error shown in IE11 console, and also the Debugger is shown and the user cannot proceed.

### Context
* Kolibri version: [v0.14.0-beta4 on BuildKite](https://buildkite.com/learningequality/kolibri-python-package/builds/1217#98d2bb86-c7ea-46c1-b95f-903a296e3e1d)
* Operating system: Windows 7 VM
* Browsers: Firefox v76, Chrome v81, and IE11
* Python: v3.6.8

**Comment by radinamatic** [comment] 2020-06-29 23:32
@cpauya Can you replicate this _without_ having the debugger running?
Or better, what is the user-facing consequence for those who are NOT trying to debug? :slightly_smiling_face: 
Are they blocked in any way?

**Comment by cpauya** [comment] 2020-06-30 06:15
Nope, I didn't enable (or touch) the debugger @radinamatic - I'm using the stock IE11 in a Win7 VM.  That's why I'm stumped with it coz it just went into debug-mode when it encountered an error.

I asked @mrpau-richard and @mrpau-julius if they can reproduce it when testing v0.14.0-beta7.

**Comment by cpauya** [comment] 2020-06-30 08:25
Ha! It only debugs when the "Developer Tools" window is shown!  (makes sense)

Here's how v0.14.0-beta7 behaves on IE11 when it is shown and when it is not.
![2020-06-30-tue--1--test v0 14 0-b7--ie11 debugger issue](https://user-images.githubusercontent.com/175580/86102284-e5953d80-baed-11ea-8d12-1433783118a2.gif)

So I guess as long as the "Developer Tools" window is not shown we won't have this issue. 😸

**Comment by mrpau-richard** [comment] 2020-06-30 09:28
@cpauya I can't reproduce this issue on Windows 7 even if the console log shown I'm using Kolibri 0.14.0 beta 7 released
![temp1](https://user-images.githubusercontent.com/8663934/86109347-de266200-baf6-11ea-8318-a786089a87aa.gif)
No errors display on the console log when I do the test.

**Comment by radinamatic** [comment] 2020-06-30 12:12
Thanks for trying to replicate and confirm!
It makes sense for the tester to keep the debugger open while testing, my concern was to see if there are any visible blockers for the end users. Let's close this for now since it seems not extant on beta7, and reopen if you notice an actual end-user-facing consequences again.

**Closed as completed by radinamatic** 2020-06-30 12:12 UTC
