### ISSUE TITLE
Eager task polling on Device=>Channels (every second)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6459] opened 2020-01-13 22:36 UTC
### Observed behavior

On an idle system, the task API is polled every second per browser login session.

This generates large log files on the server.

### Expected behavior

Throttle this? Decrease polling interval?

### User-facing consequences

None

### Errors and logs

Here is a uwsgi.log:

```
[pid: 876|app: 0|req: 30/251] 127.0.0.1 () {52 vars in 1046 bytes} [Mon Jan 13 22:32:15 2020] POST /api/tasks/tasks/deletefinishedtasks/ => generated 2 bytes in 1743 msecs (HTTP/1.0 200) 5 headers in 143 bytes (1 switches on core 0)
[pid: 877|app: 0|req: 221/252] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:17 2020] GET /api/tasks/tasks/?1578954737641=1578954737641 => generated 133 bytes in 66 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 877|app: 0|req: 222/253] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:18 2020] GET /api/tasks/tasks/?1578954738750=1578954738750 => generated 133 bytes in 64 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 877|app: 0|req: 223/254] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:19 2020] GET /api/tasks/tasks/?1578954739755=1578954739755 => generated 133 bytes in 64 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 877|app: 0|req: 224/255] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:20 2020] GET /api/tasks/tasks/?1578954740762=1578954740762 => generated 133 bytes in 61 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 876|app: 0|req: 31/256] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:21 2020] GET /api/tasks/tasks/?1578954741767=1578954741767 => generated 133 bytes in 64 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 877|app: 0|req: 225/257] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:22 2020] GET /api/tasks/tasks/?1578954742773=1578954742773 => generated 133 bytes in 1251 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 876|app: 0|req: 32/258] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:24 2020] GET /api/tasks/tasks/?1578954744114=1578954744114 => generated 133 bytes in 63 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 876|app: 0|req: 33/259] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:24 2020] GET /api/tasks/tasks/?1578954744787=1578954744787 => generated 133 bytes in 69 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 876|app: 0|req: 34/260] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:25 2020] GET /api/tasks/tasks/?1578954745794=1578954745794 => generated 133 bytes in 63 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 876|app: 0|req: 35/261] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:26 2020] GET /api/tasks/tasks/?1578954746799=1578954746799 => generated 133 bytes in 63 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 876|app: 0|req: 36/262] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:27 2020] GET /api/tasks/tasks/?1578954747805=1578954747805 => generated 133 bytes in 113 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 876|app: 0|req: 37/263] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:28 2020] GET /api/tasks/tasks/?1578954748812=1578954748812 => generated 133 bytes in 64 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 877|app: 0|req: 226/264] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:29 2020] GET /api/tasks/tasks/?1578954749818=1578954749818 => generated 133 bytes in 65 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 877|app: 0|req: 227/265] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:30 2020] GET /api/tasks/tasks/?1578954750820=1578954750820 => generated 133 bytes in 66 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
[pid: 877|app: 0|req: 228/266] 127.0.0.1 () {48 vars in 996 bytes} [Mon Jan 13 22:32:31 2020] GET /api/tasks/tasks/?1578954751823=1578954751823 => generated 133 bytes in 64 msecs (HTTP/1.0 200) 7 headers in 222 bytes (1 switches on core 0)
```

### Steps to reproduce

Log in as admin

### Context

n/a

**Comment by benjaoming** [comment] 2020-01-13 23:10
Maybe this is mitigated by automatically logging the user out?

**Comment by indirectlylit** [comment] 2020-01-14 04:03
The polling is expected behavior. What size log files are you seeing? Are they rotated?

**Comment by benjaoming** [comment] 2020-01-14 09:22
uwsgi.log is not rotated AFAIK, but there could be a mechanism that I'm not aware of. IIRC, servers use a logrotate.d configuration for this, and our command is outside.

Perhaps log rotation is a better, more fundamental answer, but it's also worth being aware of the footprint of the log archive.

Just learned that UWSGI has built-in log rotation, so we could use that? https://uwsgi-docs.readthedocs.io/en/latest/Logging.html#logging-to-files

@jredrejo should we close this issue and implement the rather simple setting above with sane defaults and easy customization?

About size: The log file was growing with one line of ~232 chars per second, testing the above lines gives roughly 1 KB per 4-5 lines... since logging something every second is 3600 per hour, and that's 900 KB per hour... very roughly speaking growing at 1 MB per hour. Does that sound correct?

**Comment by indirectlylit** [comment] 2020-03-18 22:48
Closing this issue as "works as intended". We aren't going to change the frequency of polling unless we migrate to something like websockets (see for example https://github.com/learningequality/kolibri/pull/6638) because this would negatively impact the user experience.

If the amount of logging is an issue, lets either address that in log rotations (as in the PRs referenced above) or find a way to skip logging for specific endpoints that we know will be hit often.

**Closed as completed by indirectlylit** 2020-03-18 22:48 UTC
Labels: TODO: needs clarification, TAG: performance

**Comment by indirectlylit** [comment] 2020-03-18 22:50
It should be noted though that we've had no users complain about log sizes so this is not a priority

**Comment by benjaoming** [comment] 2020-03-19 07:51
> It should be noted though that we've had no users complain about log sizes so this is not a priority

That's because logging isn't working, i.e. doesn't log (API) views :)

I agree with the conclusion.
