### ISSUE TITLE
After fresh install, clicking "view more" in search results jumps the user to the top of the page

### ISSUE THREAD

**Issue by jtamiace** [learningequality/kolibri#6911] opened 2020-05-21 16:14 UTC
### Observed behavior

This issue only occurs the first time the view more button is clicked after installation.

### Expected behavior

The user's place on the page should be maintained, and should not jump to the top of the page

### User-facing consequences

Breaking of attention, increased cognitive load in finding the spot in the search results where they left off

### Steps to reproduce

1. Install Kolibri
2. Install content
3. Search something that has enough results to require a "view more" button
4. Click view more
5. Refresh the page
6. Do another search that requires "view more"

### Context

Kolibri 0.13.3
Android app

**Comment by indirectlylit** [comment] 2020-05-21 19:34
This issue may be more pervasive across the app and routing

**Comment by Lewiscowles1986** [comment] 2020-05-22 21:49
is this JavaScript or URL-based behaviour? If the link source could be shared as well as the URL bar state before and after, that would be great.

**Comment by rtibbles** [comment] 2020-05-22 21:59
This is Javascript based URL-routing behaviour.

**Comment by indirectlylit** [comment] 2020-05-23 00:51
[core/assets/src/router.js](https://github.com/learningequality/kolibri/blob/develop/kolibri/) is responsible for all client-side routing

**Comment by Lewiscowles1986** [comment] 2020-05-23 12:31
document state before and after would also be helpful then.

Btw, it seemed the link took me elsewhere.

https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/router.js

Seems to work.

**Comment by Lewiscowles1986** [comment] 2020-05-23 12:35
One thing that could be done (although it might be "jumpy") would be to add hash-based anchors to items and have /page/2 navigate to /page/2/#page2-top

The reason I use a generic named rather than an ID offset is caching. You don't want to be busting cache for linking page to navigate to a new page as would happen if using a primary key / ID offset.

I still have not observed this behaviour though so I guess I'll need someone to go through and show how to replicate.

**Comment by Lewiscowles1986** [comment] 2020-05-23 12:37
https://router.vuejs.org/guide/advanced/scroll-behavior.html has some hints too

**Comment by Lewiscowles1986** [comment] 2020-05-23 12:39
looks like you're using a new enough vue router to fix as well 

https://github.com/learningequality/kolibri/blob/develop/packages/kolibri-core-for-export/package.json#L33

**Comment by indirectlylit** [comment] 2020-05-23 18:57
Hm right - actually we do already have some of this logic but it was moved out of router.js in b6023ca0c28904a9f4657f796ce04529b3617406: 

https://github.com/learningequality/kolibri/blob/ee081d45526b6a91b5f56e3e807b0a79633c27d9/kolibri/core/assets/src/views/CoreBase/index.vue#L145-L164

> hash-based anchors

That might be an option if we chose to disable hash-based routing. We originally chose not to use "modern" client-side routing for maximal browser support, but that might no longer be a limiting factor.
 
> I still have not observed this behaviour though so I guess I'll need someone to go through and show how to replicate.

If you want to see a related bug that may have the same root cause, check out https://github.com/learningequality/kolibri/issues/6889

In both that case and this one, the user is jumped to the top of a page when they did not expect to be.

I think we need to add some kind of switch which enables or disables the "scroll-to-top" behavior based on whether _from the user's perspective_ they are going "to a new page" or simply updating the content "of the current page". This needs to be somewhat decoupled from whether the URL or route happens to have changed.

**Comment by indirectlylit** [comment] 2020-07-13 23:24
@micahscopes any updates on this?

**Comment by micahscopes** [comment] 2020-07-16 15:58
@indirectlylit So I figured out that this specific issue has to do with what happens when someone blurs (taps out of) the search input field on the Android system browser... when that happens, for some reason the browser decides to scroll to the search field! The search input is focused by default upon navigating to the search results. If you scroll down and tap on the "more" button, it blurs the search input, and jumps back to it.  If you scroll down and hit "more" again a second time, the search input is already blurred, so the scroll jump won't happen again.

I tried finding information about this behavior on Google, but couldn't.  The behavior is reproducible on both Chrome+Android with the current 0.13 Kolibri demo site, and in the 0.14 Kolibri Android beta app.  

I connected to my a Kolibri browser session on my phone via ADB with chromium's remote developer panel, and I tried deleting all of the blur/focus/tap related events I could find, but to no avail.  I think the behavior must be specific to Chrome/Android

A very basic fix would be to blur the search input immediately upon navigating to the search results page.

**Comment by micahscopes** [comment] 2020-07-17 00:31
c.c. @jonboiser 

any thoughts?

**Comment by jonboiser** [comment] 2020-07-20 20:45
Could we see if the problem goes away if we remove this textbox-focusing code in these places. 

https://github.com/learningequality/kolibri/blob/1ab74fc5b5a907ada4592d8ab1f5897886058e19/kolibri/plugins/learn/assets/src/views/SearchBox.vue#L240-L244

https://github.com/learningequality/kolibri/blob/1ab74fc5b5a907ada4592d8ab1f5897886058e19/kolibri/plugins/learn/assets/src/views/SearchPage.vue#L80-L89

> A very basic fix would be to blur the search input immediately upon navigating to the search results page.

If this does fix things on the andorid app, we could apply this conditionally with the `isEmbeddedWebView` helper, but in general we want to keep the auto-focus/auto-select behavior for better UX. However, it might be better to implement it using straight HTML instead of via JS like we do here.

**Comment by pcenov** [comment] 2022-03-23 12:52
@radinamatic this is not extant in 0.15.1 - clicking the View more link always results in showing the rest of the available results. Tested in both Linux/Chrome and Android/Chrome setup.

**Comment by rtibbles** [comment] 2022-03-23 15:43
Closing as no longer extant. Presumably fixed by updates in 0.15.

**Closed as completed by rtibbles** 2022-03-23 15:43 UTC
Labels: P2 - normal, TAG: mobile, APP: Learn, TODO: needs QA re-review
