### ISSUE TITLE
Links run together in the PostSetupModal in Device

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10886] opened 2023-06-21 22:04 UTC
Navigate to the device plugin, and in the postSetup modal, you will see that "Choose another source" and "Add new device" run together

![image](https://github.com/learningequality/kolibri/assets/17235236/f343d220-96e2-46be-8c0c-b03ff0f1ab7b)

**Comment by im-NL** [comment] 2023-06-22 15:53
Just to clarify- we don't want "Add new device" to run, right? Or do we need the two on different lines

**Comment by Shashank245** [comment] 2023-06-23 04:20
Hey @marcellamaki, I was walking around the issue, However due to some unforeseen issues I am not able to set up the project in my local System so, won't be able to reproduce or have a look at the issue, Since it's a small one what changes do you think would be helpful to resolve it, I was thinking about some CSS Changes if that works??

**Comment by MisRob** [comment] 2023-06-28 11:43
Hello @Shashank245, thank you for your interest. Even though we could make some recommendations, I think it'd be best to focus on resolving issues with your environment setup at first so you can test if your changes work or not before you open a pull request which is something that needs to happen in one way or another. We're happy to support you. There's a section dedicated to troubleshooting the development server[ in our Kolibri Discussions](https://github.com/learningequality/kolibri/discussions/categories/q-a-development-server). Please report there and send us as much information as possible. Ideally, you'd try to set up Kolibri from scratch and posted the full terminal output so we can understand what's happening.

**Comment by Shashank245** [comment] 2023-06-30 18:21
Hello @MisRob, I tried searching for the issue and setting up Kolibri from scratch, However I am still not able to do it, maybe because I am not able to completely follow the steps of setting up the development server and my system throws errors while I install and download packages. I think it would be nice if somebody from the contributors would like to go ahead and solve the issue as it still persists. Thank you for the patience and acknowledgement

**Comment by MisRob** [comment] 2023-07-03 06:54
Alright @Shashank245, thank you for your time on this. As mentioned in my previous comment, you're welcome to reach out at any time in ways that I described there and we'll try to help you with the environment setup. Be well

**Comment by Shashank245** [comment] 2023-07-04 16:48
Thank you @MisRob for helping out and acknowledging the issues I faced.

**Closed as completed** 2023-07-18 17:56 UTC
Labels: bug, P0 - critical, DEV: frontend, SIZE: very small
