### ISSUE TITLE
Create Quiz - Channel filter ALL option doesn't bring back all channels if a previous channel filtering is applied

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7604] opened 2020-10-23 08:39 UTC
### Observed behavior

Channel filter ALL option doesn't bring back all channels if a previous channel filtering is applied.

### Expected behavior

Channel filter ALL option must bring back all channels in the list after a previous channel filtering is applied with a specific channel.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

Preconditions: Channels imported, class created
1. Login as a couch user
2. Go to Coach > Class > Plan > Quiz
3. Click the New Quiz button
4. Do a search with some query 
5. After results are displayed use the Channel filter and select a specific channel
6. After the filter is applied select ALL from the Channels filter drop-down

### Context

Kolibri 0.14.3
Device: Raspberry Pi 4
OS: Raspbian GNU, Linux 10
Browsers: Chrome (Latest) + Firefox Latest)

**Comment by jonboiser** [comment] 2020-10-23 21:12
Closing as duplicate of #5882 and others.

**Closed as completed by jonboiser** 2020-10-23 21:12 UTC
