### ISSUE TITLE
reports that exercises were not working in 0.6

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2282] opened 2017-09-25 23:04 UTC
reports from @jtamiace and @laurenlichtman that exercises didn't work

**Comment by laurenlichtman** [comment] 2017-09-25 23:08
Issue identified on Windows10, Chrome, v0.6.0-beta3 - saved locally.
This was the case for Khan Academy exercises and exercises created in Kolibri Studio (used Kolibri Demo 1 to test).

![exercise not appearing](https://user-images.githubusercontent.com/25990164/30835174-e4d34f20-a224-11e7-9a21-ce79ed750dad.JPG)

**Comment by rtibbles** [comment] 2017-09-25 23:12
This appears to be a duplicate of: https://github.com/learningequality/kolibri-exercise-perseus-plugin/issues/106

**Comment by indirectlylit** [comment] 2017-09-25 23:17
cool - let's keep this one open here for now just to track the milestone

**Closed** 2017-09-28 21:12 UTC
