### ISSUE TITLE
Select all users - Incorrect value for the number of selected users

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9632] opened 2022-08-17 09:48 UTC
## Observed behavior
Selecting and deselecting the 'Select all' button after selecting or deselecting a specific user results in incorrect number of users displayed as selected. This is valid for both Facility > Class > Enroll learners and Facility > Class > Assign coaches
This results in minor confusion.

## Steps to reproduce the issue
1. Install the latest 0.16 develop build
2. Go to Facility > Class > Enroll learners or Facility > Class > Assign coaches
3. Select the 'Select all' checkbox and observe the number of the selected users
4. Deselect some of the users and after that select again the 'Select all' checkbox - note that the number of selected users is no longer correct

## Video
https://user-images.githubusercontent.com/79847249/185088853-011d8b9f-0f61-4709-911d-1e16f3ca7256.mp4

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox, Edge

**Comment by pcenov** [comment] 2022-08-17 09:48
@radinamatic

**Comment by camperjett** [comment] 2022-08-27 09:08
Hi @pcenov! Can I take up this issue 😃

**Comment by rtibbles** [comment] 2022-08-29 22:22
This issue is also extant on 0.15.x so should be fixed there.

@camperjett if you would like to take this issue on, you are welcome to. The relevant code is found in the facility plugin in the `UserTable` component: https://github.com/learningequality/kolibri/blob/release-v0.15.x/kolibri/plugins/facility/assets/src/views/UserTable.vue#L208

The issue seems to be caused by not ensuring that the selected users are unique by their id!

**Comment by arishmaurya** [comment] 2022-12-23 02:48
@pcenov can i work on this issue ?

**Closed as completed** 2023-01-13 17:16 UTC
Labels: P1 - important, APP: Facility, DEV: frontend
