### ISSUE TITLE
FUNZA HTML5 Games do not work on iPad2 under v0.12.4

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#5667] opened 2019-06-14 07:39 UTC
### Observed behavior
The Funza Uganda HTML5 Games do not work properly on iPad2 under Kolibri v0.12.4.  It will load the page but the rendering is not correct and the user cannot click the <kbd>Get Started</kbd> button.  See attached image.

### Expected behavior
It should work on iPad2 if we are to support this device.

### User-facing consequences
User cannot interact with the Funza page.

### Errors and logs
N/A

### Steps to reproduce

1. Under Kolibri v0.12.4, import the Funza channel using the `gosim-bajih` token.
1. Open the `Channels > Funza > Funza > Funza Biology` content in the iPad2 simulator.
1. Notice that the page may render under Safari but it's not properly displayed.  It looks zoomed-in and the <kbd>Get Started</kbd> cannot be clicked.
1. I tried re-loading the page or clicking the zoom button, but still the same results.

### Context
* Kolibri version: 0.12.4 under Ubuntu 14.04
* Operating system: iOS9.3 Simulator v10.2.1
* Browser: Safari under iPad2
* Funza Uganda channel using token `gosim-bajih` 
* Testing scenario: https://github.com/learningequality/kolibri/blob/v0.12.4-beta8/integration_testing/features/common/view-all-content-types.feature#L64

![Simulator Screen Shot - iPad 2 - 2019-06-14 at 15 21 05](https://user-images.githubusercontent.com/175580/59491755-075b5c80-8eba-11e9-8542-57968136077c.png)

**Comment by cpauya** [comment] 2019-06-14 09:22
This issue also exists in v0.12.3.

**Comment by indirectlylit** [comment] 2019-06-17 15:37
thank you!

FYI for non-regressions, we generally don't automatically put it into the upcoming release

**Comment by rtibbles** [comment] 2021-08-17 23:54
@radinamatic can we confirm if this is resolved on 0.15?

**Comment by radinamatic** [comment] 2021-08-18 23:52
I am **so NOT** looking forward to testing this on Browserstack, but I see no other choice... 😒

**Comment by rtibbles** [comment] 2021-08-18 23:55
Bringing joy everywhere I go, as usual!

**Comment by radinamatic** [comment] 2021-08-30 11:03
Currently Funza games hashi is giving 404 on Kolibri Beta server, but that seems to be the case for [all HTML resources on `kolibri-beta.learningequality.org`](https://github.com/learningequality/kolibri/issues/8356)... 😕 

![Dashboard - Google Chrome_004](https://user-images.githubusercontent.com/1457929/131329018-f943a994-58c7-4a6a-8d09-4f5353a4ddff.png)

![Funza Chemistry - Kolibri QA Channel - Kolibri — Mozilla Firefox_001](https://user-images.githubusercontent.com/1457929/131329803-ee24aa7f-0aa2-41e5-9107-3fe3b9fc6486.png)

**Comment by pcenov** [comment] 2022-03-24 14:39
@radinamatic the game is working fine now in 0.15.1 on iPad Pro simulator:
![2022-03-24_16-36-53](https://user-images.githubusercontent.com/79847249/159940685-ea4875e9-19e2-4120-9792-bb1fca98c657.png)

**Comment by radinamatic** [comment] 2022-03-24 20:13
iPad Pro has a new OS than what was the issue iniatially right?

> Operating system: iOS9.3 Simulator v10.2.1
> Browser: Safari under iPad2

**Comment by radinamatic** [comment] 2022-03-24 20:14
Although I'm not sure if we are aiming to support Funza content on these old iPad tablets... 🤔

**Comment by rtibbles** [comment] 2022-03-25 16:18
I think it's more of a data point, to see if it runs or not. My assumption is that it will run, given the original issue description.

**Comment by rtibbles** [comment] 2022-04-27 22:24
Let's close this, as it does not seem to be an issue. And even if it is, it's probably Funza specific.

**Closed as completed by rtibbles** 2022-04-27 22:24 UTC
Labels: bug, P2 - normal, OS: iOS, safari
