### ISSUE TITLE
Some channel in Kolibri central server failed to import.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#2692] opened 2017-11-27 09:56 UTC
### Observed behavior

* I try to import the `PHET Interactive Simulations` channel from the `Kolibri central server`, But after click the `import` button, I automatically see the message `finished click close button to see the changes` and after that I didn't see that channel successfully imported.

### Expected behavior

* it would be good to show a message that the channel failed to import in kolibri.

### Errors and logs

Here's the  [server.log](https://github.com/learningequality/kolibri/files/1505304/server.log)
![screen shot 2017-11-27 at 4 27 54 pm](https://user-images.githubusercontent.com/8663934/33260761-dad04912-d39b-11e7-9e88-7e3a6e248c4e.png)
![screen shot 2017-11-27 at 4 27 16 pm](https://user-images.githubusercontent.com/8663934/33260773-e60a5304-d39b-11e7-9798-6dec05184308.png)

### Steps to reproduce

Install the [Kolibri 0.7.0](https://github.com/learningequality/kolibri/releases/download/v0.7.0-beta1/KolibriSetup-0.7.0.dev020171123015730_git.exe) in WIndows 7 32 bit. After the installation create an admin account and try to import the channel `PHET Interactive Simulations`.

### Context

* Kolibri version: 0.7.0
* Operating system: Windows 7 32 bit.
* Browser: Google chrome Version `62.0.3202.94 (Official Build) (32-bit)`

**Comment by indirectlylit** [comment] 2017-11-27 17:39
@aronasorman @jonboiser @lyw07 I don't see a server error here. Any idea what's happening?

**Comment by jonboiser** [comment] 2017-11-27 18:14
@mrpau-richard Would you mind trying this process again and sharing the logs from:

1. START - Clicking "select all" to choose all of Phet (logs should have one GET request to `filesizes` endpoint)
1. END - Clicking "close" after you reach finish. (logs should have request to `canceltask` endpoint).

I see a lot of extra activity in the log, including a download of Khan Academy (en), so just wanted something cleaner.

I've personally never seen the progress bar go beyond the "preparing" stage, so I'm surprised Richard got to the "finish" state.

In the logs, it seems like the download actually finished, though. What _should_ have happened is that after clicking close the channel list should have been refreshed. Here are some possibilities:

1. The Channel did get added, but has (or was annotated as having) zero resources, in which it would have been filtered out of the "Content" list.
1. The logic for refreshing the channels after clicking "close" was somehow modified (although in manual testing, it still seemed to work properly for deleting channels).

**Comment by lyw07** [comment] 2017-11-27 18:39
My understanding is that the problem is probably related to the use of the `remotecontentimport` API. When users select a topic node to import, for example `Physics` in this channel, we need to indeed pass all the node ids under this topic node to `node_ids`. Currently it seems that only this `Physics` topic node id gets passed into the `node_ids` option. Since it is a topic node not a resource node, none of the resources gets imported. If we try to import one resource node, the channel will then be shown in the device page.

**Comment by jonboiser** [comment] 2017-11-27 18:52
@lyw07 How are you able to tell which node_ids were passed to the API?

This is news to me that these APIs are unable to use ContentNodes of type 'topic'. While it's possible to enumerate all of the non-topic ContentNodes on the client side in order to fill the `node_ids` option, this concern seems to be another responsibility that is more appropriately placed on the server-side. In other words, the interface I originally assumed (i.e. `node_ids` and `excluded_node_ids` can take ContentNodes of any kind) should remain.

**Comment by lyw07** [comment] 2017-11-27 19:32
@jonboiser Sorry I think I got confused with another problem. You are right that we need to handle this in the back-end. @aronasorman and I are looking into it now.

**Comment by jonboiser** [comment] 2017-11-27 20:56
Just managed to download some Resources from KA-en (w/o DB locking) and confirmed that the channel does appear after clicking "close"

**Comment by mrpau-richard** [comment] 2017-11-28 02:00
@jonboiser here's the [Server log file](https://github.com/learningequality/kolibri/files/1508263/server.log) as you requested it at https://github.com/learningequality/kolibri/issues/2692#issuecomment-347273848

**Comment by jonboiser** [comment] 2017-11-28 02:03
Thanks @mrpau-richard. @lyw07 @aronasorman Does this log mean that no Resource files were downloaded? Mainly the "Setting the availability of 0 LocalFile objects" part

```
0it [00:00, ?it/s][37mINFO     Setting availability of 0 LocalFile objects based on passed in checksums[0m
INFO:kolibri.content.utils.annotation:Setting availability of 0 LocalFile objects based on passed in checksums
```

**Comment by lyw07** [comment] 2017-11-28 02:06
@jonboiser yes it does

**Comment by indirectlylit** [comment] 2017-11-30 20:25
Just a bump on this... I don't quite understand whether there is still a known unresolved issue?

**Comment by lyw07** [comment] 2017-11-30 20:26
I think the issue should be fixed by https://github.com/learningequality/kolibri/pull/2703

**Comment by indirectlylit** [comment] 2017-12-01 06:20
great, thanks!

**Closed by indirectlylit** 2017-12-01 06:20 UTC
Labels: P0
