### ISSUE TITLE
Unwrapped strings for translation

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#3034] opened 2018-01-05 20:13 UTC
### Observed behavior

`Download content`(ex-media) drop-down has untranslated strings, not present on Crowdin.

`High resolution`, `Low resolution` & `Subtitle`

### Screenshots

![selection_274](https://user-images.githubusercontent.com/1457929/34626412-ce3d8f68-f25c-11e7-889c-5c7486016afc.png)

![selection_292](https://user-images.githubusercontent.com/1457929/34626461-05e55842-f25d-11e7-9f0d-0f7bbf2dc5c8.png)

**Comment by rtibbles** [comment] 2018-01-05 20:13
Duplicate of #2394

**Closed by rtibbles** 2018-01-05 20:13 UTC
