### ISSUE TITLE
Video player not displaying subtitle or speed controls 

### ISSUE THREAD

**Issue by carinediaz** [learningequality/kolibri#5300] opened 2019-03-21 21:40 UTC
### Observed behavior
When playing Touchable Earth videos on the INS tablet (Chrome), I noticed the video player does not display an option for changing the video speed, nor to enable/disable subtitles.

### Expected behavior
video player displays both subtitle and speed control

### User-facing consequences

Not being able to use subtitles can affect learning for users who depend on it, and not being able to speed up the video can result in frustration. 

### Steps to reproduce

From Hack Session 3/21:

* INS Tablet number 20
* Rosetta Stone server
* Test lesson -> Touchable Earth video on Dance.
* Play video
* Observe video player.

### Context

 * Kolibri version: 0v0.12
 * Operating system Android 4.4.4
 * Browser: Chrome
* Tablet model: T1-A21w

**Comment by radinamatic** [comment] 2019-04-03 20:50
Now that @jonboiser mentioned this issue, I can't recall having seen this during that hack session... 🤔 

I had 3 tablets opened from the same INS set, and on all of them I was able to change the speed and load different subtitles when available.

**Comment by radinamatic** [comment] 2019-04-03 20:57
![IMG_20190321_143438581](https://user-images.githubusercontent.com/1457929/55512601-67ab6380-5618-11e9-9097-731cbe5b4e76.jpg)

**Comment by carinediaz** [comment] 2019-04-03 21:24
I was having the issue @radinamatic and @jonboiser and @rtibbles asked me to file it here.

**Comment by jonboiser** [comment] 2019-04-03 21:29
We have had different problems on the instant network schools (INS) tablets during testing on different hardware including video not playing at all (e.g. rasberry pi via ngrok proxy).

I haven't been able to see a crash in Sentry that comes from the video player, so it's possible that the video is simply not playable at an alternate speed and with subtitles and video.js is disabling those features as intended.

Is it possible that the way the videos are served can affect what features Video.js presents as available?

**Comment by jonboiser** [comment] 2019-08-13 21:55
I found that these controls are not accessible by keyboard (but work fine with mouse on Kolibri beta)

Video starts with cursor clicking the play button

![Kapture 2019-08-13 at 14 50 36](https://user-images.githubusercontent.com/10248067/62979981-2606a280-bdda-11e9-90c3-7a1a7e9cb2f2.gif)


1. ❌ 	At the volume control, I can mute by hitting "Enter" or "Space", but arrow buttons do not change anything.
1. ✅ At the speed control, pressing Up or Down does cycle through options
1. ❌ 	At the captions control, pressing up toggles the menu, but pressing UP and Down does not cycle through the options.

**Comment by pcenov** [comment] 2022-03-25 11:27
@radinamatic this is no longer extant in 0.15.1:

![2022-03-25_13-26-25](https://user-images.githubusercontent.com/79847249/160112658-f04d2721-1e47-4856-9f59-c77ee2afdb09.png)

**Comment by radinamatic** [comment] 2022-03-25 15:28
Thank you @pcenov, closing as fixed since the original report!

**Closed as completed by radinamatic** 2022-03-25 15:28 UTC
Labels: bug, TODO: needs clarification, TODO: needs QA re-review
