### ISSUE TITLE
"No exercises are selected" error appears even when the user has selected exercises

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7644] opened 2020-10-29 04:12 UTC
### Observed behavior

An error message stating "No exercises are selected" appears even when the user has selected exercises.

![Screen Shot 2020-10-28 at 9 12 59 PM](https://user-images.githubusercontent.com/73143721/97524657-71b35680-1962-11eb-9421-4ae990e84a58.png)

…

### Expected behavior

The user should only receive an error message if there are no exercises selected.
…

### User-facing consequences

The user may be confused when they see an error message that is contradictory to their behavior.
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. Click on the "Plan" tab at the top of the page.
3. Click on the "Quizzes" tab
4. Click the "New Quiz" button
5. Click on a channel.
6. Click on one or more exercises.
7. Click "continue." 
8. Observe the error message at the top reading, "No exercises are selected."

Note for testing - Scenario in line 23:

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-quiz.feature

…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment] 2020-11-03 20:04
Closing as duplicate of #7536

**Closed as completed by jonboiser** 2020-11-03 20:04 UTC
