### ISSUE TITLE
HTML5 and EPUB reading range not showing on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5655] opened 2019-06-12 02:07 UTC
### Observed behavior
HTML5 reading range not showing on IE11. It only shows on Chrome and Firefox

### Expected behavior
It should also show in IE11 

### User-facing consequences

…

### Errors and logs
This is from IE11, that the reading range is not showing at the bottom side.
![Screen Shot 2019-06-12 at 9 57 33 AM](https://user-images.githubusercontent.com/8663934/59318155-9fa9e380-8cf8-11e9-9aec-3951d17b3760.png)

This is from Firefox the reading range shows at the bottom side
![Screen Shot 2019-06-12 at 10 06 02 AM](https://user-images.githubusercontent.com/8663934/59318469-c6b4e500-8cf9-11e9-8f57-32043018eac2.png)

### Steps to reproduce
* Load an HTML5 exercise on IE11
* Observed that the reading range is not available.

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.0b7
 * Operating system: WIndows 7
 * Browser: IE11

**Comment by mrpau-richard** [comment] 2019-06-13 04:31
This also happened on EPUB exercise 

The reading range on the Chrome browser display properly
![Screen Shot 2019-06-13 at 11 52 15 AM](https://user-images.githubusercontent.com/8663934/59403825-e837ce80-8dd6-11e9-8cf8-fa4f95a08cbf.png)

On the IE11 browser the reading range broken
![Screen Shot 2019-06-13 at 11 51 35 AM](https://user-images.githubusercontent.com/8663934/59403831-f259cd00-8dd6-11e9-8340-b850d36cebe3.png)

**Comment by jonboiser** [comment] 2019-06-26 21:55
In the F12 developer tools while viewing an EPUB, I get an endless stream of these "Permission denied" errors ([sentry link](https://sentry.io/organizations/learningequality/issues/1087623753/?project=1379172&query=is%3Aunresolved&statsPeriod=14d)). They have no traceback and I'm not sure if it's coming from app code or the sentry SDK.

**Comment by rtibbles** [comment] 2019-06-26 22:00
Looks like this might be caused by this? https://support.microsoft.com/en-us/help/3191336/permission-denied-script-error-in-internet-explorer-11

(the epub is running inside an iframe)

**Comment by pcenov** [comment] 2022-03-10 13:33
@radinamatic This issue is still extant in 0.15.1 whit the main difference being that the HTML5 slider is now showing in IE11 but sliding it to the right or to the left doesn't do anything:

https://user-images.githubusercontent.com/79847249/157672124-c6ef90b9-db10-4d13-8ece-343d12f3d7ad.mp4

**Comment by rtibbles** [comment] 2024-01-15 20:55
We have deprecated support for IE11 in 0.16, and will be dropping support in 0.17, so I am closing this as wontfix.

**Closed as completed by rtibbles** 2024-01-15 20:55 UTC
Labels: P1 - important, OS: Windows, ie11, PLUGIN: epub
