### ISSUE TITLE
 Allow learners and coaches to edit their username facility not working.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3458] opened 2018-04-02 11:43 UTC
### Observed behavior
When learner or coach is changing the username that time it is not checking the newly assigned username is exist in the system or not. Refer attached screenshots for more information.

### Expected behavior
It must show error if new username is exist in the system.

### Steps to reproduce
1. Change the username with existing username in the system.

### Context

 * Kolibri version : kolibri 0.9.0
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshot
![newbefore_1](https://user-images.githubusercontent.com/12776071/38195050-1c326d62-3699-11e8-85e1-c4ab6ca7160c.png)
![new2](https://user-images.githubusercontent.com/12776071/38195048-1bcf1f00-3699-11e8-8025-0e7ea684d4bf.png)
![newafter_3](https://user-images.githubusercontent.com/12776071/38195049-1c031616-3699-11e8-856f-f54e8b3ad73d.png)

**Comment by mrpau-eugene** [comment] 2018-04-02 13:03
I think this is a duplicate of this one #3391

**Comment by indirectlylit** [comment] 2018-04-07 20:26
thanks! targeting #3391 to 0.10.0

**Closed by indirectlylit** 2018-04-07 20:26 UTC
Labels: TASK: bug fix

**Comment by swapnil106111** [comment] 2018-05-18 06:44
@rtibbles Tested in Kolibri 0.9.2. It is checking existing username while renaming.
