### ISSUE TITLE
Library and Browse channel - Disproportionately large cards 

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9498] opened 2022-06-08 14:21 UTC
## Observed behavior
When I have a few cards in the Recent section or in Browse channel the cards are being stretched too much and look disproportionately large.

## Steps to reproduce the issue
1. Install the following build: https://buildkite.com/learningequality/kolibri-python-package/builds/5658 from https://github.com/learningequality/kolibri/pull/9222
2. Go to the Library page and/or Browser channel

## Screenshots
![2022-06-08_11-44-27](https://user-images.githubusercontent.com/79847249/172639611-ea575c1a-f6a3-416e-8854-41ed962d16f2.png)

![2022-06-08_11-48-54](https://user-images.githubusercontent.com/79847249/172640163-70035607-baab-44df-8013-b7b988769ab0.png)

## Usage Details
Windows 10 and Ubuntu 20 - Chrome, Firefox

**Comment by radinamatic** [comment] 2022-06-08 14:55
I was trying to figure out from Figma if this was by design when there's only one card in the row, but did not find the confirmation for it... 🤔

**Comment by marcellamaki** [comment] 2022-06-08 14:58
No, this is not by design.... although I am wondering if some of it is a regression due to the screen resolution? It looks like the proportions are more like that than a laptop. I know there are designs for wide screens, and it seems like it maybe got lost ina refactor somewhere. 
@pcenov are you on a large/wide monitor for this testing? (Just so I can identify the area something is going wrong more easily)

**Comment by pcenov** [comment] 2022-06-08 15:05
Yes, 2 of my monitors are 27" and it's definitely easier to spot that there. But it's definitely the first time I'm seeing it so I decided to report it. :)

**Comment by marcellamaki** [comment] 2022-06-08 15:10
That makes sense -- it is a regression. And knowing that it's appearing there (whereas it isn't on my laptop) helps narrow down the problem. Thank you! 😊

**Comment by rtibbles** [comment] 2022-10-18 17:36
Fixed in #9774

**Closed as completed by rtibbles** 2022-10-18 17:36 UTC
Labels: P1 - important, APP: Learn, DEV: frontend
