### ISSUE TITLE
Export on device percentage bar and percentage label  is not displaying the normal behaviour

### ISSUE THREAD

**Issue by Pursottam6003** [learningequality/kolibri#10615] opened 2023-05-02 08:36 UTC
## Observed behavior

When I was trying to import the channel resources and tried to export on my local device volume2 It shows the unexpected behaviour 

I have recorded the video and hope it helps to understand the `bug`

[export option.webm](https://user-images.githubusercontent.com/81693090/235612770-ff541a53-ff33-4c9d-aafd-e0d95bb0cb03.webm)

## Errors and logs

The percentage bar is not synced with the percentage label and the percentage label is out of 100% 

## Expected behavior

The percentage bar and label should be under `100 percent `only 

## User-facing consequences

It's very difficult for users to understand the progress of exported resources and how much it needs wait to complete the whole process

## Steps to reproduce

1. Navigate to Device > Channels  
2. Click on the import button 
3. Use the imported resources from Kolibri Studio online 
4. Import any resources  channel
5. Export the channel  resources in your local volume

## Context

…

**Comment by rtibbles** [comment] 2023-05-22 23:36
Duplicate of [#5501](https://github.com/learningequality/kolibri/issues/5501)

**Closed as completed by rtibbles** 2023-05-22 23:36 UTC
