### ISSUE TITLE
after updating a channel, mark the new resources on the 'import more' page

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6227] opened 2019-12-05 17:51 UTC
### Observed behavior

currently, after updating we navigate to the tasks page, as in https://github.com/learningequality/kolibri/issues/6068

### Expected behavior

for updating channels specifically, I would expect that we use the "old" behavior of going to the "import more" page if new resources are available

thoughts @jonboiser @khangmach?

### User-facing consequences

in order to take advantage of new resources after an update, user needs to navigate back to channel

### Steps to reproduce

* publish a channel
* import
* add a new item
* upgrade it

### Context

0.13.0 beta3

**Comment by khangmach** [comment] 2019-12-05 18:12
This seems wrong to me if a channel update isn't the only thing in the task queue. If updating a channel is the first item in a long queue and you leave your device to do other things you're going to come back to your device suddenly on the new channel listing page losing the ability to monitor your other tasks.

The right approach here seems to me to be:
After a channel update finishes the call to action can be a 'Go to channel' which can replace 'Clear' only once until the user clicks on it (if you navigate back it becomes 'clear'. Or this can be another secondary btn living to the left of 'clear' btn

**Comment by indirectlylit** [comment] 2019-12-06 22:56
another point of reference in https://www.notion.so/learningequality/Newly-added-videos-on-Studio-not-imported-during-upgrade-flow-3fd8f75d381e47278343c178bfa69113

> "Newly added videos on Studio not imported during upgrade flow"
> 
> 1. Create new channel in Studio
> 2. Add stuff with no topic folder, publish.
> 3. Import by token to Kolibri
> 4. In Studio - go back and create a Topic and add stuff to it.
> 5. Publish and import to Kolibri
> 
> I did this - the things I added in the new topic did not appear in Kolibri after completing the upgrade flow

**Comment by khangmach** [comment] 2019-12-16 20:26
**Updated flow:**
1. go to a channel
2. trigger an update, which introduces “additional items available”
3. stay in ‘import more’ screen
4. queue additional items from current channel for import
5. go to task manager
6. exit task manager, and queue items from anywhere

We can do something like this where we take the progress display from the task manager and expose it as a high level update indicator and disable resource selection until the update is complete or cancelled. 

It might be messy having users be able to select resources while an update is in progress (because new resources from the channel listing would be going in and out during the update)
<img width="4880" alt="sample slice" src="https://user-images.githubusercontent.com/25045166/70940365-fc1af200-1ffe-11ea-9c23-ffcd362e7bf8.png">

**Comment by indirectlylit** [comment] 2020-03-24 16:42
reported again here: https://github.com/learningequality/kolibri/issues/6687

We may want to consider also providing an option like:

> * [x] After updating, begin import of all newly available content

**Comment by indirectlylit** [comment] 2020-05-18 20:24
another report here: https://learningequality.slack.com/archives/C0LKF6TRD/p1589820293000800

**Comment by ivanistheone** [comment] 2020-05-29 19:48
## Current Kolibri behavior

Recently @carinediaz and myself, with support from @rtibbles @jonboiser were looking at the UX problems with the UPDATE CHANNEL > IMPORT MORE workflow. Before suggesting workarounds and possible fixes, I wanted to document the current behavior (as of Kolibri 0.13.2).


### Initial state: 
A Kolibri instance has (some subset of) the "old" channel version imported



________


### Scenario 1
As a Kolibri Admin, I want to update the channel  
WHEN a content node has modified files (e.g. a video node stays in place but the associated video file has been updated)

1. MANAGE
2. VIEW CHANGES
3. UPDATE CHANNEL, CONTINUE

no further steps needed because updated file will get automatically downloaded


________


### Scenario 2A
As a Kolibri Admin, I want to update the channel  
WHEN new content node has been added AND the parent topic node has a changed thumbnail

1. MANAGE
2. VIEW CHANGES
3. UPDATE CHANNEL, CONTINUE

no further steps needed because parent node gets added bcs of the thumbnail change

Comment: This can be considered either a as a bug (according to the current design) or a feature (for users whose intent was "import this topic and all future additions to it").



________



### Scenario 2B
As a Kolibri SuAdmin, I want to update the channel  
WHEN new content node has been added

1. MANAGE
2. VIEW CHANGES
3. UPDATE CHANNEL, CONTINUE

the new additions to the topic are not imported automatically, so three further steps are required:

4. MANAGE
5. IMPORT MORE, Kolibri Studio, CONTINUE
6. [x], IMPORT


Comment: This is is the intended behavior, but confusing 

________



### Other (not tested)
Scenario 2C: partially imported (a topic node with 3x videos of which only 2x are imported) [not tested]
Scenario 2D: adding a new subtopic to a topic that contained partially imported children [not tested]




______



### Scenario 3
As a Kolibri Admin, I want to update the channel  
WHEN a new topic node has been added in the root of the channel


1. MANAGE
2. VIEW CHANGES
3. UPDATE CHANNEL, CONTINUE

the new topic was not imported automatically, so the further steps are required:

4. MANAGE
5. IMPORT MORE, Kolibri Studio, CONTINUE
6. [x], IMPORT


_______


The above notes are a good summary of observations from yesterday and today, but interested parties who want to see the workflow in action can check the videos in this playlist:

https://www.youtube.com/playlist?list=PLPGnG5XRmtsdmewsAG1u19xhKiHjkD15n

**Comment by ivanistheone** [comment] 2020-05-29 20:22
### The current content update flow is:
1. MANAGE
2. VIEW CHANGES
3. UPDATE CHANNEL , CONTINUE
---1 to 300 minutes ---
4. MANAGE
5. IMPORT MORE, Kolibri Studio, CONTINUE
6. [x]s, IMPORT


### Problems
 - The need-to-do-IMPORT MORE-after-UPDATE CHANNEL step is not obvious
 - any UI interactions that depend both on steps 1.2.3. and 4.5.6. will be difficult to implement because they straddle a long-running process (the importchannel-and-importcontent where the importcontent will update all nodes previously imported)

### Possible solution
 - Gather all the information needed before the UPDATE CHANNEL is clicked


#  Proposed new content update flow is:
1. go to the channel's "actions" page by clicking MANAGE
2. click VIEW CHANGES and Kolibri displays an tree-of-checkboxes UI:
   <img width="633" alt="step3" src="https://user-images.githubusercontent.com/163966/83540868-e8891800-a4c6-11ea-9e78-dde29d9bd456.png">
3. [x]s (user selects any new content items or topics you might want)
4. UPDATE CHANNEL , CONTINUE
(this triggers a two-step task [update, importcontent ...] where ... is the what the user-selected checkboxes in step )


### Benefits
- Bringing down a 6-step flow to a 4-step flow
- Doing all the user interactions at once
- No need to guess about the user intent (see https://github.com/learningequality/kolibri/issues/6954 ) just show them what they will be getting and ask them what they want (credit @lauradanforth )

### Drawbacks
- Mote complicated step 4. (but OK if users don't mess with the checkboxes and leave them as they are to get the current behavior update now then followup with an IMPORT MORE step later)
- Dev work required to read from and display data from an external DB

**Comment by indirectlylit** [comment] 2020-06-04 20:16
Met with @jonboiser, @rtibbles, and @khangmach. Outcomes:

## Annotating import pages for recently-updated channels

Within the 'import' screen, if the channel was updated, and diff stats are still available because no additional imports (besides update imports) have happened yet, then annotate the import screen with:

- new row in top stats table showing "Newly available resources: #, MB"
- individual resources that have just been made available string on the right: "Newly available"
- individual resources and topics that are currently queued for import with string on right: "Queued for import"

![image](https://user-images.githubusercontent.com/2367265/83805885-7d297c80-a665-11ea-9321-383d316d041f.png)


## Flow after triggering an update



 * If there are *not* new items available after importing:
    * No change in behavior
* If there *are* new items available:
  1. Wait for DB to complete loading with a loading indicator
  2. Go directly to 'import more'


![image](https://user-images.githubusercontent.com/2367265/83805897-84508a80-a665-11ea-8ca5-42b909c3c3ae.png)

**Comment by jonboiser** [comment] 2020-06-09 17:46
## Visual/String Updates
1. Add the "new or updated" label to `ChannelContentsSummary.vue` https://github.com/learningequality/kolibri/blob/0498cfd39a6c1d70e5646470a91b515619d03cd2/kolibri/plugins/device/assets/src/views/SelectContentPage/ChannelContentsSummary.vue#L60
1. To not have to make the `annotateNode` utility more complicated, create a new component to show the Green Dot + "New/ X new" label
1.  somewhere, perhaps in the same component with the green dot, add a message "In queue for import" to also be displayed in the ContentNodeRow

![image](https://user-images.githubusercontent.com/10248067/84183064-2d213000-aa40-11ea-8573-51c4b4a0edea.png)

## Behavior Updates on NewChannelVersionPage

When on `NewChannelVersionPage.vue`, after clicking "Update channel" and confirming on the modal:

1. *If `newResources` (New resources available) is 0`, navigate to the Channels Page
1. *If `newResources` is greater than 0, then 1) stay on this page, 2) show a loading indicator while the updated channels ContentNode rows are transferred, 3) disable the "Update channel" button. When the update is finished, redirect to the "import more" workflow of the the channel that was just updated.
1. (Not in screen

## Behavior updates on SelectContentPage

1.basically, show annotations for new single resources plus resource under a topic, disable checkbox and show message for nodes whose files are being automatically re-imported as part of the channel update.

**Comment by indirectlylit** [comment] 2020-06-10 23:26
great specs, thanks

**Comment by jonboiser** [comment] 2020-06-11 00:11
Added the strings here 15d5e2d4c325caa0b2db629b3113d4f57378d50b
c6dcb747da0d0735c705b8874ad367451eecf948

**Comment by indirectlylit** [comment] 2020-07-23 16:46
## Follow-up from bug bashes

### Observed behavior

The user still doesn't immediately see the results of upgrading a channel, and needs to take quite a few actions to import more:

![2020-07-23 09 41 40](https://user-images.githubusercontent.com/2367265/88314084-47019400-ccc9-11ea-923c-996fbe83b894.gif)

### Expected behavior

user should go directly to the import more screen from the previously-used import source after upgrading a channel which had newly-available items

**Comment by jonboiser** [comment] 2020-07-23 20:57
I renamed this issue to make the new annotation stuff in #7274 the "closing" PR. #7369 is a simpler issue just to fix the post-upgrade navigation issue.

**Closed as completed by jonboiser** 2020-07-23 20:57 UTC
Labels: TAG: ux update, P0 - critical, TAG: user strings
