### ISSUE TITLE
channel management - "last updated" time doesn't update

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1664] opened 2017-06-15 02:32 UTC
Tested using the latest iceqube backend. After re-importing a channel, the 'last updated' time does not change. This is true whether or not the channel was republished on the CC server between imports.

![image](https://user-images.githubusercontent.com/2367265/27162768-eb0ac28a-5137-11e7-9bed-94d7c6bc7a76.png)

**Comment by jonboiser** [comment] 2017-06-20 19:05
@indirectlylit When you re-import, do you delete the channel first?

**Comment by indirectlylit** [comment] 2017-06-20 19:06
no, I didn't try that

**Comment by jonboiser** [comment] 2017-06-20 19:09
I think what you're seeing might be expected behavior. I'm not clear if re-importing a channel actually updates/overwrites the DB it per #1676.

The 'last updated' timestamp will be changed if you delete, then re-download the channel.

**Comment by indirectlylit** [comment] 2017-06-20 19:39
Before 'delete' was a feature, re-importing was the only way to update a channel to the latest state from the CC server. On import:
* the latest version of the DB is downloaded, overwriting the old one. (that's why I expected the 'updated' time to change)
* subsequently, any newly-referenced content is also downloaded

I definitely agree that we need clearer feedback to the user about when updates are available, and whether anything actually changed on re-import.

Until then, I believe the expected behavior from a user's perspective is that the 'last updated' time reflects the last time they imported the channel, whether or not it changed.

**Comment by jonboiser** [comment] 2017-06-20 20:14
@jamalex we talked about extending the logic in `content.urils.annotation.update_channel_metadata_cache` to also handle version bumps. Does this function get called when a content DB is overwritten?

Should the logic be "if version number is higher, then update the last_updated timestamp"?

**Comment by radinamatic** [comment] 2017-07-10 14:57
> Until then, I believe the expected behavior from a user's perspective is that the 'last updated' time reflects the last time they imported the channel, whether or not it changed.

I would also favor this solution until the indicator for a new version on the CC server is implemented. As of now ([`0.5.0-beta1-dev22`](https://buildkite.com/learningequality/kolibri/builds/1673)) , info on that column indicates the time of the very first import (or re-import after the deletion) of the channel, even if the user re-imported it several times after that.

**Comment by jonboiser** [comment] 2017-08-10 19:57
When an `importchannel` command has concluded, it runs `update_channel_metadata_cache`, which actually loops through the whole content metadata folder. It works for new imports because that new metadata db will be part of the loop.

I think to handle channel upgrades correctly, I think there needs to be a function that only updates the one `channel_metadata_cache entry`.

**Comment by rtibbles** [comment] 2017-08-10 20:00
I am tempted to punt this, because this will all be fixed by my open PR on content importing (https://github.com/learningequality/kolibri/pull/1947), and I don't see it as critical for 0.5.x

**Comment by indirectlylit** [comment] 2017-08-10 20:48
agreed

**Comment by rtibbles** [comment] 2017-09-01 19:04
This is fixed in #1947

**Closed by rtibbles** 2017-09-01 19:04 UTC
Labels: TASK: bug
