### ISSUE TITLE
When startremotechannelimport is executed for the first time a 404 error happens

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#5343] opened 2019-04-03 11:28 UTC
### Observed behavior
If a channel has not being imported before, the first time it's selected in /device/#/content/channels
will produce always these two JavaScript errors, visible in the browser console:

```
VM112:1 GET ...../device/api/device_channel/0e173fca6e9052f8a474a2fb84055faf/?include_fields=total_resources%2Ctotal_file_size%2Con_device_resources%2Con_device_file_size&1554230537254=1554230537254 404 (Not Found)

api-resource.js:88 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred {request: {…}, url: "/device/api/device_channel/0e173fca6e9052f8a474a2f…2Con_device_file_size&1554230677759=1554230677759", raw: XMLHttpRequest, status: {…}, headers: {…}, …}
```
Selecting the channel for the second time does not produce the errors, as the database already has the information needed to answer the `/device/api/device_channel/0e173fca6e9052f8a474a2fb84055faf/?include_fields=total_resources%2Ctotal_file_size` request

### Expected behavior
It seems the channel resources are retrieved before the database has that information. 
This should not be happening.

### User-facing consequences
Errors in the browser console

### Steps to reproduce
1. Go to /device/#/content/channels
2. Open the browser console using devtools
3. Click on the select button for a channel that has never been explored before in that Kolibri installation

### Context
Seen in kolibri 0.12.2
Using Chrome and Firefox

**Comment by jonboiser** [comment] 2019-04-03 17:06
I've noticed this too when looking at #5228.

If you look at the order the code is _supposed_ to be executed, I'm pretty sure no calls should be made to device_channel before the channel metadata has been added to the DB, etc.

My suspicion is that this might be one of those premature execution of `then` callbacks we've seen with ConditionalPromises.

On the other hand, I'm not sure if this happened before device_channel was introduced, so maybe it lags behind the old `/channel` endpoint somehow?

**Comment by rtibbles** [comment] 2019-04-03 17:13
Are there any places where we still use a shared `pageState` at the top level? If we've modularized everything to the point where we are not doing this, we may be able to phase out the conditional promise completely.

I suppose the other way of asking this is 'where do we still use samePageCheckGenerator' and the `only` method?

**Comment by jonboiser** [comment] 2019-04-03 17:18
We use `samePageCheckGenerator` almost exclusively in the `handler.js` files, so they are meant to guard the final state-setting step in handler functions used in Vue Router (and make sure that the state-setting mutation happens only if you are in the same exact location when the network  requests kicked off).

And there is no more top-level polymorphic `pageState` used in our vuex.

It'd be nice to phase out conditional promise (or make them opt-in specifically for the handler functions), but I still think the original motivating problem is still around after moving to vuex modules.

You can still have a situation where if you quickly go back and forth to a page, that successive responses from the server will re-write what is in vuex/on-page.

**Comment by rtibbles** [comment] 2019-04-03 17:22
As our handler functions are just Vue Router entry guards - maybe the solution is to allow them to implement optional 'exit' guards that prevent any state setting from occurring after exit has happened?

**Comment by jonboiser** [comment] 2019-04-03 17:36
Yeah, if you can detect within the handler that you have exited the router location (the same way `samePageCheckGenerator` inspects that you have exited via the `pageSessionId` getter in Vuex), then we can cancel the handler function.

My more radical preferred solution is to move away from using handlers and do data fetching within components in the router lifecycle hooks. My thinking is that once a component is destroyed (by leaving a route), then any slow asynchronous calls only update a destroyed component (if anything) and you avoid the unexpected update problem.

**Comment by rtibbles** [comment] 2019-04-03 17:52
> My more radical preferred solution is to move away from using handlers and do data fetching within components in the router lifecycle hooks. My thinking is that once a component is destroyed (by leaving a route), then any slow asynchronous calls only update a destroyed component (if anything) and you avoid the unexpected update problem.

This makes sense to me, and means that vuex state is only used for truly shared state (i.e. something that would not cause render errors if it was updated by a previous async call).

I guess the main complexity this might introduce would be the right granularity of where to make the fetches, and then handling loading states - but this would have the advantage of not wiping out most of the page with a loading state, as we currently do. We might also want to lean on the `provide`/`inject` API for easily passing down data to the child components at arbitrary depths.

**Comment by indirectlylit** [comment] 2019-04-03 22:10
> My more radical preferred solution is to move away from using handlers and do data fetching within components in the router lifecycle hooks. My thinking is that once a component is destroyed (by leaving a route), then any slow asynchronous calls only update a destroyed component (if anything) and you avoid the unexpected update problem.

This logic makes sense to me too, even though it goes against some intuitions I've had for a while about client-side routing and vuex actions. Let's give it a try and see how it feels!

One thing to watch out for is that the components are _actually_ destroyed, and not re-used by some vue optimization that might bite us... or that the components are kept around in memory until the promises resolve, in which case any shared global observables will be updated exactly like they were with vuex.

> We might also want to lean on the `provide`/`inject` API for easily passing down data to the child components at arbitrary depths.

Maybe, if the object being provided/injected is an Observable. If it's not, making the state reactive [takes some hoop jumping](https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/KGrid/index.vue#L100-L121).

Overall my main fear of moving too far in the direction of shared global observables is losing the 'debuggability' of one-directional data flow: if any child component can modify global state at any time, might we end up with difficult-to-debug side effects and hard-to-understand timing issues?

**Comment by indirectlylit** [comment] 2019-04-03 22:22
> `samePageCheckGenerator`

Just to throw out another option: I've been thinking that a clean way to solve this general problem might be:

* have the router provide a monotonically increasing `currentPageID` for every navigation event
* optionally (for page-dependent requests), pass in the `currentPageID` as a custom header to the API from the resource layer
* provide middleware in the Django API to reflect the ID back in responses
* if a resource layer receives a response with an ID that does not match the current page... transform the response into some kind of 'stale response' error?

**Comment by rtibbles** [comment] 2019-04-04 17:32
Adding it to the request and expecting the server to handle this seems unnecessary and inefficient.

All requests are being initiated and resolved within a functional scope on the frontend, so I don't see much need to bring the server into this at all.

**Comment by indirectlylit** [comment] 2019-04-04 22:21
🤔 I really doubt it would have any noticeable overhead. There might be more elegant solutions but reflecting an ID back to help the client track its own bookkeeping might be an easier refactor of `conditionalPromise` rather than moving all our state to components

**Comment by rtibbles** [comment] 2019-04-05 17:22
One significant issue is that it would make every request to the API uncacheable, because each response would need to be modified to reflect the request header value.

This would add significant overhead to the server, as our most frequently requested API endpoints are the ones relating to content, which are the ones that we currently cache most aggressively.

Again, all of these requests are happening in the client side where the current page id, by whatever metric, is easily accessible, there is no need to reroute it via the server as it will always be possible to tie it to the promise in question, so this is  unnecessary, and placing an undue load on the server.

**Comment by rtibbles** [comment] 2019-04-05 17:23
(note that what I am saying is completely independent of a refactor to component level state - in fact the samePageCheckGenerators are currently a less abstract way of achieving what I am suggesting, in a completely clientside manner).

**Comment by indirectlylit** [comment] 2019-04-06 18:36
>  it would make every request to the API uncacheable

Yeah very good point.

All of these ideas are just working around the fact that native JS promises can't be cancelled. Looks like the latest generalized solution is the new `AbortController`:

* https://developer.mozilla.org/en-US/docs/Web/API/AbortController
* https://dom.spec.whatwg.org/#aborting-ongoing-activities

Something like that would let us tear-down outstanding requests on either component lifecycle hooks or router navigation guards.  No stale responses, no problems.

**Comment by rtibbles** [comment] 2019-04-06 18:45
Although, this is only for fetches, not promises. If we want to implement cancellation of the fetch themselves, we can already do that with our existing client. The issue is that the only way to communicate this cancellation through a Promise is with a rejection, so we still have to handle that in the code that deals with the results of the fetch, much as we have to do currently.

The issue still is that the Promise itself cannot be cancelled.

**Comment by indirectlylit** [comment] 2019-04-06 19:31
[Rejecting the promise](https://www.bram.us/2017/12/13/cancel-a-javascript-promise-with-abortcontroller/) with an abort error wouldn't help?

**Comment by rtibbles** [comment] 2019-04-06 19:43
You would still need to handle the abort error in every handler with a specific catch, so it still comes down to per handler logic.

**Comment by indirectlylit** [comment] 2019-04-06 19:53
or just handle it once in `handleApiError`?

**Comment by rtibbles** [comment] 2019-04-06 19:54
Which has to be applied per handler.

**Comment by indirectlylit** [comment] 2019-04-06 20:34
* storing state in transient components instead of global state
* cancellable promises
* same-page check and conditional promises
* page IDs that get reflected back from the server

they’re all implementing sort of ‘context management’ based on client-side routing... If we allow the resource layer to have knowledge of the router, a simple API might look something like

```javascript
const routeContext = router.getContextId();
SomeResource.fetch(..., routeContext);
```

If any resource promise might have resolved but the `routeContext` no longer matches the current router context ID, the promise would be rejected with an `AbortError` and `handleApiError` would silently throw it away.

**Comment by rtibbles** [comment] 2019-04-06 21:31
Could probably just implement it as a 'cancel on route' flag, because it should be able to get the context directly from the router.

Just have to make sure that things don't go wrong when there are additional async invocations inside the promise resolution as otherwise the fetch could resolve, and then the route is exited, but further async processing would continue.

**Comment by rtibbles** [comment] 2019-11-16 15:35
Unable to replicate this specific issue on current develop. @jredrejo could you confirm?

**Comment by jredrejo** [comment] 2019-11-16 19:19
@rtibbles I have just replicated it in a fresh clean develop build:
1. `KOLIBRI_HOME=/tmp/kk1 kolibri start --foreground` to start a  new kolibri home instance
2. After finishing the first run wizard, went to channels, open Chrome Dev tools and click on the button "Select Resources" to begin to import the channel `TESSA - Teacher Resources` (first one in my list)
3. As usual, the 404 error with http://localhost:8080/device/api/device_channel/a9b25ac9814742c883ce1b0579448337/?include_fields=total_resources%2Ctotal_file_size%2Con_device_resources%2Con_device_file_size&1573931176014=1573931176014 appeared

![image](https://user-images.githubusercontent.com/1008178/68998024-32087180-08ad-11ea-8af4-9ac4b42f431b.png)

So the error keeps happening the first time the channel is selected. If I don't import anything, and restart the server and do the same, the error does not happen.
It's important to notice that the error happens  **before** `startremotechannelimport` is executed for the first time, as you can see in the next screenshot:

![image](https://user-images.githubusercontent.com/1008178/68998078-ce327880-08ad-11ea-89f9-9ecfa8d4d9a2.png)

Also, importing works correctly afterwards, currently there is not user-facing effects of this bug.

**Comment by rtibbles** [comment] 2019-11-16 20:05
Hrm - isn't this intended behaviour? The `404` is what is telling us that we need to initiate the channel import task.

**Comment by jredrejo** [comment] 2019-11-16 20:49
I don't know. Previously importing didn't work after this error. Now it does.

If this is the mechanism used to trigger importing, perfect. 
My only concern is that a 404 uses to trigger the attention and is interpreted as an error. It happened to me and I have seen it reported by some tech users too.

**Comment by indirectlylit** [comment] 2019-11-16 22:40
A similar thing happens on password-less sign-in: we use a 400 as part of normal server/client communication to indicate the need for a password, but this is reported back in the console as an error.

On one hand, it is technically fine to use HTTP response codes as part of normal application logic. On the other hand, having these in the client logs risks causing devs to ignore real errors, because they might think they're part of normal app logic...

**Comment by rtibbles** [comment] 2019-11-17 04:58
We could reduce the occurrence of 404s in this instance, as frequently we have the data about which channels are actually already imported into the DB in vuex state - it just wouldn't be there if you had refreshed onto this page.

**Comment by indirectlylit** [comment] 2019-12-02 03:00
same 404 reported as bug here: https://www.notion.so/learningequality/404-during-import-from-USB-stick-f0e3114b559a4b23beacb32de346a737

**Comment by indirectlylit** [comment] 2019-12-02 03:31
and again here: https://www.notion.so/learningequality/404-when-trying-to-import-Khan-Academy-Hisabati-Tanzani-bae7f266d1c74e7fb65de7c75e8a0d1a

**Comment by benjaoming** [comment] 2020-04-20 20:42
On the same endpoint `/device/api/device_channel/<id>/`, we have seen HTTP 504 Gateway Timeout on Kolibri UWSGI/proxied installations because the synchronous annotation does not always work.

Dropping this as a note here for now, in case this issue can be fixed/reworked by moving from a synchronous process to an asynchronous.

Quote @rtibbles 

> one issue currently is that the import stats annotation happens synchronously within the first request it is needed, and is then cached for future requests. I can imagine this producing a timeout at some point on a busy machine.

**Comment by indirectlylit** [comment] 2020-06-23 17:07
reported again here: https://github.com/learningequality/kolibri/issues/7046

**Comment by indirectlylit** [comment] 2020-06-23 17:11
considering the frequency with which people see, report, and try to debug this error, we really should at least add logging indicating that it is not an error that people should be concerned about. We should do the same thing for password-free login

**Comment by rtibbles** [comment] 2020-06-29 21:00
Pre-emptive logging added in #7195

**Closed as completed by rtibbles** 2020-06-29 21:00 UTC
Labels: P1 - important, TAG: dev experience
