### ISSUE TITLE
Untranslated strings for Mexican Spanish version of Kolibri

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#2063] opened 2017-08-30 03:16 UTC
## Summary

Strings (typically from hover messages) are still untranslated for the Mx-Es version of Kolibri

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: Kolibri 0.5.0beta10.dev2
 - Operating system: Online demo at unete-demo.learningequality.org
 - Browser: Chrome

## Screenshots
"Fullscreen"
![screenshot from 2017-08-29 20 05 29](https://user-images.githubusercontent.com/5150483/29853806-dc5904b8-8cf6-11e7-8bf8-0db85594d218.png)

"Play"
![screenshot from 2017-08-29 20 05 18](https://user-images.githubusercontent.com/5150483/29853807-dc5d200c-8cf6-11e7-9d5d-04311b53f2cf.png)

"Please fill out this field"
![screenshot from 2017-08-29 20 03 21](https://user-images.githubusercontent.com/5150483/29853808-dc5dd38a-8cf6-11e7-9f6f-041c16e3cc59.png)
![screenshot from 2017-08-29 20 03 08](https://user-images.githubusercontent.com/5150483/29853809-dc6074c8-8cf6-11e7-9a86-7bad57f353ac.png)

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

The strings are well hidden, so it's not critical, but is inconsistent and jarring for the non-English speaker.

**Comment by christianmemije** [comment] 2017-08-30 04:35
Duplicate of #2036

**Comment by christianmemije** [comment] 2017-09-02 00:04
In #2005, HTML5 validation for required fields was removed. So `Please fill out this field` should be replaced by a properly translated validation inline error.

**Comment by christianmemije** [comment] 2017-09-06 22:38
Fixed in #2083 and #2005

**Closed by christianmemije** 2017-09-06 22:38 UTC
