### ISSUE TITLE
unhandled zeroconf-related errors when shutting down kolibri

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6059] opened 2019-11-14 16:32 UTC
# Observed behavior

Got an unhandled error when shutting down kolibri:

```
KeyError: 'e002.kolibri._sub._http._tcp.local.'
```

### Expected behavior

No unhandled errors

### User-facing consequences

unknown

### Errors and logs

```
INFO     Unregistering ourselves from zeroconf network...
INFO     
Kolibri instance 'e002' has left the zeroconf network.

INFO     
Kolibri instance 'e002' has left the zeroconf network.

ERROR:zeroconf:Unknown error, possibly benign: KeyError('e002.kolibri._sub._http._tcp.local.')
Traceback (most recent call last):
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/zeroconf.py", line 1938, in unregister_service
    del self.services[info.name.lower()]
KeyError: 'e002.kolibri._sub._http._tcp.local.'
INFO     Unregistering ourselves from zeroconf network...
```

### Steps to reproduce

Saw this after ctrl+c of the devserver

### Context

* devserver from source
* mac
* zeroconf branch: https://github.com/learningequality/kolibri/pull/6011

**Comment by indirectlylit** [comment] 2019-11-14 21:31
more scary-looking errors:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/Users/d/Projects/le/k013x/kolibri/utils/cli.py", line 386, in _cleanup_before_quitting
    unregister_zeroconf_service()
  File "/Users/d/Projects/le/k013x/kolibri/core/discovery/utils/network/search.py", line 164, in unregister_zeroconf_service
    logger.info("Unregistering ourselves from zeroconf network...")
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1383, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1040, in emit
    self.handleError(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 957, in handleError
    sys.stderr.write('--- Logging error ---\n')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/Users/d/Projects/le/k013x/.venv/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/d/Projects/le/k013x/kolibri/utils/cli.py", line 237, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/utils/cli.py", line 624, in services
    server.services()
  File "/Users/d/Projects/le/k013x/kolibri/utils/server.py", line 153, in services
    block()
  File "/Users/d/Projects/le/k013x/kolibri/utils/server.py", line 162, in block
    time.sleep(100000)
  File "/Users/d/Projects/le/k013x/kolibri/utils/cli.py", line 386, in _cleanup_before_quitting
    unregister_zeroconf_service()
  File "/Users/d/Projects/le/k013x/kolibri/core/discovery/utils/network/search.py", line 164, in unregister_zeroconf_service
    logger.info("Unregistering ourselves from zeroconf network...")
Message: 'Unregistering ourselves from zeroconf network...'
Arguments: ()
```

**Comment by rtibbles** [comment] 2019-11-16 14:38
I note that the shutdown listeners are getting registered in `cli.main` - so these could be triggered by someone running a Kolibri CLI command. These shutdown listeners should only be registered in `run_services` in `server.py` - not sure if this is the cause of the above, but might reduce the risk!

**Comment by indirectlylit** [comment] 2019-11-16 20:51
another one here: https://github.com/learningequality/kolibri/issues/6077

**Comment by micahscopes** [comment] 2019-11-19 00:29
Unfortunately the first message is logged by the zeroconf library, which is doing an `except Exception as e: ...`, and then logging the message :grimacing:.  The question I still have is just how critical it is.  I think it means the zeroconf service has already been unregistered, but I'm not sure why it's attempting to unregister twice.  Maybe because there are two listeners for the cleanup function, in which case it's not a big deal.

**Comment by micahscopes** [comment] 2019-11-21 18:24
I guess those scary looking errors really did live up to their scariness.  Should be fixed here: https://github.com/learningequality/kolibri/pull/6113

**Closed as completed** 2019-11-21 20:48 UTC
Labels: P0 - critical
