### ISSUE TITLE
User list not showing at the IE11 and Microsoft Edge 42.17

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3804] opened 2018-06-14 07:55 UTC
### Observed behavior
User list is not showing at the  IE11 and Microsoft Edge 42.17 browsers.

### Errors and logs
![screen shot 2018-06-14 at 3 32 37 pm](https://user-images.githubusercontent.com/8663934/41398047-a4d97f2e-6fe8-11e8-8eea-0993f0cdd7f9.png)
![screen shot 2018-06-14 at 3 33 04 pm](https://user-images.githubusercontent.com/8663934/41398062-ad1c8b2c-6fe8-11e8-8611-d4354f6ad1aa.png)

At the Firefox It will display.
![screen shot 2018-06-14 at 3 53 38 pm](https://user-images.githubusercontent.com/8663934/41398814-23cfda42-6feb-11e8-926e-fa5d0b5d0591.png)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.10.0b2
 * Operating system: Windows 10
 * Browser: IE11 and Microsoft Edge 42.17.

**Comment by indirectlylit** [comment] 2018-06-14 19:32
thank you!

**Comment by indirectlylit** [comment] 2018-06-21 02:43
@jonboiser would you mind taking a look at this?

**Comment by jonboiser** [comment] 2018-06-25 17:23
Hard to tell on the live site because no source maps, but I think the problem is coming from this line:

https://github.com/learningequality/kolibri/blob/develop/kolibri/plugins/facility_management/assets/src/userSearchUtils.js#L12

Other pages where this utility is used:

* Class List Page - OK
* Class Edit (aka Class Enroll Form) - Same Error
* Manage Permissions Page - Same Error
* Coach Reports - Same Error

**Comment by jonboiser** [comment] 2018-06-25 17:32
It appears IE11 and Edge might not support the `locale` argument used in `String::localeCompare`. Here's a hack to get around it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#Check_browser_support_for_extended_arguments

**Comment by rtibbles** [comment] 2018-06-25 20:51
Fixed in #3887

**Closed as completed by rtibbles** 2018-06-25 20:51 UTC
Labels: P0 - critical
