### ISSUE TITLE
Checking "select all" and then unchecking a selection does not update selections saved

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7645] opened 2020-10-29 04:18 UTC
### Observed behavior

If a user checks the "select all" button when adding exercises to a quiz, and then unchecks one or more of the exercises, the "select all" option does not deselect. This can result in the user having more exercises in the quiz than they intended, as it still selects all of them when they proceed to the next step despite visually having one unchecked.

See screen recording for full ramifications of this:

https://drive.google.com/file/d/1LERa1EbFoJfPdKf1NbWhUKBevWLBi8mh/view

…

### Expected behavior

If a user selects all, and then removes one or more selections, the "select all" button checkbox should revert to being unchecked.
…

### User-facing consequences

The user may continue to proceed with their quiz with more exercises selected than they intended.
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. Click on the "Plan" tab at the top of the page.
3. Click on the "Quizzes" tab
4. Click the "New Quiz" button
5. Click on a channel.
6. Click the "select all" checkbox.
7. Observe that all of the exercises are selected.
8. Uncheck one or more exercises.
9. Observe that the "select all" checkbox is still checked. 
10. Click "Continue"
11. Observe that all of the exercises are still included, even though the user unchecked one or more.

Testing Note: Checking the 'select all' checkbox and unchecking it both work correctly and show the snackbar confirmation. Scenario in line 71 below:

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-quiz.feature 

This issue occurs when trying to remove individual exercises after checking "select all."
…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment] 2020-11-03 20:35
This looks like it has the same root cause as #7536 and others and looks to be fixed in 0.14.4

**Closed as completed by jonboiser** 2020-11-03 20:35 UTC
Labels: TAG: regression
