### ISSUE TITLE
Import - Does not present contents of Export.

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4038] opened 2018-07-17 04:11 UTC
### Observed behavior
When performing import, the select tree should present the contents of the exported file. Instead, it presents the contents of the whole channel.

Storage contains 109 MB

![storage](https://user-images.githubusercontent.com/1372447/42795948-91da0e1c-89b9-11e8-8ed5-555603f32a09.png)

The Global Digital Library, for which the English subtree  was completely exported, shows the whole tree without anything selected.  To be useful, the English subtree should be selected; that is, the actual contents of the export file.
 
![f32c31a9-bca0-4d9b-b5b8-2062d7ce4b17](https://user-images.githubusercontent.com/1372447/42796011-ee870944-89b9-11e8-96f9-94583f063a7c.png)

### Expected behavior
To be useful, the English subtree should be selected; that is, the actual contents of the export file.

### User-facing consequences
Confusion.
Inability to control what gets imported.

### Steps to reproduce
Perform an import from a local file

### Context
 * Kolibri version .10
 * Linux Manjaro
 * Vivaldi browser

**Comment by indirectlylit** [comment] 2018-07-18 00:01
thanks @nobicycle - this is unfortunately a known limitation of the current implementation. We are exploring ways of improving the user experience.

You can navigate down the tree and when you get to a topic level you'll see that the content is not there. However obviously that's not a very effective work-around.

**Comment by indirectlylit** [comment] 2018-07-18 00:06
cc @jonboiser @rtibbles we should do an audit of issues related to availability and file sizes

**Comment by indirectlylit** [comment] 2019-05-15 23:23
solution is rather complex. updating milestone to 0.13.0 so this doesn't become a blocker for 0.12.4

**Comment by lyw07** [comment] 2019-06-20 22:05
seems to be a duplicate of https://github.com/learningequality/kolibri/issues/3269

**Comment by indirectlylit** [comment] 2019-06-29 01:58
Yes, I believe so. @nobicycle if these are different, please let us know.

**Closed as completed by indirectlylit** 2019-06-29 01:58 UTC
Labels: P1 - important
