### ISSUE TITLE
Using content command to move kolibri content does not update properly the options.ini file

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#10671] opened 2023-05-10 10:10 UTC
## Observed behavior

When the command to move content is used, like 
`C:\windows\system32>kolibri manage content movedirectory k:/kolibri`
or
`kolibri manage content movedirectory /tmp/kkk`

the content is moved, but options.ini is not correctly configured and the command fails

## Errors and logs

```
....
    self.update_config_content_directory(dst)
  File "c:\python36\lib\site-packages\kolibri\core\content\management\commands\content.py", line 140, in update_config_content_directory
    update_options_file("Paths", "CONTENT_DIR", dst, KOLIBRI_HOME)
  File "c:\python36\lib\site-packages\kolibri\utils\options.py", line 872, in update_options_file
    conf.write()
  File "c:\python36\lib\site-packages\kolibri\dist\configobj.py", line 2128, in write
    with open(self.filename, 'wb') as h:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Hombro\\.kolibri'
```

or 
```
.....
  File "/datos/le/mio/kolibri/kolibri/core/content/management/commands/content.py", line 104, in migrate
    self.update_config_content_directory(dst)
  File "/datos/le/mio/kolibri/kolibri/core/content/management/commands/content.py", line 141, in update_config_content_directory
    update_options_file("Paths", "CONTENT_DIR", dst, KOLIBRI_HOME)
  File "/datos/le/mio/kolibri/kolibri/utils/options.py", line 967, in update_options_file
    conf.write()
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/configobj.py", line 2128, in write
    with open(self.filename, 'wb') as h:
IsADirectoryError: [Errno 21] Is a directory: '/tmp/merge'
```

## Expected behavior
The command should ends updating correctly the `options.ini` file

## User-facing consequences
Users can't move content using this command

## Steps to reproduce
Either on windows or linux, executing the above commands

## Context
Checked in kolibri >= 0.15.x

**Comment by rtibbles** [comment] 2023-05-10 15:21
This is a duplicate of https://github.com/learningequality/kolibri/issues/10112

**Closed as completed by rtibbles** 2023-05-10 15:21 UTC
Labels: P1 - important, TAG: regression
