### ISSUE TITLE
Not able to see protractor question exercises in tablet

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#2682] opened 2017-11-23 10:53 UTC
### Observed behavior
In the KA resource, the protractor isn't visible on the tablets, although we can see the up and down arrows which is used to move the protractor upside down. This issue is only occurring on tablets.

- Channel ID: 8fc515793aad4e52b490b03c48ad21de -Maharahstra State English Medium
- Path of the topic: BalBharati---> Class 5 --->Angles---> KA Resources
- Exercise name: Measure angles

### Expected behavior
It must show whole protractor image in tablet.

### Steps to reproduce
1. Login with learner.
2. Follow the path BalBharati---> Class 5 --->Angles---> KA Resource  of channel ID 8fc515793aad4e52b490b03c48ad21de(Maharahstra State English Medium)

### Context

* Kolibri version: Kolibri 0.4.9
* Operating system: Ubuntu 14.04
* Browser: Chrome

### Screenshots
Tablet image
![tabletq](https://user-images.githubusercontent.com/12776071/33169401-9302582a-d06a-11e7-9a43-f5c1210062c4.jpg)

Server image
![serverq](https://user-images.githubusercontent.com/12776071/33169414-9ddb77fe-d06a-11e7-82a7-bf73fb0bf8dd.png)

**Comment by christianmemije** [comment] 2018-01-17 02:07
#3013 needs to first be addressed in order to attempt to debug this.

**Comment by christianmemije** [comment] 2018-03-05 22:17
Cannot reproduce, appears to have been fixed.

**Closed by christianmemije** 2018-03-05 22:17 UTC
Labels: DEV: frontend, P1 - important, TASK: bug fix

**Comment by swapnil106111** [comment] 2018-05-15 06:42
@christianmemije Tested on Kolibri 0.9.1. Able to see protractor in Chrome v66.0.3359.158.
