### ISSUE TITLE
Hide 'Sync All' button when no facilities are registered with KDP

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10755] opened 2023-05-26 14:10 UTC
## Observed behavior

None of my facilities are registered with KDP but the <kbd>SYNC ALL</kbd> is only applicable to KDP

## Expected behavior

We hide the <kbd>SYNC ALL</kbd> button when none of the facilities are registered with KDP.

## User-facing consequences

You need to have access to Kolibri Data Portal to use the 'Sync all' button. However, if you do not have access, the button should probably not be shown. The admin users on my facility gets confused everytime about the button when trying to sync the computers with each other.

<img width="918" alt="msedge_3HsrdDUfaT" src="https://github.com/learningequality/kolibri/assets/148026/9e3c804e-d043-4297-bb1e-39742cd9bbdb">

None of the devices are registered with Kolibri Data Portal nor is the facility.

## Steps to reproduce

Have one or more facilities, none of which are registered with KDP

## Context

 * Kolibri version: 0.15.12
 * Operating system: Windows
 * Browser: Chrome

**Comment by bjester** [comment] 2023-05-30 16:32
Just noting here that we can't hide the button if 'None of the devices are registered with Kolibri Data Portal nor is the facility' because the facility could actually be registered, but it may not know that until it syncs. https://github.com/learningequality/kolibri/issues/10446

**Comment by LianaHarris360** [comment] 2023-05-30 17:40
Closing this because a [new issue](https://github.com/learningequality/kolibri/issues/10758) with the solution has been created for updating 'Sync all'.

**Comment by bjester** [comment] 2023-06-08 17:33
We discussed this in more detail, and have confirmed that it is acceptable to hide/disable the <kbd>Sync all</kbd> button when there are no registered facilities. The option to KDP will still be present when syncing individual facilities

**Closed as completed** 2023-06-12 22:17 UTC
Labels: DEV: frontend, good first issue
