### ISSUE TITLE
Images are not showing in the magogenie exercise

### ISSUE THREAD

**Issue by yogeshmhaskule** [learningequality/kolibri#1304] opened 2017-04-24 12:37 UTC
## Summary
After importing test channel into kolibri. Exercise content showing properly, but corresponding "Images" of same question are not showing. 

## System information

 - Version: kolibri 0.4.0aplha4
 - Operating system: ubuntu 14.04
 - Browser: chrome and firefox
- Channel ID: 7769d932b2cc49efb18c5e665cda64ff

## How to reproduce

1. Login as device owner
2. Import channel using id "7769d932b2cc49efb18c5e665cda64ff"
3. Click on topics->MG Copied->18 Three Diamentional Shapes ->Prism, Cylinders & Cons->level1

## Screenshots
![images_not_showing](https://cloud.githubusercontent.com/assets/7850420/25337249/bf2d3de2-2918-11e7-8c76-545dfccc2569.png)

**Comment by rtibbles** [comment] 2017-04-24 14:46
@jayoshih images missing on content export?

**Comment by indirectlylit** [comment] 2017-04-24 17:05
closing as dupe of #1304 - seems to be a recurring issue across channels

**Comment by indirectlylit** [comment] 2017-04-24 17:06
dupe of #1272 rather

**Closed by indirectlylit** 2017-04-24 17:05 UTC
