### ISSUE TITLE
Export to USB fails part way through - urgent for DRC launch

### ISSUE THREAD

**Issue by Kevsy** [learningequality/kolibri#1130] opened 2017-03-24 11:30 UTC
## Summary

Export of previously imported channels to USB starts ok but then fails part way through. We can't courier the USB to DRC until we have it exported (launch critical)

## System information

Vodafone 0.3 pex, Ubuntu 14.04, Firefox browser

## Traceback or relevant snippet from server.log or browser console

```
11:12:14 [Q] INFO Got job for worker 3381
11:12:14 [Q] INFO Process-1:1:1 processing [batman-pennsylvania-high-blossom]
INFO     Exporting channel database for channel id ec164fee25ee526296e68f7c10b1e169 to /media/kev/kolibri_con/KOLIBRI_DATA
INFO:kolibri.content.management.commands.exportchannel:Exporting channel database for channel id ec164fee25ee526296e68f7c10b1e169 to /media/kev/kolibri_con/KOLIBRI_DATA
  0%|                                              | 0/20551680 [00:00<?, ?it/s]11:12:14 [Q] ERROR Failed [batman-pennsylvania-high-blossom] - [Errno 2] No such file or directory: '/home/kev/.kolibri/content/storage/5/1/51d11e967a89bd9fc074c7ba4c5e0167.perseus'
100%|█████████████████████████| 20551680/20551680 [00:00<00:00, 47967845.75it/s]
INFO     Exporting content for channel id ec164fee25ee526296e68f7c10b1e169 to /media/kev/kolibri_con/KOLIBRI_DATA
INFO:kolibri.content.management.commands.exportcontent:Exporting content for channel id ec164fee25ee526296e68f7c10b1e169 to /media/kev/kolibri_con/KOLIBRI_DATA
  6%|█▏                 | 1338411134/21594411294 [04:13<1:03:56, 5279328.57it/s]
11:16:28 [Q] ERROR Failed [batman-pennsylvania-high-blossom] - [Errno 2] No such file or directory: '/home/kev/.kolibri/content/storage/5/1/51d11e967a89bd9fc074c7ba4c5e0167.perseus'

```

## How to reproduce

1. Login as Admin
1. Manage
1. Export channel, select mounted USB

**Comment by Kevsy** [comment] 2017-03-27 13:39
Just to say we have simply copied /content/ from my test installation and sent it to DRC, and that seems to work. But the export function executed from the browser still gives that error above.

**Comment by indirectlylit** [comment] 2017-08-11 16:40
Likely a duplicate of https://github.com/learningequality/kolibri/issues/1882

**Closed by indirectlylit** 2017-08-11 16:40 UTC
Labels: DEV: backend, TASK: bug
