### ISSUE TITLE
Deleting search term and resubmitting does not return user to channel list

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7638] opened 2020-10-28 07:19 UTC
### Observed behavior

Manually clearing the search field via deleting the query and resubmitting the search does not update the results.
…

### Expected behavior

Very minor user experience issue, but when the user manually deletes a search term and presses enter (instead of clicking the x to clear the search field), would expect the app to return the user to the list of channels.
…

### User-facing consequences

The user is unable to return to the list of channels unless they click "Exit Search"
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. From the class home page, click on an existing lesson (or create a new one if there is not one already existing)
3. The lesson should open under the "Reports" tab. From the lesson title box, click the "options" drop-down menu and click "manage resources."
4. Click on a content channel
5. Enter a search term in the search bar and click the magnifying glass
6. Observe the results 
7. Use the cursor to highlight the search term and delete the text. 
8. Press "enter" on the keyboard or click the magnifying glass
9. Observe that the user is not returned to the list of channels, but stays on the same page with the same search results.

Note related to testing steps - Lines 102-106; issue occurs at line 105: 

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-lesson.feature
…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by MindfulQA** [comment] 2020-10-29 04:38
Would a fix for this also fix the below? If not, a separate ticket may be helpful.

When the user clears the search field and presses enter or clicks the magnifying glass, the complete list of channels and exercises does not return (they must click "exit search" to do so). This error occurs whether or not there were search results, whether the user clicks the X in the search bar or clears it manually, and whether the user clicks the magnifying glass or presses the enter key.

According to the gherkin scenario, when a user clears the search bar, the full list of channels/exercises/topics should return.

1. Open Kolibiri desktop app and log in to Coach account
2. Click on the "Plan" tab at the top of the page.
3. Click on the "Quizzes" tab
4. Click the "New Quiz" button
5. Enter a search term into the search bar and click the magnifying glass or press enter.
6. Observe the search results. 
7. Click the X in the search bar to clear it (or highlight with your cursor and press the delete key). 
8. Click the magnifying glass or press enter.
9. Observe that the user is not returned to the full list of channels/exercises/topics.

cc @radinamatic 

Thanks!

**Comment by jonboiser** [comment] 2020-11-03 20:11
Closing as duplicate of #7587

**Closed as completed by jonboiser** 2020-11-03 20:11 UTC
