### ISSUE TITLE
Replace "Deferred" with "-" in change facility flow

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10335] opened 2023-03-28 14:22 UTC
Reported by @jtamiace in the alpha9 bug bash 

## Observed behavior
Can we replace ‘DEFERRED’ with a ‘–’ in the merge account preview? It’s slightly alarming and confusing 

## Errors and logs
![image](https://user-images.githubusercontent.com/17235236/228269172-4312a1c8-ec7a-4a28-8634-d1947a362c98.png)

## Expected behavior
Just the "-" is more standard to our design patterns and less confusing

**Comment by estelacruz** [comment] 2023-03-30 23:22
Hello, I would like to get assigned this issue. Thank you!

**Comment by MisRob** [comment] 2023-03-31 06:49
Hi @estelacruz, thank you for your interest. You're welcome to take this issue on. If you haven't done so already, please have a look at [our developer documentation](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html). This issue is to be resolved on the `develop` branch so please open a pull request into `develop`. If you have any problems running Kolibri locally or have questions about this issue, you can use the comments section on this page. As part of your pull request, you're welcome to add yourself to the list of contributors in _AUTHORS.md_ file.

**Comment by estelacruz** [comment] 2023-04-03 03:37
Hello Michaela! I have a question about setting up Kolibri. I'm running on macOS, and have installed almost everything, but cannot get the development server to run. I had trouble installing a required python dependency ("pip install -e .") and wonder if this is part of the reason why I cannot run the devserver script. I set up the database, but cannot run devserver, production server, or separate servers. Any advice on how to navigate this error? I appreciate your help!

**Comment by MisRob** [comment] 2023-04-03 06:59
Hi @estelacruz, ah sorry to hear that. It should run on Macs, however, some people reported issues in the past. Hopefully, we can deal with that. Could you please post your terminal output as you're proceeding through the setup process?

**Comment by estelacruz** [comment] 2023-04-05 10:28
Hello! Attached is my terminal output when I attempt “pip install -e .” Let me know if you need more screenshots/information from my end

**Comment by MisRob** [comment] 2023-04-05 11:01
Hi @estelacruz, could you try to upload your terminal output again? I can't see it anywhere.

**Comment by estelacruz** [comment] 2023-04-05 18:37
Apologies about that! I followed some advice and uninstalled and reinstalled setup tools and was able to successfully install that Python dependency. But I am still having trouble running the server, both on Windows and MacOS

(Working on version 0.15x)

Issue on MacOS: after running: "yarn run devserver" or "yarn run devserver-hot learn" or "yarn run devserver core,learn" I receive an error that says there is no "devserver" script. After inspecting the package.json file I can see that my "packageManager" is "yarn@3.5.0"

Below is an image of my terminal output after running devserver (I also made sure that I have npm, node.js, and yarn installed)
<img width="1005" alt="Screen Shot 2023-04-05 at 2 06 12 PM" src="https://user-images.githubusercontent.com/79770461/230170929-2e47e859-5b81-45e4-a366-63a39101da75.png">


Issue on Windows: All python dependencies,  node.js,  yarn, npm, have been installed, but not with pyenv (used  venv since pyenv did not work with windows). We are unable to initialize the server because "Kolibri" is not being recognized as a command when running "Kolibri manage migrate"

![unnamed-1](https://user-images.githubusercontent.com/79770461/230173370-a2567167-d78a-4e54-a7f1-a3c3e1ef9478.png)

(nodeenv version on Windows: 16.13.2)

**Comment by MisRob** [comment] 2023-04-06 07:41
Thank you for the detailed reports, @estelacruz, that's very helpful, and it's too an important form of contribution since hopefully we can find out something and then make recommendations in our developer's documentation for others who experience similar problems.

## Mac

It seems that the primary issue is that `nodeenv -p --node=10.17.0` command fails. I found a similar, unanswered problem described on [StackOverflow](https://stackoverflow.com/questions/75114928/keyerror-arm64-in-pyenv-using-nodeenv-to-install-node-16-19-0) and I believe I saw another contributor experience it. Are you using M1 Mac?

- Could you try if using [nvm](https://github.com/nvm-sh/nvm) node version manager instead of `nodeenv` helps? I'm using `nvm` with Kolibri successfuly, however, I don't have Mac, so I am not sure if it could help, just an idea to experiment with.
- You could also try to do setup on `develop` branch with Node v16 (I'm afraid it might not have much impact on the `nodeenv` issue, however, eventually, you will be solving this GitHub issue on `develop` anyways, so why not to try out. [this Kolibri 0.15 section](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#checkout-release-v0-15-x) has recently become obsolete and will soon be removed). 

## Windows

Windows can be generally problematic as it's the least used platform for development in our team. That said, we appreciate reports so we can understand better what problems developers are experiencing on Windows and how we can help improve their experience.

- As for `kolibri: command not found`, one possible cause may be that `pip install -e .` didn't finish successfully since this is the command that will make `kolibri` command available. Previously, you mentioned having some issues with `pip install -e .` Do those problems still last on Windows?

- _"used venv since pyenv did not work with windows"_ - I think that using another virtual environment manager should be theoretically fine, however as mentioned, we don't have much experience with them on Windows. There's [pyenv with Windows section](https://kolibri-dev.readthedocs.io/en/develop/howtos/installing_pyenv.html?highlight=windows#installation-of-pyenv-on-windows) in our developer's documentation if you haven't seen it yet and would like to try out `pyenv` one more time.

---

If none of the above helps, I will reach out to the wider team and ask if someone has some more ideas. Please keep us posted.

**Comment by MisRob** [comment] 2023-04-06 07:54
@estelacruz I also recalled that I saw people using [Volta](https://volta.sh/) on Macs, so that may be another thing to try out to manage your node.

**Comment by estelacruz** [comment] 2023-04-10 02:09
Hello, Thank you so much for your response. 

**M1 Mac**

I am using M1 Mac, and am encountering the same issues posted on StackOverflow. After uninstalling and reinstalling everything, it seems to me that I successfully installed everything and am able to work on Kolibri 0.15. When I try to work on the develop branch with Node 16x I encounter the following issue: 

Preface: I was able to use both nvm and volta to manage node and set it to version 16.13.2

1) Node 16.13.2 is not compatible with the version of the "kolibri-root" module. Do you have any recommendations on what I can do to ensure this compatibility with node? 

<img width="919" alt="Screen Shot 2023-04-09 at 10 06 54 PM" src="https://user-images.githubusercontent.com/79770461/230811256-14200ea2-79df-4dc7-8593-b9914fdc821e.png">


Thank you for your ongoing support.

**Comment by zrg228** [comment] 2023-04-10 17:28
> Thank you for the detailed reports, @estelacruz, that's very helpful, and it's too an important form of contribution since hopefully we can find out something and then make recommendations in our developer's documentation for others who experience similar problems.
> 
> ## Mac
> It seems that the primary issue is that `nodeenv -p --node=10.17.0` command fails. I found a similar, unanswered problem described on [StackOverflow](https://stackoverflow.com/questions/75114928/keyerror-arm64-in-pyenv-using-nodeenv-to-install-node-16-19-0) and I believe I saw another contributor experience it. Are you using M1 Mac?
> 
> * Could you try if using [nvm](https://github.com/nvm-sh/nvm) node version manager instead of `nodeenv` helps? I'm using `nvm` with Kolibri successfuly, however, I don't have Mac, so I am not sure if it could help, just an idea to experiment with.
> * You could also try to do setup on `develop` branch with Node v16 (I'm afraid it might not have much impact on the `nodeenv` issue, however, eventually, you will be solving this GitHub issue on `develop` anyways, so why not to try out. [this Kolibri 0.15 section](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#checkout-release-v0-15-x) has recently become obsolete and will soon be removed).
> 
> ## Windows
> Windows can be generally problematic as it's the least used platform for development in our team. That said, we appreciate reports so we can understand better what problems developers are experiencing on Windows and how we can help improve their experience.
> 
> * As for `kolibri: command not found`, one possible cause may be that `pip install -e .` didn't finish successfully since this is the command that will make `kolibri` command available. Previously, you mentioned having some issues with `pip install -e .` Do those problems still last on Windows?
> * _"used venv since pyenv did not work with windows"_ - I think that using another virtual environment manager should be theoretically fine, however as mentioned, we don't have much experience with them on Windows. There's [pyenv with Windows section](https://kolibri-dev.readthedocs.io/en/develop/howtos/installing_pyenv.html?highlight=windows#installation-of-pyenv-on-windows) in our developer's documentation if you haven't seen it yet and would like to try out `pyenv` one more time.
> 
> If none of the above helps, I will reach out to the wider team and ask if someone has some more ideas. Please keep us posted.

Hi! I am one of Estela's group partners trying to work on the project. Me and one of the other group members, Jose, tried the `pip install -e` command and both of us encountered the following issue 
![image](https://user-images.githubusercontent.com/99768066/230952115-6a7b1b26-1e46-42ba-9c6b-cbceb61c3fdb.png)
We were able to solve the issue by changing some of the code from the env file. Specifically the `py33combat.py` file and made the following change in code to that file:

![image](https://user-images.githubusercontent.com/99768066/230956635-9ee0f2dd-ea69-4287-82b1-4ba3c2cbca8d.png).

We then ran into some problems with the versions of some of the modules when trying to run `kolibri manage migrate`. I found some fixes that involved installing earlier versions of some of the modules. Would it be helpful to document any of this? We are more than happy to propose an issue or add some of our progress to the documentation.

**Comment by MisRob** [comment] 2023-04-11 16:58
Hi @estelacruz and @zrg228, thank you for your continuous engagement.

**(1) pip install -e**
Regarding the issue with `py33combat.py` when running `pip install -e`, @zrg228, could you please let us know which dependency caused this error? From the screenshot, we can't recognize it because it is cut off. It'd be very valuable to know because we're concerned that this may be affecting Windows installation, not just the development setup. (cc @rtibbles)

**(2) Node version**
> Node 16.13.2 is not compatible with the version of the "kolibri-root" module. Do you have any recommendations on what I can do to ensure this compatibility with node?

@estelacruz, I can see that @akolson replied in the #dev-community channel where you posted the same question, we will wait for you to follow up on his comments there or here if this is still an issue.

**Comment by MisRob** [comment] 2023-04-11 17:01
> We then ran into some problems with the versions of some of the modules when trying to run kolibri manage migrate. I found some fixes that involved installing earlier versions of some of the modules. Would it be helpful to document any of this? We are more than happy to propose an issue or add some of our progress to the documentation.

@zrg228 I think that it'd be great if you could report your findings including fixes you tried in a new issue and then we could decide which one of them needs to be applied as fixes and what needs to be documented. After that is decided, I'm sure we'd appreciate your contributions. Thank you again.

**Comment by zrg228** [comment] 2023-04-11 18:46
> Hi @estelacruz and @zrg228, thank you for your continuous engagement.
> 
> **(1) pip install -e** Regarding the issue with `py33combat.py` when running `pip install -e`, @zrg228, could you please let us know which dependency caused this error? From the screenshot, we can't recognize it because it is cut off. It'd be very valuable to know because we're concerned that this may be affecting Windows installation, not just the development setup. (cc @rtibbles)
> 
> **(2) Node version**
> 
> > Node 16.13.2 is not compatible with the version of the "kolibri-root" module. Do you have any recommendations on what I can do to ensure this compatibility with node?
> 
> @estelacruz, I can see that @akolson replied in the #dev-community channel where you posted the same question, we will wait for you to follow up on his comments there or here if this is still an issue.

In terms of the issue with the `py33combat.py`, it was unclear if there was a particular dependency that was at fault. I posted a screenshot of the full error. If your talking about the file path I am happy to post but I believe it is going to be different depending on how one installs their env. (For example, me and Jose had slightly different filepaths). I agree that it seems be to be an issue with the general windows development. 

For me the file path is 
![image](https://user-images.githubusercontent.com/99768066/231259503-733a4ff8-9d26-4fce-b359-e6fd9d1f40d6.png).

This could be because we used the built in venv from python. We tried using Pyenv for Windows but discovered that the virtualenv that comes with Pyenv does not work well with windows.

**Comment by MisRob** [comment] 2023-04-13 05:49
Thank you, @zrg228. Shows up that one of our team members has just experienced a similar problem with the Python part of the setup and is looking into it. We will follow up here as soon as we know more.

**Comment by Wck-iipi** [comment] 2023-04-22 19:27
@estelacruz @zrg228 So I was reading this thread and funnily enough I have gotten both of these errors when trying to install Kolibri, so I thought I might write (in steps since mismatch of steps is what caused these errors for me) what helped me to see if this helps you too. This was mainly caused by me due to some confusion I had when trying to install Kolibri. 
Firstly, if you get the node error chances are your current branch is not develop and is the main branch or maybe you have installed dependencies of other branch before switching to develop(what I did). Easiest way to get rid of this error is completely removing kolibri folder that you cloned from github(you can remove ~/.kolibri too if it doesn't work). After installing pyenv and starting 'kolibri-py3.9'(which you have installed already), also run `pip3 install --upgrade setuptools`, this will get rid of HTML unescape error.
Then you can follow the guide as it is while copying the commands in yellow. Even then if you get error on `pip install -e .`, again run `pip3 install --upgrade setuptools`, `pip3 install --upgrade pip` and `pip3 install --upgrade distlib` and then run `pip install -e .` This fixed this problem for me.
When you will go to "Install Node.js, Yarn and other dependencies" in "Getting started", there is NO need to run `nodeenv -p --node=10.17.0` as develop branch is now stable.
Hopefully, this should work and get you running as this worked for me.

**Comment by zrg228** [comment] 2023-04-23 16:42
@Wck-iipi do you mind clarifying what you mean by deleting the kolibri folder? Do you mean delete the cloned version and reclone it from github? If not, what kolibri files are we accessing on the local machine when proceeding with the installation process.

**Comment by Wck-iipi** [comment] 2023-04-23 17:30
@zrg228 Yes, you should remove the cloned version and reclone it from github. Also, there exists a  `~/.kolibri` folder in your pc too. Delete that too just to be safe.

**Comment by estelacruz** [comment] 2023-04-24 20:02
@Wck-iipi Thank you for your input! I have followed your steps and am still having issues running the server-- did you experience the same? If you do not mind me asking, what OS are you using? When running the command "yarn run devserver", I previously ran into the following import error:

<img width="562" alt="Screen Shot 2023-04-24 at 3 55 21 PM" src="https://user-images.githubusercontent.com/79770461/234102050-8b33d4e1-1f41-4d6b-9e3e-1dafc7e70b65.png">

After finding my own workarounds and also following your suggestions, I still face the same error. Since we have encountered similar issues in the past, I thought I should ask if this was something you also experienced?

Thank you for your time and help!

**Closed as completed** 2023-06-15 15:34 UTC
Labels: SIZE: very small
