### ISSUE TITLE
Blank screen after transfer fails

### ISSUE THREAD

**Issue by socketbox** [learningequality/kolibri#9159] opened 2022-03-02 22:15 UTC
## Observed behavior
Blank screen after transfer fails and user presses "Start Over" and "Continue"
![2022-03-02_17-06](https://user-images.githubusercontent.com/1593835/156459342-caf9509c-d520-46d3-a7a9-97e8ac0b2710.png)

## Errors and logs
See attached
[console_logs.tar.gz](https://github.com/learningequality/kolibri/files/8173295/console_logs.tar.gz)

## Expected behavior
I'm shown a screen that has "Quick start" and "Advanced setup" listed as options after I choose "Start Over" and "Continue"

## User-facing consequences
Confusion. Dismay.

## Steps to reproduce
1. Get to a failed state in transferring data.
2. Elect to Start Over
3. Press Continue

## Context
Transferring between a 0.15 instance and a 0.15.1 instance, both within GCP.

**Comment by nucleogenesis** [comment] 2022-05-06 20:55
I wonder if this is due to the version discrepancy and that transfers between 0.15 and 0.15.1 are forever busted and that this state is no longer possible since it only happened during that particular failure?

**Comment by radinamatic** [comment] 2022-08-01 15:06
@marcellamaki Could we get some reviewer guidance or steps to try to reproduce? Thank you!

**Comment by rtibbles** [comment] 2023-04-15 06:45
Closing this, as it seems that this may have been specific to the broken 0.15.0 release.

**Closed as completed by rtibbles** 2023-04-15 06:45 UTC
Labels: TODO: needs QA re-review
