### ISSUE TITLE
Failed to export on shared folder

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7309] opened 2020-07-15 09:11 UTC
### Observed behavior
Kolibri failed to export on shared folder. 

![gif-temp](https://user-images.githubusercontent.com/8663934/87527072-2ed4b800-c6be-11ea-9d77-577387a27f43.gif)

### Expected behavior

better feedback that permission is denied

### User-facing consequences

hard-to-understand behavior

### Errors and logs

```
INFO 2020-07-15 17:53:27,088 kolibri.core.content.management.commands.exportchannel Exporting channel database for channel id 95a52b386f2c485cb97dd60901674a98 to Z:\KOLIBRI_DATA
ERROR 2020-07-15 17:53:27,094 kolibri.core.tasks.worker Job bbca668bd06a431b8c0af214281fd26e raised an exception: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\kolibri\core\tasks\worker.py", line 72, in handle_finished_future
    result = future.result()
  File "c:\python36\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "c:\python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\python36\lib\site-packages\kolibri\core\tasks\worker.py", line 218, in wrap
    return f(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\core\tasks\job.py", line 178, in y
    result = func(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\core\tasks\api.py", line 1178, in _localexport
    check_for_cancel=check_for_cancel,
  File "c:\python36\lib\site-packages\kolibri\dist\django\core\management\__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "c:\python36\lib\site-packages\kolibri\dist\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "c:\python36\lib\site-packages\kolibri\core\tasks\management\commands\base.py", line 113, in handle
    return self.handle_async(*args, **options)
  File "c:\python36\lib\site-packages\kolibri\core\content\management\commands\exportchannel.py", line 31, in handle_async
    with transfer.FileCopy(src, dest, cancel_check=self.is_cancelled) as copy:
  File "c:\python36\lib\site-packages\kolibri\core\content\utils\transfer.py", line 63, in __init__
    os.makedirs(filedir)
  File "c:\python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\python36\lib\os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "c:\python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'Z:\\KOLIBRI_DATA'
```

[kolibri.txt](https://github.com/learningequality/kolibri/files/4924098/kolibri.txt)

### Steps to reproduce
* Using [vmware fusion](https://www.vmware.com/asean/products/fusion.html) with Windows 7 virtual machine
* Follow this [instructions](https://docs.vmware.com/en/VMware-Fusion/11/com.vmware.fusion.using.doc/GUID-7F068DD6-4F3D-4B3C-B468-81AA9C43A197.html)  to share add folder into vm
This is my setup on shared folder 
![Screen Shot 2020-07-16 at 6 29 03 PM](https://user-images.githubusercontent.com/8663934/87660948-7167c480-c792-11ea-842d-b2476209f1da.png)
 
* Install Kolibri Windows installer 0.14.0 beta11 and start the Kolibri server
* log in as super admin user
* Import a channel and try to export on `shared folder`

### Context

Tell us about your environment, including:
 * Kolibri version: kolibri0.14.0b11
 * Operating system: Windows 7
 * Browser: Chrome

**Comment by indirectlylit** [comment] 2020-07-15 17:53
@mrpau-richard could you please add the steps to reproduce, specifically the setup with the "shared folder"

**Comment by radinamatic** [comment] 2020-07-16 02:39
I'm unable to reproduce the issue with exporting to an external drive on Windows 7.

Export in progress | Export completed
------------------------ | -----------------------
![Win7 (new start)  Running  - Oracle VM VirtualBox_800](https://user-images.githubusercontent.com/1457929/87619718-2495d680-c71d-11ea-8c7a-61873f9e03c3.png) | ![Win7 (new start)  Running  - Oracle VM VirtualBox_802](https://user-images.githubusercontent.com/1457929/87619735-2d86a800-c71d-11ea-9eca-a0e7adbfd681.png)



@mrpau-richard As @indirectlylit pointed out, check how are you setting up the drive that shows up as **Shared Folder**. That does not sound like a standard USB drive readable from the VM...? 

Please try connecting an external drive as specified by the Gherkin scenario, and make sure that if you are using the vanilla Windows 7 VM from modern.io, you probably need to install the USB 3.0 eXtensible Host Controller Driver ([read more in this thread](https://forums.virtualbox.org/viewtopic.php?f=35&t=82639#p390403))

**Comment by mrpau-richard** [comment] 2020-07-16 10:24
@radinamatic I added the `Steps to reproduce` for this issue.

**Comment by radinamatic** [comment] 2020-07-16 16:53
This is no issue when testing on VirtualBox, as I'm able to export to shared folder without problems. It must be that VMware does not assign write permissions when it sets up shared folders for VMs. Agreed to deescalate this to be fixed in the future releases.

![export-shared-folder](https://user-images.githubusercontent.com/1457929/87699786-a9243b80-c795-11ea-8634-89097d37afac.gif)

**Comment by rtibbles** [comment] 2021-04-06 23:40
Closing, as the issue here seems to be "can't write to unwriteable folder".

**Closed as completed by rtibbles** 2021-04-06 23:40 UTC
Labels: TAG: ux update, P1 - important, TAG: user strings, APP: Device
