### ISSUE TITLE
Percentage completion while importing channel keeps fluctuating

### ISSUE THREAD

**Issue by miyer03** [learningequality/kolibri#5904] opened 2019-08-27 06:26 UTC
### Observed behavior

The percentage completion shown while importing channel, is inconsistent. It fluctuates and even goes beyond 100.

### Expected behavior

Ideally it should keep increasing instead of fluctuating and also should not exceed beyond 100%.

### User-facing consequences

Doesn't impact the classroom. Coaches unsure, on how much importing is left as the percentage exceeds 100.

### Errors and logs

![Screenshot from 2019-08-23 12-54-11](https://user-images.githubusercontent.com/8583367/63746143-b1dffa80-c8c1-11e9-8157-7ebadb639031.png)

### Steps to reproduce
Import a new channel.

### Context

 * Kolibri version : 12.8
 * Operating system : Ubuntu 18.04
 * Browser: Chrome

**Comment by lyw07** [comment] 2019-09-03 19:05
Hi @miyer03, thank you for reporting this issue.

Could you provide the log files for us to further debug the issue? You can find the log files through these [steps](https://kolibri.readthedocs.io/en/latest/manage.html#locate-kolibri-log-files). Since you posted this issue eight days ago, I assume the corresponding log file could be located inside the `logs/archive` directory.

Thanks!

**Comment by miyer03** [comment] 2019-09-04 06:45
I had taken the screen shot on 23rd. Sharing the log of the same day.
[kolibri-2019-08-23.txt](https://github.com/learningequality/kolibri/files/3573052/kolibri-2019-08-23.txt)

**Comment by lyw07** [comment] 2019-09-10 17:36
Hi @miyer03 ,

thank you so much for the log file! I'm wondering if your installation is `kolibri` or `kolibri-server`. I'm asking this because we have seen a similar issue on `kolibri-server` and are actively working on it.

**Comment by miyer03** [comment] 2019-09-11 07:35
Hi @lyw07 This is definitely there in kolibri-server. Not sure on Kolibri. I just tried it in kolibri it seems to be working fine, but remember seeing it in kolibri as well but can't confirm 100% on it right now.

**Comment by intelliant01** [comment] 2019-09-11 07:43
Hi @miyer03, Can you pls try to reproduce this on the system which I had last upgraded to kolibri-server 0.3.2 + kolibri 0.12.8?

**Comment by jredrejo** [comment] 2019-09-11 11:25
hi @miyer03 , in order to reproduce the problem could you confirm:

- kolibri package version
- kolibri-server package version
- OS version
- channel token or name where you can reproduce the problem

thanks

**Comment by miyer03** [comment] 2019-09-13 06:04
![Screenshot from 2019-09-13 11-22-45](https://user-images.githubusercontent.com/8583367/64840962-ea4e3b00-d61a-11e9-8ecf-f4c9dc37a431.png)
Kolibri server : 0.3.2 - 0ubuntu1
OS : Ubuntu 16.04

If i reproduce in kolibri package I will let you know.

**Comment by lyw07** [comment] 2019-09-13 16:21
Hi @miyer03 ,

thank you for the information! does the issue exist in the instance with `Kolibri server : 0.3.2 - 0ubuntu1` and `OS : Ubuntu 16.04` as well? thanks!

**Comment by miyer03** [comment] 2019-09-16 05:05
@lyw07 thats the version of my system. Its runs on Ubuntu 16.04 and Kolibri server : 0.3.2 - 0ubuntu1

**Comment by lyw07** [comment] 2019-09-16 05:13
@miyer03 Thank you! Do you mind confirming if you are able to reproduce the issue after your upgrade to Kolibri server 0.3.2?

**Comment by miyer03** [comment] 2019-09-16 05:26
@lyw07 please confirm if kolibri server 0.3.2 is the new upgrade. Should I try sudo apt-get install kolibri-server to upgrade and then try

**Comment by lyw07** [comment] 2019-09-16 05:30
Hi @miyer03
Yes, kolibri server 0.3.2 is the latest version, so there is no need to run the command to try upgrade again. Thanks!

**Comment by miyer03** [comment] 2019-09-16 05:38
Hi 

@lyw07 just to get my understanding right as per the attached screen shot, which shows the version of server as 0.3.2 -0ubuntu1 is not the latest. how to upgrage without running the command. Will it happen automatically when connected to internet or need to do sudo apt-get update. Thanks

![64840962-ea4e3b00-d61a-11e9-8ecf-f4c9dc37a431](https://user-images.githubusercontent.com/8583367/64936151-30e9a280-d872-11e9-8a07-520a4cfe1fea.png)

**Comment by lyw07** [comment] 2019-09-16 05:47
Hi @miyer03, 
I’m sorry I don’t seem to find the part in the screenshot stating that 

> the version of server as 0.3.2 -0ubuntu1 is not the latest

Could you please point me to the specific location in the screenshot that you see it? 

If you take a look at our PPA (https://launchpad.net/~learningequality/+archive/ubuntu/kolibri), it shows that 0.3.2-0ubuntu1 is the latest version of kolibri server. Thank you!

**Comment by miyer03** [comment] 2019-09-16 06:00
> @miyer03 Thank you! Do you mind confirming if you are able to reproduce the issue after your upgrade to Kolibri server 0.3.2?

Hi @lyw07 the stated issue occurred on the latest 0.3.2 only as per the screen shot.

**Comment by lyw07** [comment] 2019-09-16 16:41
Hello @miyer03 ,

I notice that in the log you provided, the issue happened on August 23rd, 2019. Also from the second screenshot you posted in the issue, it shows that you installed `kolibri-server 0.3.2-0ubuntu1` through `learningequality/kolibri` PPA. 
We released `kolibri-server 0.3.2-0ubuntu1` in `learningequality/kolibri` PPA on August 29th, 2019, which is several days later after the error reported in the log file. 

so did the error happen again after August 29th, 2019? Thank you so much!

**Comment by miyer03** [comment] 2019-09-17 09:07
@lyw07 I tried it today again on the same server, and it seems to be working fine. May be the issue got rectified in the Aug 29th release. Closing this for now. Will re-open in case we notice it in any other place.

**Comment by lyw07** [comment] 2019-09-17 16:30
Thank you so much @miyer03 for checking this!

**Comment by miyer03** [comment] 2019-11-27 08:41
@lyw07 I upgraded to Kolibri-server to latest 12.9 and this error seem to reoccur while importing the content.

## Kolibri-server details
![Screenshot from 2019-11-27 14-00-16](https://user-images.githubusercontent.com/8583367/69707009-e82a5180-111e-11ea-9295-f7f080cfab44.png)

## Import Screenshot where its exceeding 100%

![IMG_20191127_140715](https://user-images.githubusercontent.com/8583367/69707320-87e7df80-111f-11ea-8e85-fee64f2f3378.jpg)

Please let me know in case you need logs, I can mail it to them separately.

**Comment by miyer03** [comment] 2019-11-28 04:44
Testing server Ubuntu Version : 16.04

**Comment by miyer03** [comment] 2019-11-29 08:23
This seems to be working fine in 13.0 beta release

**Comment by indirectlylit** [comment] 2019-12-02 01:09
thanks for testing! since the issue was intermittent, let's continue to keep an eye out for it

**Comment by indirectlylit** [comment] 2019-12-02 01:09
closing - we can re-open a new issue for 0.13 if it continues to be a problem

**Closed as completed by indirectlylit** 2019-12-02 01:09 UTC
Labels: bug

**Comment by lyw07** [comment] 2019-12-02 17:56
sorry I was on vacation last week and just got back in the office today. please feel free to let us know if this issue occurs again. thank you!
