### ISSUE TITLE
On Create lesson Page, there are two "x" icons available in the search bar for selecting Individual learners whereas there should be only one icon. 

### ISSUE THREAD

**Issue by JatinSharma12** [learningequality/kolibri#7607] opened 2020-10-23 11:54 UTC
### Observed behavior
On Create lesson Page, there are two "x" icons available in the search bar for selecting Individual learners whereas there should be only one icon. 

…

### Expected behavior
There should only be single "x" icon available in the Search bar.
…

### User-facing consequences
User might find it odd to have two "x" icons performing the same action.

…

### Errors and logs

```

```

…

### Steps to reproduce
1. Login as Coach.
2. Navigate to New lesson button and click.
3. Provide the Title and Description of the lesson.
4. Check the Individual users checkbox under the recipients.
5. Search learners using the search bar available.
6. Notice that the Search Bar have two "x" icons.

PFA the screenshot and logs for reference.
<img width="959" alt="NewLesson_issue" src="https://user-images.githubusercontent.com/72602444/97000174-00376a80-1554-11eb-8552-fc69bd2b76cb.png">
[kolibri-app.txt](https://github.com/learningequality/kolibri/files/5429222/kolibri-app.txt)

…

### Context

…

**Comment by rtibbles** [comment] 2021-04-06 23:03
This is a duplicate of #7768 - they have the same root cause.

**Closed as completed by rtibbles** 2021-04-06 23:03 UTC
Labels: OS: Windows, ie11, APP: Coach, DEV: frontend
