### ISSUE TITLE
Filter users by role hides the other users in the smaller list.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#6066] opened 2019-11-15 12:25 UTC
### Observed behavior

The list of users are not shown when filtering users by role from the last page.

See attached .gif
![kolibri--v0 12 9b2--filter users by user type](https://user-images.githubusercontent.com/175580/68942674-213ff900-07e4-11ea-85d7-c451f66282d4.gif)

This was observed when doing this Gherkin scenario: https://github.com/learningequality/kolibri/blob/v0.12.6-beta1/integration_testing/features/super-admin/super-admin-find-user.feature#L37 

### Expected behavior
The list must be reset with the right pagination items.

### User-facing consequences
Users will be confused with the behavior.

### Errors and logs
N/A

### Steps to reproduce

This requires a lot of users of different roles.
1. Login as Super admin then go to Facility > Users page.
1. Filter by `User type`, select `Learners` because it has the most users.
1. Navigate to the last page of the list.
1. Filter `User type` by `Coaches` (or any type that has items smaller than 10 I think).
1. Notice that the `No users match the filter` is displayed instead of the list items as filtered.
1. Also notice that the pagination arrows are enabled and that `1 - 1 of 1` is shown.

### Context
Environment:
 * Kolibri version: v0.12.9b2 (upgraded from v0.6.3)
 * Loaded with Vodafone - Instant Schools data
 * Operating system: Ubuntu 16.04.6
 * Browser: Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by jonboiser** [comment] 2020-03-02 23:56
I think this has been fixed in 0.13. But in the v0.12 branch, I think the problem is that the "page" does not get reset to page 1 when changing the role filter, only the "name" filter. So I think what's happening in the video is that we're staying on page 2 after changing the role filter, but the hidden coach is on page 1.

So to fix this, I think just add a similar watch handler for the kind role and make sure you reset the page.

**Comment by indirectlylit** [comment] 2020-06-22 01:59
@cpauya would you mind verifying that this is addressed in the latest 0.14?

**Closed as completed by indirectlylit** 2020-06-22 01:59 UTC
Labels: bug, TAG: ux update
