### ISSUE TITLE
Syncing | SetupWizard: Ensure that Devices that do not have facilities cannot be selected

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#10241] opened 2023-03-14 15:51 UTC
## Observed behavior

[Notion Report: Import fails when no facilities](https://www.notion.so/learningequality/Once-an-error-occurs-it-is-impossible-to-move-back-to-an-earlier-state-in-the-setup-wizard-dfd1ae3066684f5b93ade95f545233fa?pvs=4) -
[Notion Report: Selecting some addresses for import fails](https://www.notion.so/learningequality/Selecting-some-addresses-for-import-fails-16b9d100f4374224b3d8e9d50b1b7937?pvs=4)

**Comment by nucleogenesis** [comment] 2023-06-16 23:35
I suggest that this can be done with a similar approach as was taken on the work done here: https://github.com/learningequality/kolibri/pull/10703/files

**Comment by jredrejo** [comment] 2023-06-23 15:00
I'm closing this one because there was no way to reproduce it.
Without hacking the database there was no way to have a device without facility, as the setup wizard creates both almost at the same time.
After hacking the database to delete the facility and leave the device empty, the device appears disabled when another device is been setup and tries to import a facility:
![image (1)](https://github.com/learningequality/kolibri/assets/1008178/72c939e6-d1c3-43b9-af44-aac787d5ceba)

This was the code run in a shell to delete the facility:
```
import django
django.setup()
from kolibri.core.auth.models import Facility
Facility.objects.first().delete()
```

After it, the endpoint `/api/public/v1/facility/` returns just `[ ]` what produces the behaviour seen in the above screenshot when another device scans the network

**Closed as completed by jredrejo** 2023-06-23 15:00 UTC
Labels: P1 - important
