### ISSUE TITLE
high memory usage when importing and deleting channels

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4386] opened 2018-10-10 10:17 UTC
### Observed behavior

The client will disconnect from the Kolibri server when I delete the Khan Academy channel. I'm using the `.pex` file to start the Kolibri.

This appears to be because the server runs out of memory, as reported by @lyw07 below.

### Expected behavior

* We should quantify the amount of memory necessary to run the server
* Kolibri server should not run out of memory during import/export when memory should be sufficient

### Errors and logs

[server.log](https://github.com/learningequality/kolibri/files/2464192/server.log)

### Steps to reproduce
* Install and run the kolibri-0.10.3-beta `.pex` file on Xubuntu 18.04 64 bit
* Import the Khan Academy(English) at least 1gb file  contents size
* After the channel successfully imported then delete it.

Tell us about your environment, including:
 * Kolibri version: kolibri-0.10.3-beta
 * Operating system: Xubuntu 18.04 64 bit
 * Browser: FIrefox 61.01

**Comment by indirectlylit** [comment] 2018-10-11 17:20
By "server disconnect", do you mean that the browser says that the server is disconnected?

**Comment by mrpau-richard** [comment] 2018-10-12 04:20
Yeah it is @indirectlylit I also double check it on the terminal by running the `kolibri status` command and it show a log `Unclean shutdown(7)`

**Comment by lyw07** [comment] 2018-11-02 00:54
not able to reproduce this issue on my Xubuntu VM. I imported 2 GB content from KA English and deleted all the content on kolibri 0.10.3-beta3. 

My assumption is that kolibri process got killed because the system was out of memory. A similar issue: https://github.com/learningequality/kolibri/issues/2879. I will try to reproduce this issue again with a lower memory VM.

**Comment by indirectlylit** [comment] 2018-11-02 17:32
thanks @lyw07

**Comment by lyw07** [comment] 2018-11-13 18:11
![virtualbox_xubuntu_09_11_2018_22_15_52](https://user-images.githubusercontent.com/19424916/48433559-3d6e0d80-e72c-11e8-99f3-ade8839cae0a.png)

A similar situation happened when I tried to import 2GB KA English content. The base memory of the VM is 512MB. The server got disconnected because the system was out of memory.

**Comment by indirectlylit** [comment] 2018-11-20 17:54
thanks - I've updated the issue description

**Comment by indirectlylit** [comment] 2019-03-12 03:15
closing as duplicate of #2879

**Closed as completed by indirectlylit** 2019-03-12 03:15 UTC
Labels: bug, TAG: tech update / debt, DEV: backend
