### ISSUE TITLE
newly imported channels do not show up automatically

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#769] opened 2017-01-11 00:44 UTC
After importing a channel, it does not show up in the list until a refresh occurs

![image](https://cloud.githubusercontent.com/assets/2367265/21830786/0dd71060-d754-11e6-83dd-5afb1c57bc12.png)

**Comment by radinamatic** [comment] 2017-01-27 16:42
Confirmed after `pip install kolibri` today:

OS: Ubuntu 16.10
Browser: Firefox 50
Version: `kolibri-0.1.1rc3`

![ubuntu 16 10 start running - oracle vm virtualbox_120](https://cloud.githubusercontent.com/assets/1457929/22378954/45142ffa-e4af-11e6-976a-b4ff92f1b1b5.png)

![ubuntu 16 10 start running - oracle vm virtualbox_121](https://cloud.githubusercontent.com/assets/1457929/22378971/4c2e726e-e4af-11e6-99d7-926f667c8cb1.png)

**Comment by DXCanas** [comment] 2017-05-09 23:50
Started looking into this, possibly blocked by #538. Getting similar behavior as #847.

**Comment by indirectlylit** [comment] 2017-05-10 01:43
let's hold off working on import/export issues. Will be addressed during work by @jonboiser and @aronasorman on the UI and BBQ.

**Comment by jonboiser** [comment] 2017-06-12 18:04
@DXCanas The same behavior happens when deleting a channels in a naive way. For example, if you merely delete the channel, then remove the channel from `core.channels.list` or whatever, then on the next poll the deleted channel will appear since that's in the cache for `ChannelResource`.

To get around that for the delete case, I forced the `ChannelResource` to re-fetch after committing the deletion. The next time the channel list gets polled, it disappears. 

http://github.com/jonboiser/kolibri/blob/0a037bb21023103cd9b8b372842a01762cf87ad2/kolibri/plugins/management/assets/src/state/manageContentActions.js#L22

Not sure where to hook a similar force refetch for the case of importing a channel though.

**Comment by DXCanas** [comment] 2017-06-12 19:44
@jonboiser I'm way out of date on this bug, but I had similar thoughts about forcing the re-fetch. iirc, I got a little lost in the complexity before being able to actually work on the bug. If you're already working on this, I'd be glad to hand off. I'm going to try to get to it this week otherwise.

**Comment by jonboiser** [comment] 2017-06-12 19:47
@DXCanas  I'm not working on it, but don't really have anything going on, and have done the analysis already.

**Comment by jonboiser** [comment] 2017-06-14 19:12
This should be fixed in the above-referenced pull request.

When a import (:bug: and possibly an export) successfully completes, and when that progress bar widget is Closed, then the new channel should appear in the list, and a notification should appear.

**Closed by jonboiser** 2017-06-14 19:12 UTC
Labels: TASK: bug
