### ISSUE TITLE
Shaky window and double scroll in model when adjusting window sizes

### ISSUE THREAD

**Issue by jeepurs** [learningequality/kolibri#5826] opened 2019-07-27 23:06 UTC
### Observed behavior

Upon testing UN Women's deb installer based on 0.12.7, and creating a coach account the popup became shaky and there was a double scroll. See more in video attached. Pressing on "Save" was fine.

### Expected behavior

No shakiness at any window size.

### User-facing consequences

Unexpected behavior and annoyance, but does not critically break any critical functionality of the UN Women user flows.

### Errors and logs

…

### Steps to reproduce

1. Sign in as a super admin
2. Create new user
3. Create a learner (fine for me) or a coach (this was where there was shakiness)
4. Adjust the window size to see whether the sizing affects the behavior

### Context

VIDEO:

[VID_20190727_181449.mp4.zip](https://github.com/learningequality/kolibri/files/3438687/VID_20190727_181449.mp4.zip)

 * Kolibri version: 0.12.7 (UN Women)
 * Operating system: Linux ( i used the deb installer)
 * Browser: Chrome

**Comment by indirectlylit** [comment] 2019-07-29 18:04
thanks - yeah this issue seems to affect a small number of browsers, mainly @jeepurs from what I can tell :)

dupe of #4641 - I'll bump up the priority on that

**Closed as completed by indirectlylit** 2019-07-29 18:04 UTC
