### ISSUE TITLE
Validation message missed next to the username field that the name is already taken

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7606] opened 2020-10-23 11:07 UTC
### Actual result: 
Validation message missed next to the username field that the name is already taken
### Expected result: 
Validation message shown next to the username field that the name is already taken

### Steps to reproduce;
1. I am on the Kolibri sign-in page
2. click *Create an account* button
3. Fill in all required fields except "username"
4. Fill in exists username to the "username" field
5. Click on the "continue" button
6. Notice that the error message is missed

### Video: 
http://e.pc.cd/BRbotalK

### Context:
Kolibri version: 0.14.3
Device: Raspberry Pi 3B+
OS: tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

**Comment by jonboiser** [comment] 2020-10-23 21:22
Closing as duplicate of #7591

**Closed as completed by jonboiser** 2020-10-23 21:22 UTC
