### ISSUE TITLE
Coach content not flagged even after re-import

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#6575] opened 2020-02-15 11:28 UTC
### Observed behavior

Firstly, it is unknown why coach content was not already flagged in the initial import (done months ago).
When I noticed the issue, tried to re-import from a recently updated (thumbnails only) and published channel. But it would not. Hence deleted some content from the channel and reimported.
Yet the coach content is not flagged.

![unable_to_import](https://user-images.githubusercontent.com/2577060/74586423-2f80f980-500d-11ea-8279-95eb3712c1ba.gif)

Watch till end pls or [watch this video](https://drive.google.com/file/d/1Q4TMfZ0asvxmsfWZJzbCbCbZQRM6lEpM/view?usp=sharing) from 2:40.

This is how the content is correctly flagged and published in studio.

![Kolibri Studio - coach_content](https://user-images.githubusercontent.com/2577060/74586463-93a3bd80-500d-11ea-801c-94a44a7d5ad9.png)

_This could be specific to this channel (`zapok-dofil`) as I have not been able to observe / reproduce with another channel. Hence it may be a studio issue._

### Expected behavior

Coach content should be appropriately flagged.

### User-facing consequences

Unexpected and improper system behaviour for both coach and learners. Trust on system shall diminish if coach only content shall be leaked to learners.

### Errors and logs

Shall provide if needed.

### Steps to reproduce

As in animation above.

### Context

Any OS.
Kolibri 0.13.1rc1
Channels - `zapok-dofil`
Browser Firefox 72.0.2 (64-bit) on Windows.

May be related #3939 , https://github.com/learningequality/studio/issues/1112

**Comment by ivanistheone** [comment] 2020-02-15 15:35
I updated  (`zapok-dofil`) on the demo server and the coach content is correctly tagged now:
http://35.196.115.213/en/learn/#/topics/t/ec45d46fc1bd462abb01aa0d8c8a8e25

I believe the behaviour you saw is due to seeing a mix of content from the old version of the channel and the new. Currently the Kolibri UPDATE logic doesn't handle cases where files have stayed the same, and only node metadata has changed (e.g. role/visibility, titles, and thumbnails) so Kolibri was probably showing old channel data.

We're aware of the difficulties with the "computing what changed" as part of the UPDATE workflow, and tracking the issue here  https://github.com/learningequality/kolibri/issues/6351
and this will be fixed soon.

The recommended workaround is to **delete the channel completely, then re-import**. This way you're sure not to have the metadata from the old channel.

**Comment by intelliant01** [comment] 2020-02-16 13:59
@ivanistheone I see a few other issues but am not sure if they too can all be merged into #6351 .

> I updated (`zapok-dofil`) on the demo server and the coach content is correctly tagged now:
> http://35.196.115.213/en/learn/#/topics/t/ec45d46fc1bd462abb01aa0d8c8a8e25

I tried updating even just now and yet I don't see a notification to update to v5.

> Currently the Kolibri UPDATE logic doesn't handle cases where files have stayed the same, and only node metadata has changed (e.g. role/visibility, titles, and thumbnails) so Kolibri was probably showing old channel data.

Please do note that an entire topic node with all its containing resource nodes had been deleted. Shouldn't the related local metadata (cached or otherwise) had been cleaned up as well?

> The recommended workaround is to **delete the channel completely, then re-import**. This way you're sure not to have the metadata from the old channel.

I tried the workaround of Inspect Element and removing disabled=disabled as mentioned [herein](https://github.com/learningequality/kolibri/issues/6351#issuecomment-586615902), yet nothing changed upon Import.

I don't want to **delete the channel completely, then re-import** for fear of loosing the crucial test scenario. I actually have this problem in two of my systems (both 0.13.x).

As guided [herein](https://github.com/learningequality/studio/issues/1112#issuecomment-586612704) checked the channel's DB file manually -

```
$ sqlite3 ef2ead65de764ea4a27bba6df5282c74.sqlite3 
SQLite version 3.22.0 2018-01-22 18:45:57
Enter ".help" for usage hints.
sqlite> select version from content_channelmetadata;
5
```

Thus it seems a Kolibri channel update logic issue.

Can give remote access if that helps to get to the problem faster.

**Comment by indirectlylit** [comment] 2020-02-19 23:55
> I don't want to delete the channel completely, then re-import for fear of loosing the crucial test scenario. I actually have this problem in two of my systems (both 0.13.x).

One option would be to make a complete backup of your `~/.kolibri` folder. This should be sufficient to reproduce the scenario at a future time.

**Comment by benjaoming** [comment] 2020-03-24 14:07
I could not reproduce wrong coach item counts on a clean import of `zapok-dofil`, it's related to the missing rewrite/update of existing metadata as @ivanistheone hinted. I found other issues during test, that I'll isolate and address in other issues.

I created an isolated test channel, imported it, added coach contents and imported the new contents. Adding new coach contents did not pose issues with metadata, but in general adding contents inside existing Topic nodes seems problematic.

An import of `zapok-dofil` on a clean Kolibri 0.13.2.dev installation works fine.

Correct counts before import:

![screenshot-2020-03-24-14:03:27](https://user-images.githubusercontent.com/374612/77432888-efb4eb00-6dde-11ea-9005-25c26db8f5ee.png)

Correct summary after import:

![screenshot-2020-03-24-14:48:46](https://user-images.githubusercontent.com/374612/77432853-e7f54680-6dde-11ea-909f-a736d8895196.png)

Correct counts after import:

![screenshot-2020-03-24-14:49:00](https://user-images.githubusercontent.com/374612/77432824-dc098480-6dde-11ea-9b28-ba9bce50197a.png)


I'll disseminate the various other issues mentioned throughout this ticket in new issue reports.

**Closed as completed by benjaoming** 2020-03-24 14:07 UTC
Labels: bug, P1 - important, DEV: backend

**Comment by benjaoming** [comment] 2020-03-24 14:10
@intelliant01 thanks very much for finding and explaining these problems, I hope that while solving the various issues related to adding/editing resources in channels, we might also stumble upon a fix for what you experience with the existing channels.

Otherwise if it persists and there's a way to get your installation data, we could also investigate it that way.

**Comment by benjaoming** [comment] 2020-03-24 14:23
@ivanistheone is there a "hack" that can provoke metadata updates on topics? Am thinking if editing the title of a subtopic could propagate to rewriting metadata? What could be appropriate behavior?

**Comment by intelliant01** [comment] 2020-04-16 07:55
@benjaoming Yes, deleting and reimporting the entire channel imports the latest version 5 of the channel with the correct coach content tagging. Prior to complete deletion it would even refuse to recognise the availability of a new channel. 
Will keep a backup of the .kolibri folder for another month in case anything else needs to be tested for this.

**Comment by benjaoming** [comment] 2020-04-16 14:40
Thanks so much, @intelliant01 - let's re-open if it is reported again, much appreciate that you keep the `.kolibri` folder for a month :pray:
