### ISSUE TITLE
When a user selects a topic, there's no snackbar confirmation, and its descendants are not checked

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7646] opened 2020-10-29 04:23 UTC
### Observed behavior

When a user selects a topic, the user does not receive a snackbar confirmation, and its descendants are not selected - so only the parent topic is selected.

Screen recording:

https://drive.google.com/file/d/1rBYUXH_u2MJMASoNDCY1Kxa9ssZ3WfMJ/view

…

### Expected behavior

If a user selects a topic, all of its descendants should also be selected.
…

### User-facing consequences

The user's intended selections are not made.
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. Click on the "Plan" tab at the top of the page.
3. Click on the "Quizzes" tab
4. Click the "New Quiz" button
5. Click on a channel.
6. Click the check box next to a topic.
7. Click on the topic.
8. Observe that the subtopic(s)/descendants are not selected. 

Testing note - scenario in line 49:

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-quiz.feature

…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by MindfulQA** [comment] 2020-10-29 04:26
Would a fix for this also fix the issue below? If not, a separate ticket can be created.

_The user can't uncheck a topic and its descendants because the descendants are not automatically selected (see above)._

Testing note - Scenario in line 60:

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-quiz.feature

cc @radinamatic 

Thanks!

**Comment by jonboiser** [comment] 2020-11-03 20:32
I'm thinking this might be have the same root cause as #7536 and looks to be fixed in 0.14.4

**Closed as completed by jonboiser** 2020-11-03 20:32 UTC
Labels: bug
