### ISSUE TITLE
15.8 Kolibri

### ISSUE THREAD

**Issue by kmapds** [learningequality/kolibri#9788] opened 2022-10-21 16:51 UTC
Hello! I noticed the following issues below after Kolibri was updated to 15.8 :

1- The search bar has disappeared under Classes. This occurs when clicking into a classroom trying to search for a user. 

2-When logged into Kolibri as an admin and then trying to create a quiz/lesson, the following error message appears and the user is unable to proceed: "You must be signed in as an admin or coach in order to view this page". Admins should be able to view all lessons/quiz/content for every class and should be able to make any changes.

3- Not really a big problem but since the update the website is running slower to load the page.

## Observed behavior

1-
<img width="1104" alt="Screen Shot 2022-10-21 at 12 37 56 PM" src="https://user-images.githubusercontent.com/105886909/197247856-4ebb3d71-3f11-49df-8567-c7f18a0086e0.png">

2-<img width="1171" alt="Screen Shot 2022-10-21 at 12 49 37 PM" src="https://user-images.githubusercontent.com/105886909/197247919-645b7362-004b-4e07-9286-8e7203f981b9.png">

…

## Errors and logs

…

## Expected behavior
 
1- Admins and Coaches should be able to search for a user in their class
2- Admins should not receive error message: "You must be signed in as an admin or coach in order to view this page"when trying to edit/look at lessons/quizzes in a class.
Admins should be able to view all lessons/quiz/content for every class and should be able to make any changes.
3- Page should load faster than it is loading now.

…

## User-facing consequences
 1-  Coaches/admins are unable to search for a learner/coach in their class. They need to manually scroll through the list to search for a learner. Causes an inconvenience for large classrooms.
2- Admins are unable to edit/view quizzes/lessons/create content. 

…

## Steps to reproduce
1- Log in using an admin account. Under classes tab click on any class to view learners/coaches. You will be able to see that the search bare disappeared.
2- Log in using an admin account. Click on Coach in the hamburger menu> then click on a classroom> error message screen will populate

…

## Context

…

**Comment by marcellamaki** [comment] 2022-10-24 20:29
Hi @kmapds! Thank you for opening an issue detailing what you have noticed with the recent release. We will get to work reproducing these findings and troubleshooting and will let you know when we have updates.

**Comment by pcenov** [comment] 2022-10-25 10:34
Hi @marcellamaki I'm not able to replicate any of the above mentioned issues in 0.15.8
1. As far as I know there has never been a search bar next to the 'Enroll learners' button. All other search bars are displayed and are functioning correctly.
2. No problems accessing Kolibri as an Admin and creating lessons/quizzes.
3. No slowness observed.

**Comment by marcellamaki** [comment] 2022-10-28 16:11
Hello @kmapds, 

As you can see above, we had our QA team investigate, and we were not able to reproduce any of these issue. I also tested each issue you reported myself, and was not able to replicate them either. 

For number one, once you click the 'Enroll Learners' button, the next screen which has the list of learners to be enrolled has a search bar. Perhaps this is what you were thinking of?

**Comment by marcellamaki** [comment] 2022-11-22 14:00
Hi @kmapds - please let us know if you are still able to replicate these issues or if you have any further details so we can investigate more and try to resolve them. Otherwise we will close this out. Thank you!

**Comment by kmapds** [comment] 2022-11-22 17:57
Hi @marcellamaki -- thank you for following up. please feel free to close out this ticket :) I think i am all set

**Comment by marcellamaki** [comment] 2022-11-22 17:59
@kmapds - happy to hear that! Thanks for opening an issue on Github, and please feel free to open any again in the future should you run into any new bugs!

**Closed as completed by marcellamaki** 2022-11-22 17:59 UTC
