### ISSUE TITLE
Quiz not automatically showing at the learner classes

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5604] opened 2019-06-03 03:53 UTC
### Observed behavior
After I activated the quiz as a coach user, that quiz doesn't show at the learner classes. Unless I manually refresh the browser page.

### Expected behavior
The quiz should show at the learner page without refreshing the browser page.

### Errors and logs
![temp](https://user-images.githubusercontent.com/8663934/58774405-e2cacf00-85f3-11e9-8b00-5eaa5ceb84cd.gif)

### Steps to reproduce
* Create a quiz as a coach
* Use incognito Window to log in as a learner.
* At the coach page activate the quiz recently created
* Observed at the learner side that the quiz not show up unless you manually refresh the page.

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4-beta6
 * Operating system: Windows 7
 * Browser: Firefox 67.0

**Comment by radinamatic** [comment] 2019-06-03 12:33
Replicated on update from 0.10.3 to 0.12.4b6 on Ubuntu 16.04, so not just an issue on Windows. 
Seems related to #5547 and #5594.

**Comment by jonboiser** [comment] 2019-06-03 20:26
I don't think this is a caching issue like #5547 and #5594 . This is expected behavior.

There is a New Feature issue (#5047) to the effect that learners be able to see new Assignments without having to refresh their browser.

**Comment by indirectlylit** [comment] 2019-06-03 23:59
indeed - closing as dupe of #5047

**Closed as completed by indirectlylit** 2019-06-03 23:59 UTC
Labels: bug, P1 - important
