### ISSUE TITLE
Receiving Server Error (500) Message in "Learn" view with pre-loaded content

### ISSUE THREAD

**Issue by laurenlichtman** [learningequality/kolibri#1631] opened 2017-06-09 17:07 UTC
## Summary

Once curated channels have been loaded in Kolibri, a Server Error (500) appears when clicking on the "Learn" view.

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: v0.4.0-beta9
 - Operating system: MacBook Pro (Operating System: OS X 10.10.2) (Also replicated on Linux laptop)
 - Browser: Chrome

## How to reproduce

1. Import Content Channels into v0.4.0-beta9. Try 17e25cd51c1842dd87755dcd7cd515a4.
2. Click on "Learn"

## Screenshots

<img width="1270" alt="screen shot 2017-06-09 at 5 19 46 pm" src="https://user-images.githubusercontent.com/25990164/26985875-6ae568e4-4d13-11e7-95e1-701ada78d15c.png">
<img width="1274" alt="screen shot 2017-06-09 at 5 16 01 pm" src="https://user-images.githubusercontent.com/25990164/26985877-6cc49716-4d13-11e7-86e4-70371abeb3bc.png">

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

This issue occurred when one of our three main pilot partners was trying to see how curated content looks in Kolibri. This is quite critical to fix so that the implementation team in-country can continue with the deployment. Contact me for more info.

**Comment by jonboiser** [comment] 2017-06-09 18:59
@laurenlichtman Are you running this locally? If you are using this command (or something close to it) to start kolibri,

```
kolibri manage devserver -- --webpack --qcluster
```

Try adding this extra `--debug` bit:

```
kolibri --debug manage devserver -- --webpack --qcluster
```

And let me know if you see a screen like this:

<img width="722" alt="screen shot 2017-06-09 at 11 58 15 am" src="https://user-images.githubusercontent.com/10248067/26990287-f8d2bcfa-4d0a-11e7-8791-63faed4872a3.png">

The error on my end is pointing that the 'Youth Kiosk Channel' is missing a database column `content_license.description`.

**Comment by rtibbles** [comment] 2017-06-09 19:46
@jonboiser this may well be the issue - looks like we may need to republish that channel to prevent this error.

**Comment by jonboiser** [comment] 2017-06-09 19:52
@ralphiee22 Just republished 'Youth Kiosk', which resolves the issue on my end. Might need to check to see if the rest on that list might have a problem.

If there are other channels out on the wild that are not compatible, might need to patch client to handle this more gracefully.

**Comment by jonboiser** [comment] 2017-06-09 20:23
Just confirmed that these channels are also not compatible with app

- [ ] `ef6fc9f4f842476ca587992c81281b59` Health Information for Youths
- [ ] `7db80873586841e4a1c249b2bb8ba62d` Uganda School Channel
- [ ] `1ceff53605e55bef987d88e0908658c5 ` Khan Academy (en)

**Comment by rtibbles** [comment] 2017-06-09 20:28
I tried to implement a work around for this previously, but I think it would have to be at the point where we add the database to the ChannelMetadataCache - we would have to import it, check that the models all work without error, and then add it to the cache. Otherwise we need to alert that the database is incompatible.

**Comment by radinamatic** [comment] 2017-06-12 22:46
Same OSX as originally reported, logs are long so I'm linking them instead of c/p here:

[errors importing TESSA channel](https://docs.google.com/document/d/1hdMDw2TW3g6UM_chclr-zUV-OlPHsVl727I-8AOz0Go/edit) (we were trying to import a smaller channel, maybe TESSA channel needs  re-publishing too?)

[kolibri.log](https://docs.google.com/document/d/1IBgeCxXpbigqBrckF7QkRxDbezVfl8irKb_2-baSP-o/edit)

Still getting 500 error on Learn; Connection was being interrupted often, and eventually it got a bit late so we'll continue tomorrow. Not sure if these are incompatible db errors, due to bad connection or something else...

Tomorrow we'll try the Beta10 as @jamalex suggested.

**Comment by jamalex** [comment] 2017-06-12 22:59
Could be a content DB error, yeah. I know @aronasorman et al kicked off a re-publish for every channel, but not sure that's completed.

One suggestion: Running the server with `--debug` will turn that 500 page into a meaningful traceback.

**Comment by radinamatic** [comment] 2017-06-12 23:02
Thnks, will run it with `--debug` tomorrow! :+1:

**Comment by radinamatic** [comment] 2017-06-13 17:59
Beta10 release was still  giving errors on Learn:
![learn_error](https://user-images.githubusercontent.com/1457929/27096674-1b2b42d0-5072-11e7-9570-58ed2bbfb2d6.png)

So we removed all the old content databases, imported a small channel (Khan Academy Math Testing Channel ID `6d7c555dc3ec47abbdeb08b5870f0669`, published just prior), restarted the server and voilà, Learn was working again! :smiley: 

We left his laptop downloading the CK12 channel, and he'll send the terminal output tomorrow, in case there are any errors.

**Comment by radinamatic** [comment] 2017-06-14 11:19
Latest update, while downloading CK12 channel:

```
nicefkampala@unicef02:~/Downloads$ ./kolibri-v0.4.0-beta10.pex manage importchannel -- network 1d8f6d84618153c18c695d85074952a7
INFO     Downloading data for channel id 1d8f6d84618153c18c695d85074952a7
100%|███████████████████████████| 18101248/18101248 [00:49<00:00, 392719.86it/s]
unicefkampala@unicef02:~/Downloads$ ./kolibri-v0.4.0-beta10.pex manage importcontent -- network 1d8f6d84618153c18c695d85074952a7
  0%|                          | 24166/7485883057 [00:03<267:43:02, 7767.17it/s]
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6273a4c410>: Failed to establish a new connection: [Errno -5] No address associated with hostname',)': /content/storage/e/2/e247f0cdc82dfce441bbb48ac1e2cf8d.png
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6273a4c410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /content/storage/2/f/2f3d1295acfe998a87f62f8da08bde86.jpg
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6273a4c610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /content/storage/2/f/2f3d1295acfe998a87f62f8da08bde86.jpg
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6273a4c8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /content/storage/2/f/2f3d1295acfe998a87f62f8da08bde86.jpg
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6273a4c510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /content/storage/2/f/2f3d1295acfe998a87f62f8da08bde86.jpg
WARNING:requests.packages.urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f6273a4ca90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /content/storage/2/f/2f3d1295acfe998a87f62f8da08bde86.jpg
```

**Comment by jonboiser** [comment] 2017-06-14 19:08
@radinamatic Is that last screenshot a bad outcome? Have you ever had the app open to the Content Management Page when this `WARNING...` output occurs?

**Comment by radinamatic** [comment] 2017-06-14 21:44
@jonboiser Content Management page (see the first screenshot above) did not display any errors, only Learn did. I'd say that the last screenshot only indicates that changes in Beta10 compared to Beta9 did not have any effect on this issue.

As soon as we deleted the 6 databases that were present in /kolibri/content/databases`, and imported one really small channel that was published just prior to import, Learn was free of errors.

However, importing both TESSA and CK12 channels was unsuccessful, and gave the `WARNING:requests.packages.urllib3.connectionpool:Retrying` error in Terminal.

**Comment by harishbalachandran** [comment] 2017-06-15 01:43
@rtibbles @jamalex @radinamatic @jonboiser @laurenlichtman  , facing the same problem today. This is on **beta10**

**Events**
1. Imported 1ceff53605e55bef987d88e0908658c5, it began and 15% was done.
2. Got an error at the back end (refer the kolibri.log) and import stopped.
3. Refreshed the page and got Server Error (500)
4. Now the problem persists all the time.

**Screenshot**
![start the beta10](https://user-images.githubusercontent.com/13453618/27161545-a8fb56a4-5199-11e7-81a5-4ed20e6ae78f.png)
![beta10](https://user-images.githubusercontent.com/13453618/27161546-aac8671a-5199-11e7-9997-5d832d6aca31.png)



Kolibri.log
[kolibri_log.txt](https://github.com/learningequality/kolibri/files/1076343/kolibri_log.txt)

**Comment by radinamatic** [comment] 2017-06-15 07:52
@harishbalachandran I think that if you delete the `1ceff53605e55bef987d88e0908658c5.sqlite3` file from the `/home/<user_name>/.kolibri/content/databases` folder and restart Kolibri, the Server Error 500 in Learn will be resolved.

Which channel is `1ceff53605e55bef987d88e0908658c5`? If it is you own, you can make a small change on the CC server, re-publish it, and it should be possible to import with no errors. Otherwise @ralphiee22 or @aronasorman might need to publish it again on our side.

**Comment by harishbalachandran** [comment] 2017-06-15 08:37
@radinamatic its the KA english channel that Jamie and Aron had shared, I only have view only access.  All the resources within the channel seams to be quite useful hence trying to download and use it at the learning centre with the kids.

I deleted the .sqlite file under content, but was not able to login to device owner account that I had created.  Hence deleted the db.sqlite3 too and set up a new facility and device owner.

Now the question is if I reimport the channel 1ceff53605e55bef987d88e0908658c5, will it continue from where it stopped? Because storage directory has 9GB of data downloaded in my previous import.

**Comment by radinamatic** [comment] 2017-06-15 09:36
@harishbalachandran 

> @radinamatic its the KA english channel that Jamie and Aron had shared, I only have view only access.

Ok, just beware that KA EN channel alone is 76GB, and be mindful of the space on your device. 

> I deleted the 1ceff53605e55bef987d88e0908658c5.sqlite3 file under content, but was not able to login to device owner account that I had created. Hence deleted the db.sqlite3 too and set up a new facility and a device owner.

`./kolibri/db.sqlite3` file is the database that holds the information about the local Kolibri users, so I don't understand why where you unable to login with your device owner account, if this database was intact.

Various `.sqlite3` files that might be present in `/.kolibri/content/databases/` folder are content channels databases that you downloaded at some point. The presence of the database file here does not necessarily mean that the **full channel content** is present also, as in your case. 

> Now the question is if I reimport the channel 1ceff53605e55bef987d88e0908658c5, will it continue from where it stopped? Because storage directory has 9GB of data downloaded in my previous import.

Yes, once you start re-importing that channel, it will briefly check the previously downloaded resources, and continue from where it was interrupted before. 9GB that you report would correspond roughly to 15% of the channel content.

However, you should **hold on re-importing** until we receive the confirmation that the error presented in this issue (`OperationalError: no such column: content_license.license_description`) has been resolved.

@ralphiee22 or @aronasorman could probably give more details on when the KA EN channel has been re-published on the content curation server and ready to be imported locally.

**Comment by harishbalachandran** [comment] 2017-06-15 10:34
@radinamatic Thanks for a such a detailed reply. Yep it was strange when I was not able to login with the device owner account. But that's sorted since I have created a new one.

As you suggested, I will wait till this issue is closed and then reimport.

Thanks!

**Comment by rtibbles** [comment] 2017-06-15 14:43
Because of the size of KA English, the channel has not been republished
since the issue that Radina referenced was resolved. We have it available
as a curation source, but it will not currently work if directly
downloaded.

**Comment by radinamatic** [comment] 2017-06-16 13:11
Thanks for the update @rtibbles!

@harishbalachandran You can use the KA EN channel to curate your own with that content for now, which may even be more manageable and recommendable, because of its sheer size.

**Comment by harishbalachandran** [comment] 2017-06-16 15:19
@rtibbles @radinamatic Yep makes sense. Will use it as a curation source to create a couple of smaller channels.

**Comment by rtibbles** [comment] 2017-06-29 23:38
Closing for now, this seems to be resolved.

**Closed by rtibbles** 2017-06-29 23:38 UTC
