### ISSUE TITLE
Device and Facility pages crash after upgrade 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#3806] opened 2018-06-15 08:41 UTC
### Observed behavior
Device page crashed after the upgrade from 0.7.2 to 0.10.0b2

### Errors and logs
![screen shot 2018-06-15 at 4 37 14 pm](https://user-images.githubusercontent.com/8663934/41458915-84e195d0-70ba-11e8-84ee-e6e722b741dd.png)

### Steps to reproduce
* Install the 0.7.2
* Copy the [0.7.2 Kolibri sample data](https://drive.google.com/open?id=1HAJcFr7Yhqj2C8gE88-4gMR7sNJtQiuh) at the `.kolibri`
* Upgrade to 0.10.0b2
* Log in as admin
* navigate at the device page.

Tell us about your environment, including:
 * Kolibri version: 0.10.0b2
 * Operating system: Windows 10
 * Browser: Firefox

**Comment by indirectlylit** [comment] 2018-07-02 16:36
filed issue https://github.com/learningequality/kolibri-installer-windows/issues/78 as possible culprit

**Comment by jredrejo** [comment] 2018-08-06 16:59
Duplicate of #4021 
Both #4021 and #3806 are the same issue.

**Closed as completed** 2018-08-07 17:54 UTC
Labels: P1 - important
