### ISSUE TITLE
Preview quiz buttons not aligned 

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#6285] opened 2019-12-12 02:23 UTC
### Observed behavior
Buttons are not aligned at the preview quiz page

### Expected behavior

aligned buttons

### User-facing consequences
![Screen Shot 2019-12-12 at 10 12 23 AM](https://user-images.githubusercontent.com/8663934/70677048-feacdd00-1cc8-11ea-83d0-38a2778cc110.png)

### Errors and logs

…

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: 0.13.0b4
 * Operating system: macOS 10.14.5
 * Browser: [Kolibir mac app](https://drive.google.com/open?id=1oVlC7_viSiaCpdVoAwO6LSWdURbBfPzY)

**Comment by indirectlylit** [comment] 2019-12-13 04:00
@mrpau-richard please make sure you're always testing with the latest beta.

~I believe this was addressed in https://github.com/learningequality/kolibri/pull/6271~

Edit: actually, that PR related to import/export, not quiz creation. This may well be a real issue still - thank you

**Comment by mrpau-richard** [comment] 2019-12-13 05:47
> @mrpau-richard please make sure you're always testing with the latest beta.

Yeah, I used the old beta4 mac installer to test it and I did not notice that there is a new beta. But I tested this again on beta5 and the issue still exist.

**Comment by indirectlylit** [comment] 2019-12-13 16:32
okay - note that we're up to beta6 now though! :)

But I am sure the issue still exists there, too

**Comment by jonboiser** [comment] 2019-12-18 01:07
Don't know why I didn't see this the first time around (I thought it was a Christmas miracle), but we've seen problems with the fix in #6315 working for Safari/Webkit, but not working for Chrome. Here's what the buttons look like in Chrome.

![Screen Shot 2019-12-17 at 4 58 38 PM](https://user-images.githubusercontent.com/10248067/71047138-80e53900-20ef-11ea-93fc-8bc61b9a63ed.png)


The issue is when you mix a real button with a button-looking anchor tag, so we've tended to fix these by replacing the anchor with a button, so that the two siblings are real buttons.

**Comment by indirectlylit** [comment] 2019-12-18 02:31
Maybe we need to simply wrap the `<a>` with an `inline-block` `span`?

**Closed as completed** 2019-12-19 16:04 UTC
Labels: bug, P2 - normal
