### ISSUE TITLE
Deleted channels initially disappearing but then reappearing after time lag

### ISSUE THREAD

**Issue by EJCampbell** [learningequality/kolibri#2865] opened 2017-12-07 10:23 UTC
### Observed behavior

A) Deleted channels initially disappeared. They reappeared after time lag of 4 days.

Channels:
 1. African Storybook - picturebooks for Ghana, version 2
 2. African Storybook version 12

B) Linked to this, when working on channel mgt, Delete channel failure pop-up frequently showed. However when you clicked OK, the channel disappeared. Not sure if Delete channel failure pop-up appeared with these 2x particular channels.

![image](https://user-images.githubusercontent.com/2367265/33859347-61caf876-de88-11e7-9b4d-3465731128a9.png)

![image](https://user-images.githubusercontent.com/2367265/33859356-69481b9c-de88-11e7-9d29-4991901b775f.png)

### Expected behavior

Channels to disappear immediately

### User-facing consequences

End users seeing incorrect channels

### Errors and logs

...

### Steps to reproduce

...

### Context

* Kolibri version: Kolibri 0.6.1.dev020171205065013-git
* Operating system: Windows 10
* Browser: Chrome

**Comment by indirectlylit** [comment] 2017-12-11 23:35
Thanks for the report! We haven't seen this behavior internally. Please post here if you continue to see it.

**Comment by EJCampbell** [comment] 2017-12-12 10:30
Ok. It has happened again. Rogue public PhET channel reappeared on v2 demo site yesterday. I have not deleted it so you can see it first before removing it. The VF version needs to stay.

(I cannot seem to just paste a screenshot into github so have to save screenshot into a word doc.)
[2nd screenshot - deleted channel reappearing.docx](https://github.com/learningequality/kolibri/files/1551161/2nd.screenshot.-.deleted.channel.reappearing.docx)

**Comment by jeepurs** [comment] 2017-12-14 08:06
@indirectlylit  I replicated this issue for the online Instant Schools V2 demo site PhET channel.

**Comment by indirectlylit** [comment] 2017-12-14 20:20
@jeepurs can you elaborate on the steps we should take to reproduce? I don't want to start messing with the demo since it sounds like it's in production use.

this sounds potentially similar to #1818 but that issue was windows-specific and fixed in 0.5

**Comment by jeepurs** [comment] 2017-12-20 23:31
@indirectlylit  of course when I finally sit down to reproduce the issue, I cannot :P  Will be testing periodically over the holiday break when I suspect there will be little traffic to the demo site.  @EJCampbell if you can reproduce, please let us know!

**Comment by EJCampbell** [comment] 2018-02-26 11:50
I deleted the rogue channel on Thursday and checked the demo site again today. It has not come back. It looks as though this issue is now resolved. There was just 1x strange thing. It said 'Attempt to delete channel failed. Please try again'. However the channel was actually deleted. Screenshots in this attachment:
[v2 Demo Site Testing - Deleted Channels Reappearing - 26 Feb 2018.docx](https://github.com/learningequality/kolibri/files/1758424/v2.Demo.Site.Testing.-.Deleted.Channels.Reappearing.-.26.Feb.2018.docx)

**Comment by indirectlylit** [comment] 2018-03-06 23:29
from @EJCampbell:

> the rogue PhET channel is now showing again on the demo site. Therefore although we thought this had been resolved, there must still be a bug. I have now looked at this twice. Would it now be worth you trying to replicate the error by deleting the channel at your end, waiting a few days and seeing if it reappears again.

**Comment by jamalex** [comment] 2018-08-25 00:49
Looks like it was a holdover from this older issue: https://github.com/learningequality/kolibri/issues/1818

We've manually deleted the DB file for the "rogue channel" through the backend, so it should no longer have any way to reappear.

**Closed by jamalex** 2018-08-25 00:49 UTC
Labels: TAG: needs details, TASK: bug fix
