### ISSUE TITLE
Khan Academy English - Update 14 - resources vanished

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#5268] opened 2019-03-14 19:24 UTC
### Observed behavior

Tried updating Khan Academy content from version 12 to 14 wherein I had at least a thousand resources. All but one resource have vanished from the UI. However, the storage on disk is still occupied as before. .kolibri folder was 166 GB before I started the update and so is it even now. I can replicate this at will as I have a backup of the .kolibri folder prior to attempting the update.

Possibly related: #4342 

I have tried the ``` kolibri manage scanforcontent``` step suggested by @jredrejo at #4705 but to no avail.

In Device management it shows as occupying 724 MB. 
In Learn section, it just shows one resource i.e. a Computing exercise. 

![image](https://user-images.githubusercontent.com/2577060/54384884-59be8e80-46bb-11e9-99ac-1ba20fd882ca.png)

### Expected behavior

Channel version should have updated from 12 to 14 and allowed me to sync further content.

### User-facing consequences

Huge data, time and productivity loss.

### Errors and logs

Herein is the [kolibri.log](https://github.com/learningequality/kolibri/files/2968153/kolibri.log)

### Steps to reproduce

1. Installed Kolibri 0.12.1 and restored ```.kolibri``` backup from 0.10.0.
2. Attempted update of Khan Academy channel from 12 to 14.

### Context

Kolibri 0.12.1
Ubuntu Linux 18.04

**Comment by jonboiser** [comment] 2019-03-14 19:38
Hi @intelliant01, How did using the `scanforcontent` command work for you when you were reporting the issue with Khan Academy Version 13 in #4342?

**Comment by intelliant01** [comment] 2019-03-14 19:46
Hi @jonboiser, Sorry your question is not quiet clear to me. Yet I shall try to answer.

The ```scanforcontent``` had never worked for me as I had never tried it before. And yes, what I have experienced today seems a repeat of what I had experienced when I had tried to update KA English from version 12 to 13 on Kolibri 0.10.2 as I had reported [here](https://github.com/learningequality/kolibri/issues/4342#issuecomment-425315157).

**Comment by intelliant01** [comment] 2019-03-16 04:02
Now after having reimported 19 GB (as visible in UI) worth of Maths and Science content I see the disk space occupied has also swelled by the same number. So this is confusing as it did show that the content was present before I had started the update. 

I strongly suspect that there are a lot of stale files therein as nothing explains the 184 GB occupied space when the math of all content present adds up to less than 35 GB.

Is it possible that there are "stale" content files lying in the ```.kolibri/content/storage``` which have not been "indexed" due to some legacy bugs which may have now been fixed? 

I see that there is a vacuuming of the sqlite db done on a daily basis at around 3 AM but is there any way to do house-keeping of the content storage?

**Comment by intelliant01** [comment] 2019-03-16 10:49
> Is it possible that there are "stale" content files lying in the `.kolibri/content/storage` which have not been "indexed" due to some legacy bugs which may have now been fixed?

I think I got the answer. Just deleted the Blocky Games channel of 7 MB and it seemed to trigger the cleanup. Now the disk occupied it down to 33 GB, much within expectations.

So is this _clean-up and re-indexing_ exactly as expected or an absurd behaviour?

**Comment by jonboiser** [comment] 2019-03-18 18:49
@intelliant01 Thanks for this update, this is interesting information.

This is what I think the timeline is

1. You upgraded from version 12 to 14
1. Because a large fraction of Version 12 exercises have different files (thumbnails, .perseus files, etc.) from Version 14, these exercises are now counted as unavailable. (This is technically expected behavior, if my assumption that the various files have changed is correct). It might also explain why the `scanforcontent` command didn't help.
1. You re-download the missing contents in Version 14, which adds the _correct_ files for the various exercises, increasing the amount of storage used.
1. You deleted Blockly Games, which removes "orphaned" files in `/storage` that are not associated with a resource. This also ends up removing KA Version 12 files.

The mystery to me is how version 14 could be so radically different from version 12, which lead to what I think is happening in step 2.

**Comment by intelliant01** [comment] 2019-03-19 02:49
@jonboiser Yes, step 2 is where the mystery lies. And ~120 GB seems a lot of KA content or may be it was holding up even older "orphaned" files.

One question -
Why is the "orphaned" files cleanup only being done upon a channel deletion and not after an update such as in step 2 and is it as per design?

If you need to do any direct analysis then I can even recreate this environment and give you SSH access if you can share your public key.

**Comment by jonboiser** [comment] 2019-03-19 17:26
> Why is the "orphaned" files cleanup only being done upon a channel deletion and not after an update such as in step 2 and is it as per design?

This is simply an oversight. On my part, I have always assumed that upgrading a channel is "additive", where a newer Channel version is "superset" of the older version. Obviously, this isn't always true.

Unfortunately, the experience you've had upgrading KA from version 12 to 13 and now 12 to 14 is expected behavior, given the changes between versions. This seems unusual because KA content seems to have continuity between versions. However, if you consider an extreme case where a channel completely changes its contents between versions, this kind of data loss makes sense.

Something we have been telling people to avoid situations like this is to download everything from the new version, especially if you notice the checkboxes in the import UI go from checked/disabled (and "already on device") to unchecked (indicating the resource is not on the device), after updating the channel/channel listing.

Implementing a "cleanup" during an upgrade is definitely something we should look into to help save hard drive space, though, so thanks for making this point.

**Comment by intelliant01** [comment] 2019-03-19 18:06
> Something we have been telling people to avoid situations like this is to download everything from the new version

This is exactly what I did everytime. Sorry, I don't see how it helps address any of the undesirable situations that we are discussing herein.

**Comment by indirectlylit** [comment] 2019-08-23 23:25
see also #4592

**Comment by indirectlylit** [comment] 2019-11-06 22:16
this is being addressed in ongoing changes in 0.13.0

specifically:

* we allow people to see how much has changed in an update before committing to the upgrade
* we automatically initiate import of updated content, so that it doesn't vanish unexpectedly
* "garbage collection" of deleted content should behave reliably

**Closed as completed by indirectlylit** 2019-11-06 22:16 UTC
Labels: TAG: ux update
