### ISSUE TITLE
epub location scrubber should update percentage as you move it

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4242] opened 2018-09-13 20:34 UTC
### Observed behavior

the progress percentage doesn't update until after you change it

![image](https://user-images.githubusercontent.com/2367265/45514195-9388f980-b759-11e8-8a52-e081333463e7.png)

### Expected behavior

I would expect the percentage to change as I move it so that I can see where I'm going

### User-facing consequences

harder to navigate to a particular location, e.g. "go to 56%"

### Context

develop

----

cc @christianmemije

**Comment by jav099** [comment] 2021-03-30 16:09
Hello, I'm new to open source contributions but I'd like to help with this issue.

**Comment by bjester** [comment] 2021-03-30 18:48
Might be worth attempting to reproduce this to see if it's still an issue. I may have fixed this in passing.

**Comment by jav099** [comment] 2021-03-30 21:06
I downloaded the app from the website and used the Ebook viewer to view a book. Can confirm that the issue is still there, when I move the slider, the percentage does not update until after I stop moving the slider.

**Comment by Pursottam6003** [comment] 2023-03-31 13:01
Hii @marcellamaki  @MisRob I would like to work on this issue if its open please assign me

**Comment by marcellamaki** [comment] 2023-03-31 13:32
Hi @Pursottam6003 - thank you for your interest in contributing to Kolibri! If you have not done so already, you can review the [developer documentation](https://kolibri-dev.readthedocs.io/en/develop/index.html) and proceed with getting Kolibri set up on your machine. 

I have noticed that you requested to work on a number of issues. Please start by working on just one issue at a time. I will assign you this issue since this was the first one that you commented on, and if you would like to work on others after you have opened a PR, just let us know.

You can add a comment here if you have questions as you are working. Thank you again for your interest!

**Comment by Pursottam6003** [comment] 2023-04-01 16:53
Hii @marcellamaki  Thank You for assigning me this issue 

While working on this issue i found the **progress percentage bar is changing while moving towrads the next page or previous page** 

Could you _please explain what expected behaviour_ you need and if its not solved please guide me how to reproduce this issue @indirectlylit @marcellamaki  

![image](https://user-images.githubusercontent.com/81693090/229304041-70c5208b-04c1-4755-9be4-3bfd477ea96b.png)



Currently i am in the **develop** branch 

I would love to solve this issue

**Comment by Pursottam6003** [comment] 2023-04-04 10:00
Hi @marcellamaki could you please reply so that I can move further

**Comment by MisRob** [comment] 2023-04-05 10:52
@Pursottam6003 

From the issue description

> 
> **Expected behavior**: I would expect the percentage to change as I move it so that I can see where I'm going
> **User-facing consequences**: harder to navigate to a particular location, e.g. "go to 56%"

It seems to me it's referring to a case when you click on the bar itself to navigate rather than using previous/next page buttons. From your description, it sounds to me that you perhaps navigated rather by previous/next buttons, is that right? Have you tried clicking the bar?

**Comment by Pursottam6003** [comment] 2023-04-16 18:32
Hii @marcellamaki  I have created  PR for this issue https://github.com/learningequality/kolibri/pull/10485 

Please review it whenever you are free :)  

Thank You

**Comment by nucleogenesis** [comment] 2023-05-09 17:36
Some follow up from @Pursottam6003's efforts here in #10485, I think we may have to close that attempt for now and reconsider our approach.

Their experience maps to my previous experience giving this a try inasmuch as we don't seem to be getting an accurate or reliable value for the current total number of pages. Perhaps this will require some research into alternative ePub libraries that suit our needs (although that would also be a significant amount of work) - or maybe there is something unclear about how the ePub lib works that would help us.

**Comment by Pursottam6003** [comment] 2023-05-09 17:49
> Some follow up from @Pursottam6003's efforts here in #10485, I think we may have to close that attempt for now and reconsider our approach.
> 
> Their experience maps to my previous experience giving this a try inasmuch as we don't seem to be getting an accurate or reliable value for the current total number of pages. Perhaps this will require some research into alternative ePub libraries that suit our needs (although that would also be a significant amount of work) - or maybe there is something unclear about how the ePub lib works that would help us.

It's okay sir I will try next time to completely solve this issue. I  agree that it needs a good understanding of epub and how to use such libraries.

Thank your for your review @nucleogenesis

**Comment by radinamatic** [comment] 2024-08-06 16:31
cc @pcenov

**Comment by pcenov** [comment] 2024-08-07 09:34
Hi @radinamatic, this is no longer extant in Kolibri 0.17 - the progress percentage is updated correctly in all supported browsers:

https://github.com/user-attachments/assets/d74d9dc8-3579-44b1-9ebf-5542dc49c903

**Comment by radinamatic** [comment] 2024-08-07 14:30
Closing as not extant on 0.17!

**Closed as completed by radinamatic** 2024-08-07 14:30 UTC
Labels: TAG: ux update, P1 - important, TODO: needs decisions, PLUGIN: epub, TODO: needs QA re-review
