### ISSUE TITLE
Content Import - `Content selected` count incorrectly reported

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5639] opened 2019-06-07 19:33 UTC
### Observed behavior

Replicating [these steps exactly](https://github.com/learningequality/kolibri/issues/5548#issuecomment-498432475), when selecting resources one by one in step 6, `Content selected` is reported correctly as **165 MB (3 resources)**, but if the **Select all** checkbox is used, it is reported incorrectly as **220 MB (4 resources)**. `KOLIBRI_DATA` folder on the external drive is new and contains **only** the 3 games exported in the previous steps.

![4th-resource](https://user-images.githubusercontent.com/1457929/59128419-4a717900-896a-11e9-8425-3272b10fbc18.gif)

### Expected behavior
 `Content selected` count should be accurate.

### User-facing consequences
Uncertainty about the size and number of resources to be imported

### Errors and logs
…

### Steps to reproduce
https://github.com/learningequality/kolibri/issues/5548#issuecomment-498432475

### Context
 * Kolibri version: 0.12.4b7 upgraded from 0.10.3
 * Operating system: Ubuntu 
 * Browser: both FF & Chrome

**Comment by jonboiser** [comment] 2019-06-07 20:37
This overestimation has always happened because we are not able to check an external drive's file system to see how much of an entire topic (sub)tree is actually available to import.

So, by clicking "Select All" at a given topic, the estimate of number of resources is an upper bound, since we use the "number of resources" annotation for that topic, which includes not only direct children leaf nodes, but also all descendants from its children tree nodes.

For the Funza example, it seems that the root node has 4 child leaf nodes, and zero topics, so by clicking "Select all", we get that over-estimate of 4 resources to import. It's easy to see that this is wrong and possibly fixable (since in this totally flat structure, we have access to the "importable" flag on child nodes) in this simple case, but if Funza had multiple levels of topics, we still would have to overestimate because checking "Select all" would assume that we are importing 100% of all child topics, even if not all of these topics were available to import.

**Comment by rtibbles** [comment] 2019-06-07 21:06
Seems like this is not a regression then, and will be best addressed by the content import annotation.

**Comment by rtibbles** [comment] 2019-06-07 21:06
Changed milestone accordingly.

**Comment by radinamatic** [comment] 2019-06-10 05:36
Right, should have remembered that I already filed the issue for this in the past... :woman_facepalming: 

Ok, looking forward to the content import annotation to fix this! Unless I forget again and file the issue for the third time... :blush:

**Closed as completed** 2019-11-19 13:25 UTC
Labels: bug, P1 - important
