### ISSUE TITLE
Android App - App stops syncing with the server

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8934] opened 2021-12-15 17:12 UTC
## Observed behavior
After installing the app and importing learners it gets synced with the server but then after completing some of the assigned lessons/quizzes I have to manually restart the app to get it synced. This worked for some period of time and then it completely stopped syncing and restarting the app or the server is not solving the issue.
I do see a `django.db.utils.OperationalError: database is locked` error in the Android logs so this could be the cause - attaching both the Android and Ubuntu logs and DBs.

## Steps to reproduce the issue
1. Install the following Android build: https://buildkite.com/learningequality/kolibri-android-installer/builds/3637
2. Launch the app and login as a Learner
3. Interact with the app by completing a lesson/quiz and observe the sync status on the server at the Coach>Class>View learners page

## Additional information
![2021-12-15_18-37-42](https://user-images.githubusercontent.com/79847249/146232141-de924688-515b-45c4-9907-e41eb6d0c095.png)

## Logs and DB files: 
[UbuntuLogsAndDB.zip](https://github.com/learningequality/kolibri/files/7721388/UbuntuLogsAndDB.zip)
[AndroidLogsAndDB.zip](https://github.com/learningequality/kolibri/files/7721389/AndroidLogsAndDB.zip)

## Usage Details
 - OS: Android 7, Samsung S7

**Comment by pcenov** [comment] 2021-12-15 17:12
@radinamatic

**Comment by rtibbles** [comment] 2021-12-15 17:14
Hrm, it does seem to continue syncing after the database is locked error though - so we seem to have succeeded in making it robust to that.

**Comment by pcenov** [comment] 2021-12-15 17:26
Interesting... Adding that so far I've been able to 'fix' any syncing issues which I've been experiencing with simply restarting either the app or the server but no luck in this case so hoping that the logs and databases would give you some insight into what might be the root cause.

**Comment by radinamatic** [comment] 2021-12-16 00:34
I'm not able to reproduce this with the latest [assets APK](https://buildkite.com/learningequality/kolibri-android-installer/builds/3633) and DEB on Ubuntu 18.04: syncing continues without problems for 2 hours after the installation while I was interacting with the resources, and there was no need to restart the app... 🤔 

1 | 2
--- | ---
![Selection_032](https://user-images.githubusercontent.com/1457929/146286293-d29bd6a0-fcd6-4cc9-aff5-daef7147fc61.png) | ![Selection_033](https://user-images.githubusercontent.com/1457929/146286311-0b2d35a9-fb42-4310-9b8b-68961541cee0.png)

**Comment by rtibbles** [comment] 2021-12-16 17:12
Just to clarify @pcenov - the symptom of it 'stopping' syncing, is indications of syncing on the server UI stopping, or data actually no longer showing up in the server for recent activity, or both?

**Comment by radinamatic** [comment] 2021-12-16 17:18
@pcenov shared during our sync-up today that he was not able to replicate the syncing problem with the latest APK asset from the 0.15 branch, same as me. 

We'll keep syncing under close observation until the release and 🤞🏽 stays healthy!

**Comment by pcenov** [comment] 2021-12-17 17:03
Yup, also no issues with syncing while testing on [this build](https://buildkite.com/learningequality/kolibri-python-package/builds/4673) today with 3 learners imported to the same device.
To answer @rtibbles question: the symptom of stopping syncing was that data was actually no longer showing up in the server and newly assigned lessons not showing on the learner's device.

**Comment by radinamatic** [comment] 2021-12-17 17:46
Closing this as not extant anymore on the latest assets from the 0.15 branch.

**Closed as completed by radinamatic** 2021-12-17 17:46 UTC
