### ISSUE TITLE
kolibri start command can't detect if the port is not available.

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4189] opened 2018-08-24 02:57 UTC
### Observed behavior
I have running KA LIte server on port 8008 then I run the `kolibri start` command at the command prompt and I used the same port 8008 then kolibri say it running on that port but when I check it it's not, still KA Lite using that port.

### Expected behavior
`kolibri start` command should have an error that the port is not available.

### Errors and logs
![screen shot 2018-08-24 at 10 53 13 am](https://user-images.githubusercontent.com/8663934/44562392-fe16cd00-a78b-11e8-933b-65b9bf2a7d58.png)

### Context

Tell us about your environment, including:
 * Kolibri version: 0.10.1
 * Operating system: Windows 10
 * Browser

**Comment by benjaoming** [comment] 2018-08-27 12:09
This should be addressed in #3285

**Comment by indirectlylit** [comment] 2018-08-27 16:58
also related and targeted to 0.11.0: https://github.com/learningequality/kolibri/issues/1707

**Comment by benjaoming** [comment] 2018-08-27 17:43
@indirectlylit this was previously fixed in https://github.com/learningequality/kolibri/issues/3048, so the issue is a regression in 0.10 - not sure when, why etc :)

**Comment by lyw07** [comment] 2018-09-25 23:12
@mrpau-richard Hi! I'm wondering if you still have the `kolibri.log` file when this error happened. Thank you! My guess is that it detected the port was not available, but the error went to the log file, since the program checks the port availability right before the server starts.

**Comment by mrpau-richard** [comment] 2018-09-26 07:47
@lyw07 your right, it did show in log file that the port is not available. But the logs appear only in the `server.log` not in the `kolibri.log`. I think, we should propagate those error logs at the command prompt or terminal to notify that the port is not available.

Here are my log files:
[server.log](https://github.com/learningequality/kolibri/files/2418597/server.log)
[kolibri.log](https://github.com/learningequality/kolibri/files/2418598/kolibri.log)

**Comment by lyw07** [comment] 2018-09-26 17:19
thank you! @mrpau-richard That makes sense to me. I will find ways to let the error show up at the terminal.

**Closed as completed** 2018-10-05 15:07 UTC
Labels: bug, P1 - important
