### ISSUE TITLE
Some Khan Academy (en) exercises are not properly load on Ubuntu

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5851] opened 2019-08-06 09:51 UTC
### Observed behavior
Some Khan Academy exercises did not properly load on Ubuntu 18.04 & 16.04 using Firefox and Chrome this was reported by @radinamatic and @mrpau-julius on [Slack](https://learningequality.slack.com/archives/CAVFL3J67/p1565038754002000)

At Ubuntu 14.04 I did not reproduce this issue.

### Expected behavior
All Khan Academy exercises should load properly on Firefox and Chrome

### User-facing consequences

…

### Errors and logs
![2019-08-05_22-53-22](https://user-images.githubusercontent.com/8663934/62529347-11be2500-b871-11e9-935d-2adc608eb87b.png)
![2019-08-05_22-38-56](https://user-images.githubusercontent.com/8663934/62529362-184c9c80-b871-11e9-959a-a44a3be3b872.png)
![2019-08-05_22-38-13](https://user-images.githubusercontent.com/8663934/62529380-1e427d80-b871-11e9-8351-6ae95ae011f8.png)
![image](https://user-images.githubusercontent.com/8663934/62529397-25698b80-b871-11e9-9d70-08d6ac80bd50.png)

Please wrap errors in triple backticks for clean formatting like this:
```
01:10 info: something happened
01:12 error: something bad happened
```
-->

…

### Steps to reproduce
* Assuming that you are using Ubuntu 16.04 or 18.04
* Install `kolibri-server 0.3.0` using this [instructions](https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed)
* Import the channel Khan Academy(en)
* Try to browse the exercises on that channel

### Context

Tell us about your environment, including:
 * Kolibri version: kolibri-server 0.3.0
 * Operating system: Ubuntu 16.04 & 18.04
 * Browser: Firefox and Chrome

cc @kollivier @ralphiee22

**Comment by mrpau-julius** [comment] 2019-08-07 04:45
The same issue on CK-12 testing channel failed to load the resources of HTML5, Exercises and Funza.
![image](https://user-images.githubusercontent.com/38421180/62595143-bb53f380-b90f-11e9-86ba-108d2ca12b87.png)

**Comment by intelliant01** [comment] 2019-08-14 12:35
This may be related - https://github.com/learningequality/kolibri-server/issues/24.

**Comment by indirectlylit** [comment] 2019-08-16 23:37
I think that's correct if this can only be reproduced in `kolibri-server`. Closing as a duplicate of learningequality/kolibri-server#24

**Closed as completed by indirectlylit** 2019-08-16 23:37 UTC
