### ISSUE TITLE
Facility settings - allow learners and coaches to edit their username - does not work.

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#5594] opened 2019-05-30 10:08 UTC
### Observed behavior
This is really weird behavior.  Under the `Facility settings` page, I've checked the `allow learners and coaches to edit their username` as a super admin user.

Tested on iPad 2 simulator-Safari 9.3 and on macOS - both Chrome 74.0.xxx and Safari 12.1.1

The `username` was shown as editable (textbox) on first attempt - but after I was successful at changing, logging-out then logging-in again - now it does not show the textbox. I have refreshed the browser using `Cmd+R` to reload.

This behaviour also manifests the other way around.  When setting is unchecked, then the textbox on the client browser is still shown even after logging-out or reloading the page.

**NOTE: But after about 4 minutes that I haven't touched the browsers, then come back to them and reload the page, the correct behaviour is shown.**  Are we using some timer of some sort for the correct behaviour to propagate to the client browsers?

I have attached a `.gif` to supplement this weird behaviour.  
![kolibri--v0 12 4b4--facility-settings--allow learners and coaches to edit their username](https://user-images.githubusercontent.com/175580/58625565-4e1b5500-8305-11e9-9e0f-a4660cd9ffbc.gif)

### Expected behavior
If the setting is checked, the user can change username via textbox.  If unchecked, the user is shown only the username but cannot change it.

### User-facing consequences
If setting does not work, super admin user must manually change username per user. 

### Errors and logs
N/A

### Steps to reproduce
1. Login as super admin then check the `allow learners and coaches to edit their username` setting under the `Facility settings` page.  Logout.
1. Login as learner, go to the Profile page, then edit the username, save, then logout.
1. Login as super admin, then uncheck the setting. Logout.
1. Login as learner, go to the Profile page, then notice the username cannot be edited, logout.
1. Login as super admin, then check the setting to enable. Logout.
1. Login as learner, go to the Profile page, then notice the username still cannot be edited.

You may have to reload the page for the settings to take effect.  But after it is enabled back, the textbox will not re-appear anymore on the learner account.

### Context
Tell us about your environment, including:
 * Kolibri version: 0.12.4-beta4
 * Operating system: server=Ubuntu 18.04 vm
 * Browsers: Safari 12.1.1 and Chrome 74.0.xxx both under macOS 10.14.5, Safari 9.3 under iPad 2 on iOS 9.3 simulator

**Comment by jonboiser** [comment] 2019-05-30 19:00
This looks familiar to #5547, I'll see if I can reproduce it the same way I did there (with a difference between the local devserver and PEX).

**Comment by jonboiser** [comment] 2019-05-30 19:37
> (with a difference between the local devserver and PEX).

Yeah, same thing is happening. Running with the devserver, refreshing the App does cause the new settings to be reflected. With the PEX, the settings are not reflected after refreshing.

**Comment by rtibbles** [comment] 2019-05-30 19:40
I think it is because of the bootstrapping here: https://github.com/learningequality/kolibri/blob/release-v0.12.y/kolibri/plugins/user/templates/user/user.html#L6 (we had previously removed the caching on this, due to a similar issue, but now the entire page is cached, so we should just remove the bootstrapping).

**Comment by jonboiser** [comment] 2019-05-31 00:54
Yeah, that looks like the cause. So to fix this issue, just remove that line 6?

**Comment by rtibbles** [comment] 2019-05-31 03:56
Yes, should do it.

**Comment by rtibbles** [comment] 2019-06-07 02:45
Fixed in #5601

**Closed as completed by rtibbles** 2019-06-07 02:45 UTC
Labels: bug, P1 - important
