### ISSUE TITLE
Webpack build file missing, front-end assets cannot be loaded Error

### ISSUE THREAD

**Issue by rationality6** [learningequality/kolibri#5866] opened 2019-08-11 07:46 UTC
Instructions:

Hello, I followed the instruction in Kolibri developer documentation.
And after run server with the command "yarn run devserver" with Pipenv set, I got this error below. I tried several times set env and unset, but couldn't find a way to fix. Did I miss to type some Webpack bundle command?

server side
```
kolibri.core.webpack.hooks.WebpackError: Webpack build file missing, front-end assets cannot be loaded. Problems loading: /Users/hyunahn/.local/share/virtualenvs/kolibri-nE0xMgB-/lib/python3.7/site-packages/kolibri_exercise_perseus_plugin/build/_stats.json
ERROR    "GET /en/setup_wizard/ HTTP/1.1" 500 227678
```

client side

```

Request Method: | GET
-- | --
http://localhost:8000/en/setup_wizard/
1.11.22
WebpackError
Webpack build file missing, front-end assets cannot be loaded. Problems loading: /Users/hyunahn/.local/share/virtualenvs/kolibri-nE0xMgB-/lib/python3.7/site-packages/kolibri_exercise_perseus_plugin/build/_stats.json
/Users/hyunahn/github/kolibri/kolibri/core/webpack/hooks.py in _stats_file_content, line 139
/Users/hyunahn/.local/share/virtualenvs/kolibri-nE0xMgB-/bin/python3
3.7.3
['/Users/hyunahn/github/kolibri/kolibri/dist',  '/Users/hyunahn/.local/share/virtualenvs/kolibri-nE0xMgB-/bin',  '/Users/hyunahn/.local/share/virtualenvs/kolibri-nE0xMgB-/lib/python37.zip',  '/Users/hyunahn/.local/share/virtualenvs/kolibri-nE0xMgB-/lib/python3.7',  '/Users/hyunahn/.local/share/virtualenvs/kolibri-nE0xMgB-/lib/python3.7/lib-dynload',  '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/Users/hyunahn/.local/share/virtualenvs/kolibri-nE0xMgB-/lib/python3.7/site-packages',  '/Users/hyunahn/github/kolibri']
Sun, 11 Aug 2019 16:46:33 +0900


````

Tell us about your environment, including:
 * Kolibri version: latest dev
 * Operating system: Mac os 10.14.6
 * Browser: Chrome

**Comment by rtibbles** [comment] 2019-08-12 17:31
Thanks for the report - this is a duplicate of #5865, so I am closing this in favour of that issue. Please track the progress there!

In the meantime, you can still run the devserver by running `kolibri plugin kolibri_exercise_perseus_plugin disable` first.

**Closed as completed by rtibbles** 2019-08-12 17:31 UTC

**Comment by rationality6** [comment] 2019-08-15 04:35
Thank you! After disabling the plugin, works very well.
