### ISSUE TITLE
"Import and export users" section in Facility > Data should not appear in the Windows Kolibri App

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7767] opened 2021-01-27 09:36 UTC
### Observed behavior

In Kolibri App, on the Facility > Data page the Export Users functionality is not working. On-click the Export button nothing happens. 

@kollivier, a question to clarify the importance of this issue: Is the local export of users in the app context disabled as it is with the local export of users under the Android app?

![usersExport](https://user-images.githubusercontent.com/72492554/105972072-ebf39400-6093-11eb-8661-c2e8eb98f780.gif)

### Expected behavior

~On-click the Export button a CSV file must be generated and a prompt window for selecting a download location locally is displayed to the user.~

This functionality shouldn't be available to users when using the Windows App (which is distinct from running Kolibri using Windows as a server and viewing the frontend in a browser).

### User-facing consequences

Users of Kolibri App are unable to export user accounts data.

### Steps to reproduce

1. Launch the Kolibri App
2. Login as an admin user
3. Click the hamburger menu
4. Click Facilities
5. Click the Data tab
6. Click the Export users button

### Context

Kolibri 0.14.3 - App
Windows 10 vm
Windows 7 vm

**Comment by jredrejo** [comment] 2021-01-27 12:47
hi  @metodimilevqa is this a problem you found only in windows 10 or you can reproduce it in other OS too?

**Comment by metodimilevqa** [comment] 2021-01-27 12:52
Hi @jredrejo. The current testing session addresses the Kolibri app under Windows 10, I didn't do any tests with Windows 7 for example or other OSes. I could check Windows 7 as well but I'll need some setup time before doing the check

**Comment by jredrejo** [comment] 2021-01-27 13:19
@metodimilevqa if you can test other windows versions it would be great. I can't reproduce the problem on Linux and I'd like to know if it is a windows 10 only problem.
By chance, did you have any antivirus enabled that might have blocked the creation of the exported csv in your filesystem?

**Comment by metodimilevqa** [comment] 2021-01-27 13:22
@jredrejo OK, I'll do the check in Windows 7 and will update you about the result. No antivirus enabled on both host and guest machines.

**Comment by metodimilevqa** [comment] 2021-01-27 13:48
@jredrejo, an update - I confirm the issue is also experienced with Windows 7

**Comment by kollivier** [comment] 2021-01-27 16:31
If it's in the app, the bug is that the Export Users section is visible. The app doesn't support downloading or uploading files yet.

**Comment by jredrejo** [comment] 2021-01-27 18:02
ah, I hadn't seen the "app" word :(
That explains why I could not reproduce it in Linux as there's not a Linux app ...

**Comment by jonboiser** [comment] 2021-01-28 20:00
> If it's in the app, the bug is that the Export Users section is visible. The app doesn't support downloading or uploading files yet.

@kollivier I renamed the issue. Can I assign this to you? I'm guessing it's something to do with the user agent string test that's used to infer whether we're in "app" mode or not?

**Comment by rtibbles** [comment] 2024-01-03 21:23
Windows app is no longer under active development, but in investigating, I uncovered this #11689 - closing in favour of that.

**Closed as completed by rtibbles** 2024-01-03 21:23 UTC
Labels: bug, OS: Windows, APP: Facility, DEV: frontend
