### ISSUE TITLE
It's possible to complete to the next step of creating a new facility with an empty "Facility name" field, just making a space in the field

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7565] opened 2020-10-16 07:09 UTC
Environment; Raspberry Pi 3B+
OS: Kolibri 0.14.3 tested on Mac mini (Mid 2011) 
Browser: Google Chrome latest
Severity; minor
Preconditions; advanced setup is selected and the device name is chosen
Steps to reproduce;

1. Tap on the "Create or import facility"
2. Select the kind of  facility
3. Tap on the facility name filed
4. Make one space in the field
5. Click "continue"
6. Pay attention that it's possible to proceed to the next step with an empty facility name field

Actual result; It's possible to complete to the next step of creating a new facility with an empty "Facility name" field, just making a space in the field

Expected result; The error should be displayed after trying to proceed to the next step with an empty "Facility Name" field

Attachment; http://e.pc.cd/FJbotalK

**Comment by jredrejo** [comment] 2020-10-19 15:38
Confirmed this is an existing bug in 0.14.x
@jonboiser  #7561 didn't fix it

**Comment by jonboiser** [comment] 2020-10-19 16:03
#7574 is the fix for this issue. I just made a reference in #7561 because something there was relevant to the fix for this issue.

**Closed as completed** 2020-10-19 22:27 UTC
Labels: bug, P2 - normal
