### ISSUE TITLE
Missing lessons and activity on facility import with user activity

### ISSUE THREAD

**Issue by cyberorg** [learningequality/kolibri#7445] opened 2020-08-06 05:15 UTC
### Observed behavior

Running "kolibri manage sync --baseurl (...) --username (...) --password (...) --verbosity 3" to import "Teacher Training" facility does not import lessons.

…

### Expected behavior

Lessons and activities should be imported
…

### User-facing consequences

No lessons for the learners and no activity reports for the coaches.
…

### Errors and logs

Logs on the server side:
```
INFO 2020-08-06 10:27:31,256 kolibri.core.analytics.utils Ping succeeded! (response: {'id': 957507, 'messages': []})
INFO 2020-08-06 10:27:40,289 cherrypy.access 169.149.232.171 - - "GET /api/auth/session/current/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:27:42,663 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:27:45,676 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:27:48,092 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:27:50,999 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:27:53,582 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:27:56,054 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:27:58,667 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:01,626 cherrypy.access 169.149.232.171 - - "GET /api/public/info/" 200 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:01,891 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:02,010 cherrypy.access 169.149.205.129 - - "GET /api/morango/v1/morangoinfo/1/" 200 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:02,833 cherrypy.access 169.149.205.129 - - "GET /api/public/v1/facility/" 200 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:04,413 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:06,969 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:07,172 cherrypy.access 169.149.205.129 - - "GET /api/morango/v1/certificates/" 200 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:09,354 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:11,686 cherrypy.access 169.149.205.129 - - "POST /api/morango/v1/certificates/" 201 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:11,747 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:11,981 cherrypy.access 169.149.205.129 - - "POST /api/morango/v1/nonces/" 201 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:12,437 cherrypy.access 169.149.205.129 - - "POST /api/morango/v1/syncsessions/" 201 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:13,048 morango.sync.operations Serializing records
INFO 2020-08-06 10:28:13,665 morango.sync.operations Serialization complete
INFO 2020-08-06 10:28:13,689 morango.sync.operations Queueing records into buffer
INFO 2020-08-06 10:28:13,758 morango.sync.operations Queueing complete
INFO 2020-08-06 10:28:13,797 cherrypy.access 169.149.205.129 - - "POST /api/morango/v1/transfersessions/" 201 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:14,062 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:16,297 cherrypy.access 169.149.205.129 - - "GET /api/morango/v1/buffers/" 200 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:16,453 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:18,803 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:20,634 cherrypy.access 169.149.205.129 - - "DELETE /api/morango/v1/transfersessions/c4a6ffa1a7c64f3984338dca02e2f57f/" 204 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:21,337 cherrypy.access 169.149.205.129 - - "POST /api/morango/v1/transfersessions/" 201 0 "" "python-requests/2.21.0"
INFO 2020-08-06 10:28:21,916 cherrypy.access 169.149.232.171 - - "GET /coach/api/notifications/" 200 0 "http://iadahu.intelliant.net:8080/en/coach/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
INFO 2020-08-06 10:28:22,109 cherrypy.access 169.149.205.129 - - "DELETE /api/morango/v1/transfersessions/ed43ed80d0c246eeaf6c2d5f38fcdcdd/" 204 0 "" "python-requests/2.21.0"
```

Logs on client side:
```
INFO 2020-08-06 10:27:59,828 kolibri.utils.cli Invoking command sync --baseurl http://iadahu.intelliant.net:8080/ --username ... --password ... --verbosity 3
INFO 2020-08-06 10:28:01,318 kolibri.core.discovery.utils.network.client Attempting connections to variations of the URL: http://iadahu.intelliant.net:8080/
INFO 2020-08-06 10:28:01,331 kolibri.core.discovery.utils.network.client Attempting connection to: http://iadahu.intelliant.net:8080/
INFO 2020-08-06 10:28:01,671 kolibri.core.discovery.utils.network.client Success! We connected to: http://iadahu.intelliant.net:8080/api/public/info/
INFO 2020-08-06 10:28:11,824 kolibri.core.auth.management.commands.sync Syncing has been initiated (this may take a while)...
INFO 2020-08-06 10:28:12,767 kolibri.core.auth.management.commands.sync Creating pull transfer session
INFO 2020-08-06 10:28:17,808 kolibri.core.auth.management.commands.sync Receiving data (214/214, 292.40KB)
INFO 2020-08-06 10:28:20,700 kolibri.core.auth.management.commands.sync Completed pull transfer session
INFO 2020-08-06 10:28:21,050 kolibri.core.auth.management.commands.sync Creating push transfer session
INFO 2020-08-06 10:28:22,167 kolibri.core.auth.management.commands.sync There are no records to transfer
INFO 2020-08-06 10:28:22,168 kolibri.core.auth.management.commands.sync Completed push transfer session
INFO 2020-08-06 10:28:22,193 kolibri.core.auth.management.commands.sync Syncing has been completed.
```
Origin lessons and activities:
![origin-lessons-activities](https://user-images.githubusercontent.com/1300602/89493423-bb602b00-d7d1-11ea-94da-895bf1e54992.png)
Running Sync:
![image](https://user-images.githubusercontent.com/2367265/89585415-a8aa1e00-d7f2-11ea-9e19-05b22603093a.png)
No lessons and activities on import:
![no-lessons-on-import](https://user-images.githubusercontent.com/1300602/89493444-cca93780-d7d1-11ea-9cab-67c27ec59b62.png)

Content is available on both sides.
…

### Steps to reproduce

1. Run: `kolibri manage sync --baseurl (...) --username (...) --password (...) --verbosity 3` to import "Teacher Training, compare "Coach – Teacher Training" on http://iadahu.intelliant.net:8080/ and client system.

OR
2. Set up a new facility, create lessons, let learners start some lessons, now import the facility on another system.
…

### Context

On server:
```
Version:           0.14.0b16
OS:                Linux-5.3.7-050307-generic-x86_64-with-Ubuntu-18.04-bionic
Python:            3.6.9
Installer:         apt
Server:            Kolibri internal server
Database:          postgresql
Free disk space:   404 GB
Server time:       Thu Aug 06 2020 10:41:39 GMT+0530 (India Standard Time)
Server timezone:   Asia/Kolkata
```
On Client:
```
Version:           0.14.0b16
OS:                Linux-5.4.0-42-generic-x86_64-with-Ubuntu-20.04-focal
Python:            3.6.11
Installer:         apt
Server:            Kolibri internal server
Database:          postgresql
Free disk space:   241 GB
Server time:       Thu Aug 06 2020 10:42:21 GMT+0530 (India Standard Time)
Server timezone:   Asia/Kolkata
```

…

**Comment by cyberorg** [comment] 2020-08-06 05:37
In another facility, lessons show up, but not the activities

Source:
![another-facility-source](https://user-images.githubusercontent.com/1300602/89494972-e7c97680-d7d4-11ea-8830-5398cc1d9015.png)

After import:
![another-facility-imported](https://user-images.githubusercontent.com/1300602/89495007-f57efc00-d7d4-11ea-9ed3-fba4c3ed8d85.png)

**Comment by jonboiser** [comment] 2020-08-06 19:44
Hi @cyberorg I removed your username and password from your original post, but they are still visible in some of the screenshots (and are still accessible on GitHub since all edits to comments are saved). For your security, please make sure that you not share this info publicly.

This does look like a bug that the Quizzes in the "Teacher Training" Facility haven't been synced. Are there any differences you can think of between the "Teacher Training" and "Study Circle" quizzes ("Study Circles"" quizzes look like they _were_ imported).

As for the missing "Class Activity", this is a known issue. The data that generates the Activity is not currently synced. 

Another known issue is that if you import lessons/quizzes _but not their content_ you may also see inaccurate progress information like "15 have not started" (on the importing server) even if there was lesson/quiz progress on the source server.

**Comment by indirectlylit** [comment] 2020-08-06 21:41
I've updated the screenshot and deleted the previous edit revisions, so the password should not be visible anymore

**Comment by intelliant01** [comment] 2020-08-07 00:46
Hi @jonboiser , @cyberorg is my team mate and we had shared the credentials on purpose for ease and speed of replication at your end as this is a temporary test instance created only for the purpose of reporting these issues.

Do note the very first bug that the lessons in the "Teacher Training" facility do not sync despite all content being present on the destination.

> This does look like a bug that the Quizzes in the "Teacher Training" Facility haven't been synced.

We don't have any quizzes as yet as part of this test run. Not sure where do you see them.

> Another known issue is that if you import lessons/quizzes but not their content you may also see inaccurate progress information ...

Apologies for the lack of clarity in steps to reproduce though it is mentioned above "Content is available on both sides.". We had ensured that the requisite content is already present on the destination, yet no progress information has been synced. And this experience is random from facility to facility. That is why we shared the information about "Study Circle - Sanjay".

Do note that we have experienced these issues while attempting p2p sync across 5 devices installed with 0.14.0b16 on Linux (with and without kolibri-server) and Windows.

**Comment by intelliant01** [comment] 2020-08-07 16:44
> Do note the very first bug that the lessons in the "Teacher Training" facility do not sync despite all content being present on the destination.

We have done a complete re-run of tests with 0.14 and found the core cause of the problem. Filed this issue #7453 

And I believe the real time `Class Activity` not syncing to destination and not showing on the `Class Home` dashboard is a known issue but am unable to spot one in github. If not present, I shall create one. Once this is confirmed, this issue may be closed.

**Comment by jonboiser** [comment] 2020-08-07 18:59
Thanks for figuring this out @intelliant01 ! I will create a new issue specifically for the missing Class Activity and close this one out.

I am fairly confident that #7453 is the reason for the missing lessons (and quizzes have the same issue).

**Closed as completed by jonboiser** 2020-08-07 18:59 UTC
Labels: bug, TAG: new feature
