### ISSUE TITLE
Class activity is not being recorded - beta11

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#5217] opened 2019-02-28 19:54 UTC
### Observed behavior

![ubuntu 16 04 3 start running - oracle vm virtualbox_445](https://user-images.githubusercontent.com/1457929/53594141-7bd3ef00-3b9a-11e9-924d-162b65e8a5fa.png)

### Expected behavior
…

### User-facing consequences
…

### Errors and logs
[kolibri.log](https://github.com/learningequality/kolibri/files/2916667/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/2916668/server.log)

[Notification DB](https://learningequality.slack.com/files/U0LJG17EK/FGK4N0DRN/notifications.sqlite3)
There should have been several lesson and quiz interactions by user `abbyl` in the last 30 minutes, and more recently quiz interaction by `peterb`

### Steps to reproduce

…

### Context
Version:           0.12.0b11
OS:                Linux-4.4.0-142-generic-x86_64-with-Ubuntu-16.04-xenial
Installer:         apt
Server:            Kolibri internal server

cc @rtibbles @jonboiser @indirectlylit

**Comment by indirectlylit** [comment] 2019-02-28 20:34
Notes so far:

* the `LearnerProgressNotification` table appears to be empty
* on the surface, looks very similar to #5113
* nothing of interest in the logs

**Comment by indirectlylit** [comment] 2019-02-28 22:58
still can't reproduce locally. made a PR here with some extra logging: https://github.com/learningequality/kolibri/pull/5221

**Comment by mrpau-julius** [comment] 2019-03-01 04:46
same issue on kolibri-server.
![image](https://user-images.githubusercontent.com/38421180/53616953-0ad71a80-3c20-11e9-8f6e-55c70c347dde.png)

**Comment by jredrejo** [comment] 2019-03-01 07:33
Fixed on #5224

**Closed as completed by jredrejo** 2019-03-01 07:33 UTC
Labels: bug, P0 - critical
