### ISSUE TITLE
Remaining question count shows in negative

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#3292] opened 2018-03-05 07:19 UTC
### Observed behavior
When we submit exam after attempting some questions, it shows negative question count remaining.

For more understanding see attached screenshot.

### Expected behavior
Remaining question count should be positive.

### Steps to reproduce
1. Assign exam to the learner.
2. Login with learner.
3. Attempt few questions from exam.
4. Click on submit exam.
5. It will show pop-up with negative count.

### Context

 * Kolibri version : Kolibri 0.4.9
 * Operating system : ubuntu 14.04
 * Browser : Chrome

### Screenshots
![img-2009](https://user-images.githubusercontent.com/12776071/36962023-d89dec1a-2073-11e8-9018-a67a47deff50.JPG)

**Comment by ralphiee22** [comment] 2018-03-05 07:24
This is a duplicate of https://github.com/learningequality/kolibri/issues/3244

**Closed by ralphiee22** 2018-03-05 07:24 UTC
