### ISSUE TITLE
Missing snackbar confirmations when selecting/unselecting individual topics/resources

### ISSUE THREAD

**Issue by MindfulQA** [learningequality/kolibri#7648] opened 2020-10-29 04:36 UTC
### Observed behavior

The user does not receive snackbar confirmations when selecting or unselecting single topics or resources (only if they select or unselect all).

Screen recording:

https://drive.google.com/file/d/1r4qe9p6JrduJGuVykxc1RD1m5agqujVv/view

…

### Expected behavior

The user should see snackbar confirmations when they select or unselect individual topics or resources.
…

### User-facing consequences

The user may not be sure that the items were really selected properly, since they do receive confirmation when all are selected - so the fact that they're missing here may prove to be slightly confusing.
…

### Errors and logs

N/A
…

### Steps to reproduce

1. Open Kolibiri desktop app and log in to Coach account
2. Click on the "Plan" tab at the top of the page.
3. Click on the "Quizzes" tab
4. Click the "New Quiz" button
5. Click on a channel.
6. Click the check box next to a topic.
7. Observe that there is no snackbar confirmation in the lower left corner.
8. Click the same check box again to unselect the topic.
9. Observe that there is no snackbar confirmation in the lower left corner.

Testing note - scenario in line 65:

https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-create-quiz.feature

…

### Context

macOS Catalina 12.15.7 - Kolibri version 0.14
…

**Comment by jonboiser** [comment] 2020-11-03 20:28
I'm thinking this might be have the same root cause as #7536 and looks to be fixed in 0.14.4

**Closed as completed by jonboiser** 2020-11-03 20:28 UTC
