### ISSUE TITLE
'add new class' button is misplaced on mobile

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2278] opened 2017-09-25 22:50 UTC
currently implemented using floats, which causes ugliness:

![image](https://user-images.githubusercontent.com/2367265/30834702-333ca600-a209-11e7-82fc-4acffb0ac363.png)

**Comment by indirectlylit** [comment] 2017-09-25 22:51
![image](https://user-images.githubusercontent.com/2367265/30834762-72ba5a34-a209-11e7-87d7-0332696b90e7.png)

**Comment by rtibbles** [comment] 2017-09-26 19:30
Duplicate of #2262

**Closed by rtibbles** 2017-09-26 19:30 UTC
Labels: Beginner issue
