### ISSUE TITLE
Videos initially fail to play in Safari on MacOS and any iOS browser with 0.15.0

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#9041] opened 2022-01-25 23:59 UTC
## Observed behavior

- Videos often fail to play initially on Apple devices
- Refreshing the page sometimes resolves the issue
![Screenshot from 2022-01-25 15-40-18](https://user-images.githubusercontent.com/819838/151078078-336b3197-f43a-4bc4-83f9-81b08ee828df.png)

## Errors and logs

```
ERROR    ValueError('Response body exceeds the declared Content-Length.',)
Traceback (most recent call last):
  File "/home/bjester/.pex/install/kolibri-0.15.0-py2.py3-none-any.whl.4cc1abd08f451d6591d19b28911ed496f496fa7b/kolibri-0.15.0-py2.py3-none-any.whl/kolibri/dist/cheroot/server.py", line 1287, in communicate
    req.respond()
  File "/home/bjester/.pex/install/kolibri-0.15.0-py2.py3-none-any.whl.4cc1abd08f451d6591d19b28911ed496f496fa7b/kolibri-0.15.0-py2.py3-none-any.whl/kolibri/dist/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/home/bjester/.pex/install/kolibri-0.15.0-py2.py3-none-any.whl.4cc1abd08f451d6591d19b28911ed496f496fa7b/kolibri-0.15.0-py2.py3-none-any.whl/kolibri/dist/cheroot/wsgi.py", line 145, in respond
    self.write(chunk)
  File "/home/bjester/.pex/install/kolibri-0.15.0-py2.py3-none-any.whl.4cc1abd08f451d6591d19b28911ed496f496fa7b/kolibri-0.15.0-py2.py3-none-any.whl/kolibri/dist/cheroot/wsgi.py", line 237, in write
    'Response body exceeds the declared Content-Length.',
ValueError: Response body exceeds the declared Content-Length.

ERROR    ValueError('Response body exceeds the declared Content-Length.',)
Traceback (most recent call last):
  File "/home/bjester/.pex/install/kolibri-0.15.0-py2.py3-none-any.whl.4cc1abd08f451d6591d19b28911ed496f496fa7b/kolibri-0.15.0-py2.py3-none-any.whl/kolibri/dist/cheroot/server.py", line 1287, in communicate
    req.respond()
  File "/home/bjester/.pex/install/kolibri-0.15.0-py2.py3-none-any.whl.4cc1abd08f451d6591d19b28911ed496f496fa7b/kolibri-0.15.0-py2.py3-none-any.whl/kolibri/dist/cheroot/server.py", line 1077, in respond
    self.server.gateway(self).respond()
  File "/home/bjester/.pex/install/kolibri-0.15.0-py2.py3-none-any.whl.4cc1abd08f451d6591d19b28911ed496f496fa7b/kolibri-0.15.0-py2.py3-none-any.whl/kolibri/dist/cheroot/wsgi.py", line 145, in respond
    self.write(chunk)
  File "/home/bjester/.pex/install/kolibri-0.15.0-py2.py3-none-any.whl.4cc1abd08f451d6591d19b28911ed496f496fa7b/kolibri-0.15.0-py2.py3-none-any.whl/kolibri/dist/cheroot/wsgi.py", line 237, in write
    'Response body exceeds the declared Content-Length.',
ValueError: Response body exceeds the declared Content-Length.

```
![Screenshot from 2022-01-25 16-09-53](https://user-images.githubusercontent.com/819838/151080908-832971be-4ace-4240-8e4c-ec4e3d431c6b.png)
![Screenshot from 2022-01-25 16-09-03](https://user-images.githubusercontent.com/819838/151080922-a72c1020-4383-4af4-a7fc-9b40f4fec94d.png)

## Expected behavior

- Videos are served and played properly from Kolibri on Safari and iOS

## User-facing consequences

- Implementations using Apple devices likely impacted

## Steps to reproduce

- View otherwise supported video in Safari on a Mac running MacOS Catalina, Big Sur, or Monterey
- Also reproducible on iOS devices
- Reproduced through Browserstack

## Context

Kolibri 0.15.0
MacOS 10.15.7 (Catalina)
Safari 13.1+
Forum: https://community.learningequality.org/t/kolibri-0-15-the-media-could-not-be-loaded-either-because-the-server-or-network-failed-or-because-the-format-is-not-supported/2289

**Comment by pcenov** [comment] 2022-01-26 08:04
Looks like a duplicate of https://github.com/learningequality/kolibri/issues/6242

**Comment by rtibbles** [comment] 2022-01-26 16:45
I think it's the same as your last report there, @pcenov - although I think some of the previous reports in that issue are not the same as this one.

**Closed as completed** 2022-01-27 17:00 UTC
Labels: P1 - important, DEV: backend, OS: Mac, OS: iOS, TAG: regression
