### ISSUE TITLE
Errors on cancelling import/export (for impatient users)

### ISSUE THREAD

**Issue by radinamatic** [learningequality/kolibri#2065] opened 2017-08-30 17:46 UTC
## Summary

Pressing `Cancel` button several times during channel import/export will eventually result in error. Replicated on both Win & Linux.

@rtibbles suggestion is to render the `Cancel` button inactive after the first press. 
Maybe also a notification message that the import/export has been cancelled?

## System information

 - Version: `v0.5.0-beta11`
 - Operating system: Windows 7 - Ubuntu 16.10
 - Browser: Chrome

## Screenshots

![ubuntu3 start running - oracle vm virtualbox_570](https://user-images.githubusercontent.com/1457929/29886596-e0e09284-8dba-11e7-87e1-aa1c8d4d81bf.png)

![w7 start running - oracle vm virtualbox_566](https://user-images.githubusercontent.com/1457929/29886607-f08c4aca-8dba-11e7-83c6-bcdabc5379d7.png)

## Real-life consequences 

Annoyed impatient users.

**Comment by jonboiser** [comment] 2017-08-30 23:17
@radinamatic We can fix this by blocking the UI after the first click of 'Cancel' to prevent that second press. I can do this once after the big refactor of Device/Facility management is merged in.

It would probably help too if `/canceltask` endpoint were idempotent. It the implementation seems to not gracefully handle the case of canceling a task that does not exist.

**Comment by rtibbles** [comment] 2017-08-30 23:18
It gives a 404 if it doesn't exist - which is expected behaviour. We should probably just catch it better on the frontend.

**Comment by jonboiser** [comment] 2017-08-30 23:34
In the screenshots it returns a 500 with the HTML for the Django error debug screen in the error dump. Returning a  404 might not make sense since `/canceltask` isn't the resource address for the task being canceled. For the endpoint to be idempotent, it would be probably enough to have POST `/canceltask` with the same task id simply return `{}` again like it does when it succeeds.

**Comment by indirectlylit** [comment] 2017-09-12 01:10
Note, this is also true for the 'import' button:

![image](https://user-images.githubusercontent.com/2367265/30303347-53072872-971c-11e7-9c48-14cc5974c951.png)

It's possible to really confuse the system when that's clicked a few times at once:

![image](https://user-images.githubusercontent.com/2367265/30303364-6583845a-971c-11e7-8a85-7754800ab125.png)

```

ERROR:sqlalchemy.pool.NullPool:Exception closing connection <sqlite3.Connection object at 0x1068452e8>
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 300, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 446, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.TERROR:sqlalchemy.pool.NullPool:Exception during reset or similar id 4393132032
Traceback (most recent call last):                               | 0/459890 [00:00<?, ?it/s]
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4388925440 and this is thread id 4393132032
ERROR:sqlalchemy.pool.NullPool:Exception closing connection <sqlite3.Connection object at 0x104f9bdc8>
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 300, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 446, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4388925440 and this is thread id 4393132032
```

**Comment by jonboiser** [comment] 2017-09-12 21:12
@indirectlylit Just tried that and what seems to happen is that one of the requests actually starts the transfer, but the rest are failures. But the progress bar only looks at the first item in the array.

![screen shot 2017-09-12 at 2 10 39 pm](https://user-images.githubusercontent.com/10248067/30348481-57c68314-97c4-11e7-9da3-bd63652f990f.png)

**Comment by indirectlylit** [comment] 2017-09-12 21:48
yeah - the backend is built to support concurrent tasks but the front-end assumes (and tries to enforce) one-at-a-time

**Closed** 2017-09-13 20:19 UTC
Labels: DEV: frontend, TASK: bug
