### ISSUE TITLE
Device selection modal does not filter out your own device

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10286] opened 2023-03-21 19:26 UTC
## Observed behavior
Device selection modal does not filter out your own device

## Expected behavior
We should not be showing the device a user is on as an option for importing from.

## User-facing consequences
Confusion and/or bugs and/or errors in workflow 

## Context
[Alpha 7 bug bash](https://www.notion.so/learningequality/0-16-alpha7-bug-bash-09e7ddaf055c478f8b15860f137426a5)

**Comment by rtibbles** [comment] 2023-03-21 19:28
Do we even want to track your own device in the network location models? Maybe we should not even be listing ourselves.

**Comment by bjester** [comment] 2023-03-28 15:58
@rtibbles We do not track your own device, so I'm not sure how this happened. Needs reproduced

**Comment by rtibbles** [comment] 2023-03-28 19:19
My assumption was that there had been a regression at some point that had stopped us from preventing your own device being stored in NetworkLocation.

**Comment by jamalex** [comment] 2023-03-30 16:59
Or maybe there were multiple instances running on the same computer (IP/hostname) but with a different port and instance_id?

**Comment by akolson** [comment] 2023-04-28 14:32
I was able to pick up my devices in the modal. On restarting my laptop, these devices disappeared. I suspect these were residue devices from previously unstopped/sticky sessions. See screenshot below;
![Image](https://user-images.githubusercontent.com/5203639/235175002-73fb0ce6-24b1-4d84-b345-3d0957286178.png)
I will be spending the next hour trying replicate this with other suggested scenarios including transfer between facilities.

**Comment by bjester** [comment] 2023-04-28 15:06
@akolson Which one of those in the red rectangle was the same as the current instance? They have different IDs so they can't be the same device, and to clarify device = kolibri instance

**Comment by akolson** [comment] 2023-04-28 15:41
@rtibbles Yes device = kolibri instance. `My Device` was running from yesterdays bug bash session and `Asad` is the same as the current instance

**Comment by bjester** [comment] 2023-04-28 16:01
@akolson You meant @bjester? :smile:  So `My Device` should definitely be shown since it's a separate instance. The `Asad` shouldn't, but I notice that the IP address looks like ZeroTier. I suggest you run in debug mode and monitor the Zeroconf broadcast logs and compare the instance ID being received for that instance with the broadcasted instance

**Comment by akolson** [comment] 2023-04-28 16:06
Not sure how I read  @bjester  for @rtibbles 😄. I guess the weekend has kicked in already.

**Comment by akolson** [comment] 2023-05-15 14:40
Closing this issue for now as we continue to assess the behavior of the device selection modal. It will be reopened if the issue resurfaces.

**Closed as completed by akolson** 2023-05-15 14:40 UTC
Labels: P0 - critical, TODO: needs clarification
