### ISSUE TITLE
Learn-only devices not being successfully queued for subsequent syncs after joining a new facility

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#10358] opened 2023-03-30 20:49 UTC
## Observed behavior

We've seen several cases of a facility user "joining" their account into a remote facility, and the initial sync happening successfully, then not being auto-synced again after that, despite still being connected to the remote server.

CC @bjester @jredrejo

## Errors and logs

Example with Jamie's device as client device and Liana's as server device:
[jamie-client-side-kolibri-dbs-and-logs.zip](https://github.com/learningequality/kolibri/files/11115936/jamie-client-side-kolibri-dbs-and-logs.zip)
[liana-server-side-kolibri-dbs-and-logs.zip](https://github.com/learningequality/kolibri/files/11115942/liana-server-side-kolibri-dbs-and-logs.zip)

We noted that the sync queue on Liana's server was empty, but there was a UserSyncStatus row on Jamie's DB that had "queued=1".  Jamie did try stopping the client, changing that row to 0, and restarting, but it still didn't sync.

These rows from Liana's server logs feel like they could be relevant...
```
INFO 2023-03-30 14:36:52,933 cherrypy.access 172.27.207.186 - - "POST /api/public/syncqueue/" 404 0 "" "python-requests/2.27.1"
INFO 2023-03-30 14:36:52,936 cherrypy.access 172.27.207.186 - - "POST /api/public/syncqueue/" 404 0 "" "python-requests/2.27.1"
WARNING 2023-03-30 14:36:52,936 django.request Not Found: /api/public/syncqueue/
WARNING 2023-03-30 14:36:52,936 django.request Not Found: /api/public/syncqueue/
INFO 2023-03-30 14:36:53,005 cherrypy.access 172.27.80.35 - - "GET /api/public/info/" 200 0 "" "python-requests/2.27.1"
INFO 2023-03-30 14:36:53,096 cherrypy.access 172.27.207.186 - - "POST /api/public/syncqueue/" 404 0 "" "python-requests/2.27.1"
WARNING 2023-03-30 14:36:53,096 django.request Not Found: /api/public/syncqueue/
INFO 2023-03-30 14:36:53,367 kolibri.core.discovery.utils.network.client Attempting connections to variations of the URL: http://172.27.80.35:8000/
INFO 2023-03-30 14:36:53,367 kolibri.core.discovery.utils.network.client Attempting connection to: http://172.27.80.35:8000/
INFO 2023-03-30 14:36:53,393 cherrypy.access 172.27.54.246 - - "POST /api/public/syncqueue/" 404 0 "" "python-requests/2.27.1"
INFO 2023-03-30 14:36:53,393 cherrypy.access 172.27.54.246 - - "POST /api/public/syncqueue/" 404 0 "" "python-requests/2.27.1"
WARNING 2023-03-30 14:36:53,393 django.request Not Found: /api/public/syncqueue/
WARNING 2023-03-30 14:36:53,393 django.request Not Found: /api/public/syncqueue/
```

## Expected behavior

Magical syncing magic.

## User-facing consequences

No can haz sync.

## Steps to reproduce

Migrate user to new facility. Wait for next sync.

## Context

Kolibri 0.16 alpha 11

**Comment by jamalex** [comment] 2023-03-30 20:58
In looking into this, I was also unsure how [`UserSyncStatus`](https://github.com/learningequality/kolibri/blob/cade48f68b95700ac3e89b26786956413bf34f85/kolibri/core/device/models.py#L334) keeps track of what devices it's in the queue for -- in principle, it could be on a network with 2+ full-facility devices, and should be syncing against both, I believe?

**Comment by jredrejo** [comment] 2023-04-11 10:55
@jamalex I am not able to reproduce this, can you give more details about the kind of setup when joining to the remote facility? i.e. was it a new user or was it a merge? did you do it as an admin or using the user credentials, etc.?

When I test it, I see it synced continuously without any problem
![image](https://user-images.githubusercontent.com/1008178/231139222-cc8672b7-3af7-4c34-9057-103ea61b0832.png)

![image](https://user-images.githubusercontent.com/1008178/231139598-65b9f045-43a5-44fe-a0ae-3b993eee6c21.png)

**Comment by rtibbles** [comment] 2023-05-22 23:25
I suspect this might be resolved by changes in #10724

**Comment by bjester** [comment] 2023-05-23 17:06
One possible gotcha that I can see, and a test confirms, is the following line. The `sync_session` field is nullable on `UserSyncStatus`, so if the device hasn't done an automated LOD sync yet, I would expect `sync_session__last_activity_timestamp` to be `None` and for this to fail. Not sure why we haven't seen this yet. It could be possible with network changes after initial LOD setup:
https://github.com/learningequality/kolibri/blob/b86377c757bc405c2deeca8e1b4fbd03bfb15b1d/kolibri/core/auth/tasks.py#L571

I also question whether this code is still doing what it originally intended. It seems possible that the comment `if previous sync jobs have failed, unblock UserSyncStatus to try again` eludes to potential blocking of later syncs upon a failure, so if it isn't properly picking up the failed jobs, perhaps it's also an issue. Although, it only skips if it found a queued job:
https://github.com/learningequality/kolibri/blob/b86377c757bc405c2deeca8e1b4fbd03bfb15b1d/kolibri/core/auth/tasks.py#L577-L599

When we make requests to the sync queue, we also don't seem to be capturing timeout errors. It seems possible this could break the task chain keeping the LOD syncs going:
https://github.com/learningequality/kolibri/blob/b86377c757bc405c2deeca8e1b4fbd03bfb15b1d/kolibri/core/auth/tasks.py#L644-L659

Lastly, we're also not tracking where the server the sync has been queued with, so it isn't clear if there could be issues with multiple non-LOD servers on the network. My sense is that since we chain tasks together for managing a user sync to a particular server, through that we avoid any issues. But it could be worth checking that a 404 from one server doesn't influence the device's syncing to another server:
https://github.com/learningequality/kolibri/blob/b86377c757bc405c2deeca8e1b4fbd03bfb15b1d/kolibri/core/auth/tasks.py#L688-L694

**Comment by bjester** [comment] 2023-07-27 18:36
Reoccurred during the most recent bug hunt. Will take a look next week

**Closed as completed** 2023-09-11 23:36 UTC
Labels: P1 - important, DEV: backend
