### ISSUE TITLE
Quiz creation - Missing snackbar notification on resource selection/deselection

### ISSUE THREAD

**Issue by metodimilevqa** [learningequality/kolibri#7616] opened 2020-10-26 06:46 UTC
### Observed behavior

Under Create New Quiz page the snackbar notification messages are missing on select/deselect a resource.

### Expected behavior

Under Create New Quiz page the snackbar notification messages must be shown on select/deselect a resource.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

Preconditions: Resources imported, users created, class created
1. Login as couch user
2. Go to Coach > Classes > Class > Plan > Quiz page
3. Click New Quiz
4. Input a search query
5. Select a single resource
6. Deselect a single resource

### Context

Kolibri 0.14.3
Raspberry Pi 4
OS: Raspbian GNU, Linux 10
Chrome (latest) + Firefox (latest)

**Comment by jonboiser** [comment] 2020-10-26 16:51
This looks like a duplicate of #7536, which should be fixed in 0.14.4

**Closed as completed by jonboiser** 2020-10-26 16:51 UTC
