### ISSUE TITLE
Fullscreen button on videos is disabled in Android

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6902] opened 2020-05-20 20:56 UTC
### Observed behavior
Fullscreen is disabled
![Screenshot_20200520-135803](https://user-images.githubusercontent.com/25045166/82496746-0e172a00-9aa2-11ea-8d05-24aba52fd6ae.png)

### Expected behavior
Enabled fullscreen at all times

### User-facing consequences
Looks like a disabled feature with no explanation to user

### Steps to reproduce
Go to any video in Learn

**Comment by indirectlylit** [comment] 2020-05-21 22:19
@nucleogenesis reports that he cannot reproduce. @khangmach any guidance?

**Comment by khangmach** [comment] 2020-05-22 04:43
that's a shame, as I literally can't fullscreen any video in Learn. Here is my android version and kolibri version if that helps

![image](https://user-images.githubusercontent.com/25045166/82632055-09d73380-9bac-11ea-82aa-2c241ff3c219.png)
![image](https://user-images.githubusercontent.com/25045166/82632061-0e035100-9bac-11ea-9c91-37fd2f0d2fae.png)

The channels I've downloaded on device:
- Touchable Earth (EN)
- Free English with Hello Channel
- Global Digital Library - Book catalog
- Phet

**Comment by rtibbles** [comment] 2020-05-22 15:33
Note that we have a specific exclusion for Android webview for fullscreening, coded in:
https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreFullscreen.vue#L19

So this will only replicate inside an Android webview. I don't remember what the issue is with Android fullscreen inside a webview, but there definitely was one, hence the coded in exclusion.

I think it has something to do with this: https://developer.android.com/reference/android/webkit/WebChromeClient#onShowCustomView(android.view.View,%20android.webkit.WebChromeClient.CustomViewCallback)

We would need to invoke something specifically for Android to tell it that our webview is entering fullscreen mode.

@jamalex @kollivier tagging as solving this (other than just hiding the full screen button for now) will have implications for Android bundling.

**Comment by indirectlylit** [comment] 2020-05-23 00:43
In my opinion, not having full-screen functionality on small Android devices would be a release blocker.

**Comment by indirectlylit** [comment] 2020-06-04 15:29
from @nucleogenesis:

> I tried to get this replicated in an emulator in a way that I could also edit running code and did not have any luck

**Comment by pcenov** [comment] 2022-03-23 13:40
@radinamatic this one is fixed/not extant in 0.15.1 where the fullscreen button is functioning as intended.

**Comment by rtibbles** [comment] 2022-03-23 15:44
@pcenov was this using Android as a client device, or the Android app?

**Comment by pcenov** [comment] 2022-03-23 15:57
@rtibbles actually I was using an Android phone as a client so now that you've mentioned it I checked the Android app as well and the surprising thing is that this button is indeed still being disabled there!

**Comment by rtibbles** [comment] 2022-03-23 16:41
Yes, this is by design because of issues with making it fullscreen. This is also separately tracked on the Android repo: https://github.com/learningequality/kolibri-installer-android/issues/86

**Comment by radinamatic** [comment] 2022-04-04 05:34
Closing, as it's being tracked on the Android repo.

**Closed as completed by radinamatic** 2022-04-04 05:34 UTC
Labels: bug, P2 - normal, OS: Android, TAG: mobile
