### ISSUE TITLE
Tooltips in CoreTable headers can get cut off at box boundary

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#5106] opened 2019-02-20 01:51 UTC
### Observed behavior

CSS rules for CoreBase th/tds have an overflow hidden rule that cuts horizontal overflows off

![screen shot 2019-02-19 at 5 49 59 pm](https://user-images.githubusercontent.com/10248067/53060307-da98ba80-346e-11e9-8d4b-9a10e40ae39f.png)

![screen shot 2019-02-19 at 5 51 49 pm](https://user-images.githubusercontent.com/10248067/53060352-103da380-346f-11e9-8848-7b460da7e31a.png)

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment] 2019-02-27 00:02
re-opening due to regression noted in #5134 

Specifically, on Chrome on Linux, horizontal scrollbars can appear below table cells, even if the cell contents do not overflow.

**Comment by rtibbles** [comment] 2019-02-28 00:40
Regression should now be fixed by #5202

**Closed as completed by rtibbles** 2019-02-28 00:40 UTC
Labels: bug, P1 - important
