### ISSUE TITLE
channel navigation header tears away from side nav

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8627] opened 2021-11-07 22:24 UTC
## Observed behavior

at some browser sizes the header tears away from the side-nav:

![2021-11-07 15 29 26](https://user-images.githubusercontent.com/2367265/140663929-35b051cc-81b4-498d-92ce-f6d5b95a58d0.gif)

## Expected behavior

I would expect the side nav to continue scrolling up to the top when the header disappears

## User-facing consequences

slightly broken-looking layout

## Steps to reproduce

set browser width to ~750 px and view resources in library browser

## Context

v0.15.0-beta1

**Comment by indirectlylit** [comment] 2021-11-11 23:06
@marcellamaki FYI this behavior is improved in your PR https://github.com/learningequality/kolibri/pull/8637

![2021-11-11 18 05 54](https://user-images.githubusercontent.com/2367265/141381658-56005516-3ba3-4088-b106-6fc171fc2bc1.gif)

**Comment by MisRob** [comment] 2021-12-17 16:30
This was related to issues caused by certain layout of elements within one breakpoint. The layout seems to haven been updated recently and I can't find conditions to reproduce this particular issue anymore. I made some improvements in #8947 that were meant as a fix for this issue originally, but even without them things seems to work pretty well now to me, so closing.

**Closed as completed by MisRob** 2021-12-17 16:30 UTC
Labels: P1 - important
