### ISSUE TITLE
minor channels 'loading' icon issue

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#1660] opened 2017-06-15 01:09 UTC
It appears that the loading icon displaces elements in the table:

![gifmakerproject7](https://user-images.githubusercontent.com/2367265/27160884-632e96b2-512c-11e7-82ac-5f9791b30e49.gif)

**Comment by christianmemije** [comment] 2017-06-15 02:23
Duplicate of #1612

**Closed** 2017-06-15 14:31 UTC
