### ISSUE TITLE
Acivity tab in group report.

### ISSUE THREAD

**Issue by swapnil106111** [learningequality/kolibri#5112] opened 2019-02-20 11:05 UTC
### Observed behavior
Activity tab in groups is not showing anything.

### Expected behavior
It must show activity in activity tab.

### Steps to reproduce
1. Create lesson.
2. Click on report.
3. Click on groups.
4. Click on group name.
5. Click on Activity tab.

### Context
 * Kolibri version : Kolibri 0.12.0b4
 * Operating system : Ubuntu 14.04
 * Browser : Chrome

### Screenshot
![1](https://user-images.githubusercontent.com/12776071/53087617-93253380-352d-11e9-9401-98189d6f2afb.png)

**Comment by indirectlylit** [comment] 2019-02-20 17:51
please test in the latest beta

**Comment by swapnil106111** [comment] 2019-02-22 06:48
@indirectlylit Tested on Kolibri 0.12.0b9. Still No activity available.

![1](https://user-images.githubusercontent.com/12776071/53224806-fb922300-369b-11e9-9b10-e71c6fecf368.png)

**Comment by indirectlylit** [comment] 2019-02-22 08:48
@jonboiser @jredrejo I think you two were working on this?

**Comment by jredrejo** [comment] 2019-02-22 10:54
@indirectlylit  Yes, a couple of weeks ago I checked with jb the backend returned the right info. I could not reproduce the problem nor he could later, so I thought it was solved.

**Comment by indirectlylit** [comment] 2019-02-22 17:31
okay I'll take a quick look today

**Comment by jonboiser** [comment] 2019-02-25 21:26
@swapnil106111 Do you remember when learners were assigned to "ABC" group. In theory, this timeline should work

1. Learners are enrolled in "ABC"
1. A lesson is assigned to "ABC"
1. Learners work on that Lesson.
1. Activity appears in "ABC" group activity page.

This timeline, however, does not work

1. A lesson is assigned to whole class
1. Learners work on that Lesson.
1. Learners are enrolled in "ABC" <- Enrolled *after* they work on it
1. Activity *does not* appear in "ABC" group activity page.

There might be other variations on this timeline. There are certain conditions when a notification event gets attached to a specific learner group.

**Comment by rtibbles** [comment] 2019-02-28 02:41
@swapnil106111 can you double check the behaviour as outlined by @jonboiser in https://github.com/learningequality/kolibri/issues/5112#issuecomment-467189810 ?

**Comment by rtibbles** [comment] 2019-02-28 14:05
Not able to replicate this following the instructions that @jonboiser lays out. Appears to be working as intended.

**Comment by swapnil106111** [comment] 2019-03-01 09:06
@rtibbles @jonboiser 
Below are the process which we followed:
1. Created a group and enrolled users.
2. Assigned a lesson to the group.
3. Worked on lesson and went to the activity tab. Still not able to see activity.

**Comment by jonboiser** [comment] 2019-03-01 18:10
@swapnil106111 	Does the activity tab show data at the class home? (Click the "View All" button next to "Class Activity" at the class homepage/dashboard)

And does it show activity at the learner activity feed (CLick Reports > Learner > "Learner Name" > Activity)?

Or is this bug only happening for the Group Activity tab?

**Comment by indirectlylit** [comment] 2019-03-01 18:28
we've confirmed that this was not fixed, and did some follow-up work in https://github.com/learningequality/kolibri/issues/5217

hopefully this will be fixed by #5224 

@jonboiser it appears that this was reproducible on ubuntu by running the pex _not_ in `--foreground` mode. In that state,  no notifications were being created whatsoever. If you're able to confirm reproduction and the fix that would be very helpful

**Comment by radinamatic** [comment] 2019-03-04 00:25
@swapnil106111 Please retest with the `beta13` release, as the #5224 has fixed the group activity notifications for the scenario you are describing.

As @jonboiser noted, keep in mind that the activity of the group's members will be recorded and displayed only _if the interactions are performed within the specific group scope_ (after the group constitution, for example). 

Let's say there is a group `ABC` with 5 learners, and two of them interacted with a lesson, with the group activity correctly recorded:

![2019-03-04_1-04-22](https://user-images.githubusercontent.com/1457929/53704274-9668cb00-3e1b-11e9-9d50-f1068a8fa2bb.png)

If a new group is constituted with just those 2 learners (`Carol & John`), and the lesson is edited so that it's visible to both groups, the second group activity tab will not display anything, because all the interactions of Carol and John with that lesson happened _within the scope of the first group_ (ABC).

![2019-03-04_1-06-37](https://user-images.githubusercontent.com/1457929/53704345-3f172a80-3e1c-11e9-8b94-2bc0c2908ebf.png)

**Comment by rtibbles** [comment] 2019-03-04 07:02
Closing this issue as per @radinamatic's comments above. Can reopen if it recurs on 0.12.0-beta13 or later.

**Closed as completed by rtibbles** 2019-03-04 07:02 UTC
Labels: P1 - important

**Comment by yogeshmhaskule** [comment] 2019-03-06 09:27
tested in kolibri 0.12.0 and works fine.
![activity_1](https://user-images.githubusercontent.com/7850420/53870371-20818100-4020-11e9-8c8f-b730b3784596.png)
![activity_2](https://user-images.githubusercontent.com/7850420/53870372-20818100-4020-11e9-9fa4-cef04d89cfec.png)
