### ISSUE TITLE
Khan Academy Update to Version 13 - removed 1 GB without warning

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4342] opened 2018-09-28 03:23 UTC
### Observed behavior
Khan Academy Update to Version 13 - removed 1 GB without warning

### Expected behavior

The update should warn before deleting such a large amount of data. Administrators may then decide not to update at that time, avoiding serious disruption.  Update can then take place at an ulterior date.

In my case, 1GB was removed 
![0875d4db-db5b-4a72-a203-5f89499a232b](https://user-images.githubusercontent.com/1372447/46186334-9d415e00-c310-11e8-87bd-fa387db223c8.jpg)
…

### Context
 * Kolibri version 0.10.2
 * Operating system
$ uname -a
Linux tower 4.14.69-1-MANJARO #1 SMP PREEMPT Mon Sep 10 02:18:25 UTC 2018 x86_64 GNU/Linux

 * Browser
Vivaldi 2

**Comment by intelliant01** [comment] 2018-09-28 04:08
To put things in perspective for those trying to address this, this could be related to 2 issues - one with the Khan Academy English channel and the other with Kolibri.

I faced the same situation earlier with Kolibri 0.10.1 which has been discussed [herein](https://community.learningequality.org/t/updating-a-channel-requires-re-importing-the-channel-contents-and-not-just-the-diff/732?u=shrenik).

There was a patch release https://github.com/learningequality/kolibri/pull/4123 related to issue https://github.com/learningequality/kolibri/issues/4117 in 0.10.2 to fix this.

There was another issue related to Khan Academy English channel version 12 Maths (note, Maths only, as I discovered yesterday) videos which has been discussed [herein](https://community.learningequality.org/t/kolibiri-not-able-to-view-video-in-firefox-only/725?u=shrenik) and then addressed at https://github.com/learningequality/sushi-chef-khan-academy/issues/3.

Yesterday, I too upgraded to version 13 of the Khan Academy English channel after upgrading to Kolibri 0.10.2 and around 100+ GB downloaded content was visibly reduced to merely 1 GB as reported in the upgrade process screen but the physical disk space was not freed as evident upon checking the size of the .kolibri folder immediately thereafter. 

I have not yet tried the upgrade test with any other channel. I did not report it yesterday thinking that it could be an attempt to rectify the encoding problem of the KA-en videos. But with the above post, it seems the patch to fix Kolibri may not have addressed this specific bug. 

**Context**
 

- Kolibri verion 0.10.2

- Server side OS - Ubuntu 16.04 LTS
  Client OS - Ubuntu 16.04 LTS, Android

- Browsers - Firefox, Chrome, Chromium

**Comment by benjaoming** [comment] 2018-10-04 15:01
I like @nobicycle 's suggestion:

> The update should warn before deleting such a large amount of data.

@indirectlylit you recently made changes in the channel import steps regarding disk space etc - would this be hard to implement? I guess we need meta data for both the installed version of a channel and the available version to calculate the diff...

**Comment by indirectlylit** [comment] 2018-10-04 17:59
It's not entirely clear to me yet what's happening here: whether content actually was deleted, or was supposed to be deleted, or if the values are just being reported differently than before. I've asked the content devs to take a look.

There is certainly a UX issue here also but I'd like to get to identity root cause first.

**Comment by indirectlylit** [comment] 2018-10-15 23:18
@ralphiee22 would you mind investigating this?

**Comment by benjaoming** [comment] 2018-10-16 13:05
> I guess we need meta data for both the installed version of a channel and the available version to calculate the diff...

This diff should perhaps be about both content counts and data footprint?

**Comment by lyw07** [comment] 2018-11-28 01:02
I'm not able to replicate the error on a testing channel, so I guess this is related to the KA version 13 update?

**Comment by benjaoming** [comment] 2018-11-29 13:47
Just noticing another issue now in @intelliant01 's post:

> Yesterday, I too upgraded to version 13 of the Khan Academy English channel after upgrading to Kolibri 0.10.2 and around 100+ GB downloaded content was visibly reduced to merely 1 GB as reported in the upgrade process screen but the physical disk space was not freed as evident upon checking the size of the .kolibri folder immediately thereafter.

If this is true, then 1) alarming amounts of content are removed in the new version, is that intended? and 2) do we not free up disk space (i.e. delete old channel data) when upgrading?

**Comment by indirectlylit** [comment] 2018-12-13 18:12
possibly related? #4592

**Comment by jredrejo** [comment] 2019-01-10 17:04
@nobicycle , @intelliant01 I don't know if  you still keep the Kolibri database with the lost content. In case you do I would like to ask you to test a command we've done to recover it ( #4705 ) 
Would it be possible?

**Comment by nobicycle** [comment] 2019-01-10 22:01
Hi jredrejo,
Sorry, I zapped the DB.

**Comment by intelliant01** [comment] 2019-01-28 16:55
@jredrejo I had re-downloaded all the content from Khan Academy version 13 and I may have a copy of that. But can't say for sure if there is still content that is "lost" therein or any "diskspace not freed" as yet. 

If you can guide me with the exact steps and the before and after scenarios to note and report, I may be able to help. I can think of noting these prior and after running the test command -
1. the size of .kolibri folder in the filesystem.
2. the resource and storage occupied as reported in the UI 

Is this the command that you want me to test with ``` kolibri manage scanforcontent```?

**Comment by nobicycle** [comment] 2019-03-06 04:47
Kolibri now warns sufficiently about potential loss during  upgrades. 
The case that Kolibri unnecessarily drops already downloaded content is not proven.

For me, the issue should be closed.

**Comment by indirectlylit** [comment] 2019-03-08 20:40
thanks, closing. @intelliant01 if you're still experiencing any problems let's start new issues to track them

**Closed as completed by indirectlylit** 2019-03-08 20:40 UTC
