### ISSUE TITLE
users cannot create new accounts despite facility settings

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2606] opened 2017-11-15 02:50 UTC
### Observed behavior

facility settings:

![image](https://user-images.githubusercontent.com/2367265/32816186-55faad56-c96c-11e7-9efd-b1e5f3b6c58c.png)

login page:

![image](https://user-images.githubusercontent.com/2367265/32816198-626902a4-c96c-11e7-876f-99a9b9e04c1c.png)

### Expected behavior

Since 'allow users to sign up' is checked, users should be able to sign up.

### User-facing consequences

users cannot sign up.

### Steps to reproduce

Load attached db: [db.sqlite3.zip](https://github.com/learningequality/kolibri/files/1473264/db.sqlite3.zip)

### Context

* Kolibri version: 0.7

**Comment by indirectlylit** [comment] 2017-11-15 04:04
seeing a similar issue where 'allow login without password' does not seem to be having an effect:

![image](https://user-images.githubusercontent.com/2367265/32818254-ead6ecc8-c976-11e7-8ae2-e3d9341b3073.png)

![image](https://user-images.githubusercontent.com/2367265/32818262-f3abdbd8-c976-11e7-9603-4985b477ac79.png)

**Comment by rtibbles** [comment] 2017-11-22 00:57
Regression caused by https://github.com/learningequality/kolibri/pull/2540

**Comment by rtibbles** [comment] 2017-11-22 00:57
Needs to add `getFacilityConfig` core action to the state setters for the user app.

**Comment by rtibbles** [comment] 2017-11-28 19:57
Fixed in #2694

**Closed by rtibbles** 2017-11-28 19:57 UTC
Labels: DEV: frontend, P0, TASK: bug
