### ISSUE TITLE
Missing Graphics for Khan Academy

### ISSUE THREAD

**Issue by Marshall-B** [learningequality/kolibri#5708] opened 2019-06-25 21:31 UTC
### Observed behavior

From one of my workers...

To whom it may concern:
After extensive use of the Kolibri educational materials I have found the following problems.
Khan Academy (English)
Math 2nd Grade
Picture Graphs: None of the graphs show up.
Math 3rd Grade
Picture Graphs. Create Picture Graphs: You cannot create picture graphs.
Read Picture Graphs: The visual aid is incomplete; no names.
Math 4th Grade
Measurements and Data. Converting Units of Time: There is no answer area.
Geometry. Measuring Angles: No visible protractor
Constructing Angles. Draw Angles: No visible protractor
Angle Types. Benchmark Angles: No answer area.

I have attempted to fix these problems by opening Kolibri in various web browsers. (Google and Firefox). I have adjusted the resolution from low to high and everywhere in between. The problem is consistent on both Windows and Linux systems. 
On the whole, the Kolibri site is an invaluable educational tool. That being said, the inability for students to see and properly interact with the material is a definite hindrance to their ability to learn. 

…

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

Ubuntu Kolibri v0.12.12
I have attempted to fix these problems by opening Kolibri in various web browsers. (Google and Firefox). I have adjusted the resolution from low to high and everywhere in between. The problem is consistent on both Windows and Linux systems. 

…

**Comment by jonboiser** [comment] 2019-06-25 21:49
This looks similar to #5702. Is the Maharashtra channel using the same nodes as the latest Khan Academy channel?

**Comment by indirectlylit** [comment] 2019-06-25 21:57
looks like a duplicate of #5094, which was identified to be an upstream content issue

**Comment by indirectlylit** [comment] 2019-06-25 22:00
@Marshall-B is this from channel `8fc515793aad4e52b490b03c48ad21de`?

**Comment by jamalex** [comment] 2019-07-05 19:47
It likely wouldn't be from that channel (as it's not public), but might be from a channel that was curated a long time ago (when there were KA issues) and never updated. Steps to resolve:

A. If it's directly imported into Kolibri from the "Khan Academy (English)" channel (1ceff...), try re-importing from Studio.

B. If it was curated into another channel on Studio and then imported:
1. Go into the channel on Studio
2. Click "Sync" and choose "Assessments" and "Files"
3. It will run for a long time and may error out, but it's still running in the background, so come back an hour later and refresh the page.
4. Republish the curated channel (if the "Publish" button isn't enabled, drag-drop a content item somewhere and then back again to make it notice that there was a change).
5. Re-import this channel into Kolibri

**Comment by Marshall-B** [comment] 2019-07-22 20:11
Thanks Jamie,
    The notifications had been getting caught by the SPAM filter – I’ll have to take a look tonight when I can visit github for the other updates.  I will attempt to get KA again tomorrow when I have most of the day to get it.

-Marshall

DO NOT read, copy, or disseminate this communication unless you are the intended addressee. This e-mail communication contains confidential and/or privileged information intended only for the addressee. If you have received this communication in error, please call us immediately at 208- 331-2760 and ask to speak to the sender. Please e-mail the sender to notify him immediately that you have received the communication in error, and delete message received in error immediately.

**Closed as completed** 2019-09-25 03:02 UTC
Labels: bug, DEV: content

**Comment by jamalex** [comment] 2019-09-29 22:34
@Marshall-B We still noticed this happening while at SBWCC during our recent visit, and I believe it was a combination of it being a very old Kolibri version (0.10.0) and possibly also an older version of the KA channel. They'll need an upgrade to get things going smoothly. Thanks!

**Comment by Marshall-B** [comment] 2019-10-01 19:07
Thank you sir,
    We’re working on it – I suspect they still have the very first version that Nick Yordy put together for us almost a year ago…

-Marshall

DO NOT read, copy, or disseminate this communication unless you are the intended addressee. This e-mail communication contains confidential and/or privileged information intended only for the addressee. If you have received this communication in error, please call us immediately at 208- 331-2760 and ask to speak to the sender. Please e-mail the sender to notify him immediately that you have received the communication in error, and delete message received in error immediately.
