### ISSUE TITLE
Pre-commit hooks interfering with developer workflows

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#5409] opened 2019-04-23 17:09 UTC
### Observed behavior
Talking with @indirectlylit, some observed issues are that the existing pre-commit hooks:
- are very slow
- have issues with GUIs due to virtual envs
- interfere with in-progress commit dev workflows
- maintain rule definitions separately from Travis & dev tooling

### Expected behavior

Ideally, pre-commit hooks:
- [ ] should run as fast as possible #6583
- [ ] should support developer tools used by the team, like Git GUIs
- [ ] should not interfere with in-progress commit dev workflows
- [ ] should operate on a consistent set of rule definitions across Travis and other dev tooling #6583

### User-facing consequences

None

### Issue resolution paths
Obtain feedback and buy-in from contributors regarding pre-commit hooks and move forward with either:
1. Removing pre-commit hooks to focus on increasing the hardiness of Travis and other dev tooling for protecting code quality
2. Reworking pre-commit hooks to resolve issues in the current implementation affecting developer workflows

### References
https://github.com/learningequality/kolibri/pull/5405
https://learningequality.slack.com/archives/CB37UM23A/p1555759651088400

**Comment by benjaoming** [comment] 2019-10-30 17:00
> maintain rule definitions separately from Travis & dev tooling

Deviations between the two is a bug that should be addressed. Pre-commit can be run in CI as well as from a local environment.

Pre-commit hooks can be removed. If you do this, only CI will lint your code.

**Comment by benjaoming** [comment] 2020-02-21 23:01
I expanded the `exclude` pattern in #6583 - `pre-commit` only runs on files that are changed in commits, but I'm wondering if this is a pattern that should be expanded gradually in the same manner to achieve the speed perceived as lacking.

**Comment by indirectlylit** [comment] 2020-02-27 01:53
closing given work in #6583.

Let's re-open a new issue if necessary

**Closed as completed by indirectlylit** 2020-02-27 01:53 UTC
Labels: TAG: developer docs, TAG: dev experience

**Comment by benjaoming** [comment] 2020-02-27 11:18
Yes, if there are further issues, please separate out the feedback like this:

* Speed: Report speed issues on a per-hook basis so it's possible to understand if a particular hook has issues
* Dev tools: Please report exactly the GUIs that are causing issues so it can be investigated
* In-commit workflow: Pre-commit hooks are designed to interfere with developer's workflows when they try to commit something they shouldn't. If there are false positives, this would be an issue with that particular hook that should be fixed.

**Comment by indirectlylit** [comment] 2020-02-27 22:42
This is not an urgent issue, but  I migrated the last point here: https://github.com/learningequality/kolibri/issues/6607

>  Pre-commit hooks are designed to interfere with developer's workflows when they try to commit something they shouldn't

In other words, pre-commit is flawed by design :)

**Comment by benjaoming** [comment] 2020-02-28 09:41
@indirectlylit what do you mean? There is `git commit --no-verify` if you want to (somehow) create a commit that doesn't pass through git hooks?
