### ISSUE TITLE
When typing in letters, get the wrong error message - not setting a new PIN

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10300] opened 2023-03-23 20:50 UTC
## Observed behavior

Reported by: @jtamiace in the alpha-10 bug bash. She entered letters, but she got the wrong error message

## Errors and logs
<img width="533" alt="Screenshot 2023-03-23 at 12 49 38 PM" src="https://user-images.githubusercontent.com/17235236/227354883-fd1125eb-16df-465f-b3dd-5f03afe898eb.png">

## Expected behavior
Quick link to the strings for the learner UI: https://www.figma.com/file/MpCG7r5PULOCJsEvnTSti8/Android-Designs-2022?node-id=6080%3A27395&t=yRHs1p1Q3Sdn47N4-1

## User-facing consequences
Confusion!

## Context
0.16.0-alpha10

**Comment by nithinag10** [comment] 2023-03-24 08:32
Hi @marcellamaki, I am new to this project. Really want to contribute to this cause. 

I would like to take up this issue.

**Comment by akolson** [comment] 2023-03-24 13:02
Hi @nithinag10 ,

Thanks for you interest in contributing to Kolibri. This issues is available to be worked on, but it is for an upcoming release and therefore is time sensitive. If you are unable to work on this issue in the next two weeks, it will be reassigned to someone on our team.

If you are looking for a less-time sensitive issue, you can choose from [the help wanted tag on Kolibri,](https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+help+wanted%22) or [the beginner friendly issues on Studio](https://github.com/learningequality/studio/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+beginner+friendly%22).

Thanks again for your interest, and comment on the issue if you have any questions along the way.

**Comment by nithinag10** [comment] 2023-03-26 13:33
Hi @akolson, Thank you for the opportunity.

Don't worry, there is going to be no delay in the upcoming release. 

 I was wondering what formatting guidelines I should follow before pushing the changes.

**Comment by akolson** [comment] 2023-03-27 14:02
Hi @nithinag10. All you will need to do once you have made your changes is to run `yarn run lint-frontend:format` and formatting should be handled automatically for all affected files.

Please note that this is a pretty small fix that will involve swapping out the currently displayed translation string for the `Enter numbers only` message. This message has already been added as part of the core strings and you should therefore not add any translation strings as we are currently in a code freeze(No new strings should be added during this period as translation is on-going).

Thanks again for your interest.

**Comment by nithinag10** [comment] 2023-03-30 07:09
@AllanOXDi I tried re-creating the issue to attach the screenshots for the PR but I was not able to do that. 
Steps I followed
1. Create an account and set a PIN for the home facility.
2. Create a learner's account under the above account as the home facility. 
3. But it didn't ask me for any PIN to access the device from the learner's account as pictured in Figma. 

Did I do something wrong?

**Comment by AllanOXDi** [comment] 2023-03-30 10:18
Hi @nithinag10,  let me try to reproduce it and revert back to you. Thanks!

**Comment by pcenov** [comment] 2023-03-31 12:35
Hi @nithinag10, the correct steps to replicate this are:
1. On one device install Kolibri, setup a full facility and as a super admin create a class with learners and set a PIN.
2. On another device install Kolibri and setup it as a Learn-only device. You can import a learner from the main facility or create a new learner.
3. Using that same learner on the Learn-only device attempt to view the Device plugin. Then you will see the Enter PIN modal and the incorrect validation message.

**Comment by nithinag10** [comment] 2023-04-03 05:40
Hey @pcenov , 

I am not sure if I am doing it right, I ran into HTTPError. 

This is what I did :
1. On my device I hosted the facility. 
2. In my other device in the same network, I went into Advance Setup -> Named My device -> Registered as learn only device -> Selected my main device as facility  -> When I tried to log in as a learner (I already created a learner account) -> I am running into an HTTP Error

![account](https://user-images.githubusercontent.com/56193327/229420494-68db548d-7802-4bd3-9be5-87c1ed84ca33.png)
![image](https://user-images.githubusercontent.com/56193327/229420514-b503beef-f397-4089-8c1b-b87d97f967e7.png)
<img width="1277" alt="Screenshot 2023-04-03 at 11 08 55 AM" src="https://user-images.githubusercontent.com/56193327/229420644-c7e7c619-9ed7-4bd6-b11c-6dc921ebf757.png">
<img width="1302" alt="Screenshot 2023-04-03 at 11 09 16 AM" src="https://user-images.githubusercontent.com/56193327/229420714-93407978-5506-4f62-9219-5ccc8e9bf7a2.png">

If the problem is from my side, please let me know I will try again.

**Comment by pcenov** [comment] 2023-04-03 09:13
Hi @nithinag10 - it seem like this is a problem on your side. Could you try again following precisely my instructions with the these build assets: https://github.com/learningequality/kolibri/releases/tag/v0.16.0-alpha11? If you continue getting the `Failed: HTTPError` it would be better to report it as a separate issue with attached logs and detailed steps for replicating the issue.

**Comment by akolson** [comment] 2023-04-11 18:03
Hi @nithinag10 . Could you please confirm you are able to proceed with resolving this issue after our latest comment? If unable, it will be reassigned to someone on our team to resolve. Thanks

**Comment by akolson** [comment] 2023-04-17 12:49
Hi @nithinag10, 

We are very grateful for the efforts and time invested in trying to resolve this issue. However, please note that this issue has been reassigned to someone on the team to handle due to its time sensitivity.

Please feel free to choose other less time sensitive issues from [the help wanted tag on Kolibri,](https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+help+wanted%22) or [the beginner friendly issues on Studio](https://github.com/learningequality/studio/issues?q=is%3Aopen+is%3Aissue+label%3A%22TAG%3A+beginner+friendly%22).

Thanks again.

**Closed as completed** 2023-04-17 19:14 UTC
Labels: P1 - important
