### ISSUE TITLE
"Nothing in your library" pop up displays for guest users with library content

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#11202] opened 2023-09-06 14:51 UTC
## Observed behavior
For guest users who do have content on their device, the modal to display in learn when there is no content is displaying

## Errors and logs

<img width="1437" alt="Screenshot" src="https://github.com/learningequality/kolibri/assets/17235236/5096f4f2-1053-4bd7-abf4-35dc0ae570d3">

## Expected behavior
This modal should only display when there is no library content for signed-in users.

## Steps to reproduce
Access Kolibri when there is content in the kolibri home folder, but as a guest user

## Context
0.16.x (~beta 5)

**Comment by GarvitSinghal47** [comment] 2023-09-06 16:25
@marcellamaki i would like to work on this issue can you assign it to me

**Comment by ShivangRawat30** [comment] 2023-09-06 18:01
i would like to work on this issue

**Comment by marcellamaki** [comment] 2023-09-07 16:29
Hi @GarvitSinghal47 - I will assign you to this issue, since you requested it first. 

@ShivangRawat30 - thank you for your interest in contributing to Kolibri! You can find other issues where we would welcome community contributions using [the good first issue tag](https://github.com/learningequality/kolibri/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). We also have a [discussion page](https://github.com/learningequality/kolibri/discussions/categories/community) for community contributors, where you can find information about setting up your dev environment and ask troubleshooting questions.

**Comment by thanksameeelian** [comment] 2023-09-26 21:33
for additional context @GarvitSinghal47,  [this is the pr ](https://github.com/learningequality/kolibri/pull/10892/files)that introduced the new behavior that is now being over-applied. it's possible that something that this code relied on has changed and caused a regression, so it may be worth exploring the files initially effected.

**Comment by MisRob** [comment] 2023-10-13 07:19
Unassigning due to no activity

**Closed as completed** 2023-10-24 14:55 UTC
Labels: P0 - critical, DEV: frontend, SIZE: small
