### ISSUE TITLE
Coach - The 'Class activity' panel is not showing any activities made on learn-only devices

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11234] opened 2023-09-13 13:42 UTC
## Observed behavior
The 'Class activity' panel is not displaying any activities made on learn-only devices. It's working correctly if the learners are not on a learn-only device.
This issue was originally mentioned in a comment [here](https://github.com/learningequality/kolibri/issues/10588#issuecomment-1590989986) and probably somewhere else, but I am opening a separate issue to make sure we've got it covered.

## Expected behavior
All learner activities should be shown correctly in the 'Class activity' panel.

## Steps to reproduce the issue
1. On Device 1 setup a full facility
2. On Device 2 create a learn-only user for the facility on Device 1
3. Assign lessons/quizzes to the learner and complete them
4. As a coach go to Class home and observe the Class activity section

## Video

https://github.com/learningequality/kolibri/assets/79847249/bb0bcbd9-79ab-455b-bcd7-4f4a457634c6

##Logs

[LogsDB.zip](https://github.com/learningequality/kolibri/files/12598085/LogsDB.zip)

## Usage Details
Kolibri 0.16beta5
Windows 10, Ubuntu - Chrome

**Comment by pcenov** [comment] 2023-09-13 13:42
@radinamatic

**Comment by rtibbles** [comment] 2023-09-14 23:59
@vkWeb - be aware that I think this may be caused by the same issue that I resolved in this commit: https://github.com/learningequality/kolibri/pull/11244/commits/b470fcd5e23d6c544c3f6f592d9c2056b318011a so, can hold off on trying to resolve this for now.

**Comment by vkWeb** [comment] 2023-09-15 06:34
@rtibbles ok, holding this off. Shifting focus on another issue.

**Comment by radinamatic** [comment] 2023-09-17 09:55
Testing to confirm whether this issue has been fixed after merging #11244 - eventually yes, but syncing is still flaky, plus one other major error:

1. It's not possible to make a lesson at all:

![borked-lesson](https://github.com/learningequality/kolibri/assets/1457929/82af1ed4-596a-4cfb-80d5-50f923396e37)

2. Status is not reported simultaneously between the Quizzes panel and the Activity panel. After waiting several minutes at this step, I had to reload the page to see the activity reported in the panel on the right:

![class-home1](https://github.com/learningequality/kolibri/assets/1457929/7ae534c6-ed32-4d75-a602-c689fe5038f7)

And vice-versa with the second quiz, once the 'completed' status was reported in the Activities panel, it took other reload or navigating away and back to see the 'completed' status reported in the Quizzes panel:

![class-home2](https://github.com/learningequality/kolibri/assets/1457929/c08afec7-d9b1-4efb-8f66-00439a38fb30)

3. Syncing is still working 'cuando quiere' (inconsistently):
   a) Even after the learner user was correctly imported and immediately saw the quiz on the Class home, the status was still 'Not connected to server' in the learner profile, and the same status was reported on the Coach side. It would eventually change first to 'Not recently synced'. This latest status kept randomly appearing during the testing - was it maybe set to be a catch-all status?
   
   b) After the first quiz was completed and status appeared on the Coach side in the Class home, I proceeded to make a second quiz, but there was no way for it to appear on the LoD for several minutes (statuses were respectively 'Waiting to sync' and 'Syncing'). It took rebooting the Android and stopping/restarting the `kolibri service` on the server for it to eventually appear.

   c) Even with that the quiz resources were missing at first (just 5 Perseus questions, thus a couple of tenths of KB), at which step the learner was unable to answer the questions. The message 'Unable to submit quiz...' here makes no sense and should also be corrected in the spirit of #11243 (cc @marcellamaki ) 

1 | 2
-- | --
![Screenshot_2023-09-17-10-27-45-159_org learningequality Kolibri](https://github.com/learningequality/kolibri/assets/1457929/c0640e42-1881-47bc-95dc-a26b92ff6db8) | ![Screenshot_2023-09-17-10-26-42-361_org learningequality Kolibri](https://github.com/learningequality/kolibri/assets/1457929/e31803f5-e267-48d4-8b8f-98bc1ce385aa)


Server: Ubuntu 20.04 
[UbuntuSrever-logs.zip](https://github.com/learningequality/kolibri/files/12642479/UbuntuSrever-logs.zip)

LoD logs: Android 13
[AndroidLearner-logs.zip](https://github.com/learningequality/kolibri/files/12642481/AndroidLearner-logs.zip)

**Comment by rtibbles** [comment] 2023-09-26 14:51
So it seems this issue is indeed fixed. Other issues reported here are filed as follow up.

**Closed as completed by rtibbles** 2023-09-26 14:51 UTC
Labels: bug, P0 - critical, APP: Coach, DEV: frontend
