### ISSUE TITLE
Input field accepts the value without any errors on the *create new quiz* page after leaving the input field with a number outside the range of 1-50

### ISSUE THREAD

**Issue by ghost** [learningequality/kolibri#7594] opened 2020-10-21 07:32 UTC
### Actual result: 
Input field accepts the value without any errors on the *create new quiz* page after leaving the input field with a number outside the range of 1-50
### Expected result: 
Input field has the red outline on the *create new quiz* page after leaving the input field with a number outside the range of 1-50

### Preconditions:
User is logged in as a coach;  *Coach - '<class>' > Plan > Quizzes* page is opened

### Steps to reproduce;
1. Click on the "New Quiz" button
2. Enter the title for a quiz and select exercises
3. Enter a number outside the range of 1-50 to the "number of questions" field
4. Leave the input field or attempt to continue or finish the quiz
5. Notice that the errors are missed

### Video: 
https://take.ms/L1aUg

### Context:
Kolibri version: 0.14.3
Device: Raspberry Pi 3B+
OS: tested on Mac mini (Mid 2011) macOS Sierra v 10.12.6
Browser: Google Chrome latest

**Comment by jonboiser** [comment] 2020-10-23 22:31
Closing as  a near duplicate of #7597

**Closed as completed by jonboiser** 2020-10-23 22:31 UTC
