### ISSUE TITLE
content/utils/transfer.py and 'No matching schema found for this database' errors

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8389] opened 2021-09-03 16:54 UTC
## Observed behavior

When trying to import content from Studio on an individual-user device, got this error before the list of channels from Studio was shown:  

```
INFO: 127.0.0.1 - - "GET /en/device/" 304 0 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
INFO: 127.0.0.1 - - "GET /api/auth/session/current/" 200 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
INFO: 127.0.0.1 - - "GET /device/api/device_channel/" 200 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
INFO: 127.0.0.1 - - "GET /api/auth/facility/" 200 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
INFO: 127.0.0.1 - - "GET /api/content/remotechannel/kolibri_studio_status/" 200 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
INFO: 127.0.0.1 - - "GET /device/api/device_channel/" 200 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
WARNING  Did not find language code tpi in our le_utils.constants!
WARNING  Did not find language code brh in our le_utils.constants!
WARNING  Did not find language code taj in our le_utils.constants!
WARNING  Did not find language code bxk in our le_utils.constants!
WARNING  Did not find language code enq in our le_utils.constants!
WARNING  Did not find language code yao in our le_utils.constants!
WARNING  Did not find language code new in our le_utils.constants!
WARNING  Did not find language code kak in our le_utils.constants!
WARNING  Did not find language code kam in our le_utils.constants!
WARNING  Did not find language code mai in our le_utils.constants!
WARNING  Did not find language code awa in our le_utils.constants!
WARNING  Did not find language code pbu in our le_utils.constants!
WARNING  Did not find language code pbt in our le_utils.constants!
WARNING  Did not find language code tum in our le_utils.constants!
WARNING  Did not find language code bcc in our le_utils.constants!
WARNING  Did not find language code srr in our le_utils.constants!
WARNING  Did not find language code dty in our le_utils.constants!
WARNING  Did not find language code thl in our le_utils.constants!
WARNING  Did not find language code guz in our le_utils.constants!
INFO: 127.0.0.1 - - "GET /api/content/remotechannel/" 200 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
INFO: 127.0.0.1 - - "GET /api/device/freespace/" 200 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
INFO: 127.0.0.1 - - "GET /device/api/device_channel/0294a064f7224899887ce07bd47f9991/" 404 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
WARNING  Not Found: /device/api/device_channel/0294a064f7224899887ce07bd47f9991/
INFO: 127.0.0.1 - - "GET /api/content/remotechannel/0294a064f7224899887ce07bd47f9991/" 200 0 "http://localhost:8000/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0"
INFO     Downloading data for channel id 0294a064f7224899887ce07bd47f9991
INFO     Downloading data for channel id 0294a064f7224899887ce07bd47f9991
ERROR    Job bbde45a7dd3e4666a8a01fd92460ba95 raised an exception: Traceback (most recent call last):
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/transfer.py", line 95, in next
    chunk = next(self._content_iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 788, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/d/kolibri/A/content/databases/0294a064f7224899887ce07bd47f9991.sqlite3.transfer' -> '/Users/d/kolibri/A/content/databases/0294a064f7224899887ce07bd47f9991.sqlite3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/worker.py", line 62, in handle_finished_future
    result = future.result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/job.py", line 115, in execute_job
    result = func(*args, **kwargs)
  File "/Users/d/Projects/le/kolibri/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/d/Projects/le/kolibri/.venv/lib/python3.8/site-packages/django/core/managERROR    Job bbde45a7dd3e4666a8a01fd92460ba95 raised an exception: Traceback (most recent call last):
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/worker.py", line 62, in handle_finished_future
    result = future.result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/job.py", line 115, in execute_job
    result = func(*args, **kwargs)
  File "/Users/d/Projects/le/kolibri/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/d/Projects/le/kolibri/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/management/commands/base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 184, in handle_async
    self.download_channel(
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 94, in download_channel
    self._transfer(DOWNLOAD_METHOD, channel_id, baseurl, no_upgrade=no_upgrade)
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 133, in _transfer
    self._start_file_transfer(
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 171, in _start_file_transfer
    import_ran = import_channel_by_id(channel_id, self.is_cancelled)
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 26, in import_channel_by_id
    return channel_import.import_channel_from_local_db(
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/channel_import.py", line 1060, in import_channel_from_local_db
    import_manager = initialize_import_manager(channel_id, cancel_check=cancel_check)
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/channel_import.py", line 1016, in initialize_import_manager
    channel_metadata = read_channel_metadata_from_db_file(
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/channels.py", line 85, in read_channel_metadata_from_db_file
    source = Bridge(sqlite_file_path=channeldbpath)
  File "/Users/d/Projects/le/koliement/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/management/commands/base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 184, in handle_async
    self.download_channel(
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 94, in download_channel
    self._transfer(DOWNLOAD_METHOD, channel_id, baseurl, no_upgrade=no_upgrade)
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 133, in _transfer
    self._start_file_transfer(
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/management/commands/importchannel.py", line 158, in _start_file_transfer
    for chunk in filetransfer:
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/transfer.py", line 91, in __next__
    return self.next()
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/transfer.py", line 210, in next
    chunk = super(FileDownload, self).next()
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/transfer.py", line 99, in next
    self.finalize()
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/transfer.py", line 140, in finalize
    self._move_tmp_to_dest()
  File "/Users/d/Projects/le/kolibri/kolibri/core/content/utils/transfer.py", line 105, in _move_tmp_to_dest
    shutil.move(self.dest_tmp, self.dest)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 802, in move
    copy_function(src, real_dst)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/d/kolibri/A/content/databases/0294a064f7224899887ce07bd47f9991.sqlite3.transfer'

bri/kolibri/core/content/utils/sqlalchemybridge.py", line 309, in __init__
    raise SchemaNotFoundError("No matching schema found for this database")
kolibri.core.content.utils.sqlalchemybridge.SchemaNotFoundError: No matching schema found for this database
```

## Steps to reproduce

This was a single-user device created by importing one user from another instance of Kolibri

## Context

latest `develop`

**Comment by indirectlylit** [comment] 2021-09-03 17:05
tried with a fresh kolibri home folder and did not reproduce again. Saved the old one in case debugging is necessary

**Comment by rtibbles** [comment] 2021-09-03 23:56
It looks like it was trying to move the downloading 'transfer' file to the actual file name, and then things went wrong... then it tried to open the non-existent database file after the failed move?

**Comment by rtibbles** [comment] 2022-07-28 19:47
Closing as not reproducible for now.

**Closed as completed by rtibbles** 2022-07-28 19:47 UTC
