### ISSUE TITLE
can't scroll PDFs on mobile safari (iOS)

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2158] opened 2017-09-12 22:44 UTC
Go to page, try to scroll PDF. Doesn't work in embedded or full-screen mode.

Reproducible in Browserstack:

![image](https://user-images.githubusercontent.com/2367265/30351642-40c4d8c0-97d1-11e7-9ed5-c4e97792da37.png)

**Comment by kollivier** [comment] 2019-01-03 22:40
Unable to reproduce in iOS 9+ on device or simulator in the general case, and iOS v7 was notably buggy after the huge UI rework, so I am going to close this issue.

**Closed by kollivier** 2019-01-03 22:40 UTC
Labels: DEV: frontend, OS: iOS, TAG: beginner issue, TAG: bug fix
