### ISSUE TITLE
Profile dropdown option is purple in profile page

### ISSUE THREAD

**Issue by khangmach** [learningequality/kolibri#5416] opened 2019-04-24 18:55 UTC
### Observed behavior
Profile option in user dropdown is purple **ONLY** when you are already in the profile page

<img width="830" alt="Screen Shot 2019-04-24 at 11 50 39 AM" src="https://user-images.githubusercontent.com/25045166/56685633-4376fb80-6687-11e9-93ec-2fc7a74c5787.png">

### Expected behavior
Black link text like the other dropdown options

### User-facing consequences
- inconsistency issues

### Steps to reproduce
- Navigate to user profile page
- Click on the user dropdown

### Context
 * Kolibri version: Kolibri 0.12.2 beta site
 * Operating system: MacOS
 * Browser: Chrome, Firefox

**Comment by jonboiser** [comment] 2019-04-24 19:22
This seems like expected behavior, because the "Profile" link has the "active link" styling.

This issue is similar to #3876, in that having a self-link on the profile page can cause unique behavior.

**Comment by khangmach** [comment] 2019-04-24 20:52
Let's take the active link styling out, as this isn't a normal pattern we see from dropdown buttons

**Comment by jonboiser** [comment] 2019-04-24 21:19
The link components used in the top-right dropdown are the same as the ones used in the left slide-out navigation (i.e. CoreMenuOption). So, we should implement a way to override this behavior just for the drop down version?

![Screen Shot 2019-04-24 at 2 19 09 PM](https://user-images.githubusercontent.com/10248067/56694658-05d09d80-669c-11e9-8656-bc78334b5c63.png)

**Comment by khangmach** [comment] 2019-04-24 22:07
I thought we had always used this component for the user dropdown. 

<img width="203" alt="Screen Shot 2019-04-24 at 3 05 15 PM" src="https://user-images.githubusercontent.com/25045166/56697030-7a0e3f80-66a2-11e9-9fe5-88a25a558f82.png">

> So, we should implement a way to override this behavior just for the drop down version?

I would think the inverse would be ideal. The hamburger menu being an exception to any kind of dropdown component, since there's only one menu and a bunch of dropdowns everywhere

**Comment by rtibbles** [comment] 2019-04-24 22:34
Slightly janky, but we could conditionalize the `active` computed property by `$slots.icon`: https://github.com/learningequality/kolibri/blob/develop/kolibri/core/assets/src/views/CoreMenu/CoreMenuOption.vue#L17

**Comment by jonboiser** [comment] 2019-04-24 22:51
So I guess the problem is that both the (SideNav > CoreMenu) and the Dropdown (AppBar > CoreMenu) both use the component `UserProfileSideNavEntry`, which is an anchor tag (hence it receives and active style). When it's in SideNav, we want it to be purple, but in AppBar we don't want it purple.

To simply make it not purple, could we write a CSS rule in AppBar that overrides this styling for any CoreMenuOptions?

**Comment by khangmach** [comment] 2019-04-25 00:32
that makes sense to me :o

**Comment by rtibbles** [comment] 2019-04-25 00:59
I can do a quick fix for this.

**Closed as completed** 2019-04-25 22:43 UTC
Labels: bug
