### ISSUE TITLE
Cannot scroll HTML5 Flexbooks with finger drag on iOS devices

### ISSUE THREAD

**Issue by cpauya** [learningequality/kolibri#5650] opened 2019-06-11 08:55 UTC
### Observed behavior
When viewing a Flexbook content in iPad2, there is no scrollbar so that the user can view the rest of the content.  User also cannot scroll down.

Clicking on the "full-screen" button at the upper right portion blows the content to occupy the whole browser page BUT the content still cannot be scrolled-down.  Refer to screenshot below where the right-side Safari 12.1 browser shows a scrollbar on the content.

### Expected behavior
There must be a scrollbar to view the Flexbook content or user should be able to scroll down to see further content.

### User-facing consequences
Users cannot see the rest of the Flexbook contents.

 
### Errors and logs
N/A

### Steps to reproduce
Import the `CK-12` channel.
Open the CK-12 Flexbook content in the iPad2 simulator.  Example: 

> Channels - CK-12 - Science - Earth Science - Introduction to Earth Science - Scientific Community

### Context
 * Kolibri version: 0.12.4-beta7
 * Operating system: iPad2 on iOS 9.3 Simulator
 * Browser: Safari 9.3

Left: Safari in iOS 9.3 Simulator
Right: Safari 12.1 in macOS Mojave

<img width="1828" alt="Screenshot 2019-06-11 16 51 40" src="https://user-images.githubusercontent.com/175580/59257820-43e44980-8c69-11e9-869a-c33599efff7a.png">

**Comment by indirectlylit** [comment] 2019-06-11 15:29
do we know if this exists in 0.12.3?

**Comment by rtibbles** [comment] 2019-06-11 15:32
Seems to be extant there too:
![image](https://user-images.githubusercontent.com/1680573/59285799-694e6480-8c23-11e9-9132-b4bba68edbc5.png)

**Comment by indirectlylit** [comment] 2019-06-11 15:46
pushing to 0.12.5 because this is not a regression

![image](https://user-images.githubusercontent.com/2367265/59286952-ac6a0100-8c3e-11e9-9072-ca04bfe219d4.png)

**Comment by cpauya** [comment] 2019-06-12 07:41
This issue exists on PLIX contents too.

Right: iPad2 on iOS 9.3 Simulator
Left: Safari 12.1.1 on macOS Mojave

<img width="1752" alt="Screenshot 2019-06-12 15 39 00" src="https://user-images.githubusercontent.com/175580/59332263-65f0d100-8d28-11e9-9219-d4a89066762f.png">

**Comment by jonboiser** [comment] 2019-06-27 20:10
This happens on other iOS devices as well. Experienced this on my personal iPhone X as well as newer iOS devices on Browserstack.

**Comment by pcenov** [comment] 2022-03-10 12:49
@radinamatic this issue is no longer extant in Kolibri 0.15.1
Tested on iPad4 on iOS 14.4 Simulator
Browser: Safari 14.4
![2022-03-10_14-35-00](https://user-images.githubusercontent.com/79847249/157665070-cb1e2750-e4f0-4ee8-8c2e-5bc83aa968f6.png)

**Comment by rtibbles** [comment] 2022-03-18 22:48
Closing as fixed.

**Closed as completed by rtibbles** 2022-03-18 22:48 UTC
Labels: bug, P1 - important, OS: iOS, safari
