### ISSUE TITLE
Kolibri quiz data format v0 v1 update logic problem

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#5425] opened 2019-04-25 14:58 UTC
### Observed behavior

The demo site gets stuck when trying to access the quizzes reports and the difficult questions tab. 
http://kolibridemo-ar.learningequality.org/coach/#/9a3a81c57b6bb53c748d630986fe377a/reports/quizzes/4b62e6528a7d35ed0bc08127704a7e63/questions  
got to the link ^ by clicking DIFFICULT QUESTSION from this page http://kolibridemo-ar.learningequality.org/coach/#/9a3a81c57b6bb53c748d630986fe377a/reports/quizzes/4b62e6528a7d35ed0bc08127704a7e63/learners (edited)
traceback.png 

### Expected behavior

see list of Qs

### User-facing consequences

Any users that have created quizzes in old version of Kolibri might experience problems when upating to lates 0.12.y

### Errors and logs

Frontend:
<img width="665" alt="traceback" src="https://user-images.githubusercontent.com/163966/56745506-7a611600-6748-11e9-949b-cea660f549ea.png">

```
>>> from kolibri.core.exams.models import *
>>> Exam.objects.all()
<SyncableModelQuerySet [<Exam: تمرين مهارة الاستماع الأول: السندباد والجزيرة المتحركة>, <Exam: نصف القطر ، القطر>, <Exam: نصف القطر>]>
>>> quiz = Exam.objects.all()[0]
>>> pprint(quiz.__dict__)
{'_morango_dirty_bit': True,
 '_morango_partition': u'ce3611ba232ab07ad5da00bbb3fd3f3a',
 '_morango_source_id': u'68ba3d1ca5344701b56740573155e3ed',
 '_state': <django.db.models.base.ModelState object at 0x7fb241698350>,
 'active': True,
 'archive': False,
 'collection_id': '9a3a81c57b6bb53c748d630986fe377a',
 'creator_id': 'a3d140a0bb958c5e260ae951077ceccb',
 'data_model_version': 0,
 'dataset_id': 'ce3611ba232ab07ad5da00bbb3fd3f3a',
 'id': '4b62e6528a7d35ed0bc08127704a7e63',
 'learners_see_fixed_order': False,
 'question_count': 11,
 'question_sources': [{u'exercise_id': u'1d527bd3433b5e73a82b75eb007742be',
                       u'number_of_questions': 11,
                       u'title': u'\u0627\u0644\u0627\u0633\u062a\u0645\u0627\u0639'}],
 'seed': 358,
 'title': u'\u062a\u0645\u0631\u064a\u0646 \u0645\u0647\u0627\u0631\u0629 \u0627\u0644\u0627\u0633\u062a\u0645\u0627\u0639 \u0627\u0644\u0623\u0648\u0644: \u0627\u0644\u0633\u0646\u062f\u0628\u0627\u062f \u0648\u0627\u0644\u062c\u0632\u064a\u0631\u0629 \u0627\u0644\u0645\u062a\u062d\u0631\u0643\u0629'}
```

### Steps to reproduce

  - Create quiz with `kolibri-0.11.1.pex` 
  - Update to `kolibri-0.12.2.pex`
  - Try viewing report about difficult questions of quiz in 0.12.2

Note: note tested ^ above steps. Assuming this is what happened.

### Context

Kolibri version and date installed:
```
-rw-r--r-- 1 kolibri kolibri 81712424 Jan 12 00:05 kolibri-0.11.1.pex 
-rw-r--r-- 1 kolibri kolibri 90204694 Mar  4 23:10 kolibri-0.12.0.pex
-rw-r--r-- 1 kolibri kolibri 90386039 Mar 29 01:31 kolibri-0.12.2.pex
```

Example quiz was created in Feb so can assume it was created in kolibri-0.11.1.pex

**Comment by indirectlylit** [comment] 2019-04-25 19:03
related

* https://github.com/learningequality/kolibri/issues/4940
* https://github.com/learningequality/kolibri/issues/5427

**Comment by bjester** [comment] 2019-05-03 17:47
I was unable to reproduce this issue following the reproduce steps. The difficult questions report loaded for me in 0.12.2 after creating an exam in 0.11.1 and upgrading to 0.12.2.

**Comment by bjester** [comment] 2019-05-03 17:52
No issues with the `0.12.3a0` pex either.

**Comment by ivanistheone** [comment] 2019-05-03 18:56
Okay that's weird—maybe it was some temporary caching issue?

I just went to the difficult questions link posted above http://kolibridemo-ar.learningequality.org/coach/#/9a3a81c57b6bb53c748d630986fe377a/reports/quizzes/4b62e6528a7d35ed0bc08127704a7e63/questions  and it seems to render fine now. I have not updated that demo server in the meantime.

Or perhaps the error was occurring because the list was empty, but now the bug is gone because we have some questions to show it it. 

I'd write this off as a transient/temporary bug and close this issue (but still be on the lookout in case it comes up again).

**Comment by bjester** [comment] 2019-05-03 19:10
@ivanistheone I just created a new quiz and looked at the Difficult Questions report for the quiz without a learner having completed it, and saw no errors. I also completed it as a learner with 100% score and again, saw no errors. So I agree, perhaps it was a random issue and everything looks good now! I will close it.

**Closed as completed by bjester** 2019-05-03 19:10 UTC
Labels: P1 - important
